### ISSUE TITLE
paperの訳語を決めたい

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1009]
本サイト内でいま、paperの訳語として「提案文書」と「論文」で表記揺れしています。

研究界隈ではpaperと言ったら「論文」になるのだと思いますが、C++標準規格に導入するための議論と具体的な仕様案はproposal paperをpaperと言ってるのだと思うので私は「提案文書」としていました。

こちら、ご意見いただきたいです。

**Comment by onihusube** [comment]
私は「提案文書」派ですが、単に「提案」って略してることも多い気がします。

**Comment by faithandbrave** [comment]
なるほど、ではそのあたりへに影響を与えることも含めて、訳語を検討しましょう。

**Comment by yumetodo** [comment]
近年のNxxxxとPRxxxxではpaperでも性質が違っている気がしますが一応proposalには違いないので、「提案」ないし「提案文章」で良いものと思います。

**Comment by akinomyoga** [comment]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/ など眺めると Nxxxx は paper ではありますが最早提案文書にはこの番号は付かないように見えます。Pxxxx は「提案」・「提案文書」で良いと思いますが、他は臨機応変ということで良い気がします (cpprefjp で paper として参照するのは提案のことがほとんどだとは思いますが)。

個人的には特に paper の訳語としてきっちりと定めるのであれば、「提案」よりは「提案文書」の方が良い気がします。提案を paper の訳語としてしまうと、普通の日本語の意味で提案という語を使いにくくなる気がします (例えば提案文書の中に書かれている個々の提案自体を指したいときなど)。

**Comment by faithandbrave** [comment]
ひとまず、「論文」は「提案文書」に直していく、というので合意できそうですね。
こちらは訳語表に追加しておきます。

「提案」の使われ方は一度調べてみます。曖昧さがある使われ方をしているようであれば、こちらで相談します。

Nxxxx系の呼び方はとくに決める必要はない気がしていますが (Working Draftなら規格案、Editor's ReportはほぼWikiでしか使わない、みたいに個別に名前がありそう)、必要そうなら言ってください。

**Comment by faithandbrave** [comment]
「提案」をできるだけ「提案文書」に直しました。
@onihusube 残った「提案」の使われ方でまだ気になるところがあったら直してください。困ったらissueで相談していただければ。

訳語としては決まって、一通り直したので、このissueは終了します。
@onihusube @yumetodo @akinomyoga ご協力ありがとうございました。
