### ISSUE TITLE
[C++23] thisポインタをもつ必要のない演算子をstaticとして宣言できるようにする

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1029]
- [P1169R4 static operator()](https://wg21.link/p1169r4)

**Comment by yohhoy** [comment]
[P2589R0 static operator[]](https://wg21.link/p2589r0) も同時対応が楽そうです。

**Comment by faithandbrave** [comment]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4929.html

このEditor's ReportをまだWikiに書いてなかったので把握してませんでした。。。Wikiは更新しておきます。
ひとまずこの件は、タスクをいっしょにしちゃってください。
