### ISSUE TITLE
[C++23] レガシーC関数からスマートポインタへの直接出力をサポートする、スマートポインタアダプタ

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1050]
- [P1132R8](https://wg21.link/p1132r8)	out_ptr - a scalable output pointer abstraction

**Comment by yohhoy** [comment]
機能説明を利用者の目的ベースで書き換えました。

```diff
- 出力ポインタと入出力ポインタの抽象
+ レガシーC関数からスマートポインタへの直接出力をサポートする、スマートポインタアダプタ
```

**Comment by yohhoy** [comment]
下記課題が残るものの、最低限の記述は完了したのでCLOSEします。

1. cpprefpでの例示コードは、提案文書にある基本的なExample 1例のみの引用です。本機能のユースケースはレガシーC関数との連携にあるため、実行可能かつ簡潔な例示コードを作るのが難しい側面があります。

2. `outptr_t`/`inout_ptr_t`クラス[`operator void**()`戻り値](http://eel.is/c++draft/out.ptr.t#15.2)文面を正しく理解できておらず、cpprefjpでの説明文は怪しい気がします...

> Returns: A pointer value `v` such that:
> - [...]
> - any modification of `*v` that is not followed by a subsequent modification of `*this` affects the value of `p` during the destruction of `*this`, such that `static_­cast<void*>(p) == *v`.
