### ISSUE TITLE
[C++23] expected

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1066]
- [P0323R12](https://wg21.link/p0323r12)	std::expected
- [P2549R1](https://wg21.link/p2549r1)	`std::unexpected<E>` should have `error()` as member accessor
- [P2505R5](https://wg21.link/p2505r5) Monadic Functions for `std::expected`

作業タスク
- [x] `expected<T, E>`
- [x] `expected<cv void, E>`
- [x] `unexpected<E>`
- [x] `unexpect_t`
- [x] `bad_expected_access<E>`

**Comment by yohhoy** [comment]
C++23クラステンプレート`std::expected<T, E>`には、`std::expected<cv void, E>`部分特殊化バージョンが定義されています。

- https://eel.is/c++draft/expected.expected
- https://eel.is/c++draft/expected.void

当初は`expected`各メンバページに部分特殊化の説明を追加していく想定でしたが、思ったより両者の差分が大きいこと（`T=cv void`を前提とした簡約化やオーバーロード差異）に気づきました。

そこで、プライマリレンプレートと部分特殊化バージョンをクラス説明レベルで分離してしまった方がスッキリしそうです。

ディレクトリ構造の素案：

- /reference/expected/(各種メンバ).md
- /reference/expected.void/(各種メンバ).md

@faithandbrave さん：
現時点のcpprefjpサイトではこのような「プライマリンプレートと部分特殊化でクラスレベルの分離」を行っている事例がないため、どのように対処するのが適切かを相談させてください。

**Comment by faithandbrave** [comment]
一旦やりやすい方法で書いてもらって、それをあとでルール化しましょうか。
書いてるうちにうまくいかないところとか出てくるかもしれませんので。
いまのところ、そういった事例はないです。

あとでstart_editing/directory_structure.mdにPull Requestいただければ

**Comment by faithandbrave** [comment]
https://cpprefjp.github.io/reference/future/promise/set_value.html

`promise<void>`とかは、ページは分けていないですが、オーバーロードのように特殊化の説明を分けているものはあります。

**Comment by yohhoy** [comment]
`promise<R>`の説明構造を確認してみました : https://eel.is/c++draft/futures.promise
ちょっとした違いであれば、プライマリンプレートと同一ページで説明してしまえばOKですね。（[`bad_expected_access<void>`](https://eel.is/c++draft/expected.bad.void)はその予定）

`expected<T,E>`は特にコンストラクタ／代入演算子／`emplace`あたりが（既に）ごちゃごちゃしているので、ひとまずクラスレベル分離の方向で進めたいと思います。

**Comment by yohhoy** [comment]
> expected<T,E>は[...]、ひとまずクラスレベル分離の方向で進めたいと思います。

996f8d3679187e3abf7240299e2609f33975c35d にて、実験的に数ページだけcpprefjpサイトへデプロイしてみました。

自分で確認した範囲では、2つの問題を見つけました：

1. ページ上部のパンくずリストが部分的に機能しない。これは(人力)リダイレクトを促すページを作ってしまえば解決すると思います。
@faithandbrave さん：サイト変換ルールを正しく把握していないのですが、ファイルパスは `/reference/expected/expected.void.md` でよいでしょうか？

![structure](https://user-images.githubusercontent.com/839636/217693405-4d1e791d-e699-4064-9d8f-b81f42a308d4.png)

2. サイト内検索(crsearch)で、プライマリテンプレートと部分特殊化版で2重にHITしてしまう。こちらは、この挙動で良しとするしかないかなと考えています。

![crsearch](https://user-images.githubusercontent.com/839636/217693418-0d6dcdf1-ce5b-4126-b0d7-1549781349bd.png)

**Comment by faithandbrave** [comment]
> @faithandbrave さん：サイト変換ルールを正しく把握していないのですが、ファイルパスは /reference/expected/expected.void.md でよいでしょうか？

はい、それで大丈夫です。

> サイト内検索(crsearch)で、プライマリテンプレートと部分特殊化版で2重にHITしてしまう。こちらは、この挙動で良しとするしかないかなと考えています。

`expected<void>[meta class]`
とすれば分けられそうな気もしますが、どうでしょう

**Comment by yohhoy** [comment]
以下の対処を行いました。

* `/reference/expected/expected.void.md `プレイスホルダーページを用意
* 各メンバ説明ページのメタ情報は `expected.void[meta class]` を記述

**Comment by yohhoy** [comment]
done!
