### ISSUE TITLE
[C++23] Rangeからコンテナへの変換

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1069]
- [P1206R7](https://wg21.link/p1206r7)	ranges::to: A function to convert any range to a container
- [P2499R0](https://wg21.link/p2499r0)	string_view range constructor should be explicit

**Comment by tetsurom** [comment]
3983f026a31e240e333cda929e12086f94ca1bdb

**Comment by faithandbrave** [comment]
@suomesta さんを担当にしておきましたー

**Comment by suomesta** [comment]
https://github.com/cpprefjp/site/commit/1276fca74674bb2f54108a79e630d3ec65037855
https://github.com/cpprefjp/site/commit/e2d69e3d688ced5fc4f44851620756eb65fd6f25
https://github.com/cpprefjp/site/commit/774a74a79b885dc153f93a2be943b4c886907cf9
https://github.com/cpprefjp/site/commit/1a35e93266f3576c084fc9b57381139f3820a3cd
https://github.com/cpprefjp/site/commit/d3eeb80c76c6cceb1e5b3ddef1a21e658ba14a3a
以上で完了と思います

**Comment by faithandbrave** [comment]
ありがとうございます！たいへん助かります！
