### ISSUE TITLE
[C++23] cbeginを常にconst iteratorが返るようにする

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1084]
- [P2278R4](https://wg21.link/p2278r4)	cbegin should always return a constant iterator

**Comment by onihusube** [comment]
この辺のリンクをメモしておいて、終わりです

- [P2836 R1 std::basic_const_iterator should follow its underlying type's convertibility](https://github.com/cplusplus/papers/issues/1509)
- [LWG Issue 3946. The definition of const_iterator_t should be reworked](https://cplusplus.github.io/LWG/issue3946)
