### ISSUE TITLE
shift_leftにシフト数として負数を指定可能と読める記述

### ISSUE THREAD

**Issue by tshino** [cpprefjp/site#1132]
細かいことで恐縮ですが、若干不正確な説明を見つけたので指摘させてください。

`std::ranges::shift_left` では事前条件が `n >= 0` となっていますが、備考蘭で

> シフト数として負数を指定するとなにも起こらないが、

と書かれているため、負数を指定可能のような誤解を与えそうです。
この場合負数はundefined behaviorとなるはずなので、

> シフト数として負数を指定することはできないが、

のような記載が望ましいと思われます。
https://github.com/cpprefjp/site/blob/master/reference/algorithm/ranges_shift_left.md

**Comment by tshino** [comment]
規格の調べ方に慣れていないので確信はないですが、
C++20からある`std::shift_left`の方は負数を指定可能だったようですが、
C++23で追加された`std::ranges::shift_left`では負数はpreconditionで除外されている、という違いがあるようです。

**Comment by onihusube** [comment]
ご指摘は正しそうです。

どうやら、C++20の非Rangeアルゴリズムの頃から、`std::shift_left`/`std::shift_right`ともに事前条件として`n >= 0 is true`が指定されてします。

C++23のRangeアルゴリズム版もそれを引き継いでいるようです。

**Comment by tshino** [comment]
確認ありがとうございます！

気になっていたのは `std::shift_left` のページで参考リンクにある [P0769R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0769r2.pdf) では事前条件の記載がなく、`If n <= 0 or n >= last - first, does nothing.` となっていたことでした。
ですが、C++20の参照する規格案となっているN4861を見ると事前条件の記載があることが分かりました。

確認が取れたので、以下の4ページについて修正すれば良さそうですね。

- `std::shift_left`
- `std::shift_right`
- `std::ranges::shift_left`
- `std::ranges::shift_right`

修正内容:
- 事前条件の記載が無いページは記載を追加
- 効果の「 `n <= 0' である場合何もしない」を「 `n == 0' である場合何もしない」 に修正
- 備考の「負数を指定すると何も起こらない」を修正

**Comment by yohhoy** [comment]
> 気になっていたのは `std::shift_left` のページで参考リンクにある [P0769R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0769r2.pdf) では事前条件の記載がなく、If n <= 0 or n >= last - first, does nothing. となっていたことでした。

[経緯を調べてみた](https://github.com/cplusplus/draft/commit/f6f211301f4865183cbde4fb72fa566d72dc5e95#diff-f2a7860b1e40793f29760cc88cb8e8571e1dcfe8a53c1b9579ef4c5c35c9d9bfR5821)ところ、[P1243R4 Rangify New Algorithms](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1243r4.pdf) にてレンジ版 `std::ranges::shift_{left,right}` が追加される際に、非レンジ版に対しても "Preconditions: n >= 0 is true." が追加されていました。
 
[N4859 Editors' Report -- Programming Languages -- C++](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4859.html) によれば、NBコメント US 318 への対応とのことです。

> LWG poll 22: [P1243R4 "Rangify new algorithms"](http://wg21.link/p1243r4), resolving 3 NB comments:
>
> - NB FR 305: Add more range-enabled algorithms
> - NB US 307: Add more range-enabled algorithms
> - NB US 318: Handle negative shift counts

**Comment by tshino** [comment]
そうすると、`std::shift_left`と`std::shift_right`の参照の欄にP1243R4も追加した方が良さそうでしょうか？

**Comment by yohhoy** [comment]
@tshino さん：そうですね。参照リストに [P1243R4 Rangify New Algorithms](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1243r4.pdf) も追加しておくとよさそうです。
