### ISSUE TITLE
cpprefjpアイコンを再デザインします

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1136]
現在のcpprefjpアイコンは、ライセンスが「[クリエイティブ・コモンズ 表示 - 非営利 - 改変禁止 4.0 国際 (CC BY-NC-ND 4.0)](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ja)」になっていて、改変禁止となっています。

それが今後のコントリビューターの方々にお配りするステッカー作成において、以下のような支障があります：

1. 「cpprefjp 2023 Contributor」のような文字載せができない (アイコンとかぶらなくても)
2. 印刷対象による色味の調整ができない

このアイコン画像の著作権者も不在であるためライセンス変更もしにくいので、アイコン画像の再デザインを発注しようと思います。
デザインは、『プログラミングの魔導書』の画像全般を作成していただいた[zakさん](https://twitter.com/zakkas783)に依頼します。

ライセンスは新たな著作権者との相談になりますが、CC BYかCC0かPublic Domainになると思います。

懸念などあれば教えてください。

**Comment by yumetodo** [comment]
一応確認ですが、もとのアイコン制作者とはあれっきりではありますが、Twitterはやってるみたいですし連絡をとるという考え方はなしでしょうか？

**Comment by yumetodo** [comment]
当時のライセンス決定背景を見るに

>CC-BYだと、たとえば誰かが勝手にcpprefjpのロゴを使ったTシャツを作って有料で配ったりした場合に、制限できないと思います。そういう利用可能性を含めて許可するという趣旨であれば、僕はCC-BYにすることに異存はありません。

とありますから、支障を正攻法で解決できないとは思わないのですが・・・。

---

ところで当時 @faithandbrave さんも述べられていた

>ライセンスはそれで行きましょう。ロゴとかアイコンのデザインについては、好きにいじられると印象操作に使われたりもしますしね。

という点については今どう考えているか気になります。

**Comment by akinomyoga** [comment]
> このアイコン画像の著作権者も不在であるためライセンス変更もしにくいので、アイコン画像の再デザインを発注しようと思います。

CC-BY-NC-ND などのライセンスは不特定多数に対する一括の権利許可の話なので、ライセンスの変更を依頼しなくても、それとは別に cpprefjp の組織として著作権保持者から個別に許可をもらうのも可能ですよね。というより、改めて考えると、通常はロゴなどの依頼をする時には、依頼者は不特定多数の人の利用よりはより広い利用許諾を著作者から明示的もしくは黙示的に取得するものの気がします。むしろ今まで不特定多数の利用と同レベルの利用範囲で運用してきたのが変だったのかも。現在のライセンスだと、cpprefjp とは全く関係ない非営利組織がこのアイコンを使って新しい別の C++ サイトを作るのもOKってことになりませんか。

新しいデザインを発注する時にも cpprefjp における利用許諾と、不特定多数に対するライセンスによる利用許諾については独立に議論してはっきりさせ、発注時の契約の一部としてデザイナーとの合意を作っておくと良いのではないかと思います。或いは著作権譲渡をしてもらえれば(例えば @faithandbrave さんに)ライセンスはいつでも自由に変更できますが、それにはちゃんと契約書というか法的に有効な書類を作る必要があるはず。

> 当時のライセンス決定背景を見るに
> 
> > CC-BYだと、たとえば誰かが勝手にcpprefjpのロゴを使ったTシャツを作って有料で配ったりした場合に、制限できないと思います。そういう利用可能性を含めて許可するという趣旨であれば、僕はCC-BYにすることに異存はありません。
> 
> とありますから、支障を正攻法で解決できないとは思わないのですが・・・。

別にライセンスがあったとしても著作権者にコンタクトを取ってはいけないってことではないので、もし必要があれば全然コンタクトは取って良いというかちゃんと取るべきだと思いますね。ただ、今後も頻繁にということになりそうであれば、一旦は袂を分かったのですから何処かの時点で新しいデザインに切り替えた方がお互いやりやすいのかなとも思います。

というかもう既にzakさんにご相談しているのでしたら、今更やっぱりやめましたってのも何だかなって思います。

何れにしても、新しいデザインに変えたとしても、事後でも良いのでさきさかさんに「ライセンスや利用許諾でもっと動きやすいものが必要になったので」と変更の経緯について一報入れるのが誠意と思います。さきさかさんはそういうことで不安になる方のようでしたから。コミュニケーション不足、よくなかったなって思ってます。

**Comment by faithandbrave** [comment]
さきさかさんには、私はTwitterではブロックされて対話拒否されてしまっていますので、代理でどなたかに相談してもらうにしても、今後の都度相談は継続性の面で困難だと判断しました。ほかの連絡手段で私が連絡するにしても、対話拒否の姿勢はすでに受け取ってしまってるので困難だと考えます。

ライセンス変更のみがんばってやったとしても、著作人格権は元の著作者が持つことになるので、元著作権者の思い入れを壊すようなことはできず、今後、元著作権者と相談が必要になる場面はでてきてしまうだろうと考えています。

また、ライセンス変更やデザイン変更のこういった議論は遅かれ早かれ起こるものだと思います。
しがらみをずっと抱えて進んでいくのも辛いので、どこかで切り替えを行う必要があるのだと思います。

ライセンス変更による悪用の懸念はありますが、まず自分たちが使えないといけないと考えます。しかし、akinomyogaさんのおっしゃることももっともなので、不特定多数向けと我々向けで別なライセンス合意をとるようにしようと思います。

**Comment by faithandbrave** [comment]
想定用途も事前にzakさんと相談して合意をとります。
まだ考えきれていないですが、事例も調べてみます。

**Comment by yumetodo** [comment]
@akinomyoga さんの指摘に同意します。

また

>何れにしても、新しいデザインに変えたとしても、事後でも良いのでさきさかさんに「ライセンスや利用許諾でもっと動きやすいものが必要になったので」と変更の経緯について一報入れるのが誠意と思います。さきさかさんはそういうことで不安になる方のようでしたから。コミュニケーション不足、よくなかったなって思ってます。

この連絡は行うべきと思いますので、どのタイミングで出すか、検討いただければ私なり誰かが伝書鳩できるものと思います。

**Comment by h-sao** [comment]
アイコンに関してはライセンスも含めて、コミュニティ全体（特に @faithandbrave さん）が扱いやすいものに変更してしまう方が良いと思います
また @faithandbrave さんが元々アイコンを作られた方と対話出来ない関係になっているのに、わざわざ連絡を行う必要はないように思います
cpprefjpはコミュニティなので、他の対話可能なコミュニティメンバーが誰の支持を仰ぐわけでもなく善意で伝えてあげる、程度で良いのではないでしょうか
過去の経緯を深く知っているわけではありませんので、外した意見かもしれませんが
わたしはそこまで @faithandbrave さんに負担をかけなくても良いのではないかなと思いました

**Comment by faithandbrave** [comment]
スケジュール感としては、2024年のはじめにステッカー制作を開始する予定なので、年末くらいに新アイコンがほしい、というのはzakさんに伝えてあります。
なので、すぐにデザインが上がってくるものではないと思います。

**Comment by faithandbrave** [comment]
https://github.com/cpprefjp/image/tree/master/cpprefjp/icon

新しいアイコンができました。v2.0として置いてあります。
アイコン自体は12月末に上がってきていたのですが、私の確認不足でお知らせが遅くなってしまいました。

LICENSEファイルにまとめてありますが、zakさんからcpprefjp teamに著作権を譲渡してもらっています。
ですので、cpprefjp teamの合意の元、ライセンス変更や改変が行えるものとしています。
cpprefjpの外部への公開のライセンスとしては、変わらず[CC BY-NC-ND 4.0)](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ja)でよいかと思いますが、懸念があったら教えてください。

こちら問題なければ、アイコンの置き換え作業と、それに続いてステッカーの発注作業をしていこうと思います。
1/19(金)くらいまでにご意見いただければ。

**Comment by faithandbrave** [comment]
zakさんからいただいた、デザイン意図です。

1. デザイン素案はさきさかさんの"和風"を踏襲
    - 色: 浅葱色 と 天色
    - 亀甲文様 : 長く安定して続くイメージ (あと C++グローバルアイコン(下図参照)のクリスタルを踏襲
    - 手裏剣2枚
2. ダークモード/ライトモードの視認性の維持(下図参照)

<img src="https://github.com/cpprefjp/site/assets/240038/24a8a6f3-76af-4018-bfe0-f37585220622" width="300"><br>
<img src="https://github.com/cpprefjp/site/assets/240038/ffd5b62f-c6a9-4572-b955-1ea93d3a8fb4" width="300"><br>
<img src="https://github.com/cpprefjp/site/assets/240038/c0a0f6e9-f610-451e-abd6-2db52bf404d4" width="300"><br>

**Comment by faithandbrave** [comment]
faviconの置き換えと、ステッカーの作成を進めますー

**Comment by faithandbrave** [comment]
アイコンの更新が完了しました！
ステッカーの作成と配布については、数日中にデザインができると思うので、そしたらissueを立てます。

**Comment by yumetodo** [comment]
@faithandbrave 気がつくのが遅れたのですが、このレポジトリ自体のアイコンも追従したほうが望ましいのではないでしょうか？

![image](https://github.com/cpprefjp/site/assets/10869046/c31563ad-9f2b-4622-a9f2-70f288173616)

**Comment by faithandbrave** [comment]
@yumetodo
報告ありがとうございます。更新しました。
反映に時間がかかるようですが、私のほうでは更新を確認できました。

ほかにも更新漏れがあったら教えてください。
