### ISSUE TITLE
コントリビューターの呼び名を考える

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1140]
- #1139 

CEDECの発表では、 @onihusube さん、 @tetsurom さんの肩書きが「cpprefjpコントリビューター」になっていました (所属を記載する必要があったため、所属会社ではなくこのコミュニティ所属にした)。

「コントリビューター」は、私としては貢献してくれる外部の人という「メンバーではない」印象を受けます。

今後ステッカー制作をする上でも「cpprefjp Contributor 2023」のような印字をしようかと考えているのですが、コントリビューターの方がどう呼ばれたらうれしいのかを考えた上で、このプロジェクトに参加してくださる方々の呼び名を決めていきたいです。

考えられる名称としては、こんなところでしょうか。

- コントリビューター (Contributor, これまでのまま)
- メンバー (Member)
- 編集者 (英語表記はEditor)
- コミッター (Committer)

ほかの候補も挙げていただいていいので、どういう呼ばれ方をしたらうれしい (誇らしい) か教えていただきたいです。

**Comment by yohhoy** [comment]
個人的には「コントリビュータ(Contributor)」でさほど違和感ありませんが、一つの意見として挙げておきます。

次点候補だと「編集者(Editor)」かなと思いました。
cpprefjpの実運用としては、Wikipediaのようなコミュニティに近いのかなと理解しています。

「メンバー (Member)」や「コミッター (Committer)」だと、少しだけクローズドな印象があります。
よくあるOSSでは、強い権限をもつ中核メンバとそれ以外の参加者で構成されるケースが多い気がします。
cpprefjpの場合、1回目のPRから [GitHubのpeople](https://github.com/orgs/cpprefjp/people) へ招待するなど、かなりオープンな運用を行ってる印象をもっています。

**Comment by h-sao** [comment]
まずはノミネートおめでとうございます！
わたしも「コントリビューター」で良いかなと思います
「コミッター」だとクローズドな印象はありつつも、プログラムに強い勢です！というドヤ感（実態はオープンな運用だけど、ともかく誇らしげ）が出るような気はします
他の呼び名もということなので、なんとか絞りだしてみました

- アドボケート (Advocate)：めっちゃ広めてくれるイメージ、会社っぽい
- コラボレーター (Collaborator)：共同作業感が出るような気がします

**Comment by faithandbrave** [comment]
すいません、発表の件は公表前だったようで、取り急ぎissueを削除しました。

**Comment by faithandbrave** [comment]
このままにしますー
