### ISSUE TITLE
std::ranges::borrowed_range の例のコメントについて

### ISSUE THREAD

**Issue by sukeya** [cpprefjp/site#1150]
初めまして。
すけやと申します。
よろしくお願いします。

たまたま見つけたのですが、以下の行での「文字列」は「int」ではないでしょうか？

https://github.com/cpprefjp/site/blob/0bbeedbb56fd825f21ead503b0edf8f47875d4f3/reference/ranges/borrowed_range.md?plain=1#L46

**Comment by faithandbrave** [comment]
@sukeya さん、報告ありがとうございます。
ご指摘の通り間違いでしたので、修正しました。

数分後にWebサイトに反映されます。
