### ISSUE TITLE
map/set の erase に存在しないキーを指定した場合の動作が未定義？

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#1152]
以下で map/set の erase() に存在しないキーを指定した場合の動作は未定義であるという変更が入っていました。
https://github.com/cpprefjp/site/commit/587bd5b265057b6b9f69895cf8c98d6c37bdd483
https://github.com/cpprefjp/site/commit/a6c9e227b387d2aa8631acc1df6f78468d690702

でも、存在しないかもしれないキーを erase() に指定することはよくあるものと思い、未定義動作となると
実用上不便で、動作の記述「指定されたキーをもつ要素を削除する」（[規格上の記述](https://timsong-cpp.github.io/cppwp/n4868/tab:container.assoc.req#row-33-column-3-sentence-1)も同様）から考えても
存在しないキーを指定した場合には何も起こらないという解釈が自然なものと思います。

動作は未定義であるというのは間違いではないか、間違いないとされる場合は出典はどこか、
確認おねがいします。

**Comment by faithandbrave** [comment]
解釈の問題でしたが、実装を確認したところ、libstdc++、libc++では存在しないキーが指定された場合は何もしない動作になっていました。
こちら修正しておきます。

イテレータ指定の方は、`end()`を指定したらlibstdc++ではassertに引っかかるようでした。
libc++の方はendがくることを想定していないのか、問答無用で指定されたイテレータの要素を削除しようとしてるようでした。

**Comment by k-satoda** [comment]
@faithandbrave iterator 指定のほうに end() を渡した場合は↓の "dereferenceable" に該当しないため
動作は未定義で間違いないと思います。
https://timsong-cpp.github.io/cppwp/n4868/associative.reqmts.general#8.sentence-1
> ..., q denotes a valid dereferenceable constant iterator to a, r denotes a valid dereferenceable iterator to a ...
