### ISSUE TITLE
C++23言語機能「行末スペースを無視するよう規定」の説明文が不正確

### ISSUE THREAD

**Issue by kusunosetoru** [cpprefjp/site#1160]
[C++23](https://cpprefjp.github.io/lang/cpp23.html)のページで言語機能「行末スペースを無視するよう規定」(P2223R2 Trimming whitespaces before line splicing)の説明で「行末が`\`でおわっていた場合に」とありますが、正しくは「行末が`\ `でおわっていた場合に」と`\`記号のあとに空白文字がある必要があります。

なお、[ソースコード](https://raw.githubusercontent.com/cpprefjp/site/master/lang/cpp23.md)では「行末が\`\ \`でおわっていた場合に」と空白文字が入っており、[Github上でのプレビュー](https://github.com/cpprefjp/site/blob/master/lang/cpp23.md)では正しく表示されています。

site_generatorが使用しているPython-Markdownは開始のバックティックの直後および終了のバックティックの直前の連続する空白文字を除去する（参考：Python-Markdown/markdown#321）のに対し、CommonMarkの[Code spansの仕様](https://spec.commonmark.org/0.29/#code-spans)では「\` a\`」のように一方にだけ空白文字がある場合には除去しないという仕様の違いがあるようです。

**Comment by kenichiice** [comment]
https://developer.mozilla.org/ja/docs/Web/CSS/white-space

を見るとデフォルト（`white-space: normal;`）では要素内の行末の空白は除去されるようなので、`code`要素に対してCSSで `white-space: pre;` を指定すれば正しく表示できそうに思いました。

**Comment by kenichiice** [comment]
シンプルなHTMLで試してみた所、デフォルトでは `code`要素の行末のスペースは表示されるようでした。
cpprefjpの`code`要素には `display: inline-block;` が指定されていて、これがあると行末のスペースが除去されてしまうようです。

なので、次のどちらかを行うと表示が変わるのではないかと思います。

* `display: inline-block;` をやめる
* `white-space: pre;` を追加する

**Comment by kusunosetoru** [comment]
すみません。[C++23言語機能の実装状況](https://cpprefjp.github.io/implementation-status.html#cpp23)にも同じ表記があるんですが、報告から漏れていました。

**Comment by faithandbrave** [comment]
ありがとうございます。
手元でHTMLサーバーを動かしてやってみます。

実装状況の方も同様に修正しておきます。

**Comment by faithandbrave** [comment]
`<code>`タグに`white-space: pre;`をつけて直りました！
@kusunosetoru さん、 @kenichiice さん、ご協力ありがとうございました。
