### ISSUE TITLE
[C++26] 宣言のみで使用しない変数の名前として`_`をサポート

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1172]
- [P2169R4 A nice placeholder with no name](http://open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2169r4.pdf)

**Comment by faithandbrave** [comment]
@rotarymars 対応ありがとうございます〜

**Comment by faithandbrave** [comment]
終了かどうかわからないので、一旦閉じないでおきます。

**Comment by rotarymars** [comment]
すみません、勝手に閉じても良いのか分からず、閉じていませんでした。
閉じさせていただきます。
