### ISSUE TITLE
[C++26] 基本文字集合に@、$、\`を追加

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1178]
- [P2558R2 Add @, $, and \` to the basic character set](http://open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2558r2.html)

**Comment by K10-K10** [comment]
私でよければやります。

**Comment by faithandbrave** [comment]
よろしくお願いします！

- https://github.com/cpprefjp/site/blob/master/lang/cpp26.md
- https://github.com/cpprefjp/site/blob/master/implementation-status.md

この2ページに、.md.nolinkという形式になっているのがあるので、.nolinkを消してページを足してくださいませ。

**Comment by K10-K10** [comment]
一度確認いただけると幸いです

**Comment by faithandbrave** [comment]
https://cpprefjp.github.io/lang/cpp26/add_atsign_dollar_graveaccent_to_the_basic_character_set.html

```md
基本文字集合に
$ (U+0024)
@ (U+0040)
` (U+0060)
の3文字を加える。  
```

これが箇条書き記法でないために、表示上は1行になっていますが、意図通りでしょうか？

あとは誤字がありました。

```diff
- 他言語絵の
+ 他言語への
```

**Comment by faithandbrave** [comment]
それとローカルルールで恐縮ですが、以下のページにあるように、

- https://github.com/cpprefjp/site/blob/master/start_editing/markdown_cpprefjp.md

> includeとmain関数を含む原則すべてのC/C++言語のコードブロックにはexampleタグをつけてください。

こういうのがありますので、コードブロックを「\`\`\`cpp example」にしておいていただけると助かります。

**Comment by K10-K10** [comment]
修正しました

**Comment by faithandbrave** [comment]
対応ありがとうございます！
完了したらクローズしてくださいませ

**Comment by K10-K10** [comment]
クローズ
