### ISSUE TITLE
2023年 報酬受け取りの申請をお願いします

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1217]
- [申請フォームはこちら](https://forms.gle/TkvDVjHoAJcwoY15A)

スポンサー様方からいただいたお金からもろもろ手数料を引かれた金額が169,308円です。
これを、2023年1月から2023年11月までの期間中の貢献に応じて、コントリビューターの方々に分配します。

分配レートは、以下の表のrate列を参照してください (報酬受け取りを辞退された方は0.0%になっています)。
これで決まった金額から振込手数料 ([こちらを参照](https://www.bk.mufg.jp/tesuuryou/furikomi.html)) を引いた金額を、支払わせていただきます。

報酬の受け取りを希望される方は、このissueのトップにある申請フォームから、振込先口座の提出をお願いします。提出期限は、2023年12月17日 (日) まででお願いします。

この投稿の時点ではまだ分配金額が確定していないので、請求書は別途メールで提出いただければと思います。提出先はこちらです。
cpprefjp_org@googlegroups.com

請求書の内容としては、最低限、以下があれば大丈夫だと思います。適格事業者番号 (インボイス) がある方は記載してください。

- 請求書作成者の氏名 : ご自身の氏名
- 取引年月日 : 2023年1月1日から2023年11月30日
- 取引内容 : cpprefjp/boostjpの編集作業
- 取引金額 : (税込で指定金額を記載)
- 取引先の名称 : cpprefjp高橋晶

| user | base points | points | base rate | rate |
|------|-------------|--------|-----------|------|
| @faithandbrave | 6168 | 6168 | 44.8% | 0.0% |
| @yohhoy | 3276 | 3276 | 23.8% | 0.0% |
| @onihusube | 1983 | 1983 | 14.4% | 0.0% |
| @suomesta | 983 | 983 | 7.14% | 55.0% |
| @tomolatoon | 518 | 518 | 3.76% | 29.0% |
| @grafi-tt | 267 | 100 | 1.94% | 5.6% |
| @wx257osn2 | 114 | 114 | 0.828% | 0.0% |
| @h-sao | 89 | 89 | 0.646% | 4.98% |
| @yknishidate | 75 | 75 | 0.545% | 4.2% |
| @tetsurom | 60 | 60 | 0.436% | 0.0% |
| @tshino | 30 | 30 | 0.218% | 0.0% |
| @Reputeless | 30 | 30 | 0.218% | 0.0% |
| @kenichiice | 29 | 29 | 0.211% | 0.0% |
| @ROCKTAKEY | 22 | 22 | 0.16% | 1.23% |
| @acd1034 | 20 | 20 | 0.145% | 0.0% |
| @nu4nu | 16 | 16 | 0.116% | 0.0% |
| @sf624 | 15 | 15 | 0.109% | 0.0% |
| @sutatoruta | 14 | 14 | 0.102% | 0.0% |
| @komori-n | 11 | 11 | 0.0799% | 0.0% |
| @g-suizu | 10 | 10 | 0.0726% | 0.0% |
| @yumetodo | 7 | 7 | 0.0508% | 0.0% |
| @k-satoda | 5 | 5 | 0.0363% | 0.0% |
| @akinomyoga | 5 | 5 | 0.0363% | 0.0% |
| @sakujiro-inagaki | 5 | 5 | 0.0363% | 0.0% |
| @toru-fukaya | 5 | 5 | 0.0363% | 0.0% |
| @ToruNiina | 3 | 3 | 0.0218% | 0.0% |
| @HansRobo | 1 | 1 | 0.00726% | 0.0% |
| @yutopp | 1 | 1 | 0.00726% | 0.0% |
| @norisio | 1 | 1 | 0.00726% | 0.0% |
| @kamitani08 | 1 | 1 | 0.00726% | 0.0% |
| @cupro29 | 1 | 1 | 0.00726% | 0.0% |
| @KisaragiEffective | 1 | 1 | 0.00726% | 0.0% |
| @suzuki-kei | 1 | 1 | 0.00726% | 0.0% |

報酬受け取りの表明をいただいた方は以下：

- @tomolatoon 
- @h-sao 
- @suomesta 
- @ROCKTAKEY
- @grafi-tt 
- @yknishidate

**Comment by faithandbrave** [comment]
- 「辞退したけど、やっぱり報酬を受け取りたい」
- 「Nポイントまで落として報酬を受け取りたい」
-  「報酬受け取りを辞退する」

などのコメントもお待ちしております。

**Comment by k-satoda** [comment]
@faithandbrave お知らせ遅くなっちゃいましたが、報酬受け取りを辞退します。よろしくおねがいします。

**Comment by faithandbrave** [comment]
@grafi-tt 申請フォームから振込先の入力をお願いしますー

**Comment by faithandbrave** [comment]
分配金が決まりましたー。
1円未満の額については、最近接遇数への丸め (銀行丸め) で計算しています。

- 分配金の総額 : 169,308円

| user | rate | 分配金 | 手数料を引いた額 (実際のお支払額) |
|------|----|--------|-----|
| @suomesta | 55.0% | 93,120円 | 92,900円 |
| @tomolatoon | 29.0% | 49,100円 | 48,880円 |
| @grafi-tt | 5.6% | 9,482円 | (振込先がわかったら入力します) |
| @h-sao | 4.98% | 8,432円 | 8,432円 |
| @yknishidate | 4.2% | 7,110円 | 6,956円 |
| @ROCKTAKEY | 1.23% | 2,082円 | 2,082円 |

報酬を受け取られる方には、手数料を引いた額で振り込みます (全員分の振込先が集まり次第)。
請求書の作成と送付をお願いしますー。

**Comment by faithandbrave** [comment]
全員分の振込先がそろったので、朝起きたら銀行行ってきます！
(屋号付き口座はインターネットバンキングを使えないので銀行のATMで…)

**Comment by faithandbrave** [comment]
振り込み完了しましたー。
あとは、報酬を受け取られた方々から請求書が送られてきたらクローズします。

**Comment by faithandbrave** [comment]
請求書をいただいた方の管理用チェックボックス


- [x] @suomesta
- [ ] @tomolatoon
- [ ] @grafi-tt
- [ ] @h-sao
- [x] @yknishidate
- [ ] @ROCKTAKEY

**Comment by faithandbrave** [comment]
@h-sao @grafi-tt 
請求書の提出をお願いしますー。

**Comment by h-sao** [comment]
@faithandbrave 
12/19火に送ってあるのですが、届いてないですか？

**Comment by h-sao** [comment]
さっき、も一度転送しておきました。迷惑メールになってるのかもしれないです。
もしこれでも届いてないようならまた教えてくださいmm

**Comment by faithandbrave** [comment]
@h-sao もう一度送っていただいたのは届きましたー。ありがとうございます。
前に送っていただいたのはGoogle Groupのメーリングリストに届いてなかったので、設定を見直しておきます…

**Comment by grafi-tt** [comment]
@faithandbrave すみません、送信しました。

**Comment by faithandbrave** [comment]
@grafi-tt ありがとうございます。受領しました。

これで全員分の請求書をいただいたので、2023年分の報酬支払いは完了です。

**Comment by yumetodo** [comment]
確定申告の時期が近づいていますが、参考情報です。

https://github.com/azu/github-sponsors-tax
