### ISSUE TITLE
サイトのメニューがずっとロード中のままになってしまう

### ISSUE THREAD

**Issue by ROCKTAKEY** [cpprefjp/site#1229]
下記画像のように、サイドバーのメニューがずっとロード中になっています。FirefoxとEdgeで確認しました。

![image](https://github.com/cpprefjp/site/assets/20369462/c9bc49dd-ef94-4f12-ab94-7a7fda12004e)

今原因を調査する時間が私にないので、現象の報告だけさせていただきました。

**Comment by faithandbrave** [comment]
報告ありがとうございます。調べます。

**Comment by onihusube** [comment]
既存の名前付き要件を参考に修正してみましたがダメでした・・・

**Comment by faithandbrave** [comment]
あれ、直ってるように見えますよ。リロードの問題ではないですか？

**Comment by faithandbrave** [comment]
https://github.com/cpprefjp/cpprefjp.github.io

HTMLのデプロイ完了は、このリポジトリのコミットに✓ (チェックマーク) がついてるかでわかります。

**Comment by faithandbrave** [comment]
@onihusube
対応ありがとうございましたー。
問題なさそうなのでこれで閉じます

**Comment by faithandbrave** [comment]
CIも直しておきましたので、同じ原因の問題は起きなくなるはずです。
