### ISSUE TITLE
[C++26] 線形代数ライブラリ

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1233]
- [P1673R13 A free function linear algebra interface based on the BLAS](https://open-std.org/jtc1/sc22/wg21/docs/papers/2023/p1673r13.html)

## BLAS 1
- [x] setup_givens_rotation, setup_givens_rotation_result
- [x] apply_givens_rotation
- [x] swap_elements
- [x] scale
- [x] copy
- [x] add
- [x] dot
- [x] dotc
- [x] vector_sum_of_squares, sum_of_squares_result
- [x] vector_two_norm
- [x] vector_abs_sum
- [x] vector_idx_abs_max
- [x] matrix_frob_norm
- [x] matrix_one_norm
- [x] matrix_inf_norm

## BLAS 2
- [x] matrix_vector_product
- [x] symmetric_matrix_vector_product
- [x] hermitian_matrix_vector_product
- [x] triangular_matrix_vector_product
- [x] triangular_matrix_vector_solve
- [x] matrix_rank_1_update
- [x] matrix_rank_1_update_c
- [x] symmetric_matrix_rank_1_update
- [x] hermitian_matrix_rank_1_update
- [x] symmetric_matrix_rank_2_update
- [x] hermitian_matrix_rank_2_update

## BLAS 3
- [x] matrix_product
- [x] symmetric_matrix_product
- [x] hermitian_matrix_product
- [x] triangular_matrix_product
- [x] triangular_matrix_left_product
- [x] triangular_matrix_right_product
- [x] symmetric_matrix_rank_k_update
- [x] hermitian_matrix_rank_k_update
- [x] symmetric_matrix_rank_2k_update
- [x] hermitian_matrix_rank_2k_update
- [x] triangular_matrix_matrix_left_solve
- [x] triangular_matrix_matrix_right_solve

## Others
- [x] layout_blas_packed
- [x] scaled, scaled_accessor
- [x] conjugated, conjugated_accessor
- [x] transposed, layout_transpose
- [x] conjugate_transposed
- [x] column_major, row_major
- [x] upper_triangle, lower_triangle
- [x] implicit_unit_diagonal, explicit_diagonal

**Comment by yohhoy** [comment]
#1279

**Comment by sukeya** [comment]
@yohhoy レビューして頂きありがとうございます。
大体問題ないのですが、一部のページでレイアウトが崩れていました(以前から崩れていたかもしれません)。

- [vector_abs_sum](https://github.com/cpprefjp/site/blob/c7e4c78d7b4c106e9ba43a0c771aa937fe30d6f1/reference/linalg/vector_abs_sum.md)
- [vector_idx_abs_max](https://github.com/cpprefjp/site/blob/c7e4c78d7b4c106e9ba43a0c771aa937fe30d6f1/reference/linalg/vector_idx_abs_max.md)

vector_idx_abs_maxの方は更にargmaxが正しく出力されていませんでした。
後ほど修正する予定ですが、とりあえず報告しました。

**Comment by sukeya** [comment]
とりあえず全ての関数の記事を書きましたが、例が書かれていない関数は以下の通りです。
- [ ] setup_givens_rotation, setup_givens_rotation_result
- [ ] apply_givens_rotation
- [ ] swap_elements
- [ ] scale
- [ ] copy
- [ ] add
- [ ] dot

**Comment by sukeya** [comment]
提案文書を全部読むつもりでしたが、他にやることがあったり気力を保てなかったりしたため、読み切れそうにありません。
一通り記事を書いたのでこのタスクを閉じようと思うのですが、どうでしょうか？

**Comment by yohhoy** [comment]
@sukeya 大規模Paperの対応、お疲れ様でした！
追加内容が一通りカバーされているため、CLOSEで良い気はしています。

**Comment by faithandbrave** [comment]
大量の執筆ありがとうございます！
クローズしていただいて大丈夫です！追加で必要なことがあとから判明したら、気づいた人が直していきましょう

**Comment by sukeya** [comment]
cpprefjpにお世話になっているので、恩返しできて良かったです:)

了解しました〜
では、今後はその方針で追記することにして閉じようと思います。
