### ISSUE TITLE
cpprefjp 2023ステッカー申請

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1245]
- [申請フォーム](https://forms.gle/jp8EnjVWe6XZuKTU6)

cpprefjpのコントリビューターの皆さま向けに、cpprefjpステッカーを作成しようと思います。
デザインは以下です。

![cpprefjp-sticker2023](https://github.com/cpprefjp/site/assets/240038/3a26e6d8-44ed-40d8-8d11-d133b15a3fc2)

ステッカーの受け取り対象者は、2023年12月 **までに** cpprefjp / boostjpにコントリビュート (コミット) した方です。これはGoogle Sites時代も含みます。

2024年からはその年にコントリビュートされた方のみを対象とさせていただこうと思うので、2023年だけこれまでにコントリビュートされた方全員を対象とします。

ステッカーの受け取りを希望される方は、2週間後の2024年2月6日 (火) 23:59までに、一番上の申請フォームから申請をお願いします。
発送時期は、2024年3月中までには完了させる見込みです。その時期に引っ越しを予定されていたり日本にいないという方などは、発送時期を遅らせることもできますので、申請フォームのコメント欄から個別の希望を教えてください。

受け取りを希望された枚数 + 予備として数枚しか作らないので、申請はお早めにお願いします。

**Comment by yumetodo** [comment]
駆け込みですが申請送りました、よろしくお願いします

**Comment by faithandbrave** [comment]
ステッカーの申請を締め切りましたー。
お伝えするのを忘れてましたが、ステッカーはこれから発注するので、お渡しは2/9(金)のC++ MIXには間に合わないです… (手渡しは次回のつもりでした)。

**Comment by faithandbrave** [comment]
私の手元に届いたら、引っ越し予定の方には個別に住所確認の連絡をします。

**Comment by faithandbrave** [comment]
ステッカーを発注しました。
私の手元には2024年2月22日くらいに届くと思います。

**Comment by yumetodo** [comment]
>お渡しは2/9(金)のC++ MIXには間に合わないです… (手渡しは次回のつもりでした)。

あ、そうなんですね、すると次回C++MIX出られるかちょっと定かではないので郵送のほうがありがたいです。

**Comment by faithandbrave** [comment]
@yumetodo 
りょうかいです

**Comment by faithandbrave** [comment]
ステッカーが届きました。
仕上がりは問題なさそうでしたので、これでみなさんに本日 (2/22木) 発送する予定です。

**Comment by faithandbrave** [comment]
普通郵便で発送したので、連休明けくらいからみなさんのお手元に届きはじめると思います。
一週間ほどしても届かなかったら教えてください。予備も数枚あるので再発送します。

**Comment by yumetodo** [comment]
![DSC_3532](https://github.com/cpprefjp/site/assets/10869046/9204333c-944b-4f70-9741-534cec4a5718)

無事に届きました、ありがとうございます！
