### ISSUE TITLE
範囲for文範囲初期化子内の一時オブジェクト延命の説明見直し

### ISSUE THREAD

**Issue by yohhoy** [cpprefjp/site#1246]
C++23言語機能「範囲for文が範囲初期化子内で生じた一時オブジェクトを延命することを規定」(#1111) の説明にある、一時オブジェクト延命の対象外となる例外条項に疑問があります。

> ただし、次の場合には適用されない。
> - 一時オブジェクトが関数の引数の場合
> - 一時オブジェクトの(この規定が適用されない場合の)寿命が  for-range-initializer  完全式の終わりではない場合

提案文書 [P2644R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2644r0.pdf) を読む限り、上記記載のような例外は存在せず for-range-initializer で生成された全ての一時オブジェクトはfor文末尾まで延命されるように思えます。

cc: @tetsurom さん

**Comment by faithandbrave** [comment]
とくに制限はないように見えます。

**Comment by tetsurom** [comment]
P2644R0の記述は

> The fourth context is when a temporary object is created in the for-range-initializer of a rangebased for statement. Such a temporary object persists until the completion of the statement. 

で、(おそらく)当時参考にしたページ(https://timsong-cpp.github.io/cppwp/class.temporary)は

> The fourth context is when a temporary object *other than a function parameter object* is created in the for-range-initializer of a range-based for statement. *If such a temporary object would otherwise be destroyed at the end of the for-range-initializer full-expression,* the object persists *for the lifetime of the reference initialized by the for-range-initializer.*

となっていて、執筆時に後者の記述をそのように解釈したものと思われます。ただ、この変更はC++23の範囲内で行われたのか、C++26相当なのかは考えていませんでした。

**Comment by yohhoy** [comment]
> 提案文書 [P2644R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2644r0.pdf) を読む限り(後略)

すみません🙇 最終採択文書の勘違いに端を発していますね。正しくは [P2718R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2718r0.html) を参照すべきでした。

**Comment by yohhoy** [comment]
> このサンプルとしては、P2718で追加されているこちらの例が一番分かりやすい（分かりやすいとは言ってない）かと
> ```cpp
> using T = std::list<int>;
> const T& f1(const T& t) { return t; }
> const T& f2(T t)        { return t; }
> T g();
> 
> void foo() {
>   for (auto e : f1(g())) {}  // OK, lifetime of return value of g() extended
>   for (auto e : f2(g())) {}  // undefined behavior
> }
> ```

まさに当該箇所に関して、StackOverflowの質問 [Are function parameter objects temporary objects?](https://stackoverflow.com/questions/77676199/) への回答で言及されていました。

> So the "other than a function parameter object" wording is referring to the parameter `t` of `f2`.

この回答解釈に従えば、`f2`はRange-based forでなくともUBを引き起こすケースですから、"a temporary object other than a function parameter object" と明示的に除外されているのも納得感があります。

**Comment by yohhoy** [comment]
本件、 @tetsurom さんのオリジナル説明に致命的な誤りはなく、私(yohhoy)の誤解によるものと理解しています。大変失礼しました。

> 現在の記述は間違ってはいないにしても誤解を招く表現かもしれません。

@onihusube さんが指摘するように、疑問を抱いた一因は「一時オブジェクトが関数の引数」を例示サンプルでいう「`f1`/`f2`関数の実引数に与える`g()`戻り値としての一時オブジェクト」と誤解釈したためでした。

> このサンプルコードを盛り込むなどして、分かりやすくしたほうがいいですね。

サンプルコードの引用、賛成です。ただ、補足説明がないとかなり難解な例示コードですね...

**Comment by onihusube** [comment]
```cpp
using T = std::list<int>;
const T& f1(const T& t) { return t; }
const T& f2(T t)        { return t; }
T g();

void foo() {
  for (auto e : f1(g())) {}  // OK, lifetime of return value of g() extended
  for (auto e : f2(g())) {}  // undefined behavior
}
```

この例について少し考えていましたが、本質的には`f2`のローカル変数（関数引数）`t`への参照を返しているのがUBの原因で、（一般的に）一時オブジェクトと呼ばれるものは生成されていない気もしてきました。`f() -> t`はコピー省略によって直接構築されるはずで、それは`f2()`内では立派な左辺値です。

このような`f2()`の呼び出し時に作成されるローカルオブジェクトの事を外から見て一時オブジェクトと呼ぶのかはわかりませんが。むずかしいですね・・・

**Comment by faithandbrave** [comment]
記事の参照欄に、対応する提案文書も書いておいていただければ。
https://cpprefjp.github.io/lang/cpp23/lifetime_extension_in_range_based_for_loop.html

**Comment by yohhoy** [comment]
a199a4943b749cbfa776d0ff75a77bd6ec885fea 時点で残っている P2718R0 Annex C 引用コードは、C++20／C++23で挙動が変わってしまうエッジケースのニュアンスが強いので、読者の混乱をさけるために削除したほうが良いと思いました。いかがでしょう。

> 範囲for文の危険性を減らすだけではなく、この仕様はRAIIのためのオブジェクトを無名で作るのに使うことができる。
> ```cpp
> // P2718R0より引用
> void f() {
>     std::vector<int> v = { 42, 17, 13 };
>     std::mutex m;
>     for (int x : static_cast<void>(std::lock_guard<std::mutex>(m)), v) {
>         ...
>     }
> }
> ```

上記以外の加筆・修正頂いた内容については、追加コメントはありません。

**Comment by tetsurom** [comment]
確認ありがとうございます。確かに、積極的に使っていくものではなさそうな印象だったので、削除しました。

**Comment by yohhoy** [comment]
> 仮に第1センテンスが "a temporary object <del>other than a function parameter object</del> is created in the for-range-initializer of a range-based for statement." では、Range-based for構文の式 for-range-initializer に起因して生じる全ての一時オブジェクト（例示f2関数内部の引数tを含む）が延命されることになってしまう

上記言及に関して、[CWG 2849 Parameter objects are not temporary objects](https://wg21.cmeerw.net/cwg/issue2849) がDefect Reportとして採択され、当該Wording箇所 "other than a function parameter object" が削除されていました...

本Issueで議論された結論には影響なさそうです。おそらく。
