### ISSUE TITLE
疑問: nullptr_t 引数のコンストラクターに noexcept がない?

### ISSUE THREAD

**Issue by kazssym** [cpprefjp/site#1249]
`shared_ptr(nullptr_t)` のコンストラクターで `noexcept` がないのは正しいでしょうか

https://github.com/cpprefjp/site/blob/8250474933368f71448e5a3cad3eb78d0f101ed2/reference/memory/shared_ptr/op_constructor.md?plain=1#L53

**Comment by kazssym** [comment]
これですかね
https://cplusplus.github.io/LWG/lwg-defects.html#2365

**Comment by onihusube** [comment]
[C++20のドラフト](https://timsong-cpp.github.io/cppwp/n4861/util.smartptr.shared#:~:text=constexpr%20shared_ptr(nullptr_t)%20noexcept%20%3A%20shared_ptr()%20%7B%20%7D)だと`noexcept`はついてるので、あるのが正しいですね。

ご指摘のLWG Issue2365がC++17に対して適用されたことで付くようになったのだと思われます。このような細かい（個別の提案になってないような）Issueの対応は手が回らない面があります・・・

**Comment by faithandbrave** [comment]
こちら、どなたが修正されますか？
@kazssym さんの方で修正・Pull Requestを作成されますか？

**Comment by kazssym** [comment]
急ぐ必要がなければ手をつけるかと思いますが、それで良ければ

**Comment by faithandbrave** [comment]
急いでないので、お手すきのときにお願いします！
