### ISSUE TITLE
雑多な議論をする場所の相談

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1267]
たまにX/Twitter上で「cpprefjpがもっとこんな感じだったらいいのに」という意見が上がることがありますが、多くの場合はその意見をした方がissueを起こすまでには至らず、改善につながらない取りこぼしがたくさんがあるのではないかという危惧があります。

issueを起こすハードルが高いようであれば、問題提起とまでいかなくても気軽に意見・感想を言える場所があったほうがいいのかもしれません。

Slack / Discordを用意しているOSSプロジェクトも多数あるかと思いますが、ログが一定期間で消滅してしまうことや、Google検索に引っかからず情報蓄積ができない問題があると思います。

私の提案としては、GitHub Issueのピン留め機能を使って、閉じないissueとして「cpprefjp雑談部屋」を作ってはどうだろうかと考えました。
そこで出た意見で詳細な議論が必要なら別issueを立てるという運用ができそうな気がしています。
issueは個別に通知がこないよう設定できるので (unsubscribe)、雑談でぽんぽん通知がくることに興味がない人はその機能を使ってもらえばよいかと思います。
「X/Twitterでこんな意見があったよ」というのも、そのissue上で拾いあげて相談できるといいのかなと思いました。

いかがでしょうか？ご意見お待ちしております。

**Comment by faithandbrave** [comment]
GitHub Discussionsを使わない提案にしてる理由としては、ひとまず1部屋あれば十分そうだからですね。
テーマ別の部屋がたくさん必要になったらGitHub Discussionsを検討してもいい気がしますが、現在のアクティブメンバー数を考えると、必要性はそんなに高くない気がしています。

**Comment by faithandbrave** [comment]
専門分野ごとの相談ごとをしたい場合は、その限りではないと思います。

**Comment by yumetodo** [comment]
小さく始めるという点でいいのではないでしょうか？

**Comment by h-sao** [comment]
issueだとDiscordに比べると、発言の敷居そのものはやはり上がる気はします

> issueを起こすハードルが高い

起こすハードルもあるし、書き込むのもそれなりの気合いが必要な方も居ると思います
Githubは完全に証跡が付くので、そこまで真剣に考えたわけじゃないんだけど…の様な意見は確かに書き込みにくいです
（こんなけ書き込んでるわたしも、そういう雑多な意見は書き込みにくい）

しかしやってみないと判らない所はあると思うので、ゆるめ雑談issueを作ってみて、運用してみるのは賛成です
特に

> 「X/Twitterでこんな意見があったよ」というのも、そのissue上で拾いあげて相談

これなどは、早速出来そうな気はします

**Comment by faithandbrave** [comment]
ネガティブな意見はなさそうでしたので、雑談部屋issueを作るという方向で検討を進めましょう。
運用ルール案を考えてみますので、少しお待ちください。

**Comment by faithandbrave** [comment]
最初からあまり縛りを強くしたくない気はしますが、ルールのたたき台を考えてみました。

```
cpprefjp雑談部屋ルール

- issueに起こすほどでもない雑多な議論をする場所です
- 通知がうるさいと感じた方は、issue個別で通知をオフにできるので、そちらをご利用ください
- 個人のつぶやきをゆるく投稿してもらってOKです
- cpprefjpメンバー以外の投稿も歓迎します
- X/Twitterなど、ほかの場所で発せられたcpprefjpの問題などがあったら、ここで教えてください (issueを起こしてもらってもOKです)
- ここで始まった話題で詳細な議論が必要になってきたら、ぜひissueを起こして移動してください
- 専門分野ごとの部屋が必要になってきたら、部屋を分けることを検討します
- 質問掲示板というわけではないので、回答が得られることは期待しないでください
- だれかが議論していても、気にせず別な話題を投稿してください
- 攻撃的な批判、ハラスメント行為、ヘイトなどは禁止とします
```

**Comment by faithandbrave** [comment]
話題の制限はいまのところしない想定でいましたが、懸念があったら教えてください。
荒らしがいたら私の独断で追い出しますが、GitHubアカウントで稚拙なことをするユーザーは多くない気がしています。

**Comment by faithandbrave** [comment]
https://github.com/cpprefjp/site/issues/1273

**Comment by faithandbrave** [comment]
雑談部屋を作ってピン留めしましたー
