### ISSUE TITLE
数式ブロックのインデントを見直す

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1284]
> [sukeya](https://github.com/sukeya) commented [15 hours ago](https://github.com/cpprefjp/site/issues/1273#issuecomment-2131243988)
> こんばんは。
些細なことなのですが、LaTeXで書いた数式が左詰めになっているように見えてちょっと気になりました(例えば[ここ](https://cpprefjp.github.io/reference/linalg/setup_givens_rotation.html))。
個人的には引用くらいのスペースが前につくとより見やすくなると思いました(例えば[ここ](https://ja.wikipedia.org/wiki/%E3%83%8A%E3%83%93%E3%82%A8%E2%80%93%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%82%B9%E6%96%B9%E7%A8%8B%E5%BC%8F))。

調べました。

MathJaxのこのへんの設定をいじれば、数式ブロック (displayMath) のインデントを変更できそうです。
https://github.com/cpprefjp/site_generator/commit/94b9dcb2a2f4b609adee36b9fcc50b4e60b1be29

設定のドキュメントはこちら。
- [TeX Input Processor Options - MathJax](https://docs.mathjax.org/en/latest/options/input/tex.html)

私の手が空いたら着手しようと思いますが、どなたか引き取れそうだったら引き取ってください。

**Comment by faithandbrave** [comment]
@sukeya 
直りました。
これくらいでどうでしょう？

**Comment by sukeya** [comment]
素早い対応ありがとうございます！
見やすくなり、良いと思います。

**Comment by faithandbrave** [comment]
ではこれで閉じますー

**Comment by yumetodo** [comment]
@faithandbrave　すみません、 `https://polyfill.io/v3/polyfill.min.js?features=es6`って何目的で読み込んでいる感じでしょう？

**Comment by faithandbrave** [comment]
はい、MathJax v3のドキュメントに従っています。

**Comment by yumetodo** [comment]
cpprefjpではIE11をサポートしていないので、
https://caniuse.com/promises
を見る限り、不要なのではないかと思うわけです。

ref: https://github.com/cpprefjp/site/issues/477#issuecomment-343039905

**Comment by faithandbrave** [comment]
たしかにIE11用っぽいので、削除しちゃってよさそうな気がしますね
https://docs.mathjax.org/en/latest/web/start.html#browser-compatibility

**Comment by akinomyoga** [comment]
後で見た時に「なぜ MathJax 標準ではないロードの仕方をしているんだ」という疑問が生じるので、何故 polyfill 入れないのかコメントを入れるならそれで良いと思います。あと、IE11 対応しないとしても、後続の MathJax で余計なエラーが出ない様に [IE 除外](https://ja.wikipedia.org/wiki/%E6%9D%A1%E4%BB%B6%E4%BB%98%E3%81%8D%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88) できませんか? こんな感じでしょうか:

```html
<!--[if !IE]><!-->
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>
<!--<![endif]-->
```

**Comment by faithandbrave** [comment]
@yumetodo どうでしょう？

**Comment by yumetodo** [comment]
反応が遅れました。

#477 が議論された2017年には、まだIEは無視できないシェアがあり、故に「エラーが出ても最低限表示できるようにする」という方針がとられたのは妥当だったと言えるでしょう。

しかしIE11を無効化するKBが配布されるようになった今、IE11が動作する環境は、WindowsのサーバーOSか、LTSC版を用意する必要があり、(仕事柄職場には検証環境ありますが)、私物の検証環境を作って維持するのは大変です。また多くのユーザーはIEを回避する選択肢を持ち合わせているはずです。

そういうわけで、このissueからは外れてきてしまいますが、そもそもIEのサポートを明示的に切っておきたいです。

---

そのうえで、 @akinomyoga さん提案の条件付きコメントですが、リンク先にも記載のある通り、こちらはIE5-IE9まででサポートされた記法であり、IE11では単なるコメントとして認識されます。その他のブラウザでも同様です。したがって、今回のケースでIEでのみ読み込ませることを目的として条件付きコメントを使うことはできません。どうしてもそういうことをするならUser-Agentを見て出し分けるWebサーバーが必要になるでしょう。

---

以上の2点から、単にpolyfillを除去しておく、あるいは

```html
<-- IEはサポートしないので https://polyfill.io/v3/polyfill.min.js?features=es6 は読み込まない -->
```

等としておくのがいいのではないでしょうか(この場合、templateエンジン向けのコメント記法があればそっちのほうがbetter)。

**Comment by faithandbrave** [comment]
Microsoftがサポートを終了しているブラウザですから、正しく動かないのはIEユーザーの自己責任として、yumetodoさん案のコメントアウトで対応としては十分な気がしますね。がんばりどころではない気がします。

```
<!-- IEはサポートしないので https://polyfill.io/v3/polyfill.min.js?features=es6 は読み込まない -->
```

**Comment by yumetodo** [comment]
>IE を明示的に切るというと、IE で開いたら対応していませんページにジャンプするなどですか。

あ、いえ、IEで壊れるかどうかを検討しないという意味合いでした。

**Comment by faithandbrave** [comment]
5月のGoogle Analyticsのレポートを確認したところ、アクティブユーザー5.86万人のうち、IEユーザーは15人でした

**Comment by faithandbrave** [comment]
では、コメントアウトしますね

**Comment by faithandbrave** [comment]
polyfillの読み込みをコメントアウトしました。
https://cpprefjp.github.io/reference/cmath/cos.html
数式は問題なく動いてそうです。

これで閉じます。
問題あったらまたreopenしてください。
