### ISSUE TITLE
カッコと括弧の表記揺れ

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1295]
サイト内で「カッコ」と「括弧」で表記揺れしているのでどちらかに統一したいです。

プログラミングの文脈ではどちらも多く使われているようですが、希望があれば教えてください。

私としては「カッコ」の方がよいと考えます。これは漢字が連続すると読みにくいため、ひらがな・カタカナ・漢字のバランスをとるために「カッコ」の方が文章内で使いやすいという考えです。

**Comment by yohhoy** [comment]
2024/7/11時点で「カッコ」優勢ですし、読みやすさを考慮した「カッコ」表記に一票投じます。

```sh
$ find . -name "*.md" | xargs grep "カッコ" | wc -l
138
$ find . -name "*.md" | xargs grep "括弧" | wc -l
26
```
