### ISSUE TITLE
cpprefjp Tシャツの制作について

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1296]
- [ゲーム開発者のための C++17～C++23, 近年の C++ 規格策定の動向 - CEDEC 2024](https://cedec.cesa.or.jp/2024/session/detail/s6609118bb9dfd/)

今年もCEDEC (ゲーム開発者のカンファレンス) にて、cpprefjp所属の方の発表があります ( @Reputeless , @tetsurom , @onihusube  )。
それに合わせて、発表者用にcpprefjpのTシャツを作ろうとしています。

cpprefjpのコントリビューターおよびスポンサーの方も、実費をいただければ発注しようと思います。

## デザイン

【白】
![cpprefjp T-shirt](https://github.com/cpprefjp/site/assets/240038/71da4f09-cf10-4d64-b8e6-be9c3b57c093)

(追加)【ロイヤルブルー】
![cpprefjp T-shirt blue bright](https://github.com/cpprefjp/site/assets/240038/2bdda5bb-cf14-422a-94b8-6c634186469f)

## 価格
価格は枚数次第ではありますが、以下のようになると思います。

- 3,313円 (送料無料)

- 個人ごとのカラーごとに発注します
- 発注サイト上で送料無料なので、自分でレターパックライト (370円) を使って発送するよりも、1枚分を発注して送料無料にしたほうが安かったです

## Tシャツの素材

Tシャツの素材としては、スポーツでも使いやすい速乾・吸汗のもので、以下の商品になります。サイズは一人ひとり選べます。

- [glimmer 4.4オンス ドライTシャツ - ラクスル](https://novelty.raksul.com/products/226?psi=52712&quantity=5&trial=false&plain=false)

## 申請方法、支払い方法
- [cpprefjp Tシャツ2024 - Googleフォーム](https://forms.gle/sgA9fiWV4fas1hm47)

上記の申請フォームから申請をお願いします。
2024年8月1日 23時59分までに申請があった分を発注させていただきます。

支払い方法と金額は、申請フォームに入力いただいたメールアドレスに個別にご連絡させていただきます。
4枚以上を発注される方がいた場合は、発送方法の相談も個別にさせていただければと思います。

<del>
## このあとの流れ
このあとの流れですが、以下のように進めようと思います。

1. 発表者向けのが届いたら、商品の質を確認 (7月20日くらいに届く予定)
2. 発送先の入力フォームを用意して、みなさんに書いてもらう (2週間程度の募集期間を設ける)
3. かかった費用の振込先 (私宛、銀行振込) を、フォームに入力していただいたメールアドレスに個別にご連絡
</del>

## 応相談

<del>Tシャツのカラーは白のみですが (別カラーは別でお金がかかるので)、お金がかかってもいいから別カラーがほしい、という方がいたら相談させてください。</del>
カラーは現在、白とロイヤルブルーを予定していますが、別カラーの希望もあればご意見ください。カラーごとの希望者が少なければその分お高くなってしまうので、その点ご了承ください。
ご不明点や相談ごとがあれば教えてください。

なお、cpprefjpのアイコンは.svgファイルは以下の場所にありますので、個人でグッズ制作することに対する制限は、とくに考えておりません。

- <https://github.com/cpprefjp/image/tree/master/cpprefjp/icon>

**Comment by faithandbrave** [comment]
「cpprefjpコントリビューター」には、スポンサーの方も含みます！

**Comment by faithandbrave** [comment]
@sukeya
了解しました〜。別カラーでもし1枚の注文になると、単価が3,313円になってしまいますが、それでもよいでしょうか？
ロイヤルブルーの希望がもしお一人だけだったら、私のほうでデザイン案だけ作って、ご自身で注文していただいた方が送料分だけ安くなるかもですね。

一旦、ロイヤルブルーでのデザイン案を作ってみます。

**Comment by faithandbrave** [comment]
それとTシャツの注文について、コントリビューター限定の機会とするためにデザインデータはいまのところ非公開にしていますが、これについて公開しても問題ないという考えの方がいたら、それもご意見いただければと思います。

**Comment by faithandbrave** [comment]
ロイヤルブルーのTシャツデザインです。
黒文字 → 白文字にしました。

![cpprefjp T-shirt blue](https://github.com/cpprefjp/site/assets/240038/42cce1b0-dfa1-4206-933c-f7ab5c897253)

**Comment by sukeya** [comment]
デザインしていただきありがとうございます！
私だけかもしれませんが、ロイヤルブルーが暗めの色なので、プログラムの白以外の文字が若干見にくく感じました。
それらも明るい色にすると見やすくなるかもしれません^^;

**Comment by faithandbrave** [comment]
白以外の文字色を明るくしてみました。これでいかがでしょう。

![cpprefjp T-shirt blue bright](https://github.com/cpprefjp/site/assets/240038/f3541e36-4409-4219-933e-e852dbb49b4f)

**Comment by sukeya** [comment]
ありがとうございます!
かなり見やすくなりました。

**Comment by faithandbrave** [comment]
確認ありがとうございます。ではブルーはこれでいきましょう。
ほかの方も、カラー要望などあればご意見ください。

**Comment by faithandbrave** [comment]
それと考慮不足でしたが、1人1枚の縛りはとくになくてよいかと思います。
2枚以上の方にはレターパックライトでは送れないと思うので、ほかの発送方法も検討しておきます。
とくにスポンサーの方は複数枚の注文をされる場合があるかもしれません。

**Comment by faithandbrave** [comment]
一番上のコメントを、最新情報に更新しました。

- ロイヤルブルーを追加
- ほかのカラーも希望があれば相談ください
- 2枚以上の注文の場合は、送料がお高くなります

**Comment by yumetodo** [comment]
ロイヤルブルーかっこいいので欲しくなりました。

**Comment by faithandbrave** [comment]
ホワイトのTシャツが届きました〜。
品質としては問題なさそうでしたので、申請フォームを用意しますー

![tshirt](https://github.com/user-attachments/assets/386fbe4b-7348-4eac-b5df-a434efce82f5)

**Comment by faithandbrave** [comment]
- [cpprefjp Tシャツ2023 - Googleフォーム](https://forms.gle/sgA9fiWV4fas1hm47)

Tシャツの申請フォームを作りました〜。
8月1日 23時59分までに申請があった分を発注させていただきます。

支払い方法と金額は、申請フォームに入力いただいたメールアドレスに個別にご連絡させていただきます。
4枚以上を発注される方がいた場合は、発送方法の相談も個別にさせていただければと思います。

このコメントは、一番上の投稿にも記載しておきます。
それでは、申請お待ちしております〜。

**Comment by h-sao** [comment]
1枚白で申請しました！
ところで、フォームには住所の記載はありますが、宛名（氏名）の記載をする場所がないです
郵送するなら宛名は合ったほうがいいのではないでしょうか？

**Comment by faithandbrave** [comment]
ありゃ、失礼しました。
申請フォームに宛名を追加しました。

@h-sao 
回答の編集を許可しましたので、お手数ですが入力お願いします。

**Comment by faithandbrave** [comment]
あ、ロイヤルブルーは私も1枚発注します。

**Comment by wx257osn2** [comment]
Tシャツ2023，2023…？😵 (白1, ロイヤルブルー1で投げました)

**Comment by faithandbrave** [comment]
2024でした。直しました

**Comment by faithandbrave** [comment]
- [glimmer 4.4オンス ドライTシャツ - ラクスル](https://novelty.raksul.com/products/226?psi=52712&quantity=5&trial=false&plain=false)

こちらの商品がそもそも送料無料でした。
なので、送料の請求はなしで、発注サイトから直接発送してもらうようにします。

**Comment by h-sao** [comment]
@faithandbrave 
編集リンクが分からなくなったので（ほんまごめん）
青も追加で頼みました
 (合わせて、白1, ロイヤルブルー1でお願いします)

**Comment by faithandbrave** [comment]
ありゃ、お手数おかけしました。

**Comment by faithandbrave** [comment]
価格は結局、1カラーあたり3,313円になりそうですね。
一人ごとカラーごと発注して送料無料にするのが一番安くなりそうなので。

一人で同じカラーを大量発注すると話は変わってきますが…

**Comment by faithandbrave** [comment]
価格がころころ変わってすいません。。。

**Comment by sukeya** [comment]
すみません。サイズは指定できますか？

**Comment by faithandbrave** [comment]
すいません、完全に忘れてました。
サイズのラジオボタンを追加しました。

すいませんが、すでに入力していただいた方は、サイズを教えてください。
公開したくない方は、私にDMをください。

mail:
faithandbrave@gmail.com

X:
cpp_akira

**Comment by wx257osn2** [comment]
> すでに入力していただいた方は、サイズを教えてください。

編集リンクをサルベージできたので編集しときました

**Comment by faithandbrave** [comment]
Tシャツのサイズ情報、全員分いただきました〜。
申請フォームに書く場所がない要望があれば、一番下に「自由入力欄 (要望などあれば)」を用意したのでそちらに書いてください。

**Comment by faithandbrave** [comment]
Tシャツの申請期間が1週間をきりましたー。8月1日までの申請お待ちしております。

**Comment by faithandbrave** [comment]
明日 (8月1日) までですー

**Comment by faithandbrave** [comment]
申請を締め切りましたー。

そしてごめんなさい。
ホワイトは全員分の発注をして8月19日に出荷予定なのですが、、、
ロイヤルブルーが在庫なしになってしまいまして、いまは入荷待ちになっています。こちら申し訳ありませんが入荷されるまでお待ちいただくことになりそうです。
毎日ウォッチしておきます！すいません！

**Comment by faithandbrave** [comment]
それからもう一つごめんなさい！
Tシャツ単価につきまして、3,313円 (送料込み) とアナウンスしていましたが、ロイヤルブルーは少し高くて3,505円 (送料込み) でした！
確認不足ですいません。。。

**Comment by faithandbrave** [comment]
ホワイトは発送されたようです。一週間ほど経っても届かない方はご連絡ください。

**Comment by faithandbrave** [comment]
ロイヤルブルーの在庫がなかなか復活しませんね…。

ひとまず、ホワイトカラーのみ発注いただいた方に、請求書を送らせていただきました。
銀行振込かPayPayを指定しておりますが、ほかの送金方法がよい場合は個別にご相談させてください。

**Comment by faithandbrave** [comment]
ロイヤルブルーの在庫が復活したので発注しますー

**Comment by faithandbrave** [comment]
全員分の発注が完了しましたー。
ロイヤルブルーの発送は9月3日の予定です。発送予定日から一週間程度が経っても届かない場合は、ご連絡ください。

発送予定日から一週間程度が経ち、問題が起きてなさそうでしたら、私から請求書をメールでご連絡させていただきます。
faithandbrave@gmail.com から連絡が行きます。

それでは到着までしばらくお待ちください。

**Comment by yumetodo** [comment]
無事に到着しました！見落としてなければまだ請求書は来ていないと思うのでお待ちしています。

**Comment by faithandbrave** [comment]
(ホワイトカラーのみ以外をご注文の方) 全員に、請求書を送りましたー。
問題が起きてなさそうなら、一週間程度でこのissueを閉じます！

今回はCEDECの発表に合わせてTシャツを作ったので、来年また作るかは未定です (C++の更新もないですし)。
要望があればグッズは検討するのと、今回のTシャツが追加でほしくなった方がいたらできるだけ要望にお応えしたいと思います。
雑談部屋や、私へのDMなどでご相談くださいませ。
