### ISSUE TITLE
markdownの番号付きリストが正しく出力されない

### ISSUE THREAD

**Issue by sukeya** [cpprefjp/site#1298]
以下のページで番号付きリストが正しく出力されません。

- [reference/linalg/matrix_inf_norm](https://cpprefjp.github.io/reference/linalg/matrix_inf_norm.html)
- [reference/linalg/matrix_one_norm](https://cpprefjp.github.io/reference/linalg/matrix_one_norm.html)

どちらのページも「戻り値」節の「(1),(2)」節の「もし、〜」と「そうでないなら、〜」が番号付きリストですが、ただのリストになってしまっています。
どなたか修正してもらえると助かります。

**Comment by faithandbrave** [comment]
直りました〜。インデントが足りてなかったようです。2スペース → 4スペース
