### ISSUE TITLE
utility.md 内の見出しが間違っている

### ISSUE THREAD

**Issue by reika727** [cpprefjp/site#1302]
この部分の見出しが「列挙型」となっていますが、誤りかと思われます。
https://github.com/cpprefjp/site/blob/d035fff53945c2ee8fb4fd006156e74e510f20eb/reference/utility.md?plain=1#L71-L75

**Comment by sukeya** [comment]
ご指摘ありがとうございます！

@yohhoy 
見出しをどうしましょうか？
私は「アサーション」くらいでいいかなと思いました。

**Comment by yohhoy** [comment]
指摘Thanks 1b669b142f7641f9d1239543ab39082ccb21dc26 でのコピペミス（変更漏れ）ですねorz

[<utility>ヘッダ仕様記述](https://eel.is/c++draft/utility.syn) では "unreachable" となっているため、関数説明と合わせるなら「不到達表明」とかでしょうか。

```cpp
// [utility.unreachable], unreachable
[[noreturn]] void unreachable();
```

**Comment by faithandbrave** [comment]
漢字の連続がしんどそうなので、私は「到達しない表明」でもいいのかなという気がしました

**Comment by yumetodo** [comment]
規格書の記述を無視して俯瞰してみると、もう少し大きな分類でくくって「最適化支援」というのもありかなと思いましたが、他のものもないので「到達しない表明」でいいかなと思います。

**Comment by yohhoy** [comment]
「到達しない表明」 がよさそうですね。
@reika727 さんで修正されますか？ or 私(yohhoy)が対応してもよいです。

**Comment by reika727** [comment]
@yohhoy 
ご提案の通り修正いたしました。https://github.com/cpprefjp/site/pull/1303
ありがとうございました。m(_ _)m
