### ISSUE TITLE
P2362R3「1ワイド文字に収まらないワイド文字リテラルを禁止する」の記事でLが抜けている？

### ISSUE THREAD

**Issue by Kiterai** [cpprefjp/site#1304]
https://cpprefjp.github.io/lang/cpp23/remove_non_encodable_wide_character_literals_and_multicharacter_wide_character_literals.html

誤
```cpp
wchar_t a = '🤦'; // C++20:OK, C++23:OK \U0001f926
wchar_t b = 'ab'; // C++20:OK, C++23:NG マルチキャラクタリテラル
wchar_t c = 'é́';  // C++20:OK, C++23:NG \u0065\u0301
```
正
```cpp
wchar_t a = L'🤦'; // C++20:OK, C++23:OK \U0001f926
wchar_t b = L'ab'; // C++20:OK, C++23:NG マルチキャラクタリテラル
wchar_t c = L'é́';  // C++20:OK, C++23:NG \u0065\u0301
```

だと思うのですが、一応他の人のチェックが欲しいのでissue建てさせて頂きました

**Comment by faithandbrave** [comment]
報告ありがとうございます。
ご指摘の修正内容でOKだと思います。

**Comment by Kiterai** [comment]
ご確認ありがとうございました。修正をコミットしました。 https://github.com/cpprefjp/site/commit/bf71e354c80718e23c67361e31b83a23d91eb184
