### ISSUE TITLE
[C++26][ライブラリ] mdspanに対するdextents指定の冗長さを解決するstd::dimsを追加

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1310]
- [P2389R2 `dextents` Index Type Parameter](https://open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2389r2.html)

**Comment by yohhoy** [comment]
0ed791c866e8d0547c8bee66e80ee33d41eead5f 対応済み
