### ISSUE TITLE
[C++26][ライブラリ] mdspanのlayout_left_paddedとlayout_right_padded

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1341]
- [P2642R6 Padded `mdspan` layouts](https://open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2642r6.pdf)

これはもうおわってる気がするので、確認したら作業者をassignして閉じます。

**Comment by yohhoy** [comment]
こちら、現時点(2024-08-08)では対応途中だったかもしれません。

**Comment by yohhoy** [comment]
メンバ関数群の例示コードは未記述なのですが、低需要かつ `layout_{left,right}` とさほど変わらないため一旦完了とさせてください。
