### ISSUE TITLE
[C++26][ライブラリ] spanとmdspanの推論補助を改善

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1342]
- [P3029R1 Better `mdspan's` CTAD](https://open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3029r1.html)

**Comment by yohhoy** [comment]
17c594a2e02c0f17280415486fc4491812ca4e0c
417ea3031d564d8c68fec29786bde9de0c2f56ea
