### ISSUE TITLE
未定義動作を表す「未定義」に「未定義動作」用語を使うようにする

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#1347]
- https://github.com/cpprefjp/site/issues/1321

> [tshino](https://github.com/tshino) commented [13 hours ago](https://github.com/cpprefjp/site/issues/1321#issuecomment-2310266458)
> 「～の動作は未定義である」のように元の表現「未定義(の)動作」を変形する言い回しはもともと要注意ですね。現状でも検索すると「未定義」がUB以外の意味で使われていそうなのに「未定義の動作」のポップアップが出るところがあります。
> この問題は別の議論になりますが、例えば用語のユニーク性が低ければ用語を切り取ったり倒置する表現は避けるなどの編集ルールで軽減できる問題のように思います。
> なので、訳語候補の変形した言い回しの自由度が低かったとしても、それほど大きな問題では無いと思います。

タスクとしては、以下になるかと思います。

1. GLOBAL_DEFINED_WORDS.json の用語定義から「未定義の動作」「未定義」を削除し、「未定義動作」に一本化する
2. 現状の「未定義動作」を意味して「未定義」と記述しているところを「未定義動作」用語を使うよう直す

考慮漏れなどあれば教えてください。慎重な作業が必要になる場合は、Pull Request上などで洗い出しと箇所ごとの相談をしましょう。

**Comment by faithandbrave** [comment]
https://github.com/cpprefjp/site/blob/master/.github/workflows/script/ngword_check.py

NGワードのCIにも、「未定義の動作」と「動作は未定義で」を追加してください

**Comment by akinomyoga** [comment]
未定義の動作までも禁止する必要はあるでしょうか。規格警察すると本来は "未定義の動作" で、検索すると MISRA だとか CERT だとかの解説では未定義の動作としていて、一方で未定義動作はブログ記事や Qiita 記事で膾炙している語のように思います。cpprefjp 内部では未定義動作が主要のようなので劣勢かもですが、未定義の動作を禁止するほどのことでしょうか。

**Comment by tshino** [comment]
たしかに、問題が少しずれているかも知れません。
誤ったポップアップを消すのが必要なのは言うまでもなく、他の問題についてここで指摘したいです。
私が最初に問題を見つけたときに思ったのは、少し違う観点だったからです。

根本的には、曖昧性の問題

- 言い回しの変化があることで、用語の言い換えなのか一般的な意味なのか、文意の読み取りが難しくなる

があると思います。
ポップアップは偽陰性（用語ではないと誤判断する）を抑制する効果はあると思います。

ただ、一般的な意味で使っていてポップアップも出ない場合に起きる偽陽性（用語だと誤判断する）の対策としては、（ポップアップは効かないので）他の対策があると良いと思いました。

つまり、「UBではない文脈で「未定義」が使われている箇所」の根本的な曖昧性の問題は、ポップアップが出なくなってもあまり改善しないと思います。

以下の範囲の言い回しは、曖昧性の観点では問題なさそうに思います。
```
未定義動作
未定義の動作
動作は未定義
挙動は未定義  // ←人によっては確信を持てないので微妙と感じそう
```

現在見つかる以下の例文では、個人的に、UBのことかどうか迷うものも含まれます。
```
reference/cstddef/offsetof.md
スタンダードレイアウトではないクラス型においての`offsetof`の利用は条件付きのサポートとなる（C++17より以前は未定義）。

reference/ios/ios_base/op_constructor.md
コピーコンストラクタは `private` で未定義（C++03 まで）、あるいは、`public` で `delete`（C++11 から）である。

reference/atomic/atomic_ref/op_plus_assign.md
結果として未定義アドレスになる場合があるが、それ以外の未定義動作はない
// この文脈だと未定義アドレスは未定義動作に含まれるように読める
```

これらがポップアップの対象でない場合、ポップアップが出ないようにするだけでは、曖昧性は放置されるので、問題が解決しないというわけです。
これらを個別に、より誤解の生じにくい表現に改めることが対策になると思います。

**Comment by faithandbrave** [comment]
決まった以外の「未定義」の使い方を検出するくらいは、がんばればできそうな気はしますね。
ひとまずその検出スクリプトを作ってから、個別の問題を眺めましょうか。
スクリプトは一旦、私の方で作ってみます。

**Comment by faithandbrave** [comment]
- https://github.com/cpprefjp/site/pull/1348

用語の意図しない使用を検出するスクリプトを作ってPull Requestを提出しました。
そちらで相談しましょう。
