### ISSUE TITLE
ブラウザの印刷機能において 1 ページ目しか印刷できない

### ISSUE THREAD

**Issue by akinomyoga** [cpprefjp/site#1364]
タイトルの通り、ブラウザの印刷機能において各記事の 1 ページ目しか印刷できません。Chrome/Firefox/Edge 何れも駄目です。

これまでにそういう議論はあったか確認してみたのですが `@saki7` さんがちらっと言及しているだけのようです。

https://github.com/cpprefjp/site/issues/477#issuecomment-342550382

> ### CSS
>
> [...]
>
> ブラウザの印刷機能で印刷をする時に正しく表示されるようにするのは新規の機能になるので、余裕ができたらやりたいなと思っています。
>
> [...]

これはスタイルシート (`@media print`) で対応できそうな気がします。

**Comment by faithandbrave** [comment]
- https://github.com/cpprefjp/kunai/pull/144

これで直りはしました。
どなたかレビューしてもらえれば

**Comment by faithandbrave** [comment]
@yumetodo さんにレビューしてもらって、マージしました。
これでクローズします。問題あればreopenしてください。

**Comment by yumetodo** [comment]
ref: https://github.com/cpprefjp/kunai/issues/34
