### ISSUE TITLE
ローカルで変換結果を確認するには？

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#209]
cpprefjp/site をローカルで編集したあと git push する前の段階で、
編集箇所の HTML での表示やリンクの確認はみなさんどうされてるんでしょう
か？

未確認の状態で push して GitHub で確認っていうのは何かミスしてたときに
他の人に迷惑になっちゃいそうですし、 cpprefjp/andare の変換で
問題・エラーが出ないことをただ祈って待つというのもマズいように思います。

・・・と思って cpprefjp/andare のソースを眺めていると、ちょっといじれば
ローカルでも動きそうな感じだったので、実際にここ最近の編集で使ってたのが
こちらの改造（コピペ実装＆コードブロックの変換にバグあり）になります。
https://github.com/k-satoda/cpprefjp-andare/tree/enable-local-conversion
これと cpprefjp/site のほうに即席で作った Makefile とを組み合わせて、
編集後に make を叩いて変換して結果を確認してました。
[Makefile](https://gist.github.com/k-satoda/617a2676fbfe78b6d2b7)

何かもっとよさそうな確認方法があれば教えてください。

現状で特に他に確認方法が無く、上記ブランチの変更（および Makefile ？）が
他の人にも役に立ちそうなら、作業環境としてまじめに整備しにかかるのがいい
のかなー、とか思ってます。

**Comment by melpon** [comment]
ツールは site_generator に移行したし、site_generator はローカルで確認できるはずなので、閉じます。

**Comment by k-satoda** [comment]
すいません。移行先の環境を試して閉じようとか思ってましたが、ぜんぜん
できてませんでした。未だに目処も立ってないですけど、試してなんかあったら
別の issue にします。

**Comment by melpon** [comment]
:+1:
