### ISSUE TITLE
regex_constantsのクラスページを作成する

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#212]
`regex_contants`のクラスページを作成しておください。

**Comment by faithandbrave** [comment]
このタスクを引き取ってもいいでしょうか？

**Comment by faithandbrave** [comment]
引き取ります。

**Comment by usagi** [comment]
すみませぬーお願いします!

On 2015年4月1日 11:47:09 GMT+09:00, Akira Takahashi <notifications@github.com> wrote:
>引き取ります。
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cpprefjp/site/issues/212#issuecomment-88320558

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
