### ISSUE TITLE
basic_streambufはムーブコンストラクタを持つか

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#239]
拾うのが遅れてしまったのですが、Twitter上でnu11p0_6477さんから、以下の質問・確認がありました。

<https://twitter.com/nu11p0_6477/status/532454608711348224>

> <https://sites.google.com/site/cpprefjp/reference/streambuf/basic_streambuf/basic_streambuf>
> ここに`basic_streambuf`がmove ctorを持つと書いてありますが、N3337、cppreference.com、cplusplus.comを参照したところcopy ctorしか無いようです #cpprefjp

対応としては、以下の2つを行うのがいいと思いますが、いかがでしょう。 
1. まず規格書の確認
2. ムーブコンストラクタが実際にはなければ、cpprefjpの該当する記述を削除。あるのであれば、参照ヶ所をcpprefjpの該当ページに書いておく(同じ疑問を持った人への、重複対応をしないため、cpprefjp内での暗黙知を明示にしておく)

ひとまずデフォルトの担当者を、 @egtra さんに設定させていただきます。
私の方でも時間がとれるときに書かれている箇所を探しますが、書かれていないことを探すのは難しいので、書いた人に参照ヶ所を教えてもらうのが早い、という理由からです。

**Comment by egtra** [comment]
N3936で確認しました。たしかに`basic_streambuf`にムーブコンストラクタはありませんでした。`basic_stringbuf`や`basic_filebuf`にはあるので、混同していたのかもしれません。ともあれ削除します。

**Comment by faithandbrave** [comment]
いつまでも問題をそのままにしておくのも良くないので、引き取ります。
