### ISSUE TITLE
cpprefjpサイトでのusing namespace std;は避けるべきか？

### ISSUE THREAD

**Issue by yohhoy** [cpprefjp/site#244]
cpprefjpサイト内のサンプルコードでは、`using namespace std;`記述を極力避けるべきでしょうか。

2014/1/14現在、一部ページに偏って`using namespace std;`が利用されていました。（map, set, unordered_mapヘッダと他数件）
```
$ find . -name "*.md" | xargs grep "using namespace std;" | wc -l
116
```

`std::chrono`や`std::placeholders`等の存在もあるため、個人的には`using namespace`一律回避というのもストイックすぎかと考えていますが、リファレンスサイトということもあり`using namespace std;`だけは避けた方が無難かなとも思っています。

**Comment by faithandbrave** [comment]
避けたほうがいいですね。
サンプルコード中の識別子と、標準ライブラリの識別子を見分けるためのスキルが別途必要になってしまうので。

**Comment by oniprog** [comment]
map, set, unordered_mapについて対応します．時間をください．

**Comment by faithandbrave** [comment]
それでは、 @oniprog さんにお任せします！よろしくお願いします！

**Comment by yohhoy** [comment]
"他数件"と書いた2件だけ修正してしまいました。

**Comment by oniprog** [comment]
map, set, unordered_mapについて修正しました．

**Comment by faithandbrave** [comment]
確認しました。 @oniprog さん、対応ありがとうございます！

**Comment by yohhoy** [comment]
:+1:
