### ISSUE TITLE
非メンバ関数mdファイルの適切な配置位置

### ISSUE THREAD

**Issue by yohhoy** [cpprefjp/site#245]
`<utility>`ヘッダ`make_pair`関数テンプレートの位置がおかしい気がします。`pair`クラステンプレートのメンバではないため、utility直下にあるべき？

**Comment by yohhoy** [comment]
`tuple`と`make_tuple`の関係も同様になっていました。この構造は意図的でしょうか？（であればcloseしてください）

**Comment by faithandbrave** [comment]
統一はできていないのですが、非メンバ関数は基本的に、関連するクラスのディレクトリに置こうと思っています。

ヘッダのディレクトリに置くのは、swapや比較演算子の場合に問題になります。swap_for_pairとかのファイル名にはしたくないので。

**Comment by faithandbrave** [comment]
ちなみに、`<chrono>`の場合、算術・比較演算子をヘッダのページに置いていますが、これは`duration`と`time_point`の組み合わせがあるからです。このあたりが悩みどころです。

**Comment by yohhoy** [comment]
> ヘッダのディレクトリに置くのは、swapや比較演算子の場合に問題になります。swap_for_pairとかのファイル名にはしたくないので。
確かに非メンバ関数を一律ヘッダ直下にしてしまうと、ファイル名衝突のリスクがありますね…

**Comment by yohhoy** [comment]
以後、類似ケースで参照されることも考えて、issueタイトルを一般化しました。

**Comment by faithandbrave** [comment]
> 結局、ケース・バイ・ケースでよきに計らいましょうという雰囲気でしょうか。

今のところ、ぼくから提案する方針としては、以下のようになります：

- 基本的に、非メンバ関数は関連するクラスのディレクトリにページを置く
- 複数のクラスが対象となる非メンバ関数(`swap`や算術演算子、比較演算子など)については、それらの上位ディレクトリ(ヘッダのディレクトリ)にページを置く

この「基本的に」が曖昧で、たとえば`<string>`ヘッダの`to_string()`系関数は、ヘッダのディレクトリにあってもいいのではないかと思っています。これは、`to_string()`の反対にある`stoi()`関数が、将来的に別の文字列型をパラメータとして受け取ることを想定してもいいのではないか、という考えからです。(そんなことはないかもしれない)
このようなケースは、関数単位で議論があっていいと思います。

「基本的に」に含まれると考えている部分で統一できていないところは、ぼくが把握している範囲では以下です：

- `<utility>`ヘッダにある、`pair`用の`get()`関数
- `<system_error>`ヘッダにある、ヘルパ関数と出力ストリーム演算子

**Comment by melpon** [comment]
http://www.cplusplus.com/reference/utility/pair/ の非メンバのところを見ると「Non-member function overloads」とか書いてたりしますね。
これに倣うなら、オーバーロードして使うことを意図してる関数（これが複数のクラスに跨ったりはしないと思いたい）はクラス内に、そうでないのは外に、ということになりそうですね。

**Comment by faithandbrave** [comment]
ぼくは関連性でまとめていましたが、オーバーロードを意図しているか否かでまとめると、明確でよさそうですね。そうしましょうか。

その方針にする場合は、以下のように修正することになります。

- `make_pair()`を、`<utility>`ヘッダの直下に置く。
- `<utility>`ヘッダのページに、`make_pair()`へのリンクを書く
- `pair`クラスのページに、「##非メンバ関数」の下に「###ヘルパ関数」という分類を作って`make_pair`へのリンクを貼る(これはcplusplus.comではSee alsoにあたるもの)。
- `pair`の`get`は、オーバーロードを意図しているので`pair`下に移動する。
- `<chrono>`の演算子は、置く場所は変えられないので、`duration`と`time_point`それぞれのページからリンクを貼って、ヘッダページからのリンクは外す。

ここで`get`を「オーバーロードを意図しているもの」とみなしていますが、このようなケースは、議論の余地あり、という方針にしていいと思います。

**Comment by faithandbrave** [comment]
現在判明している、pair、chrono、tupleについて、上記方針で対応しました。
