### ISSUE TITLE
外部リンクのリンク切れ

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#248]
外部リンクに一部リンク切れを発見したのですが、適切な対処法がわからなかったので報告します。

- [外部ライブラリ](https://github.com/cpprefjp/site/blob/master/third_party_library.md)
	URL: http://opencv.willowgarage.com/wiki/
	リンクテキスト: OpenCV

- [editors_doc/cpprefjpを編集するには](https://github.com/cpprefjp/site/blob/master/editors_doc/start_editing.md)
	URL: http://blog.2310.net/archives/6
	リンクテキスト: Markdown文法の全訳

- [reference/system_error/errc](https://github.com/cpprefjp/site/blob/master/reference/system_error/errc.md)
	URL: http://pinka99.ddo.jp/nanao/work/errno.html
	リンクテキスト: Unix系errno一覧

**Comment by faithandbrave** [comment]
引き取ります。
