### ISSUE TITLE
Google Sitesから現ページへのリンクを作れないか

### ISSUE THREAD

**Issue by egtra** [cpprefjp/site#249]
わたくし、いつもGoogleの検索でcpprefjpを利用していました。ところが、先日のGoogle Sitesのコンテンツ削除以降、まだ http://cpprefjp.github.io/ のほうが検索結果に出てこず不便な状態です。

Google Sitesの旧サイトにおいて、各ページに「 http://cpprefjp.github.io/… に移行しました」という手動でのリダイレクトを促すページを設置するなどということはできないでしょうか？

副次的な効果として、旧サイトに向けてハイパーリンクを張っている世の中のウェブページの救済にもなるかと考えています。

**Comment by faithandbrave** [comment]
Google検索は、定期的にロボットが巡回して検索結果を更新します。その更新がまだ行われていないために、旧サイトが検索に引っかかるのでしょう。旧サイトのページを削除する際には、検索に引っかからないようにするメタ情報も埋め込んだので、そのうち引っかからないようになります。
新サイトの魅力向上によって非参照数を増やし、検索順位を上げるのがいいと考えます。

旧サイトからの移行については、2ヶ月前からアナウンスしていました。それについて意見を募集する期間も設けました。それが終わったいま、旧サイトについて労力は割きたくないです。

**Comment by faithandbrave** [comment]
GitHub Pagesの方が検索に引っかからないのは、SEO関連のことをほとんど何もしていないからなので、SEOについて調べながら対策していくと検索順位は向上するようになります。

簡単なところだろ、sitemap.xmlを作ることでだいぶよくなるはずです。
<http://www.mk-mode.com/octopress/2013/07/31/web-sitemap-robots/>

**Comment by faithandbrave** [comment]
GitHub PagesのSEO関係、上記2件については、 @melpon に作業依頼しておきました。

**Comment by faithandbrave** [comment]
sitemap.xmlを追加してもらいました。
https://github.com/cpprefjp/site_generator/commit/f3908f9e30f98e5b3241c474fe5e3ace713b5bfd

いま検索したら、だいぶ引っかかりやすくなっています。

**Comment by faithandbrave** [comment]
旧サイトがGoogle検索に引っかからなくなりました。これを今から巻き戻す作業はせず、新サイトの検索順位を向上させることに注力したいと思います。
その改善については別Issueで議論しようと思うので、このIssueは申し訳ないですがクローズします。
