### ISSUE TITLE
[SEO] std::名前空間を付けた検索の順位を上げる

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#250]
GitHub Pagesに移行したcpprefjpサイトの、検索順位を向上させる施策についての議論です。
(sitemapが反映されれば、旧サイトと同等程度の検索順位にはなるはずです。もろもろ調べながらやっているので、最大1ヶ月ほどお待ちください。)

現状、「vector cpprefjp」でGoogle検索すればvectorのクラスページがトップに来ますが、「std::vector cpprefjp」と検索すると全然引っかかりません。

この対策として、以下のいずれか、もしくは全てを対応していきたいと考えています。

1. ページタイトルに名前空間を付ける (クラス、および非メンバ関数のページ)
2. 全てのHTMLのkeyword metaタグに、「C++」「STL」「std」とかを入れる
3. 説明文章中の識別子は、名前空間をフルで書く (書籍『C++ポケットリファレンス』がそうしています)

@usagi さんに調べてもらったところによると、検索順位ではページタイトルの効果がすごく高いそうなので、少なくても 1. は対応したいと考えています。

その他、 @melpon からは、cplusplus.com の以下のページを参考に、
http://www.cplusplus.com/reference/vector/vector/
種別（class template）、名前空間（`std::`）、ヘッダ名（`<vector>`）を、.mdのどこかにメタ情報として書けるようにしたらどうか、という意見が出ています。

何かご意見あればお願いします！
このIssueでは、具体的に「どんな対策をするか」を考えて、実際に実施するタスクは別Issueとして作るつもりです。

**Comment by faithandbrave** [comment]
現在、ページタイトルに使用している、「# (見出し1)」の次の行に、箇条書き記法で以下のようにメタ情報を書くようにするのはどうでしょうか。

```
* header[vector] // 所属ヘッダ
* kind[class template] // 種別(class, class template, function, function template, enum, variable, macro)
* namespace[std] // 名前空間(マクロを考慮して省略可)
* class[vector] // 所属クラス(省略可)
```

ページタイトルを直せず編集せず、追加のメタ情報にするのは、その扱いをあとから変えやすいからです。一度ページタイトルにstdとか`<vector>`とかを書いてしまうと、あとからそれを解析して別な用途のために使うのが難しくなります。
メタ情報にするなら、ページタイトルにそのまま使ってもいいし、SEO用のmetaタグに使ってもいいし、何らかのサイト内検索の仕組みに応用することもできます。

**Comment by kariya-mitsuru** [comment]
SEO は良く分からないのですが、現在 Google で検索する時、例えば「C++ vector」では出てきていないようなので、少なくとも「C++」が検索ワードとして検索エンジンに検知できるようにした方が良いのではないかと思います。

**Comment by faithandbrave** [comment]
ですね。
site_generatorの以下のコミットで、cpprefjpのトップページ以外に、` - cpprefjp C++日本語リファレンス`というサフィックスが`<title>`タグに付くようになりました。

https://github.com/cpprefjp/site_generator/commit/80f680749511e9474d997f43623dcf3e32c71805

これで改善しなかったら、以下のようなメタタグを埋め込んでもらいましょう。

```
<meta name="keywords" content="C++,std::vector::push_back,vector::push_back,push_back">
```

**Comment by melpon** [comment]
メタ情報、書き換えるのが大変そうなので自動で取得できそうなのは自動でやりたい気もしますが、それはそれで難しそうなので諦めるのがいいですかね…。

あとシンタックスハイライトの指定は「対象文字列[命令 引数]」なので、
```
* vector[meta header] // 所属ヘッダ(リファレンスページ以外では省略可)
* function[meta kind] // 種別(リファレンスページ以外では省略可。class, class template, function, function template, enum, variable, typedef, macro)
* std[meta namespace] // 名前空間(マクロを考慮して省略可, 名前空間の区切りは`::`)
* vector[meta class] // 所属クラス(省略可, クラスページでは省略する, structと書けるようにはしない)
```
の方が一貫性はありそう（でも書きにくそう）。

**Comment by faithandbrave** [comment]
ではそんな感じにしましょうか。

kindについては、てきとうに考えすぎたので、もう少し考えましょう。
Haskell界隈では、型の型をkind(種)と呼ぶので、それをC++が取り入れる可能性を考慮して、採用はやめましょう。
family, categoryなども使われていたりするので、ここは一単語にこだわらずに、「id-type」(identifier-type, 識別子の種類)とするのでどうでしょうか。

**Comment by melpon** [comment]
> ここは一単語にこだわらずに、「id-type」(identifier-type, 識別子の種類)とするのでどうでしょうか。
良いと思います。
まあ、この辺は最悪一括置換できる場所なので、あまり深く考えずにやってもいいかなと思います。

**Comment by faithandbrave** [comment]
ここまで、異論らしい異論もでていないので、このあたりを結論として、実際の対応に入っていきましょう。
対応のためのIssueを別途用意するので、そのIssueを発行したらここはクローズします。
