### ISSUE TITLE
検索性向上のメタ情報を、雛形ページに記載する

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#252]
#251 の仕様を参照。

**Comment by kariya-mitsuru** [comment]
operator new と operator delete はグローバル名前空間ですが、名前空間メタ情報はどのようにしたらよいでしょうか？

**Comment by faithandbrave** [comment]
マクロと同じく、名前空間のメタ情報を省略ですね。

**Comment by kariya-mitsuru** [comment]
なるほど、ありがとうございます。
修正しました。

**Comment by melpon** [comment]
(C++11) もメタ情報にしてしまった方がいいかも、という気もしてきました

**Comment by faithandbrave** [comment]
site_generator側を先に対応してくれれば、こちらも対応しますよ(タイトルの旧バージョン情報削除、およびメタ情報の付加)。

**Comment by melpon** [comment]
了解です。じゃあ対応コード書いたら伝えます。
(C++11)って、「C++11以降じゃないと存在しない」って意味で、例えば「C++03でも使えるけど微妙に仕様が違うよ」的なのには付けてないですよね？

**Comment by faithandbrave** [comment]
はい。

**Comment by yohhoy** [comment]
（別Issueに分けた方が良い気もしましたが）「C++NN以降では非推奨」というのも存在するので、「C++11以降で新しく追加」と同じようにメタ情報化できると便利かと思いました。

**Comment by melpon** [comment]
cpp11[meta cpp]  // C++11以降で使える
cpp11deprecated[meta cpp] // C++11以降はdeprecated
みたいな感じですかね。

**Comment by faithandbrave** [comment]
removedもあるといいですね。deprecatedはそのうち消える可能性があるので。
まだ対応していないですが、C++03で`<algorithm>`で定義されていた`std::swap`がC++11で`<utility>`に移動したので、そういうので使いたいです。

**Comment by melpon** [comment]
元のタスクと離れてしまったし、C++11やC++14対応は別issueにして、これは閉じましょうか

**Comment by faithandbrave** [comment]
元のタスクがまだ終わってないので、リオープン。ぼくの担当です。

**Comment by faithandbrave** [comment]
対応しました。
