### ISSUE TITLE
冗長なbool()

### ISSUE THREAD

**Issue by redboltz** [cpprefjp/site#253]
http://cpprefjp.github.io/reference/algorithm/includes.html
などで、bool(式)のbool()が冗長ではないでしょうか？

```C++
template <class InputIterator1, class InputIterator2, class Compare>
bool includes(InputIterator1 first1, InputIterator1 last1,
              InputIterator2 first2, InputIterator2 last2,
              Compare comp)
{
  for (; first2 != last2; ++first1)
    if (bool(first1 == last1) || bool(comp(*first2, *first1)))
      return false;
    else if (!bool(comp(*first1, *first2)))
      ++first2;
  return true;
}
```

**Comment by faithandbrave** [comment]
これはおそらく、イテレータの等値比較と、要素の比較関数が「boolに変換可能であること」を表現しているのだと思いますが、if文では式がboolに変換されるため、たしかにboolへの変換は冗長に見えます。
@kariya-mitsuru さんの意見を待ちます。

**Comment by melpon** [comment]
`Compare`の戻り値は`bool`へcontextually convertibleでないといけない（25.4¶2）ですが、否定演算子を適用できなければならない、という規定は無いです。
なので、以下のような`result`型を返す場合には必要なんじゃないかなと思います。

http://melpon.org/wandbox/permlink/50OjgtpY1ToVL2uU
```cpp
struct result {
    // contextually convertible to bool
    explicit operator bool() {
        return true;
    }
    void operator!() = delete;
};

result comp(int, int) { return result(); }

int main() {
    if (comp(0, 0)) ; // OK
    if (!comp(0, 0)) ; // コンパイルエラー！
    if (!bool(comp(0, 0))) ; // OK
}
```

**Comment by redboltz** [comment]
なるほどぉ。あとは、!bool(式)以外のパターンで、統一感？としてbool()を付けるか、不要かといった感じの話ですかね。

**Comment by melpon** [comment]
`if (bool(first1 == last1) || bool(comp(*first2, *first1)))`の部分も同じで、
```
void operator||(result a, result b) = delete;
```
してた場合にはコンパイルエラーになります。

**Comment by kariya-mitsuru** [comment]
@melpon さんのおっしゃる通り、Compare の要件以外のあらゆる意地悪をしても正常に動くよう意図的に付けました。
実際は、そんなアホなことする人はいないと思いますが…
ちなみに、libstdc++ とか libc++ とかは、付いて無いところも多いですね。
前にバグ報告しようかちょっとだけ悩んだんですが、そこまで深刻な問題でもないかなぁ、と思って報告してません…

**Comment by melpon** [comment]
このままで問題なさそうな気がするので、3/16(月)のどこか（日本時間）に閉じようと思います。 cc: @redboltz @faithandbrave

**Comment by faithandbrave** [comment]
レスポンス忘れてました。ぼくはこのままで問題ないです。
