### ISSUE TITLE
数式の記載について（あるいは、MathJax 使いたい）

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#254]
各ページ内で数式を記載しているところがあると思うのですが、みなさんはどうやって画像を作成してますか？（オンラインで作成？自前環境で作成？）
個人的にはいちいち画像を作成するのが面倒なので、MathJax が使えるとうれしいなぁ、と思ったりするのですが、あんまり需要無いでしょうか？（何かとバッティングするかな？）

**Comment by faithandbrave** [comment]
`<random>`のところでは、[editors_doc/random_figure.md](https://github.com/cpprefjp/site/blob/master/editors_doc/random_figure.md)に記載していますが、以下のオンラインエディタを使用しています。

[Online Latex Equation Editor - Sciweavers](http://www.sciweavers.org/free-online-latex-equation-editor)

ですが、私はこだわりがあるわけではないので、`<math>`ヘッダの数式を書いている @bolero-MURAKAMI さんの合意がとれて、編集者向けドキュメントに何を使っているか書いていただければ、なんでもいいです。

**Comment by faithandbrave** [comment]
MathJaxは、htmlに数式を書いて、MathJaxサイトのJavaScriptに解釈させるものなんですね。
オンラインじゃないと数式が読めないのが難点ではありますね。現在のcpprefjpも、図はGitHubリポジトリから毎回持ってきているので、オフライン需要が出てきたら、その対応はそのとき考える、でいいでしょう。

ちなみに、書籍『C++ポケットリファレンス』では、編集さんに数式を指示するために、Google Chart APIを使っていました。
http://d.hatena.ne.jp/Michael_e29/20120305/1330928706

**Comment by usagi** [comment]
JSアドオン的なツールは便利は良いのですが、できればstaticに埋め込みたいですね。

対応可能ならgithubからgh-pagesへのデプロイ時の変換で HTML5 MATHML 形式の記述に対してブラウザーの実装レベルに応じてMathJaxを表示できるようにする対応が良いのかなーと思ったり。HTML5 MATHMLの埋め込みはそのままで、非対応ブラウザー環境でのみMathJaxがロードされる仕掛けにする。

こうすると世の中のウェブブラウザーで数式の表示が問題なくなる未来にもmdのソースの汚れや実行時のスクリプトに依存した静的ではないデメリットも避けられてみんな幸せかなーと。

**Comment by kariya-mitsuru** [comment]
MathML で必要に応じて MathJax、良さそうですね。
個人的には md には TeX 形式で書いておいて site_generator で MathML に変換されるとシアワセなのですが、なかなか難しいですかね…
Google Chart API は知らなかったのですが、最近は Javascript 版に移行して img 版は非推奨になってるっぽいですね…

**Comment by usagi** [comment]
はい、わたしもTeXの方がタグ書くより手間なくて嬉しいと思うのですが、 markdown の規格がインラインのHTMLを許容しているはずなので、その範囲で、melponが書く対応コード（ TeX to mathml ）のコストを考えると、最終的にはHTMLになるものなので数式部分は妥協してMATHMLかなーというちょっと残念な提案。TeXの方が嬉しい人おおいはず、とは思うものの。

**Comment by melpon** [comment]
動的にやるなら、MathJaxはTeXを$$や$（optional）で囲んだ文字列をMathMLやFont+HTMLに変換してくれるっぽいので、そんな構文で普通にmdファイルに書けばそのまま出力されて変換できそうな予感が。
ただ、ロードする必要のないページで読ませるのは無駄なので、そこら辺はsite_generator側に手を入れる必要がありそうです。

静的(& fallback to MathJax)にやるなら、TeXをMathMLに変換するツールをどうするか悩みますね。
オフラインなツールだと環境設定が面倒になるし、オンラインなツールだとネットワークに繋がってないと変換できないので。

 # pull req お待ちしております

**Comment by faithandbrave** [comment]
それでは、担当してくれる方は、自分をassignしてください。

**Comment by melpon** [comment]
ひとまず MathJax を使えるようにするのはやります。
まだ何かしたいってことであれば、どなたかお願いします。

**Comment by usagi** [comment]
考えてみると数式でぐぐる人も居ないと思うので、あんまりstatic化される事考えなくてよかったかな。
@melpon おつかれさまです！

**Comment by kariya-mitsuru** [comment]
ありがとうございます！＞@melpon さん

**Comment by melpon** [comment]
実装しました。使い方は上記コミット参照。
置き換えた例: http://cpprefjp.github.io/reference/random/linear_congruential_engine.html

**Comment by faithandbrave** [comment]
ありがとうございます！
それじゃ、練習も兼ねて、`<random>`ヘッダの数式は、ぼくがMathJaxに書き換えておきます。

@kariya-mitsuru さんは、`<cmath>`で書き換えを行っていく場合は、cpprefjp/imageリポジトリにある数式画像を削除していってください。

@kariya-mitsuru さんの確認がとれたらこのIssueを終了します。

**Comment by faithandbrave** [comment]
問題なさそうなので閉じます。

**Comment by kariya-mitsuru** [comment]
バッチリです！
めっさ便利になりました！！
