### ISSUE TITLE
メンバ型の解説ページを作ることを許可したい

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#255]
とくに規定はなかったのですが、たとえば`unordered_map`のページでは、メンバ型の解説がかなり長くなっています。
http://cpprefjp.github.io/reference/unordered_map/unordered_map.html

そのため、クラス概要ページでのメンバ型の解説は簡易的なものとし、個別の型の解説ページで詳細を解説することを許可したいです。「許可」と言っているのは、メンバ型の解説ページは、必ず用意するものではない、ということを意図しています。

何か懸念事項等ある方はいますか？

**Comment by usagi** [comment]
:+1: メンバー型ページあってよいと思います。

**Comment by melpon** [comment]
- サイドバーに出す順序、ルールをどうするか
- メタ情報(id-type)に何を入れるか
- editors_docにあるテンプレートページに、型の説明用のクラスを追加しておきたい

**Comment by faithandbrave** [comment]
> サイドバーに出す順序、ルールをどうするか
メンバ関数、メンバ型の順になっていればいいと思います。メンバ型は一番後ろです。

> メタ情報(id-type)に何を入れるか
`typedef`があるので、それにしましょう。
テンプレートは、ぼくの方で用意します。

**Comment by melpon** [comment]
>> サイドバーに出す順序、ルールをどうするか
> メンバ関数、メンバ型の順になっていればいいと思います。メンバ型は一番後ろです。

今は順序のルールをファイル名で分岐してて、「先頭が op_ じゃなければメンバ関数」というルールなので、今のルールだとメンバ型が入る余地が無いです。
なので、「type_ ならメンバ型」「op_ でも type_ でもなければメンバ関数」みたいな感じにする必要があるかなと。
あと、"一番後ろ" だとちょっと曖昧なので https://github.com/cpprefjp/site_generator/blob/master/settings/cpprefjp.py#L71 で言うところの '__functions__' の後ろを意図してるのか 'op_istream' の後ろを意図してるのか教えてください。

**Comment by faithandbrave** [comment]
いちおう`thread::id`だけ内部クラスで、例外的にクラス階層の下にクラスページがあるのですが、普通のメンバ型は`type_`を頭に付ければいいかな。それでいきましょうか。
場所は、演算子のさらに後ろ。`op_istream`の後ろでお願いします。

**Comment by faithandbrave** [comment]
`type_`で大丈夫かなーと思っていたら、やっぱり`<type_traits>`が一番下に来てた。
http://cpprefjp.github.io/reference.html

**Comment by melpon** [comment]
ぎょえー

**Comment by melpon** [comment]
そういえばこれやらないと。`type_`じゃない良いフレーズありますかね？

**Comment by melpon** [comment]
候補として適当に挙げてみる
- `classtype_`と`typedef_`
- `_type_`
- `ttype_`
- `type-`
- `innertype_`

**Comment by yohhoy** [comment]
メンバ型のページというのは、1ページ=1メンバ型を想定しているのでしょうか？
1ページで全部記載する方法なら、固定ページ名（`member_types.md`など）にするという手段があるかなと思いました。

**Comment by faithandbrave** [comment]
メンバ型のページに、何を書くか考えましょうか。

- バージョンごとの定義
- 概要
- 備考(用途、注意事項、バージョンによる変更の経緯を含む)

書かなくていいもの：
- サンプルコード

typedefのページ例として、`intptr_t`はこれくらいの分量になっています。
http://cpprefjp.github.io/reference/cstdint/intptr_t.html

私としては、これくらいの分量なら、型ごとにページを用意した方が、説明を書きやすいのではないかと思います。1ページに全部を押し込めると、詳細な説明を(心理的に)書きにくいように思います。

**Comment by faithandbrave** [comment]
@melpon の候補からは、`_type_`か`type-`あたりがいいように思います。
将来的に、クラスと関数が混在したページ(ヘッダページとか)で、並び順を入れ替えるという要求が出てきたときに対応しやすいと考えるためです。

**Comment by usagi** [comment]
ケバブケース案 +1 // `type-`

**Comment by melpon** [comment]
では `type-` にします。

**Comment by faithandbrave** [comment]
雛形ページを作成したので、これで終了とします。
気になったところがあったら修正お願いします。
