### ISSUE TITLE
C++11、C++14メタ情報の対応

### ISSUE THREAD

**Issue by melpon** [cpprefjp/site#256]
```
cpp11[meta cpp] // C++11以降で使える
cpp11deprecated[meta cpp] // C++11以降はdeprecated
cpp14removed[meta cpp] // C++14で削除された
```
みたいな感じで。
site_generator 側の対応を先にやって、それから site 側の対応をする。

関連: #252

**Comment by melpon** [comment]
@faithandbrave 大体対応完了しました。
以下のメタ情報が指定可能です。
```
* cpp11[meta cpp]  # C++11で追加
* cpp14[meta cpp]  # C++14で追加
* cpp11deprecated[meta cpp]  # C++11で非推奨
* cpp14deprecated[meta cpp]  # C++14で非推奨
* cpp14removed[meta cpp]  # C++14で削除
```
これらのメタ情報は複数個書いても大丈夫です。

タイトル名をメタ情報に変換するのは（機械的に）やったので、あとは `cpp11deprecated` と `cpp14deprecated` と `cpp14removed` を入れれば完了になると思います。

が、非推奨のってそもそも cpprefjp に書いてなかった気がするので、これってあるんでしたっけ。

**Comment by faithandbrave** [comment]
非推奨はいまあるのだと、`<algorithm>`ヘッダの`random_shuffle`ですね。
まだ書いていないものだと、`bind1st`とか`auto_ptr`です。
削除されたものはないです(`gets`のリファレンスは書いてない)。

ぼくの方で、雛形ファイルにメタ情報の書き方を追加しておきます。

**Comment by melpon** [comment]
だん http://cpprefjp.github.io/reference/algorithm/random_shuffle.html

> ぼくの方で、雛形ファイルにメタ情報の書き方を追加しておきます。
お願いします！

**Comment by faithandbrave** [comment]
完了しました。対応ありがとうございます！
