### ISSUE TITLE
cstdint: __STDC_LIMIT_MACROS, __STDC_CONSTANT_MACROS の扱い

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#257]
[cstdint](https://github.com/cpprefjp/site/blob/6067e1b6b98486a8e62af54a1f2325aca3eb4b81/reference/cstdint.md) のページで、マクロ提供の条件として __STDC_LIMIT_MACROS, __STDC_CONSTANT_MACROS について触れられていますが、これらの条件は規格に存在しません。
https://stackoverflow.com/questions/986426/what-do-stdc-limit-macros-and-stdc-constant-macros-mean
> This isn't part of the C++ standard, but it has been adopted by more than one implementation.

C99 の脚注で触れられていたもののその後削除されており、 C11, C++11 には含まれていないという状況のようです。

C++11 の 18.4.1 [cstdint.syn] p2 にある [Note](https://github.com/cplusplus/draft/blob/0b7593f0e716910bab7c1511533b2f9b5a886de1/source/support.tex#L1263) で、これらのマクロは採用されていないことが明記されています。
> ... In particular, the symbols __STDC_LIMIT_MACROS and
> __STDC_CONSTANT_MACROS (mentioned in footnotes 219, 220, and 222 in
> the C standard) play no role in C++.

cpprefjp では単に削除するか、規格と同様に動作しないことを注釈として記載するか、これらのマクロが動作する実装を列挙するか・・・といったあたりで迷う感じだったので、とりあえず Issue で挙げさせてもらっておきます。

現状の記述が何に基づいていたのか、というあたりの情報をもらえれば対応を決めやすそうです。

**Comment by faithandbrave** [comment]
そのマクロ名で調べて、C++でどうなっているのかを知ることができるようにするのがいいと思います。
ページの下の方に備考節を作って、そこで注釈を書く、というのでどうでしょうか。そのマクロが動作する実装を書く、というのは詳細にあたるので、そこまでもし書かれるのであれば、そのマクロ専用のページを作成して書くのがいいと思います。

基本的には、「正確な情報に、不要なものはない」というのを方針にして進めてもらえればと思います。

**Comment by k-satoda** [comment]
方針について了解しました。この件についてはここで書いたような情報を備考にまとめようと思います。

これらのマクロを採用している実装についての情報は持っていないので、 SO へのリンクを置きつつそういう実装があったという情報もある、程度の書き方にしておくつもりです。

**Comment by faithandbrave** [comment]
よろしくお願いします！
