### ISSUE TITLE
vectorとdequeの挿入操作: 例外発生時の動作

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#258]
https://github.com/cpprefjp/site/commit/3fbbb6ede123d7180598aeecab06162e064e70d1#diff-e0c7cef6bbedb0e324c89e56a0e20f83R33
> もし、例外が発生した場合には、挿入操作中の単一要素については副作用が発生しない。

おそらく翻訳ミスで、意味が通らなくなってしまっているように思います。

正しくは「両端への単一要素の挿入中に例外が発生した場合には副作用が発生しない」（ vector の場合「両端」→「終端」）というような意味になるだろうと思ってます。

つづく括弧内の「～で例外が発生した場合を除く」は、両端への単一要素追加の場合は適用されない（途中への単一要素追加や、複数要素追加の場合のみ適用される）ものになると思います。つまり両端への単一要素追加の場合に限り、あらゆる例外に対して副作用が発生しないことが保証されている、と。

[原文](https://github.com/cplusplus/draft/blob/2aeea152aac85dff3111d2fb5cdabec7791d2c21/source/containers.tex#L3144)が難解なので僕もちょっと自信がないところもあります。複数要素追加の際にコピーコンストラクタなどで例外が発生した場合の動作の規定が抜けてるような気がしたり・・・。

この Issue で解釈を詰めさせてもらったうえで、必要な修正を同様の各所に反映できれば（してもられば）、と思ってます。ご意見ください。

**Comment by faithandbrave** [comment]
報告ありがとうございます。少し時間がかかりますが、原文を読み直します。

**Comment by yohhoy** [comment]
[LWG 2252](http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2252)をみると、コンテナ端位置への「単一要素の挿入操作」でのみ強い例外保証を与える、が修正意図のように読めます。
> Formulate only the exceptions from that (or where other general statements might lead to the impression, that the blanket statement no longer applies):
>
> - [...]
> - Clarify that all single-element insertions at either end of a deque have the strong guarantee.
> - Clarify that all single-element insertions at the end of a vector have the strong guarantee.

最低限の修正で済ませるなら、`s/挿入操作中の単一要素については/単一要素の挿入操作については/g` でとりあえず意味が通るかと思います。

**Comment by faithandbrave** [comment]
確認しました。 @k-satoda さんから提案のあった以下の文章への修正で大丈夫だと思います。

>  deque: 「両端への単一要素の挿入中に例外が発生した場合には副作用が発生しない」
>  vector: 「終端への単一要素の挿入中に例外が発生した場合には副作用が発生しない」

@yohhoy さんの意見についてですが、これはpush_back/emplace_backだけでなく、insert/emplaceも対象にして書かれている文章であるので、やはり「両端」「終端」は必要だと思います。

**Comment by k-satoda** [comment]
要素型のコピー・ムーブおよびイテレータ操作で例外が発生した場合を除いている括弧内の記述に関連して、もう一箇所（と同様の各所に）修正が要りそうなので念のため挙げておきます。
https://github.com/cpprefjp/site/commit/3fbbb6ede123d7180598aeecab06162e064e70d1#diff-e0c7cef6bbedb0e324c89e56a0e20f83R78
> C++11までは「もし、例外が発生した場合には、副作用が発生しない。」という保証があった...

この点も LWG #2252 で挙げられている実際の状況と食い違っているようです。
> ..., saying that the strong guarantee is only given if constructors and assignments do not throw.
>
> That means, the strong guarantee of C++03 is broken with C++11.

C++11 で誤って「～で例外が発生した場合を除く」のぶんだけ抜け落ちてしまっていた強い例外安全保証の復活ということになっています。（ついでに v.insert(v.end(), x) などのケースもカバーされるようになってるようです。）

**Comment by faithandbrave** [comment]
整理します。この理解で合っているでしょうか。

- このIssueの目的は、C++03で保証されていた動作がC++11で壊れていたものの修正。
	- C++11では`noexcept`対応のために、例外を投げる条件を厳密化した。
	- その対応によって仕様に抜けが発生してしまった。
	- C++03では「`push_back()`と`push_front()`で例外が送出された場合、副作用がない」という保証。
	- C++11では「(挿入操作において、)`InputIterator`範囲の各要素の、コピーコンストラクタ、ムーブコンストラクタ、コピー代入演算子、ムーブ代入演算子で例外が発生した場合、挿入操作中の単一要素は副作用が発生しない。**それ以外で例外が発生した場合、その動作は未規定。**」
	- この「それ以外」が加わったことによって、(条件を満たせば)例外を投げない強い保証ができなくなっていたので、C++14で修正した。
- それに加えて、対象となる挿入操作をC++14で拡大する。
	- 対象となる挿入操作は以下：
	- `push_back()`
	- `push_front()`
	- `emplace_back()` (new)
	- `emplace_front()` (deque) (new)
	- `insert()` : dequeは両端、vectorは終端 (new)
	- `emplace()` : dequeは両端、vectorは終端 (new)

混みいったIssueのようなので、この理解で合っていたら、上記の箇条書きをそのまま貼り付けるのでいかがでしょうか。

**Comment by k-satoda** [comment]
> 整理します。この理解で合っているでしょうか。

残念ながらいくつか事実と異なる部分があるようでしたので、少し長くなっちゃいましたが、以下にそれぞれコメントをはさむ形で挙げます。（いつも文面の推敲に時間をかけすぎてる気がしてるので、今回は返信速度を優先させてもらってます。）

> - このIssueの目的は、C++03で保証されていた動作がC++11で壊れていたものの修正。

「LWG #2252 の目的は」ということでいいですよね。（この github 上の Issue じゃなくて。）

なお LWG #2252 へのリンクですが、 open-std のやつだとロードが重いので、比較的ロードが早い github の URL を挙げておきます。
http://cplusplus.github.io/LWG/lwg-defects.html#2252
公式は open-std だと思うので記事中のリンクはそっちのほうがいいだろうとは思ってます。

>   - C++11では`noexcept`対応のために、例外を投げる条件を厳密化した。
>   - その対応によって仕様に抜けが発生してしまった。

LWG #2252 に、問題発生の経緯について以下の記述があります。
> It seems the error came in when [N2350](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2350.pdf) and [N2345](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2345.pdf) became accepted and where integrated into the working draft [N2369](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2369.pdf).

N2369 の 23.2.5.4 [vector.modifiers] を見ると insert() についての記述に push_back() が組み入れられており、この時点で問題が発生したことが確認できます。この変更は N2345 で 23.2.5.4 [vector.modifiers] に対する変更として挙がっていたもののようです。 N2345 は emplace 系の操作を追加するものとなっており、「`noexcept`対応のため」ということではなかったようです。

>   - C++03では「`push_back()`と`push_front()`で例外が送出された場合、副作用がない」という保証。

ここは間違いないと思います。 vector::push_back() について 23.2.4.3 [lib.vector.modifiers] に個別の規定が無いので、コンテナ一般の 23.2.1 [container.requirements.general] の規定が適用されます。

例えば push_back() 中に要素型のコピーやムーブ操作で例外を発生した場合でも副作用が無いことが保証されます。

>   - C++11では「(挿入操作において、)`InputIterator`範囲の各要素の、コピーコンストラクタ、ムーブコンストラクタ、コピー代入演算子、ムーブ代入演算子で例外が発生した場合、挿入操作中の単一要素は副作用が発生しない。**それ以外で例外が発生した場合、その動作は未規定。**」
>   - この「それ以外」が加わったことによって、(条件を満たせば)例外を投げない強い保証ができなくなっていたので、C++14で修正した。

いくつか誤りがあるようです。正しくは下記のようになると思います。

  - C++11では「(挿入操作において、)要素型 T のコピーコンストラクタ、ムーブコンストラクタ、コピー代入演算子、ムーブ代入演算子、あるいは`InputIterator`の操作**以外**で例外が発生した場合、副作用が発生しない。**列挙された操作で例外が発生した場合の動作は未規定。**」

例えば push_back() 中に要素型のコピーやムーブ操作で例外を発生した場合が未規定の場合に該当してしまうことになります。

なお C++14 での修正については github でコミットが確認できるようだったのでリンクを挙げておきます。
https://github.com/cplusplus/draft/commit/c79aa9dc74cf8ad8fdab75b274f8ffaea4cc4c14

> - それに加えて、対象となる挿入操作をC++14で拡大する。
>   - 対象となる挿入操作は以下：
>   - `push_back()`
>   - `push_front()`

下の `emplace_front()` に "(deque)" の記述があるので、ここの `push_front()` にも要る？あるいは両方要らない？

>   - `emplace_back()` (new)
>   - `emplace_front()` (deque) (new)
>   - `insert()` : dequeは両端、vectorは終端 (new)
>   - `emplace()` : dequeは両端、vectorは終端 (new)

insert(), emplace() については単一要素の場合に限っての話となります。

> 混みいったIssueのようなので、この理解で合っていたら、上記の箇条書きをそのまま貼り付けるのでいかがでしょうか。

どこかのページ（ vector::push_back() あるいは emplace_back() あたり？）にそんな感じで貼り付けて、関係する各関数の文面からはリンクで済ませるのがいいんじゃないかと思います。

**Comment by faithandbrave** [comment]
確認ありがとうございます。それでは、その内容で段階的に対応していきます。
`vector::push_back()`あたりにまとめようと思います。

**Comment by faithandbrave** [comment]
修正しました。問題あれば再オープン、もしくは直接修正お願いします。

**Comment by k-satoda** [comment]
対応ありがとうございます。でも残念ながらいくつか誤りがあるようだったので、それぞれ修正をかけていきます。

**Comment by k-satoda** [comment]
この件について僕が気付けた問題はひととおり修正しました。クローズします。
