### ISSUE TITLE
hashの関数呼び出し演算子にconstは必須かどうか

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#262]
以下の指摘があり、私の方で調査はしたのですがちょっと自信がありません。どなたか調査にご協力いただけると助かります。

<https://twitter.com/psychi/status/641231229107376128>

> @psychi
> C++標準のハッシュ関数`std::hash::operator()`って、`const`修飾するのが仕様なんじゃろか。cpprefjpをみると`const`修飾がないけど、VC++とclangの実装だと`const`修飾しないと`std::unordered_map`に使えず。

> @cpp_akira
> @psychi 規格にインタフェースの明記はないのですが、Hash requirementsを読み直してみると、"The value returned shall depend only on the argument k"とあるので、`const`修飾が必須なのかもしれませんね。

対象ページ： <http://cpprefjp.github.io/reference/functional/hash.html>

**Comment by planaria** [comment]
> h is a value of type (possibly const) H,

とありますが、これは
「hはconstかもしれないのでconstでも使えるようにせよ」
と解釈できる気がします。

**Comment by faithandbrave** [comment]
@planaria さん、ありがとうございます！たしかにそうですね。
この文章で、関数呼び出し演算子がconstであることが断定できそうです。
私の方で修正しておきます。
ありがとうございました！
