### ISSUE TITLE
名前空間に対するメタ情報（meta id-type）

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#263]
std::regex_constants は名前空間なのですが、独立したページがあります。
このような場合、meta id-type に namespace とか指定しても大丈夫でしょうか？
それとも、meta id-type を指定しない方が良いでしょうか？

**Comment by faithandbrave** [comment]
`namespace[meta id-type]`は、用意してもらったつもりはなかったですが、なんでも設定できるように見えます。
<https://github.com/cpprefjp/markdown_to_html/blob/f5128411fe80c569ee416d49597c6bb048ff0523/meta.py#L84>

**Comment by faithandbrave** [comment]
ちなみに、名前空間のページは、`std::regex_constants`に加えて、`std::this_thread`もあります。設定される場合には、こちらもお願いします。

**Comment by kariya-mitsuru** [comment]
両方に namespace を設定しました。

**Comment by faithandbrave** [comment]
表示も大丈夫そうですね。

**Comment by kariya-mitsuru** [comment]
editors_doc のテンプレートページにも種別を追加しておきました。

**Comment by faithandbrave** [comment]
ありがとうございます。確認しました。
https://github.com/cpprefjp/site/commit/4855bce93a7db066219916539283c647ac85fc1b

**Comment by kariya-mitsuru** [comment]
追加で問題ないようなので、クローズします。
