### ISSUE TITLE
各ページのナビゲーション部分の更新について

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#264]
すみません、こちらか site_generator 側かちょっとわからないのですが…

サイトに新規ページが追加されたり、既存ページのページタイトルが変わった場合、変更のあったページ自身のナビゲーション（メニュー？）部分は当然最新になるのですが、他のページのナビゲーション部分は更新されていないように思うのですが、何か特別な更新手順等あるのでしょうか？

**Comment by faithandbrave** [comment]
新規ページが追加された日、もしくはページタイトルが変更された日の24時に、更新がかかるそうです。

**Comment by kariya-mitsuru** [comment]
なるほど、日が変わるまで待てばよかったのですね。
了解です。
