### ISSUE TITLE
リンク切れの修正

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#266]
以下の 2 つのリンクが切れているのですが、どのように修正すべきでしょうか。

1. ページ：http://cpprefjp.github.io/mailing-lists.html  
    リンク：[cpp-threads -- C++ threads standardisation](http://www.decadent.org.uk/cgi-bin/mailman/listinfo/cpp-threads)  
    それっぽいサイトは見つけたのですが、こちらで良いでしょうか？  
    リンク：[The cpp-threads Archives](https://www.decadent.org.uk/pipermail/cpp-threads/)
2. ページ：http://cpprefjp.github.io/reference/random/fisher_f_distribution.html  
    リンク：[fisher_f_distribution.tsv.7z](https://github.com/cpprefjp/image/raw/master/reference/random/fisher_f_distribution/discrete_distribution.tsv.7z)  
    それっぽいファイルが過去に削除されていたのですが、フォルダは合っているもののファイル名が異なるのでこれで正しいのか判断がつきませんでした。  
    リンク：[discrete_distribution.tsv.7z](https://github.com/cpprefjp/image/raw/b1228d7283532cc5801e1e6f55385ba0b3a63dc2/reference/random/fisher_f_distribution/discrete_distribution.tsv.7z)  
    また、このファイルで良い場合、他の箇所のように .tsv.7z から .tsv に展開した方が良いでしょうか？

**Comment by kariya-mitsuru** [comment]
後者は discrete_distribution にあるものと同一だったので、違うっぽいですね…

**Comment by faithandbrave** [comment]
スレッドのメーリングリストはそこで大丈夫ですね。現在も生きているメーリングリストではなく、経緯の資料として見るためにリンクを置いておいたものなので、`<thread>`ヘッダページあたりに移動してもいいかもしれません。
7zのファイルはバージョン管理と相性が悪そうなので、tsvにして置き直してあります。そのクラスのサンプルコードを実行すればtsvが出力されるようになっているはずです。

**Comment by kariya-mitsuru** [comment]
cpp-threads の方は、ヘッダページに移動＆リンク切れ修正しました。
tsv の方はグラフを作る難易度が高いのでちょっと待ってください…

**Comment by faithandbrave** [comment]
よろしくお願いします！図は、normal_distributionとかで使っている簡単なのでいいですよ。
https://github.com/cpprefjp/image/tree/master/reference/random/normal_distribution

**Comment by kariya-mitsuru** [comment]
元のグラフに似せて作ってみました。
こんな感じで大丈夫でしょうか？
http://cpprefjp.github.io/reference/random/fisher_f_distribution.html
https://github.com/cpprefjp/image/tree/master/reference/random/fisher_f_distribution

**Comment by faithandbrave** [comment]
バッチリです！ありがとうございます！

**Comment by kariya-mitsuru** [comment]
ご確認ありがとうございます。
それでは対応完了したのでクローズします。
