### ISSUE TITLE
ライブラリ編完了 言語編の作り方を考える

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#267]
正規表現ライブラリを完成させるマイルストーンが完了し、これによってcpprefjpのライブラリ編が完了しました。
まだIostreamとロケール関係が残っていますが、それは追々やっていきましょう。
4年間、2,543ページ(書籍8冊分くらい)と、途方もない量の作業でしたが、お付き合いいただきありがとうございました！

近々、東京で打ち上げをやる予定ですので、近くの方はお立ち寄りください。

[cpprefjpライブラリ編完了の打ち上げ - connpass](http://connpass.com/event/20632/)

現在のcpprefjpの状況は、以下のWikiページを参照してください。

- [C++11までの進捗状況](https://github.com/cpprefjp/site/wiki/progress)
- [C++14の対応状況](https://github.com/cpprefjp/site/wiki/cpp14)

前回のマイルストーンを決めるときに、「次は言語編をやる」と言っていたように、今度はC++の言語機能の解説に入っていきたいと考えています。
言語機能の解説を、どの範囲で、どのくらいの厳密さで、どのような構成で書くのか、みなさんからご意見をいただいて決めていきたいです。

私としては、以下のように考えています。

- [コンパイラの実装状況ページ](http://cpprefjp.github.io/implementation-status.html)に沿って、C++11、C++14で追加・更新された言語機能を解説する。
- C++全体の言語機能を解説することは、とりあえず目指さない。
    - バージョン更新に追従するのがたいへんなのと、量がまた途方もなくなるので、できるところから。
- ページ構成としては、以下の順に項目を並べる。
    - 概要として、機能の簡単な説明と使い方
    - より詳細な仕様(完璧は目指さず、徐々に詳細にしていく)
    - その機能が必要になった背景・経緯
    - 検討されたほかの選択肢(没になった提案とその理由, optional)
    - 関連項目
    - 参照(提案文書、Core Issue、他サイト・ブログの解説記事)

ご意見お待ちしております。
週末しか議論に参加できない人とかを考慮して、最後に意見がでてから1週間後まで合意を待って決定、というふうにして結論を出そうと思います。よろしくお願いします。

**Comment by faithandbrave** [comment]
私の方針で行く場合は、以下のように階層を作っていくことになると考えています。

- lang/cpp11
- lang/cpp14

言語の更新内容のみを扱うのにこの階層名はどうなんだろう、と思ったりもしましたが、必要になったらlang/allとかlang/generalとかの階層名で全体的な言語仕様を扱えばいいかなというふうに考えました。

**Comment by faithandbrave** [comment]
@egtra さんから、「言語拡張を書きたい」という提案を受けました。
これについて、私の方針で行く場合には、lang/extensionという階層を作ってそこで作業してもらえばいいいかな、と思います。

**Comment by usagi** [comment]
> 「言語拡張を書きたい」
> lang/extension

良さそう。確かに日本語の情報は散見される程度の状況に感じられるし、cpprefjpとして整理してまとめる価値は高そう。

**Comment by faithandbrave** [comment]
10/17(土)くらいまで意見を募集し、とくになければ私の案で進めさせていただきたいと思います。

**Comment by yohhoy** [comment]
> 言語機能の解説を、どの範囲で、どのくらいの厳密さで、どのような構成で書くのか、[...]

ターゲット層というか想定読者の前提知識をどう置くのか、というガイドラインが必要だと思いました。横断的な共通設定が無いと、ページによっては初学者向けになったり、エキスパート向けになったりとバラバラになってしまう気がします。

C++11、C++14（以降）の差分記述がメインになると思いますので、「C++03言語機能を概要くらいは知ってる」が前提でしょうか。"概要を知ってる"ってどういうレベルだという問題はありますが…

厳格な合意レベル到達は不可能だと思っていますが、「～できる程度の知識」という表現で何個か並べられると良いなと考えています。（言いだしっぺですが案が無いので提起だけ）

**Comment by faithandbrave** [comment]
いま考えているのはバージョンの差分なので、「前バージョンの知識を持っている人」がターゲットでよいかと思います。

仕様を解説する節は詳細さが求められるでしょうから、規格書の記述に近い形になるでしょう。
概要やその機能の背景といった節は、以下のページくらいの内容を、と考えていました。

<https://isocpp.org/faq>

C# の岩永さんのサイトに載っている新機能のあたりも、それと同じくらいの概要文章だと考えています。

<http://ufcpp.net/study/csharp/>

「仕様の節を読まなくても、概要文章だけでプログラムを書けて、凝ったことをしようとしたときに仕様の節が必要になる」というような使い方ができるといいですね。
これはライブラリ編の方も同様だと考えています。いまは概要が一文だけになっているところが多いですが、もうちょっと概要文章を充実させたいです。

**Comment by faithandbrave** [comment]
それと、書き方がバラバラになるのをできるだけ抑えるために、方針が決まったら私のほうで、雛形ページと、なにか一つ言語機能の解説ページを作ろうかと思っています。
それらのページをレビューして作り方が決まったら、そのページの説明粒度や書き方を参考にして、ほかの解説ページを作っていければと思います。

**Comment by usagi** [comment]
:+1:

**Comment by egtra** [comment]
いいと思います。私が言った、言語拡張についても、同様の方針でやっていけば良さそうですね。

**Comment by faithandbrave** [comment]
別の案や反対意見がとくにでなかったので、上に挙げた方針で進めようと思います。
たたき台の記事を書いてそれをレビューするまでの一連のタスクを作ったら、このIssueを閉じます。

**Comment by usagi** [comment]
:+1:
