### ISSUE TITLE
イテレータの説明を書く

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#269]
以下の2つを書こうと考えています。
- イテレータとは(コンテナとアルゴリズムの中間インタフェースである、とか)
- イテレータの分類

やり方としては、articleに記事を置いて、それを`<iterator>`ヘッダページの冒頭で参照する、という形にしようと思います。

**Comment by faithandbrave** [comment]
「イテレータの分類」ページはいま、 @melpon が書いているそうです。

**Comment by melpon** [comment]
ということで引き取ります。

**Comment by faithandbrave** [comment]
`/reference/concepts`ディレクトリの下に、CopyAssignableやDefaultConstructibleなどのコンセプトを解説するページを追加しておいたので、イテレータを解説する際に使って(リンクを貼って)ください。

**Comment by faithandbrave** [comment]
このタスクは #712 でやるので終了します。
