### ISSUE TITLE
ページ名"SI単位"は適切でない(？)

### ISSUE THREAD

**Issue by yohhoy** [cpprefjp/site#270]
https://github.com/cpprefjp/site/blob/master/reference/ratio/si_unit.md
上記ページは「SI単位」というページ名ですが、実際には`kilo`や`milli`などの「SI基本単位につけられるSI接頭辞」のリストです。

とはいえ、厳密さをとって「SI接頭辞」では一般に分かり辛いのではとの懸念もあり、一旦Issueとしてあげました。

参考：[国際単位系](https://ja.wikipedia.org/wiki/%E5%9B%BD%E9%9A%9B%E5%8D%98%E4%BD%8D%E7%B3%BB)、[SI接頭辞](https://ja.wikipedia.org/wiki/SI%E6%8E%A5%E9%A0%AD%E8%BE%9E) by Wikipedia

**Comment by faithandbrave** [comment]
調べなおしてから返信します！少しお待ちください。

**Comment by faithandbrave** [comment]
調べました。SI接頭辞でよさそうな気がします。調べる際のキーワードにもなりますので。
「SI接頭語」と言っているところも見かけましたが、「SI接頭辞」の方が主流のようです。

ページファイル名は`si_unit_prefix.md`あたりでしょうか。
Metric prefixという言葉もよく使われるようですが、日本語だとSI prefixもMetric prefixも、どちらも「SI接頭辞」と訳されるみたいですね。規格書でも「SI」という言葉は出てきているので、その言葉は残すのがいいでしょうね。

**Comment by usagi** [comment]
化学系に長いこと居た染み付きで"一般には"というのはもしかしたらずれがあるのかもしれませんが、その上でも「SI接頭辞」とするのが良いと思います。

少くとも現代のサイエンス教育ではSI接頭辞と教えたりを通常としているはずですし、SI接頭辞でわかりにくい層というのは「キロとかミリとかそういうやつ」という表現でないと通じない層かと思うので、それは仕方ないかなーと。

**Comment by usagi** [comment]
あんまり大きく変えたくなければ「SI単位系」とすれば組立単位や接頭辞も含めてひっくるめた表現にはなりますが、実際のところはそのうちのSI接頭辞のみしか扱っていないページなので、やはりその意味でもSI接頭辞とするのが良いと思います。

**Comment by faithandbrave** [comment]
修正は @yohhoy さんにお願いしますね。

**Comment by yohhoy** [comment]
ページ名は「SI接頭辞」に編集しようと思います。ファイル名は`si_prefix.md`でしょうか？

**Comment by faithandbrave** [comment]
OKです。
