### ISSUE TITLE
fix-up: random/extreme_value_distribution: 数式の修正

### ISSUE THREAD

**Issue by usagi** [cpprefjp/site#277]
> exp は \exp にしていただけますか．

rel.: https://github.com/cpprefjp/site/issues/272#issuecomment-149095785

------

既に閉じたチケットで複数の修正をすべきではないと考えるのでコメントを頂いた事後に発生した別件として対応。

**Comment by usagi** [comment]
@e-kwsm fixed. thanks :+1:

**Comment by e-kwsm** [comment]
you too
