### ISSUE TITLE
言語編の作り方として、たたき台の記事をレビューする

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#278]
言語編を作り始めるのに際して、まず以下のページを作りました。

- `/lang.md`に言語編のトップページ
- `/lang/cpp11.md`にC++11の概要説明、および機能リストと各機能解説へのリンク
- `/lang/cpp14.md`にC++14の(以下同上)

それと、各機能の解説を書いていくにあたって、参考とするためのたたき台記事を書きました。

- `/lang/cpp11/nullptr.md`
- HTMLはこちら : <http://cpprefjp.github.io/lang/cpp11/nullptr.html>

技術的な細かい間違いは、別でIssueを立てるか直接修正するかしていただくとして、ここでは、以下のことを議論したいです：

- 解説の分量が必要十分か
- 概要文章を読むだけで使えるか
- 項目は必要十分か

このレビューが終わったら、C++11とC++14の、各言語機能を書くタスクをIssueとして作ろうと思います。レビューよろしくお願いします。

**Comment by usagi** [comment]
1. その機能を使うエグザンプルがあると機能を知ろうとページを訪れる人には心強い親切になるかもしれない
2. 「この機能が必要になった背景・経緯」と「検討されたほかの選択肢」は有意義だが、1段階見出しレベルを落としてコラムというかmiscというか、そうしたものの中のコンテント群とした方がページを参照する素人、玄人ともに機能把握やページ構成の把握と見やすさの面から良好になるかもしれない。
    - また、記事を初稿で書く段階からこれらを十分に記述できない場合にも、できる範囲で作業を分担してくれる人はいるかもしれないので、テンプレートとしてはあるが初稿ではオプショナル（項目は用意するが「執筆中」としてもよいなど）な扱いでもよいかもしれない。

-----

テンプレおつおつ :+1:

**Comment by faithandbrave** [comment]
> その機能を使うエグザンプルがあると機能を知ろうとページを訪れる人には心強い親切になるかもしれない

概要のところに書いたつもりですが、専用の項目が必要ということでしょうか？

> 「この機能が必要になった背景・経緯」と「検討されたほかの選択肢」は有意義だが、1段階見出しレベルを落として

んー。「この機能が必要になった背景・経緯」というのは、使い方に直結するもので、「この機能によって解決したい問題はなんだったのか」の詳細なのですよね。なので、これは言語設計に興味があるないに関わらず重要度の高いものだと考えています。

「検討されたほかの選択肢」は見出しレベル3にしてもよいのですが、見出しレベル2は何にするのがいいでしょうね・・・。

**Comment by faithandbrave** [comment]
> また、記事を初稿で書く段階からこれらを十分に記述できない場合にも、できる範囲で作業を分担してくれる人はいるかもしれないので、テンプレートとしてはあるが初稿ではオプショナル（項目は用意するが「執筆中」としてもよいなど）な扱いでもよいかもしれない。

cpprefjpはライブラリ編も元々そういう方針なので、雛形に書いておきますかね。

**Comment by usagi** [comment]
> 概要のところに書いたつもりですが、専用の項目が必要ということでしょうか？

そうか、確かに。`nullptr`だと概要のコード例も短く、それがエグザンプルを兼ねている事に気づかず失礼しました。

リファレンスでは http://cpprefjp.github.io/reference/array.html のように「概要」と「コード例」を分けて解説していたので、サイト構成全体へのユーザビリティー的にも「コード例」が明示的に分離されている事は好ましいかも。

あるいは、「概要」の内部の1段下レベルの見出しで「コード例」を明示するのも解説としてのまとまりが「概要」で得られて良いかもしれません。

やってみて、「コード例」を明示的な見出しにしてしまうと、見出しが多くてごちゃごちゃしてしまうという事が無ければ、明示自体はした方が優しいかもしれません。

**Comment by faithandbrave** [comment]
仕様の下に、コード例を追加してみました。
https://github.com/cpprefjp/site/commit/0845c76e1fef6fe596a3c9f7e4ee5f063c82757f

**Comment by usagi** [comment]
> 仕様の下に、コード例を追加してみました。

項目が増えて少々煩雑になったようにも見えてしまいますが、私はこの追加は先に述べたユーザビリティーなどからも良い修正に思います。

ほか、ご意見出してくれる方あればちらほら伺いたいですね。

**Comment by faithandbrave** [comment]
10月31日(土)中くらいまで意見を待ちます！
