### ISSUE TITLE
コード部分の { に謎の赤枠がついて表示されている

### ISSUE THREAD

**Issue by usagi** [cpprefjp/site#279]
http://cpprefjp.github.io/lang/cpp11/nullptr.html を見ていて気付いた。

![image](https://cloud.githubusercontent.com/assets/115972/10629257/405463e6-7808-11e5-8834-c5cb4d8d69a3.png)

詳しく解析していないが、chromiumのインスペクターによると、特定のCSSファイルではなく要素へ直接style指定されているようだ。

![image](https://cloud.githubusercontent.com/assets/115972/10629281/7099b862-7808-11e5-85fd-dc0275517332.png)

.md --> .html の変換時についてるのかな？

**Comment by melpon** [comment]
これはシンタックスハイライトで使ってる [Pygments](http://pygments.org/) がエラートークンの場合に設定するものですね。
http://pygments.org/demo/2916302/
今回の場合、`class`の後ろにクラス名が来てなくてうまいこと解釈できなくなっているのだと思います。

Pygments自体を直すか、エラートークンを無視するCSSや設定を書くようにするとかそういう感じになると思いますが、別にそこまでしなくてもいいんじゃないかなぁという気も。

**Comment by faithandbrave** [comment]
Pygmentsのドキュメントを読むと、エラートークンのスタイルを設定する機能があるみたいなので、これを使えばいけるかも？

<http://pygments.org/docs/styles/>

```
from pygments.style import Style
from pygments.token import Keyword, Name, Comment, String, Error, \
     Number, Operator, Generic

class YourStyle(Style):
    default_style = ""
    styles = {
        Comment:                'italic #888',
        Keyword:                'bold #005',
        Name:                   '#f00',
        Name.Function:          '#0f0',
        Name.Class:             'bold #0f0',
        String:                 'bg:#eee #111'
    }
```

PygmentsはまだC++14の構文に対応していないようで、桁区切り文字がエラーとなります。
<http://cpprefjp.github.io/lang/cpp14/digit_separators.html>
Pygmentsの対応を待つか、エラー表示だけ消しておくか、どっちかですね。nullptrの方は永遠に直らない気がするので、エラー表示を消しておくのがいい気がします。

**Comment by usagi** [comment]
じわじわーっとユーザーは「なんだろう？」って違和感あるいは何か意味があって枠がついているのかもって感じてユーザビリティー的にちょっと不親切なので、できれば暫定措置で赤枠つかないようにCSS調整するだけでも対応できると良さ気ですねー。

対応可能性の調査、ありがとうございます。

**Comment by usagi** [comment]
Thanks! :+1:
