### ISSUE TITLE
言語機能の解説を書く : C++11 auto

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#284]
/lang/cpp11階層以下に、autoの解説を書いてください。

書き方は、以下のページを参考にしてください：

- /editors_doc/lang_template_page.md
- /lang/cpp11/nullptr.md

**Comment by faithandbrave** [comment]
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2004/n1721.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1794.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1894.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n1984.pdf>

**Comment by kariya-mitsuru** [comment]
自信ないけどやってみます

**Comment by faithandbrave** [comment]
よろしくお願いします！(ぼくができれば書きたくなかったものなので、助かります)

**Comment by kariya-mitsuru** [comment]
書きましたので、クローズします。
何かあれば修正お願いします…
