### ISSUE TITLE
言語機能の解説を書く : C++11 decltype

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#285]
/lang/cpp11階層以下に、decltypeの解説を書いてください。

書き方は、以下のページを参考にしてください：

- /editors_doc/lang_template_page.md
- /lang/cpp11/nullptr.md

**Comment by faithandbrave** [comment]
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2003/n1478.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2003/n1527.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2004/n1607.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2004/n1705.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n1978.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2115.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2343.pdf>

**Comment by faithandbrave** [comment]
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#743
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#950
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3031.pdf
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3276.pdf

**Comment by kariya-mitsuru** [comment]
一応書き終わったのでクローズします。
誤りや不足等あったらバンバン修正してください…

**Comment by faithandbrave** [comment]
ありがとうございます！あとはムーブセマンティクスだけですね。(タスク上は)
