### ISSUE TITLE
言語機能の解説を書く : C++11 右辺値参照・ムーブセマンティクス

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#303]
/lang/cpp11階層以下に、右辺値参照・ムーブセマンティクスの解説を書いてください。

書き方は、以下のページを参考にしてください：

- /editors_doc/lang_template_page.md
- /lang/cpp11/nullptr.md

**Comment by faithandbrave** [comment]
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2118.html>

**Comment by LoliGothick** [comment]
やります

**Comment by faithandbrave** [comment]
よろしくお願いします！不明点があれば相談してください。

**Comment by LoliGothick** [comment]
遅くなりましたが、草案ができました
https://github.com/LoliGothick/cpprefjp-draft/blob/master/rvalue_ref_and_move_semantics.md

**Comment by faithandbrave** [comment]
ありがとうございます！
構成および内容として問題なさそうですので、これでpull requestをお願いします。
あとは追々、加筆修正していきましょう。

**Comment by LoliGothick** [comment]
了解しました
