### ISSUE TITLE
言語機能の解説を書く : C++11 可変引数テンプレート

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#309]
/lang/cpp11階層以下に、可変引数テンプレートの解説を書いてください。

書き方は、以下のページを参考にしてください：

- /editors_doc/lang_template_page.md
- /lang/cpp11/nullptr.md

**Comment by faithandbrave** [comment]
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2003/n1483.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2004/n1603.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2004/n1704.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2080.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2152.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2191.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2242.pdf>

<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2488.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2555.pdf>

**Comment by bolero-MURAKAMI** [comment]
『パラメータパックの拡張』の説明について、
> f(g(args)...)のようにパラメータパックの各要素に共通の処理を適用することもできる。

この文言上は、共通の処理を記述するのが式(expression)であるのか文(statement)であるのか若しくは両方であるのか不明瞭です。

以下のように書いた方が宜しいと思います。
> f(g(args)...)のようにパラメータパックの各要素に共通の処理を適用する式を書くこともできる。

**Comment by faithandbrave** [comment]
修正しました。ありがとうございます。
