### ISSUE TITLE
言語機能の解説を書く : C++11 overrideとfinal

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#311]
/lang/cpp11階層以下に、overrideとfinalの解説を書いてください。

書き方は、以下のページを参考にしてください：

- /editors_doc/lang_template_page.md
- /lang/cpp11/nullptr.md

**Comment by faithandbrave** [comment]
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1827.htm>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2009/n2852.html>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3151.html>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3163.pdf>
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3234.pdf>

**Comment by katsuster** [comment]
経緯だけが非常に長くなってしまいましたが、
ひとまず第1版として入れさせていただきます。
