### ISSUE TITLE
アライメントとアラインメント

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#344]
alignmentの訳語が、サイト内で表記揺れしています。以下の2つがありますが、どちらがより適切でしょうか。

- アライメント
- アラインメント

英辞郎を見る限りでは( <http://eow.alc.co.jp/search?q=alignment> )、発音はəláinməntとなっているので、n(ん)は含むように見えます。
どこかalignmentに関する日本で有名な解説サイトや書籍があったら、そこの訳語を採用するとかでもいいと思います。

ご意見お待ちしています。

**Comment by faithandbrave** [comment]
結論がでたら、以下のページの訳語表に追加します。
<http://cpprefjp.github.io/working_style.html>

**Comment by faithandbrave** [comment]
Intel C++ Compilerの公式日本語ドキュメントでは「アライメント」が採用されているようです。
<http://www.intel.co.jp/content/dam/www/public/ijkk/jp/ja/documents/developer/ccomp40j.pdf>

**Comment by usagi** [comment]
- 一般的に日本語のカタカナ語にする時に落とす「詰まる発音のン」ではないかと思う。
- 類似の例としては "enlightenment" とか
    - alc : http://eow.alc.co.jp/search?q=enlightenment&ref=sp
        - レベル8、発音inláitə_n_mənt、カナエンライトゥ_ン_メント、エンライト_ン_メント、分節en・light・e_n_・ment
    - wikipedia.jp : https://ja.wikipedia.org/wiki/Enlightenment
        - 日本語のカタカナ語として一般には「エンライトメント」となる

**Comment by faithandbrave** [comment]
それは知りませんでした。では、「アライメント」にしましょうか。
2016/01/12(火) 15:00くらいまで待ってとくに反対意見がなければ、それで決めます。

**Comment by melpon** [comment]
アライメントに :+1:

**Comment by katsuster** [comment]
同じ記事内で表記揺れさせてました、申し訳ないです…。
「アライメント」に一票です。

以下参考です。
* 大辞泉は「アラインメント」でした。
http://dictionary.goo.ne.jp/jn/7055/meaning/m0u/
* MSDN は表記揺れしていました…。
https://msdn.microsoft.com/ja-jp/library/ycsb6wwf.aspx

**Comment by faithandbrave** [comment]
> 同じ記事内で表記揺れさせてました、申し訳ないです…。

気にしないでください！間違いや表記揺れがあったら誰かが気づいて直しますので、このプロジェクトでは、ひとつのコミットで完璧は目指さなくて大丈夫です！
