### ISSUE TITLE
他の人が書いたページの修正について

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#349]
https://github.com/cpprefjp/site/commits/8dc457b3ead1865500ce02c454de2e3fba226099?author=k-satoda
こういう、他の人が書いたところの修正について、黙って勝手に入れちゃう
よりも一度プルリクエストの形にしたほうがよかったりするでしょうか？

元の記事を書いた人に伝えないといけなさそう、勝手に書き変えられると
気を悪くされることもある？自分も間違ってるかも？・・・とかいうあたりを
気にしてます。

ただ、気にしすぎで、面倒なだけだったりするかも？とも思います。

~~特にどうしろということがなければ、次やるときはプルリクエストにしてみる
つもりです。~~（考え直した内容でコメント追加しました。→ https://github.com/cpprefjp/site/issues/349#issuecomment-189785609 ）

**Comment by faithandbrave** [comment]
Twitterでも返信しましたが、こちらでも。

誰かに修正内容を確認してほしい場合はpull requestでもいいかなと思いますが、修正されたものに問題ありそうならissueを作るので、今までのやり方でも大丈夫です。非常に助かってます。
とくに @k-satoda さんの場合には、修正のコミットに理由を明記してくださっているので、そのやり方であれば問題ないです。理由が記載されていないと「なんで直したんだよ」とクレームが来そうなので、とくにほかの人が書いたものに対する修正は、コミットメッセージに気をつけたほうがいいですね。

pull requestかissueで必ずやってほしいものとしては、これまでの方針・スコープに含まれない新しいことをやる場合ですね。その際は、合意をとってほしいです。

これは私の意見として表明しましたが、ほかに意見がある方はお願いします。
このissueに対する結論が出たら、私の方でCONTRIBUTING.mdファイルを作成して、ルールを明文化しようと思います。そのルールの改訂についてもissue/pull requestを受け付けられるようにします。
意見はとくになければ2016年3月2日 18:00くらいに締め切ります。

**Comment by k-satoda** [comment]
返信ありがとうございます。

この issue 作ったあと、「黙って直す」と「pull requestを作る」のほかにも
その間を取る感じの「issueを作る」「コミット（差分）にコメントをつける」
というやりかたもあるなーと思いました。後者２つの場合は、元を書いた人に
伝えることはできたうえで、ブランチが要らない、承認・マージなどの手間を
要求することはないという点で pull request よりも面倒がなさそうです。

後者の２つの間でも、コメントをつける形のほうが issue タイトルとかも
考えないぶん楽にできそうに思います。簡単に問題点を書き出したうえで
「異論なければそのうち修正入れときます」みたいな感じで。

「他の人が書いたところの修正」といっても誤字脱字・書式の修正（内容・
意図が変わらない修正？）は特に何もする必要なく、黙って直接入れちゃえば
いいと思ってます。

ということで、コミットされた記事に問題と思われる箇所を見つけたときには
↓こんなフローで動き方を選ぼうと思ってます。
- 修正方針がわからない・複数考えられるが決めかねるようなら
  issue を作る。
- 修正はできるが修正内容について修正者以外の合意・確認が必要そうなら
  pull request を作る。
- 元の記事を書いた人に伝えておきたいだけなら、
  事前にコメントを飛ばしたうえで直接修正する。
- ↑のようなことが何もなければ直接修正でいい。

**Comment by faithandbrave** [comment]
そのフローに合意します。

**Comment by tshino** [comment]
最近ここへjoinした者ですが、早速いくつか「人の記事の修正」をコミットしました。
間違っていたり、もっとよい修正方法がある可能性は分かっていて、迷いもあったので、
このような指針が明文化されると助かります。

**Comment by faithandbrave** [comment]
@tshino 
すごく助かってます！編集者向けドキュメントはなるべく用意するようにしているのですが、まだまだ十分と言えないところはあります。ほかにご不明な点があれば、今回と同じようにissueを立てていただければと思います。

**Comment by faithandbrave** [comment]
CONTRIBUTING.md を追加しました。 @k-satoda さんからいただいたフローを、ほぼそのまま記載してあります。そちらにも記載してありますが、方針の変更を提案する場合には、issueかpull requestを作っていただければと思います。

**Comment by usagi** [comment]
わかりやすくてGOOD :+1:
