### ISSUE TITLE
要約にHTMLタグを使っているページについて

### ISSUE THREAD

**Issue by katsuster** [cpprefjp/site#350]
要約にHTMLタグを使っているページ（例えばreference/deque.md）は、タグを使わないように直した方が良いでしょうか？

Markdownのプレビューでは問題ないように見えるものの、site_generatorによる変換後のHTMLを見ると、上部に要約が表示されてしまいます。
http://cpprefjp.github.io/reference/deque.html

**Comment by usagi** [comment]
![image](https://cloud.githubusercontent.com/assets/115972/13445149/ee7f1972-e04d-11e5-81db-cb34142efcbb.png)

なるほど、これは悲しみ。バグなので見つけたら修正して頂けると助かります。ご指摘ありがとうございます。

**Comment by faithandbrave** [comment]
ちょっと待ってくださいね。これはまず、site_generator側のバグだと思われますので、タグを直すのはそのあとでお願いします。必要があってHTMLタグを使っているところもありますので(supとかです)、site_generator側のバグを直してからじゃないと、バグを隠すことになってしまいそうです。

**Comment by melpon** [comment]
cpprefjpは[Twitter Cards](https://dev.twitter.com/ja/cards/overview)や[OGP](http://ogp.me/)に対応しているのですが、それのdescriptionがエスケープされてなくておかしなことになってました。

**Comment by usagi** [comment]
あらま、判断ミスリプごめん＞かくい
  ＆修正おつ

**Comment by katsuster** [comment]
反応遅くてすみません。修正ありがとうございます。
コミット差分見たらエスケープする/しないが 2文字で表現されていて驚きでした。

サイトの方も直っていましたので、クローズいたします。
