### ISSUE TITLE
サイズ付きデアロケーションの例について

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#352]
[サイズ付きデアロケーション](http://cpprefjp.kariyam.com/lang/cpp14/sized_deallocation.html)の例の中に

> デストラクタを明示的に定義しない場合、
> 破棄処理を呼び出す必要なしと判断され、
> delete演算子が呼び出されない可能性がある

とのコメントがあるのですが、これは規格書のどこかで言及されているものでしょうか？
探してはみたのですが、ちょっと見つからなかったので…

**Comment by kariya-mitsuru** [comment]
あ、すみません、ついでに。
例が配列形式なのは何か意図があるでしょうか？

配列形式は [CWG Issue 1788. Sized deallocation of array of non-class type](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1788) で修正が入ってるので、C++14 の規格書通りに実装されている処理系は無いんじゃないかなぁ、と思ったもので…
（こんなの実装できね～よっていう Issue なので…）

**Comment by faithandbrave** [comment]
その1788によるものですね。non trivialなデストラクタを持ってないと、サイズを受け取るdelete演算子が現在のどの実装でも呼ばれなかったのでそうしています。

配列形式にしているのは、C++標準ライブラリで定義されているグローバル変数が非配列のみだからですね。置き換えとして定義しているnewとdeleteが標準のグローバル変数のためにも呼ばれるので、標準出力として、例に使っているAオブジェクトのアロケートだけを出力したかったのでした。

**Comment by kariya-mitsuru** [comment]
なるほど。であれば、

> デストラクタを明示的に定義しない場合、
> 破棄処理を呼び出す必要なしと判断され、
> delete演算子が呼び出されない可能性がある

は、

> デストラクタを明示的に定義しない場合、
> サイズをとる delete演算子が呼び出されない可能性がある

の方が良いと思うのですがいかがでしょう。

「破棄処理を呼び出す必要なしと判断され」の部分は、実際のところは
「破棄処理を呼び出さなくて良いことから要素数を保存する必要がないため、サイズが不明となり」
が正しいと思うのですが、長ったらしいですし、規格にそこまで記載されているわけでもないので。

**Comment by faithandbrave** [comment]
修正しました。
