### ISSUE TITLE
__STDC_MB_MIGHT_NEQ_WC__ について

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#353]
[C99互換で導入された定義済みマクロ](http://cpprefjp.kariyam.com/lang/cpp11/c99_predefined_macros.html) に `__STDC_MB_MIGHT_NEQ_WC__` が記載されているのですが、このマクロは C99 にはありません（C11にはある）。
以下のような修正方法があると思いますが、どのように修正すれば良いでしょうか。
1. このページのタイトルを変える
2. `__STDC_MB_MIGHT_NEQ_WC__` だけ別ページに切り出す
3. その他

**Comment by faithandbrave** [comment]
こっちに移動しましょう。
<http://cpprefjp.github.io/lang/cpp11/predefined_macros.html>

**Comment by kariya-mitsuru** [comment]
ありがとうございます。移しました！
