### ISSUE TITLE
「後置戻り値型をプレースホルダーにすることを許可」について

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#355]
[後置戻り値型をプレースホルダーにすることを許可](https://github.com/cpprefjp/site/blob/master/lang/cpp14/placeholder_type_in_trailing_return_type.md) の「この機能が必要になった背景・経緯」に

> この機能は、C++14で導入された「通常関数の戻り値型推論」の機能で、戻り値の型推論を補助するために導入された。

とあるのですが、これは cwg の issue や提案のペーパーか何かに記載があるでしょうか？

通常関数の戻り値型推論の場合、わざわざ後置戻り値型でプレースホルダーを使用しなくても、直接 `auto&` などを使用する事ができるので、この機能はあくまでもラムダ式の戻り値型指定の機能強化を目的としていると思っていたのですが…

**Comment by faithandbrave** [comment]
どこに載ってたのか忘れてしまったのですが、読み直したらラムダ式で参照を返すのが目的と書いてあったので、修正しておきます。
