### ISSUE TITLE
C++11 extern template: 実行ファイルサイズ、リンク時最適化への言及について

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#357]
https://github.com/cpprefjp/site/blob/904776446e00b1abbf5f71cfa70a9499fe136fb1/lang/cpp11/extern_template.md
> これを使用することによって、複数の翻訳単位で同じテンプレートの
> インスタンス化が行われることを抑制できる。それによって、コンパイル速度が
> 向上すること、および実行ファイルのサイズが膨れ上がるのを抑える効果が期待
> できる。

テンプレート実体によるバイナリはリンク時にひとつにまとめる必要がある
ので、実行ファイルに残るバイナリのサイズが  extern template の使用で変わる
ことはなく、ここの「実行ファイルのサイズ」は「各翻訳単位に対応する
オブジェクトファイルのサイズ」の間違いかと思います。
（これは N1987 の Introduction でも確認できます。）

ただ、備考で以下のような言及もあります。
> バイナリサイズの肥大化については、コンパイラの「リンク時最適化
> (Link Time Optimization, LTO)」によっても抑制を期待できる。

ここの「バイナリサイズ」が実行ファイルサイズのことを言っているのか、
オブジェクトファイルサイズのことを言っているのか、わかりません。また、
どちらにしても extern template とはあまり関係無いように思います。
（ N1987 でもリンク時最適化についての言及は見当たりませんでした。）

もし実行ファイルサイズのことであれば先に挙げた点を修正するにあたって
いっしょに削除しちゃえばいいと思いますが、それで大丈夫でしょうか？

やっぱり言及しておいたほうがいいということであれば、 extern template と
リンク時最適化との関係、あるいはリンク時最適化とバイナリサイズ
（オブジェクトファイルサイズ？）との関係について情報をください。

**Comment by faithandbrave** [comment]
すいません、勘違いでした。修正お願いします。リンク時最適化の文章も削除していただいて大丈夫です。
