### ISSUE TITLE
INTn_MIN, [U]INTn_MAX の具体的な定義内容が C99 の規定に違反している

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#358]
https://github.com/cpprefjp/site/commit/d1ba8acca46a6979e1b129821834ae29f37ec8c8#diff-f9a976c23417136f880e58ca2104f98cR7
> +#define UINT16_MAX (uint16_t)65535U

上記箇所を含めていくつか INTn_MIN, [U]INTn_MAX の具体的な定義内容を
記述している箇所について。

C99 ([wg14 n1256](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf)) 7.18.2 p2 より
> Each instance of any defined macro shall be replaced by a constant
> expression suitable for use in #if preprocessing directives, and this
> expression shall have the same type as would an expression that is an
> object of the corresponding type converted according to the integer
> promotions. ...

...ということで、プリプロセッサで使える定数であることが要求されている
ことからキャストを含めることはできません。また、型については対応する型
そのものではなくその型を整数昇格させた型と一致することが要求されて
います。

１点目に付いてはキャストを外して済ませることが考えられますが、２点目も
考慮すると、型が固定でない以上は具体的な型が期待できるかのような記述は
やっぱり望ましくないと思います。

他の INT_FASTn_MIN などと同様に定義内容は "implementation-defined" に
置き換えてしまうのがいいんじゃないかと思ってます。わかりやすい数値の
表記も欲しいということであれば概要の数式での表記の後ろに添える感じで。

お知らせも兼ねてまずは @faithandbrave さんにアサインさせてもらいますが、
特に異論無いまま置いてあればやる気が出たときに手をつけるかもしれません。

**Comment by faithandbrave** [comment]
ありがとうございます。私のほうで対応します。

**Comment by faithandbrave** [comment]
修正しました。問題があれば、reopenするか直接修正してください。
