### ISSUE TITLE
「1バイトが7ビット」？

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#359]
https://github.com/cpprefjp/site/commit/6d2c3997c741dbac1d1247e092c6759c3f6591e0#diff-01b7ff6b64842e28f1c03373435df0d3R21
> CPUによっては1バイトが7ビットや9ビットになる場合があるため、そういった
> 環境では8ビットの乗数幅を持つ整数型が定義されていない可能性がある。

ここで言う「バイト」が C++ における「バイト」であれば、 CHAR_BIT >= 8 が
要求されるため 7 ビットにはならないです。「CPUによっては」とあるので
CHAR_BIT とは違う話なのかもしれませんが、 CPU の定義する「バイト」が
7 ビットというのは聞いたことがなくて、改めてちょっと検索してみた範囲でも
見つけられていません。

なお CHAR_BITS が 9 ビットの処理系がかつて存在したことは確認できました。
http://pdp-10.trailing-edge.com/SRI_NIC_PERM_FS_1_19910112/01/c/include/limits.h.html

そんなわけで「処理系によっては1バイトが8ビットでないことがあり、
そういった環境では～」あたりでいいんじゃないかと思います。
6d2c3997c741dbac1d1247e092c6759c3f6591e0 と 947f869aad7dc4727d3d84faa8696323da52e1ec で手が入った箇所以外に同様の記述が無いかどうか
気になってますが、特に探してはないです。

お知らせも兼ねてまずは @kariya-mitsuru さんにアサインさせてもらいますが、
特に異論無いまま置いてあればやる気が出たときに手をつけるかもしれません。

**Comment by faithandbrave** [comment]
修正案の内容としてはそれで問題ないと思います。
CHAR_BITが属している`<climits>`は、freestanding環境の対象外なので、C++のあらゆる処理系に要求されるものではないような気がしてます。

**Comment by k-satoda** [comment]
@faithandbrave @kariya-mitsuru 対応ありがとうございます。

対応してもらったところのほかに「1バイトが7ビット」というような記述が
無いか "(7|７)\s*(bit|ビット)" で検索してみてヒットしなかったので、
クローズします。
