### ISSUE TITLE
[C++14][言語機能] 宣言時のメンバ初期化を持つ型の集成体初期化を許可

### ISSUE THREAD

**Issue by yohhoy** [cpprefjp/site#361]
記事タイトルからは [N3605 Member initializers and aggregates](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3605.html) が主題のように読めますが、[CWG Defect #1270. Brace elision in array temporary initialization ](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1270)の説明がメインになっています。

```
struct S {
  int a;
  int b = 5;
};
S s0{ 1, 2 };  // a=1,b=2で構築
S s1{ 1 };  // a=1,b=5で構築
```

現状のCWG#1270説明を消す必要もないと思いますが、N3605の内容は新たに追記が必要かと考えます。

**Comment by faithandbrave** [comment]
正しい説明を @yohhoy さんが把握しているのであれば、 @yohhoy さんが修正されるのがよいかと思います。現在の説明は大きく変えていただいてかまわないのと、必要であれば全て削除して書き直していただいてもかまいません。

※ おそらく、私はこのサイトで2,000ページ近く書いてると思いますが、それらページの全ての問題報告に私が直接修正することはできないので、今回のことに限らず、そのような報告があった場合、可能であればページ執筆者以外もご協力いただけると助かります。

**Comment by yohhoy** [comment]
加筆作業はこちらで可能です。言語機能ページは先にタイトル一覧があってから内容を書かれていたと思ったので、タイトルで元々目指していた内容を確認しておきたいというのが本Issueの意図でした。

**Comment by faithandbrave** [comment]
N3653とCWG DR1270を混同していたようです。記事タイトルの意図としては、N3653の方でした。
加筆作業お願いします。

**Comment by yohhoy** [comment]
確認ありがとうございます。（少し時間を頂きますが）記事更新しておきます。

**Comment by yohhoy** [comment]
#955 での現状整理通り、コミット 39325f4b21fd96255cbcbfd5c39d065efe8deb30 での下準備にともなって
「宣言時のメンバ初期化を持つ型の集成体初期化を許可」 cpp14/brace_elision_in_array_temporary_initialization ページを作る必要あり。

**Comment by yohhoy** [comment]
5年（！）も放置していたので、本issueの割り当てを外します。どなたか対応お願いします...
