### ISSUE TITLE
https対応

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#374]
2017年1月1日から、iOSでhttpsのページしか見れなくなることもあり、cpprefjp/boostjpのGitHub Pagesをhttpsに対応しようと思います。

作業としてはGitHub Pagesリポジトリの設定でhttpsのチェックボックスをオンにするだけなのですが、念のためアナウンスとしてIssueを立てました。

- [Securing your GitHub Pages site with HTTPS - GitHub Help](https://help.github.com/articles/securing-your-github-pages-site-with-https/)

問題なければ、12月2日にその対応をし、動作しているようであれば本Issueを閉じようと思います。
懸念事項があればそれまでにコメントください。

**Comment by faithandbrave** [comment]
関連Issue : https://github.com/boostjp/site/issues/117

**Comment by melpon** [comment]
リダイレクトされるとはいえ、httpサイトに行くのは嬉しくないので、https化した際に以下のURLもhttpsに直しておいた方が良さそう。

```
CONTRIBUTING.md|2 col 85| 本リポジトリは、C++の日本語リファレンスサイト[cpprefjp](http://cpprefjp.github.io/)のコンテンツを扱っています。私たちは、本サイトを一緒に編集していただける方を歓迎いたします。
README.md|4 col 76| このリポジトリは、C++リファレンスサイト[cpprefjp](http://cpprefjp.github.io/)のMarkdownソースです。
```

あと https://github.com/cpprefjp/site の説明URLも。

**Comment by faithandbrave** [comment]
直しておきます。
MarkdownからHTMLへの変換も直す必要があるでしょうか？

**Comment by melpon** [comment]
あーなるほど、今直しても問題なかったんですね。

> MarkdownからHTMLへの変換も直す必要があるでしょうか？

大丈夫だと思ってましたが、今見たら

https://github.com/cpprefjp/site_generator/blob/master/settings/cpprefjp.py#L17

こんなのがあったので、これをhttpsにしておく必要がありそう。

**Comment by faithandbrave** [comment]
明記していなかったですが、Googleの常時SSL化宣言 (HTTP Everywhere)もあり、HTTPSに対応していないサイトはGoogleの検索順位が下げられたりするので、対応すること自体は必須になりますね。

ここで言う「HTTPS対応の懸念事項」とは、httpsで本サイトにアクセスするとブラウザから「危険なサイトだから開けない」と言われて、デフォルトhttpsにしたときにユーザーに見えなくなってしまう、といった問題を洗い出しましょう、ということでした。

**Comment by faithandbrave** [comment]
site_generatorは、修正の反映を @melpon にしてもらう必要があるので、可能なら @melpon に作業をしてもらったほうが早いと思いますが、お願いできますか？

**Comment by melpon** [comment]
修正ed。反映はデイリー更新で勝手にやってくれるはず（念のため帰ったらスクリプト確認してみます）

**Comment by faithandbrave** [comment]
ありがとうございます。

**Comment by faithandbrave** [comment]
今のところ、cpprefjpもboostjpも大丈夫そうですね。セキュリティ警告が出力されることなく閲覧できて、サイト内のリンクもhttpsになっています。

**Comment by faithandbrave** [comment]
httpsに強制リダイレクトするよう設定しました。2〜3日様子を見て、問題なさそうであればこのIssueを終了します。

**Comment by faithandbrave** [comment]
問題なさそうなのでクローズします。
