### ISSUE TITLE
ISO IEC 60559 に準拠しているか確認する方法

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#380]
`<cmath>`の多くのページで以下の記述があります。

> 処理系が ISO IEC 60559 に準拠しているかどうかは、C99 の場合はマクロ `__STDC_IEC_559__` が `1` に定義されている事で判別可能であるが、C++ 規格書には該当する記載を見つけることができなかった。

C++では[`std::numeric_limits<FloatingPointType>::is_iec559` == true](https://cpprefjp.github.io/reference/limits/numeric_limits/is_iec559.html)で調べることができそうですが、どうでしょう。

`is_iec559`は、C++11の規格では以下のようになっています：

> `static constexpr bool is_iec559;`
> True if and only if the type adheres to IEC 559 standard.
> Meaningful for all floating point types.
> 全ての浮動小数点型について、IEC 559標準に準拠している場合にのみ`true`となる

具体的な実装として、libstdc++では`__STDC_IEC_559__`は使用されず、以下のように定義されます：

```cpp
static bool is_iec559 = has_infinity && has_quiet_NaN && has_denorm == denorm_present;
```

`has_infinity`や`has_quiet_NaN`などは、`<cfloat>`/`<float.h>`にはない処理系定義の組み込みマクロで実装されます。

**Comment by katsuster** [comment]
本筋と関係ないですが、参考までに。

libc++ の is_iec559 の実装を見ると、long double 以外は、型ごとに true/false を直値で定義していました。
なぜか long double だけは下記のようになっていて ppc, ppc64 は false でした。

```
#if (defined(__ppc__) || defined(__ppc64__))
    static _LIBCPP_CONSTEXPR const bool is_iec559 = false;
#else
    static _LIBCPP_CONSTEXPR const bool is_iec559 = true;
#endif
```

**Comment by faithandbrave** [comment]
@katsuster 参考情報の追加、ありがとうございます。

**Comment by faithandbrave** [comment]
@kariya-mitsuru さんのコミットで、`numeric_limits::is_iec559`をISO IEC 60559に準拠しているかの判定に使用しているところを見つけました。
https://github.com/cpprefjp/site/commit/8fcba4b87bc9fb23940096663606a108dc5827b1

ですので、このIssueについて @kariya-mitsuru さんからは事前に合意がとれているようでした。
とくに反対意見がなければ、これを `<cmath>` 全体に適用していきます。
特定の処理系の `numeric_limits::is_iec559` の実装に問題がある場合は、`is_iec559`のページの処理系備考に記載していただくことになると思います。
