### ISSUE TITLE
外部リンク先のページが消失している場合、リンク先をInternet Archiveのものに置き換えても良いか？

### ISSUE THREAD

**Issue by egtra** [cpprefjp/site#381]
外部のウェブページへのリンクの中には、その先の内容が無くなっている（404 Not Foundだったり、トップページへのリダイレクトだったりする）ものがあります。それらについて、[Internet Archive: Wayback Machine](https://archive.org/web/)で現存したときの状態が保存されているものがあります。

- [スレッドローカルストレージ](https://cpprefjp.github.io/lang/cpp11/thread_local_storage.html)
    - http://h30097.www3.hp.com/docs/base_doc/DOCUMENTATION/V51B_HTML/ARH9VDTE/THRDSCHP.HTM#anch_1024
        - → http://web.archive.org/web/20120817032847/http://h30097.www3.hp.com/docs/base_doc/DOCUMENTATION/V51B_HTML/ARH9VDTE/THRDSCHP.HTM#anch_1024
    - http://devrsrc1.external.hp.com/STKT/impacts/i320.html
        - → http://web.archive.org/web/20070212210310/http://devrsrc1.external.hp.com/STKT/impacts/i320.html
    - http://www.intel.com/software/products/compilers/clin/docs/ug_cpp/lin1057.htm
        - → http://web.archive.org/web/20090916083115/http://www.intel.com/software/products/compilers/clin/docs/ug_cpp/lin1057.htm
- [minstd_rand](https://cpprefjp.github.io/reference/random/minstd_rand.html)および[minstd_rand0](https://cpprefjp.github.io/reference/random/minstd_rand0.html)
    - http://www32.ocn.ne.jp/~yss/rand.html
        - → http://web.archive.org/web/20121114001645/http://www32.ocn.ne.jp/~yss/rand.html
- [scoped_allocator_adaptor](https://cpprefjp.github.io/reference/scoped_allocator/scoped_allocator_adaptor.html)
    - http://www32.ocn.ne.jp/~ons/text/CPP0xFAQ.html.ja#scoped-allocator
        - → http://web.archive.org/web/20150716062153/http://www32.ocn.ne.jp/~ons/text/CPP0xFAQ.html.ja#scoped-allocator
    - ただし、これは本家 http://www.stroustrup.com/C++11FAQ.html#scoped-allocator が現存しているので、これを併記としたい。

そこで、リンク先のURLを上記のようなInternet ArchiveのURLに変更したいと考えていますが、どうでしょうか？

なお、現時点で対象となる（リンク先が消失していることを私が認識していて、Internet Archiveに収録されている）リンクは、上記がすべてです。

**Comment by usagi** [comment]
なるほど、今後の事も考えると"理想"は「変換」時にリンク切れを検出して、リンク切れだった場合は記事の該当業の最終変更日時をgitから回収して、その日時に直近の過去のInternet Archivesの記事へのリンクにする、といった具合の事も考えられる。（もちろんそこそこ実装コストがかかるのであくまでも"理想"）

個人的な見解としては cpprefjp の設置目的を第一に考えると、少なくとも現時点でリンク切れあるいはおかしなリンク先に飛ぶなりリンク先の内容が変わってしまっている場合には気付いた時点で記事のソースを直接編集する事により該当のリンク先を Internet Archives から記事の当時の編集者が意図した内容を cpprefjp のユーザーが難しい事を気にすることなく参照可能とする事は、放置を含めた他の選択よりも better ではないか、と考えます。

要約：賛同 👍

**Comment by faithandbrave** [comment]
んー。多くの場合に置き換え可能な技術ページはあるでしょうから、アーカイブを持ってこなくてもよいように思います。
閉鎖したサイト、消失したページには作者の意図があるでしょうから、それを掘り起こすことはやめたほうがいいのではないでしょうか。

**Comment by egtra** [comment]
たしかに、置き換えが可能ならそれで代替すれば良いだろうという点は納得します。

すると残るは、スレッドローカルストレージの3ページです。ベンダーの技術情報で、代替となるページが見当たりませんでした。これについても、同じくアーカイブの使用は避けるほうがよいと考えていますでしょうか？

**Comment by faithandbrave** [comment]
スレッドローカルストレージのリンクは、WG21の提案文書から持ってきた歴史的経緯のページですね。
経緯としては「ベンダー独自の実装があった」ということだけわかれば十分とも考えられます。その場合は、単にリンク切れのページを削除してもよいように思います。
経緯としてきちんと残しておく目的があるのであれば、ベンダー独自の実装をこちらのページで解説するのもよいでしょう。
ベンダー独自の実装は、古くてもう使わなくなったものですが、標準化されたものと違ったアプローチを持つものもあるかもしれませんので、そのあたりは重要度によって異なる対応をすることが必要かもしれません。

**Comment by egtra** [comment]
はい、おっしゃるとおり、あの部分はベンダー独自の機能があったことを提示することが目的でしょう。そのため、アーカイブで示すことが必須ではないことに同意です。その方向性（ごく簡単な説明文で置き換える）で修正に取りかかろうと思います。

> ベンダー独自の実装は、古くてもう使わなくなったものですが、標準化されたものと違ったアプローチを持つものもあるかもしれませんので、そのあたりは重要度によって異なる対応をすることが必要かもしれません。
そうですね。将来、ものによっては改めて検討すべき場合が生じるかもしれません。ただ、スレッドローカルストレージにおいては、これに該当するとは考えられませんので、今回はその必要はなさそうと考えています。

論点はすべて解決しましたので、修正が完了したらクローズするつもりです。ありがとうございます。
