### ISSUE TITLE
Visual C++ 2017のバージョン番号を14.1とする

### ISSUE THREAD

**Issue by egtra** [cpprefjp/site#387]
[コンパイラの実装状況](https://cpprefjp.github.io/implementation-status.html)で、Visual C++ 2017で実装されたものについて、現在、MSVC 15.0と表記されています。しかし、以下のように、実際には15.0ではないので修正するつもりです。

- インストール先ディレクトリ14.10.24728となっている。`cl.exe`の製品バージョン番号は`14.10.24728.0`となっている。ともにVisual Studio 2017 RC。
- IDE上では、プラットフォーム ツールセットv141と表記されている。

14.1と変更したいと思います。

**Comment by faithandbrave** [comment]
よろしくお願いします。
