### ISSUE TITLE
C++14 変換関数の型推論

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#389]
@kariya-mitsuru さんが[`auto`](https://cpprefjp.github.io/lang/cpp11/auto.html)の解説ページに記載したnolinkの「C++14 変換関数の型推論」ですが、これは提案文書もしくはIssueとしてはどれに当たるでしょうか。
私の方では見つけられませんでした。
質問の回答が得られたら、このIssueをタスクに変更しようと思います。

**Comment by kariya-mitsuru** [comment]
どうも、通常関数の戻り値型推論で一緒に入ってるようです。
ちょっと書き方を変えた方がいいかもしれませんね…

**Comment by faithandbrave** [comment]
もしかして、これのことでしょうか？

- [後置戻り値型をプレースホルダーにすることを許可](https://cpprefjp.github.io/lang/cpp14/placeholder_type_in_trailing_return_type.html)

**Comment by kariya-mitsuru** [comment]
いえ、[通常関数の戻り値型推論](https://cpprefjp.github.io/lang/cpp14/return_type_deduction_for_normal_functions.html)の方です。
規格書の §7.1.6.4[dcl.spec.auto] で placeholder type が使える場所が規定されていますが、[N3638 Return type deduction for normal functions](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3638.html) の Proposed wording でその中に *conversion-function-id* がしれっと追加されています。
ユーザ定義変換関数は通常関数とは言わないと思いますし、文法的にも *conversion-function-id* は戻り値型ではない（*declarator-id* なのでどちらかと言えば関数名の扱い）ので分けて書いたのですが、見た感じ特に個別の議論なく通常関数の戻り値型推論と区別なく追加されたようなので、参照する側で「通常関数の戻り値型推論（ユーザ定義変換関数の型推論を含む）」などと直そうかな、と思っていますがいかがでしょうか。

**Comment by faithandbrave** [comment]
なるほど、了解しました。では対応は、 @kariya-mitsuru さんにお願いしますね。

**Comment by faithandbrave** [comment]
https://github.com/cpprefjp/site/commit/987fc81983e0cda6f9c3af457c806b8de159ff81
