### ISSUE TITLE
グローバル修飾リストの構造を決める

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#391]
@e-kwsm さんが以下のコミットで、GLOBAL_QUALIFY_LIST.txtの構造を変更しています。

https://github.com/cpprefjp/site/commit/b30ffc88bbc5c207bb6516e9ef059acd4d4f9155

これは元々の構造を作った私の意図とは異なるため、[CONTRIBUTING.md](https://github.com/cpprefjp/site/blob/master/CONTRIBUTING.md)にある「ほかの人が書いたコンテンツの編集方法」ルールに従って、どのような構造にすべきかを議論する必要があります。

まず、私が作った構造では、ヘッダファイルがまず並べられて、各ヘッダファイルに紐づく形で機能の修飾リストが並ぶようにしてありました。

```
* <deque>[link /reference/deque.md]
* std::deque[link /reference/deque.md]
* <forward_list>[link /reference/forward_list.md]
* std::forward_list[link /reference/forward_list.md]
* <list>[link /reference/list.md]
* std::list[link /reference/list.md]
* <queue>[link /reference/queue.md]
* <stack>[link /reference/stack.md]
* <vector>[link /reference/vector.md]
* std::vector[link /reference/vector.md]
* v.begin()[link /reference/vector/begin.md]
* v.end()[link /reference/vector/end.md]
* v.size()[link /reference/vector/size.md]
```

https://github.com/cpprefjp/site/blob/a78dd47d90673a22b0af26def2f0a80bb1fcbda6/GLOBAL_QUALIFY_LIST.txt

@e-kwsm さんが変更した構造では、全てがアルファベット順に並びます。

```
* <deque>[link /reference/deque.md]
* <exception>[link /reference/exception.md]
* <forward_list>[link /reference/forward_list.md]
...

* std::accumulate[link /reference/numeric/accumulate.md]
* std::allocator[link /reference/memory/allocator.md]
* std::array[link /reference/array.md]
* std::atomic[link /reference/atomic/atomic.md]
* std::back_inserter[link /reference/iterator/back_inserter.md]
* std::basic_string[link /reference/string/basic_string.md]
* std::begin[link /reference/iterator/begin.md]
* std::bitset[link /reference/bitset.md]
* std::boolalpha[link /reference/ios/boolalpha.md]
```

https://github.com/cpprefjp/site/blob/b30ffc88bbc5c207bb6516e9ef059acd4d4f9155/GLOBAL_QUALIFY_LIST.txt

この構造に従う場合、作業フローを整備して「コミットする際は必ずソートをかけること」というルールを設ける必要があるでしょう。その場合、Linux/macOS環境では`sort GLOBAL_QUALIFY_LIST.txt`コマンド、Windowsでも同様のコマンドで処理できそうです。

このIssueでは、GLOBAL_QUALIFY_LIST.txtの当面の構造を決め、新たに改定が必要である場合には新しいIssueを立てることにしましょう。

MarkdownからHTMLへのコンバーターの処理効率はとくに気にする必要はないと思いますので、管理のしやすさという点でご意見をいただければと思います。

2つの対立する案が出ているため、意見がなければいずれかに決定する、ということは今回はできそうにありません。合意が得られるよう、当事者を含め意見をいただければと思います。

**Comment by faithandbrave** [comment]
私の意見としては、入力するだけならアルファベット順の方がしやすいと思いますが、管理のしやすさという点では、私が作った元々の構造の方がやりやすいと考えています。以下のような機能は管理がしやすい代表例ですが、

```
* <memory>[link /reference/memory.md]
* std::allocator[link /reference/memory/allocator.md]
* std::shared_ptr[link /reference/memory/shared_ptr.md]
* std::unique_ptr[link /reference/memory/unique_ptr.md]

...

* <string>[link /reference/string.md]
* std::string[link /reference/string/basic_string.md]
* std::wstring[link /reference/string/basic_string.md]
* std::u16string[link /reference/string/basic_string.md]
* std::u32string[link /reference/string/basic_string.md]
* std::basic_string[link /reference/string/basic_string.md]

...

* <iterator>[link /reference/iterator.md]
* std::distance[link /reference/iterator/distance.md]
* std::begin[link /reference/iterator/begin.md]
* std::end[link /reference/iterator/end.md]
* std::ostream_iterator[link /reference/iterator/ostream_iterator.md]
* std::back_inserter[link /reference/iterator/back_inserter.md]

...

* <algorithm>[link /reference/algorithm.md]
* std::for_each[link /reference/algorithm/for_each.md]
* std::copy[link /reference/algorithm/copy.md]
* std::sort[link /reference/algorithm/sort.md]
```

これらはアルファベット順にしてしまうと、「サイト内で、このヘッダの機能としてこれらの機能はよく使用する」というものの一覧を取得するために、grepする必要が出てきます。「登録したい識別子がすでに登録されていないか調べるために検索する」という使い方ならアルファベット順でもよいのでしょうけど、今のところ32ヘッダ分のコード修飾を付けた私の作業経験としては、それだとやりにくいですね。
というのも、サンプルコードでインクルードを見つけた時点で、グローバル修飾リストのそのヘッダファイルを参照すれば、どれがグローバル修飾に登録されていてどれが登録されていないかがわかるため、ヘッダファイル以外を検索することなく「この機能はページごとに修飾すればいい」ということがわかるからです。これがアルファベット順だと、サンプルコード中で使用されている全ての識別子を、グローバル修飾リストのなかから個別に検索する必要があります。それは作業者の私としては大きな手間であると考えます。

**Comment by melpon** [comment]
ほぼ編集しない自分が言うのもなんですが、アルファベット順でいいと思います。
というのも、「ヘッダファイルに紐づく形で機能の修飾リストを並べる」ぐらいだと「ヘッダファイルの並び順」「各修飾の並び順」「複数のヘッダに跨って使いたい名前（あるのか知らない）」「ヘッダに紐付いていない名前（あるのか知らない）」とか、結構決める必要のあるルールが出てきて、決めるのも覚えるのも面倒だし、どこに入れるのが適切か分からない名前が出てきた時にそれを議論するのも面倒だからです。

もし自分が追加するとしたら、追加したい名前で検索して重複が無いことを調べてから適当に追加すると思います。
その際に、追加する位置として適切な場所がどこかを考える必要があるというのは面倒だなぁと思います。

> まず、私が作った構造では、ヘッダファイルがまず並べられて、各ヘッダファイルに紐づく形で機能の修飾リストが並ぶようにしてありました。

多分この（暗黙の）ルールに @e-kwsm さんは気が付いていなくて（自分も気が付かなかった）「変な並びだな。ソートしておこう」になったんだと思います。

ただ、自分はほぼ編集してないので、意見としての重みは大分低くていいです。やってる人優先で。

**Comment by faithandbrave** [comment]
> 「複数のヘッダに跨って使いたい名前（あるのか知らない）」

リンクとしてはないです。色、太字、斜体ならありえますが、いまのところはそれもないです。

> 「ヘッダに紐付いていない名前（あるのか知らない）」

implementation-definedがそうですね。これは一番上に置いてありました。

**Comment by faithandbrave** [comment]
補足情報ですが、グローバル修飾リストはちょくちょく編集するものではなく、サイト内で頻出するものを洗い出してしまったら、C++の言語バージョンが上がらない限りは安定状態になるものであると考えています。

いま私がやっている作業は、サイト内の全てのページにコード修飾を付加するというものです。それが終わってしまえば、頻出する識別子の洗い出しは完了します。また、それによってページ追加やサンプルコードの追加・修正をする際に、既存のどのページを参考にすることもできるようになります。

**Comment by faithandbrave** [comment]
それと、論点として「グローバル修飾リストの管理のしやすさ」を挙げていましたが、「実際にそれを使って編集作業をする際の参照のしやすさ」も必要でした。
アルファベット順の場合は、どうすれば使いやすいかを提案していただけると助かります。私が挙げた以下のユースケースに対して、アルファベット順でどうすれば使いやすいかを教えていただきたいです。

> というのも、サンプルコードでインクルードを見つけた時点で、グローバル修飾リストのそのヘッダファイルを参照すれば、どれがグローバル修飾に登録されていてどれが登録されていないかがわかるため、ヘッダファイル以外を検索することなく「この機能はページごとに修飾すればいい」ということがわかるからです。これがアルファベット順だと、サンプルコード中で使用されている全ての識別子を、グローバル修飾リストのなかから個別に検索する必要があります。それは作業者の私としては大きな手間であると考えます。

先に述べたように、グローバル修飾リストは安定状態になる予定ですので、それを編集するよりも参照する方が頻度が高くなります。

**Comment by usagi** [comment]
単純に行を文字列としてソートされた https://github.com/cpprefjp/site/blob/b30ffc88bbc5c207bb6516e9ef059acd4d4f9155/GLOBAL_QUALIFY_LIST.txt （ @e-kwsm 新方式 ）は一見するとソース上もリストの整理としても美しく見える可能性があるが、このリストの本質は https://github.com/cpprefjp/site/blob/a78dd47d90673a22b0af26def2f0a80bb1fcbda6/GLOBAL_QUALIFY_LIST.txt （ @faithandbrave 旧方式 ）の様に単純な行の文字列ではなくリストとしてのデータ構造が本質であって、つまり旧方式の様にリンク先について文字列上もリストの意味論としての認識上もソートされいる方がより適切で美しく、また保守コストについても悪いという事は無いと思います。

要約: @faithandbrave 旧方式に賛同。

**Comment by melpon** [comment]
> アルファベット順の場合は、どうすれば使いやすいかを提案していただけると助かります。私が挙げた以下のユースケースに対して、アルファベット順でどうすれば使いやすいかを教えていただきたいです。

どのような並びになっていても、自分は個別に検索して既存の名前があるかどうか調べると思います。
今の（暗黙の）ルールを覚えるコストと、毎回検索するコストは、そんなにヘビーに参照してない自分にとっては後者のほうが楽だからです。
なので、使いやすさに関してはどちらも同じで、管理する手間が省ける分アルファベットの方がいい、という感じです。

**Comment by melpon** [comment]
ある程度編集するなら、`GLOBAL_QUALIFY_LIST.txt` を読み込んでそれらを全部ハイライトするような仕組みを用意するかも。
どれぐらいコストの掛かる話なのか、やってない自分はよく分からないので、まあヘビーに編集してる @faithandbrave のやりたいような形でいいと思います。

**Comment by faithandbrave** [comment]
> ある程度編集するなら、GLOBAL_QUALIFY_LIST.txt を読み込んでそれらを全部ハイライトするような仕組みを用意するかも。

ちょっとうまく解釈できなかったのですが、専用ビューアを作るという話ですか？

私は実際にコード修飾の作業をしている一人ですが、新たな編集者が使いにくいと参加のハードルになってしまうので、まだ取り掛かっていない人にとって使いにくそうと感じるのであれば、それも重要な意見だと思います。

たとえば、私の構造が説明なしに使うにはわかりにくいのであれば、`GLOBAL_QUALIFY_LIST.txt`の最初の一行をコメント扱いにして、そこに構造の説明を書くこともできるでしょう。

構造がわかっていれば使いやすいかどうか、作業していない現時点で判断しにくそうであれば、まだ作業していない30ヘッダが残っていますので、そのうち数ページで実際に作業してみるのもよいと思います。私の作業はアルファベット順にやっています(ファイルシステムの並び)ので、残りは以下です：

```
<list>
<locale>
<map>
<memory>
<mutex>
<new>
<numeric>
<ostream>
<queue>
<random>
<ratio>
<regex>
<scoped_allocator>
<set>
<shared_mutex>
<sstream>
<stack>
<streambuf>
<string>
<system_error>
<thread>
<tuple>
<type_traits>
<typeindex>
<typeinfo>
<unordered_map>
<unordered_set>
<utility>
<valarray>
<vector>
```

**Comment by faithandbrave** [comment]
@melpon が「今の (暗黙の) ルール」と言ってるので、まだ明確にしていなかったルールを書いておきます。

- ヘッダの順番は reference.md の並び。なのでたとえばコンテナ関係が一箇所に集まっている
- ヘッダ内の並びは現在はてきとうで、関連するものを集めている。これをアルファベット順にしていないのは、`<iterator>`で`std::begin()`の次に`std::end()`ではなく`std::distance()`が出てきたら気持ち悪いため
- ヘッダに含まれない機能はリストの先頭。これは今のところ一つしかないので、並び順はない

**Comment by e-kwsm** [comment]
ソートしたのは見やすさのためもありますが，何かを追加するときにすぐ分かるかとおもったからです．ヘッダが雑然と並んでいる現状では分かりにくいです．
ヘッダ名やヘッダ下の要素はソートした方がいいと思います．

リスト構造を明示するなら以下はどうでしょうか
1. 異なるヘッダ間に空行を入れる
```
...
* <iterator>[link /reference/iterator.md]
* std::distance[link /reference/iterator/distance.md]
...

* <memory>[link /reference/memory.md]
* std::allocator[link /reference/memory/allocator.md]
...

* <string>[link /reference/string.md]
* std::string[link /reference/string/basic_string.md]
...
```

2. ヘッダの下の要素をインデントする
```
...
* <iterator>[link /reference/iterator.md]
    * std::distance[link /reference/iterator/distance.md]
...
* <memory>[link /reference/memory.md]
    * std::allocator[link /reference/memory/allocator.md]
...
* <string>[link /reference/string.md]
    * std::string[link /reference/string/basic_string.md]
...
```

問題がなければですが．

**Comment by e-kwsm** [comment]
すいません間違えてクローズしました

**Comment by faithandbrave** [comment]
@e-kwsm さんの新しい1. と2. の案は、私としてはどちらも私の意図を反映しているので使いやすいと思います。構造を付けた上でヘッダとヘッダ内の機能をソートすることは、私が今のところ妥協できる範囲です。
コンバーターに修正を加えることになりますが、空行を読み飛ばすか、先頭の空白を除去(trim left)するかだけなので、実装コストは大したことはないでしょう。

**Comment by faithandbrave** [comment]
@melpon の要件を満たすには、ルールが説明することなく理解できる必要がありそうですが、 @e-kwsm さんの新しい案は受け入れられるものでしょうか？

**Comment by melpon** [comment]
> ちょっとうまく解釈できなかったのですが、専用ビューアを作るという話ですか？

いえ、単純に Vim に `/std::accumulate\|std::allocator\|...` のようなでかい検索文字列を渡して、それらがハイライトされてない部分だけどうするか考える、というのをイメージしてました。
でかい検索文字列でちゃんと動作するのか微妙なところですが…。

> @melpon の要件を満たすには、ルールが説明することなく理解できる必要がありそうですが、 @e-kwsm さんの新しい案は受け入れられるものでしょうか？

自分はどんなルールでも問題ないです。
メリットがそこまで無いならよりシンプルな方がいいよね、程度のモチベーションで発言していて、より深く関わってる人がメリットを多く感じているなら、そちらに合わせたほうが良いと思っています。

**Comment by faithandbrave** [comment]
では、週末しかここを見ない人のことを考慮して、2017/02/12(日)中くらいまで意見を募集します。
今のところは、 @e-kwsm さんの新しい提案の1. か2. で考えます。どちらがよいかはツールの作りやすさを調べて決めることにしましょう。

方針によってはコード修飾の作業が一からやり直しになることも考えられるため、私の作業は一旦止めます。

**Comment by faithandbrave** [comment]
新しい構造の1. と2. の案ですが、「2. ヘッダの下の要素をインデントする」の方が良さそうだと思いました。当面の問題を解決するだけならどちらでもよいのですが、今後どの機能がどのヘッダに属しているかの情報をなんらかの用途に使用することを考えた場合に、2. の方が扱いやすいです。
1. の方の問題点は、ヘッダに属さない機能を列挙する際や、属する機能がとくにないヘッダが並ぶときに、やはり不要に思える空行が発生することなどがあります。

あとは、Linux/macOSのsortコマンドで、トップリストだけ、サブリストだけをソートできればよいのですが・・・。cpprefjpの編集者向けツールとしてPythonやRubyを推奨してよいのであればそれを使ってもよいのですが、どうするのがよいでしょうね。

**Comment by e-kwsm** [comment]
ソートしましょうか？
一旦ソートしてしまえば追加するときに気を付ければよいかと．

**Comment by faithandbrave** [comment]
では、結論が出たあとのソートは @e-kwsm さんにお願いします。
ソートツールを用意すべきかと思いましたが、気をつけるくらいでよければルール整備だけにしておきましょうか。

**Comment by e-kwsm** [comment]
今後 `constexpr` や `static_assert` といったキーワードをリストに追加する (例えば `* static_assert [link /lang/cpp11/static_assert.md]`) ことはあり得ますか？
もしそうならその扱いについても決めておいた方が良いかと思います．

**Comment by faithandbrave** [comment]
いまのところcpprefjpでの言語解説はバージョン間の差分であるため、微妙なところです。

`long long`は今後仕様が変わる可能性が低いために積極的にリンクを貼っていましたが、`constexpr`や`static_assert`はC++11で入ってその後さらなる機能拡張が入っているため、C++11のページにリンクを貼ることが適切かどうか悩ましいです。参照リンクで機能拡張は辿れるようにはしてあるため、C++11の`constexpr`ページにリンクを貼れば、C++14での変更点ページを参照しやすくはなっているのですけどね・・・。

**Comment by faithandbrave** [comment]
ほかに意見がなさそうでしたので、 @e-kwsm さんの 2. 案を結論にしたいと思います。
site_generatorをインデントに対応するよう修正し、その変更がサーバーに反映されたら #392 のPull Requestをマージして、本Issueをクローズします。

**Comment by faithandbrave** [comment]
site_generator側の対応が完了しました。今夜のデイリー変換でサーバーに適用されるはずです。明日、Pull Requestをマージします。(いまマージするとコンバーターが動かなくなる)

**Comment by faithandbrave** [comment]
マージしました。

言語機能へのリンクについては、私は現在良いアイディアを持っていない状態です。そのため、なにか良い考えが思いついたら別途Issueを立てて提案していただけると助かります。
