### ISSUE TITLE
サイト内のtypedefをusingに置き換えてもよいか

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#394]
C++17の規格書から、typedefによる型の別名が、usingを使用するよう修正されます。修正が行われたのは以下の段階です：

- [N4603 Editor's Report -- Committee Draft, Standard for Programming Language C++](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/n4603.html)
> commit c8f1863b67ce555c7576faddb50bd8707bfe0bee
> Author: Alisdair Meredith <public@alisdairm.net>
> Date:   Wed Jun 8 01:35:02 2016 -0400
> 
>     [18-30] Replace typedefs with alias-declarations (#704)
> 
>     This set of changes replace (almost) all use of 'typedef' in the library
>         with a type alias instead:
>             typedef Original NewName;
>          ->
>             using NewName = Original;
> 
>         Attention was paid to retaining table-like formatting where present, which
>         is worth reviewing in case I made idiosyncratic choices.
> 
>         Clause 29 [atomic] was specifically ignored, as there is a desire for the
>         contained code to look as close to a C compatible header as possible.

cpprefjpサイト内では、C++11から入った機能かどうかに関わらず、規格書の宣言を記載しているのがほとんどです。C++11から入った機能でもtypedefを使用していたりusingを使用していたりします。
C++17からのこの変更にともない、cpprefjp内の方針を決めておく必要があるかと思います。考えられる選択肢としては、以下のようになると思います：

1. サイト内の全ての型の別名を、usingに置き換える (気づいたところを随時対応)
2. typedefを任意にusingに置き換えることを許可する (1. と違うのは、サイト内の方針としてusingを使うか、編集者の裁量に任せるか)
3. C++11以降に入った機能のみusingを使用する。ただし、C++98/03からあった機能がC++11で修正されたものもあるため、判断が難しい。たとえばメンバ型の追加など

私の意見としては、C++11が策定されてから5年が経過しており、コンパイラのデフォルトC++バージョンもC++14になっていたりするので、時間経過によるC++11認知度の向上が期待できること、認知度の向上を促すことを理由として、 1. の方針を推します。
C++03までしか知らない人でも、C++03での標準ライブラリの型の別名を知っていれば、usingの意味はすぐに理解できるのではないかと思います。例として、`typedef basic_string<char> string;`を知っていれば`using string = basic_string<char>;`の意味は推測できると思います。

**Comment by usagi** [comment]
案1に賛同。

**Comment by yumetodo** [comment]
同じく案1に賛同。しかし

>気づいたところを随時対応

というのは機械的なツール(textlint的な何か)での検出と置換は行わないということでしょうか？

**Comment by faithandbrave** [comment]
あぁ、すいません。ちゃんと調べてなかったので難しいところがあるかと思い、随時対応と書きましたが、ざっと検索したところ、`memory_order`の定義以外は、正規表現で一発置換できそうです。
(言語機能の解説は対象外で、ライブラリ側だけが対象になるはずです。)

`memory_order`はCに合わせた定義になっていましたが、C++17ではC++的な定義に変わります。

```cpp
// before
namespace std {
  typedef enum memory_order {
    memory_order_relaxed, memory_order_consume, memory_order_acquire,
    memory_order_release, memory_order_acq_rel, memory_order_seq_cst
  } memory_order;
}
```

```cpp
// after
namespace std {
  enum memory_order {
    memory_order_relaxed, memory_order_consume, memory_order_acquire,
    memory_order_release, memory_order_acq_rel, memory_order_seq_cst
  };
}
```

**Comment by k44** [comment]
clang-tidy の modernize-use-using を使えば出来そうな気がします。
http://clang.llvm.org/extra/clang-tidy/checks/modernize-use-using.html

**Comment by faithandbrave** [comment]
目的が達成できるなら手段はなんでもかまいませんよ。作業自体も引き取っていただける方がいたらお願いします。

**Comment by e-kwsm** [comment]
案1に賛成です．sed だとこうでしょうか．
`sed -i 's/typedef\s\+\(.\+\)\s\+\(\S\+\);/using \2 = \1;/' hoge.md`

**Comment by e-kwsm** [comment]
一部うまくいきませんでしたが手動で直せると思います．

**Comment by e-kwsm** [comment]
コードの修正については（多分）できました．

本文の説明についてはどうしますか？たとえば [map::value_compare](https://cpprefjp.github.io/reference/map/map/value_compare.html) の
> `result_type`	関数オブジェクトとしての戻り型。`bool` の typedef

で「typedef」を「型エイリアス」に直しますか？

**Comment by faithandbrave** [comment]
その修正で問題ないと思います。

**Comment by faithandbrave** [comment]
反対意見もなさそうですし、 @e-kwsm さんからのPull Requestも来たので、案1を結論としましょう。大きな問題があればreopenしていただき、最悪revertするということでお願いします。
