### ISSUE TITLE
[C++17][言語機能] インライン変数

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#404]
インライン変数の言語機能解説を作成してください。

- [C++1z インライン変数](http://faithandbrave.hateblo.jp/entry/2016/11/11/172954)
- [P0607R0 inline variables for the standard library](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0607r0.html)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
初版をコミットしましたので、クローズします。
