### ISSUE TITLE
[C++17][言語機能] 単一要素の波カッコ初期化をTに推論する

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#406]
C++17での仕様変更「単一要素の波カッコ初期化をTに推論する」について、解説を作成してください。

- [C++1z 単一要素の波カッコ初期化をTに推論する](http://faithandbrave.hateblo.jp/entry/2016/11/16/154357)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by yumetodo** [comment]
@e-kwsm

```cpp
int main()
{
  // リストによるコピー初期化の型推論はこれまで通り
  [[gnu::unused]] auto assign_brace_single = {0};      // std::initilizer_list<int>
  [[gnu::unused]] auto assign_brace_multi  = {0, 1};   // std::initilizer_list<int>
  // auto assign_brace_bad = {0, 1.0}; // 不適格: int と double からは推論できない

  // リストによる直接初期化の型推論の規則が変更された
  [[gnu::unused]] auto brace_init_single{0};           // C++17 までは std::initilizer_list<int>, C++17 からは int
  // auto brace_init_multi{0, 1};      // C++17 までは std::initilizer_list<int>, C++17 からは 不適格
}
```

をコンパイルすると

https://wandbox.org/permlink/KFUQYFTEVV3B7TJf

```
prog.cc: In function 'int main()':
prog.cc:4:48: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
   [[gnu::unused]] auto assign_brace_single = {0};      // std::initilizer_list<int>
                                                ^
prog.cc:5:51: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
   [[gnu::unused]] auto assign_brace_multi  = {0, 1};   // std::initilizer_list<int>
```

となる。

つまり

```cpp
#include <initializer_list>
```

が必要だと考える。

(あと、 `std::initilizer_list` じゃなくて `std::initializer_list` ですよね・・・？)

というわけで、修正しました

**Comment by e-kwsm** [comment]
> つまり
> ```cpp
> #include <initializer_list>
> ```
> が必要だと考える。

https://wandbox.org/permlink/KFUQYFTEVV3B7TJf だと確かにコンパイルが通らないのですが，元々の例はちゃんと通る (`iostream` が読んでる？) ので別にインクルードしなくても問題ないと思います．

> (あと、 `std::initilizer_list` じゃなくて `std::initializer_list` ですよね・・・？)

タイポでした．ありがあとうございます．
