### ISSUE TITLE
[C++17][言語機能] [[nodiscard]]属性

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#408]
`[[nodiscard]]`属性の言語機能解説を作成してください。

- [戻り値を捨ててはならないことを指定する`[[nodiscard]]`属性](http://faithandbrave.hateblo.jp/entry/2016/10/11/164434)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
fallthrough, unusedと一緒にこちらも作ります。

**Comment by katsuster** [comment]
一通り書きましたのでcloseします。
