### ISSUE TITLE
[C++17][言語機能] 参照メンバをもつクラスの置き換え

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#411]
「参照メンバをもつクラスの置き換え」の言語機能解説を作成してください。

- [P0137R1 Core Issue 1776: Replacement of class objects containing reference members](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0137r1.html)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by alphya** [comment]
やっておきました！よろしければレビューをお願いします！

**Comment by faithandbrave** [comment]
@alphya さん、対応ありがとうございました！
細かいところは私の方で修正しておきます。

**Comment by alphya** [comment]
@faithandbrave さん、ありがとうございます！！
