### ISSUE TITLE
[C++17][言語機能] if文とswitch文の条件式と初期化を分離

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#413]
「if文とswitch文の条件式と初期化を分離」の解説を作成してください。

- [C++1z if文とswitch文の条件式と初期化を分離](http://faithandbrave.hateblo.jp/entry/2016/11/15/160217)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
初版書きましたのでクローズします。
