### ISSUE TITLE
[C++17][言語機能] [[fallthrough]]属性

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#414]
`[[fallthrough]]`属性の言語機能解説を作成してください。

- [C++1z フォールスルー時の警告を抑制する`[[fallthrough]]`属性](http://faithandbrave.hateblo.jp/entry/2016/10/06/182914)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
一通り書きましたのでcloseします。
