### ISSUE TITLE
[C++17][言語機能] if constexpr文

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#415]
`if constexpr`文の言語機能解説を作成してください。

- [C++1z if constexpr文](http://faithandbrave.hateblo.jp/entry/2016/12/22/171238)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

- [x] 概要
- [ ] この機能が必要になった背景・経緯
- [ ] 検討されたほかの選択肢

**Comment by yumetodo** [comment]
if constexprを使うとき、特定条件時にコンパイルを失敗させる - Qiita
http://qiita.com/saka1_p/items/e8c4dfdbfa88449190c5

static_assertと組み合わせることは需要がありそうなので例に追加する予定

**Comment by faithandbrave** [comment]
@yumetodo このタスクは完了していますか？

**Comment by yumetodo** [comment]
@faithandbrave ごめんなさい、まだです・・・
規格化の経緯を書こうと思って手を付けていません・・・。

**Comment by yumetodo** [comment]
@faithandbrave ずいぶん放置してしまっているこのissueですが、当分規格化の経緯を執筆できそうにありません。
一度assignを外れておきたいと思うのですが

**Comment by faithandbrave** [comment]
はい、わかりました。余裕ができたら引き取ります。

**Comment by akinomyoga** [comment]
Twitter 上で @yumetodo さんと少し[議論](https://twitter.com/yumetodo/status/1147099050774151169)がありましたので関連する提案へのリンクをここにまとめます。実際に記事を書くかは決め兼ねています。

- [[PDF] N3322: A Preliminary Proposal for a Static if](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3322.pdf)
- [[PDF] N3329: Proposal: static if declaration](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3329.pdf)
- [[PDF] N3576: SG8 Concepts Teleconference Minutes – 2013-03-12](https://isocpp.org/files/papers/N3576.pdf) §2.1
- [[PDF] N3613: “Static If ” Considered](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3613.pdf)
- [N4461: Static if resurrected](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4461.html)
- [P0128R0: constexpr_if](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0128r0.html)
- [P0128R1: constexpr if](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0128r1.html)
- [P0292R0: constexpr if: A slightly different syntax](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0292r0.html)
- [P0292R1: constexpr if: A slightly different syntax](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0292r1.html)
- [P0292R2: constexpr if: A slightly different syntax](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0292r2.html)
