### ISSUE TITLE
[C++17][言語機能] 畳み込み式

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#418]
畳み込み式 (Fold expressions)の言語機能解説を作成してください。

- [C++1z 畳み込み式](http://faithandbrave.hateblo.jp/entry/2016/12/07/185947)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by e-kwsm** [comment]
テーブルの中で `|`, `||` を使いたいのですがどうしたらいいですか？
`<table></table>` をべた書きしても手元で変換して見た感じダメでした（そもそも筋が悪いかと）．

**Comment by faithandbrave** [comment]
`std::atomic`クラスのところでやってますが、文字参照を使用します。
https://raw.githubusercontent.com/cpprefjp/site/master/reference/atomic/atomic.md

```
| <code>[operator&#x7C;=](atomic/op_or_assign.md)</code> | OR演算 |
```

**Comment by e-kwsm** [comment]
正しく反映されました．ありがとうございます．
