### ISSUE TITLE
[C++17][言語機能] クラステンプレートのテンプレート引数推論

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#420]
「クラステンプレートのテンプレート引数推論」の言語機能解説を作成してください。
この機能への標準ライブラリ側対応により、推論補助式のページをどのように書くか検討する必要があります。`op_deduction_guide.md`を用意すればよさそう。

- [C++1z クラステンプレートのテンプレート引数推論](http://faithandbrave.hateblo.jp/entry/2016/10/24/173323)
- [P0433R2 Integrating template deduction for class templates into the standard library](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0433r2.html)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by yumetodo** [comment]
実引数推定の言語機能は
P0091R3: [Template argument deduction for class templates (Rev. 6)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0091r3.html)
によるもので、P0433はそれによる標準ライブラリへの影響調査と改善ですよね・・・？

**Comment by yumetodo** [comment]
>Using make functions with classes that aren't movable like std::lock_guard requires appealing to highly abstruse language features like copy elision for prvalues (P0135R0), contributing to the perception that C++' conceptual model is beyond ordinary mortals.

っていうけど、結局RVOを義務化する方向になったし、この言語仕様の要求理由としてはいらなくなった感が・・・他に上げている理由はともかく

**Comment by faithandbrave** [comment]
このタスクで具体的に何を作業すればよいかの確認でしょうか？ライブラリ機能への対応がこのタスクに含まれるかという質問であれば、含みません。P0091の内容のみです。
ただし、言語機能の解説ページで、標準ライブラリの対応への言及は必要になるかもしれません。

**Comment by faithandbrave** [comment]
完了。

**Comment by faithandbrave** [comment]
- [P0702R1 Language support for Constructor Template Argument Deduction](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0702r1.html)

2017年6月のToronto会議で採択された提案文書ですが、これはC++17の欠陥としてC++17に入ってるようです。GCC 8.1 (daily) のC++1zモードでも動作しました。

**Comment by faithandbrave** [comment]
```cpp
#include <vector>
#include <type_traits>

int main()
{
    std::vector v{std::vector{1, 2, 3}};
    static_assert(std::is_same_v<
        decltype(v),
        std::vector<int>
    >);
}
```
