### ISSUE TITLE
[C++17][言語機能] 非型テンプレートパラメータのauto宣言

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#421]
「非型テンプレートパラメータのauto宣言」の言語機能解説を作成してください。

- [C++1z 非型テンプレートパラメータの`auto`宣言](http://faithandbrave.hateblo.jp/entry/2016/10/26/180406)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by faithandbrave** [comment]
予定が立ってないので、一旦担当を手放します。

**Comment by alphya** [comment]
初版をコミットしたので、クローズしておきます！
