### ISSUE TITLE
[C++17][言語機能] 全ての非型テンプレート引数の定数式評価を許可

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#422]
「全ての非型テンプレート引数の定数式評価を許可」の解説を作成してください。

- [C++1z 全ての非型テンプレート引数の定数式評価を許可](http://faithandbrave.hateblo.jp/entry/2016/10/27/180801)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by alphya** [comment]
初版を追加しました！ご確認お願いいたします！
