### ISSUE TITLE
[C++17][言語機能] using宣言のパック展開

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#423]
「using宣言のパック展開」の解説を作成してください。

- [C++1z using宣言のパック展開](http://faithandbrave.hateblo.jp/entry/2017/02/01/153354)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
遅くなってごめんなさいですが、初版をコミットしたのでクローズします。

**Comment by faithandbrave** [comment]
ありがとうございます！すごく助かってます！ (最近バタバタしていて、私もなかなか作業できていないです…)
