### ISSUE TITLE
[C++17][言語機能] static_assertのメッセージ省略を許可

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#424]
「static_assertのメッセージ省略を許可」の解説を作成してください。

- [C++17 `static_assert`のメッセージ省略を許可](http://faithandbrave.hateblo.jp/entry/2016/04/22/163123)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by e-kwsm** [comment]
すいません，amend して push -f したら更新が反映されなくなってしまいました．

**Comment by faithandbrave** [comment]
あ、MarkdownからHTMLへの変換サーバーは、masterブランチへのpushを検知してpullしていますので、masterブランチに対してpush -fはしないようお願いします。変換サーバーがpullに失敗するようになります。

**Comment by yumetodo** [comment]
@faithandbrave それ
https://github.com/cpprefjp/site/blob/master/CONTRIBUTING.md
あたりに書いておいて方がいいような・・・、もしくはbranchをprotect

**Comment by faithandbrave** [comment]
んー、masterブランチにpush -fしてはいけないのは、Gitの一般的な作法だと考えていて、そのようなものはなるべく外の文献にお任せしたいところです。
ひとまず、サーバー管理をお願いしている @melpon に復旧依頼をしておきました。

**Comment by yumetodo** [comment]
というより複数人開発のGithubの使い方の前提として大事なbranchはOwner以外force pushできないようにprotectしておくものだと思っていたので、むしろforce pushできたことに驚きです・・・
むしろ今まで
https://cpplover.blogspot.jp/2013/11/jenkinsgit-push-force.html
みたいな事件が起きなくてよかった・・・

**Comment by faithandbrave** [comment]
ひとまず、以下のリポジトリのmasterブランチは、push -fできないようにしておきました。

- cpprefjp/site
- cpprefjp/image
- boostjp/site
- boostjp/image

**Comment by e-kwsm** [comment]
ご迷惑をおかけしました

**Comment by faithandbrave** [comment]
いえ、こちらも事故が起こる体制になっていました。遅くても朝には復旧していると思います。
