### ISSUE TITLE
[C++17][言語機能] 入れ子名前空間の定義

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#425]
「入れ子名前空間の定義」の解説を作成してください。

- [C++1z 入れ子名前空間の定義](http://faithandbrave.hateblo.jp/entry/2016/10/19/142023)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by usagi** [comment]
6c5f1d96
