### ISSUE TITLE
[C++17][言語機能] 名前空間と列挙子への属性付加を許可

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#426]
「名前空間と列挙子への属性付加を許可」の解説を作成してください。

- [C++1z 名前空間と列挙子への属性付加を許可](http://faithandbrave.hateblo.jp/entry/2016/10/13/150637)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
遅くなってしまいましたが、書きましたのでcloseします。
