### ISSUE TITLE
[C++17][言語機能] 属性の名前空間指定に繰り返しをなくす

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#429]
「属性の名前空間指定に繰り返しをなくす」の解説を作成してください。

- [C++1z 属性の名前空間指定に繰り返しをなくす](http://faithandbrave.hateblo.jp/entry/2016/10/14/162719)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
一通り書いたのでcloseします。
