### ISSUE TITLE
[C++17][言語機能] 不明な属性を無視する

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#430]
「不明な属性を無視する」の解説を作成してください。

- [C++1z 不明な属性を無視する](http://faithandbrave.hateblo.jp/entry/2016/10/18/152240)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
一通り書いたのでcloseします。

**Comment by yumetodo** [comment]
@katsuster 出力の項にclangのコンパイル結果を張っている意図がいまいちわからないのですが・・・。C++14までの挙動の例でいいんですよね？

**Comment by faithandbrave** [comment]
この仕様に対するClangとGCCの動作は、「不明な属性が指定されたときは、デフォルトで警告を出力する。ただし、不明な属性の指定が意図したものであることを示すために、警告を抑制するオプションを用意する」といったところでしょうか。
Clangでは`-Wno-unknown-attributes`を付けない限り警告が出力されますね。

この仕様に対する動作の想定として、「警告が出力されない」ことと「警告が出力されること」で @katsuster さんと @yumetodo で認識が一致していないように感じます。
私も警告が出力されず単に無視されると想定していました。備考欄に、コンパイラの動作を明記しておいた方がよいかもしれませんね。

**Comment by katsuster** [comment]
@yumetodo さん、ご指摘ありがとうございます。C++14ではなくC++17の挙動のつもりで載せています。
@faithandbrave さんのおっしゃるような「不明な属性の指定が意図したものであることを示すために、警告を抑制するオプションを用意する」までは考えが至らず。P0283R2の'Any attribute-token that is not recognized by the implementation is ignored.'を「不明な属性をill-formedにしないこと」くらいに理解していました。

結果にwarningを載せることは私も違和感がありましたが、

- 標準はその点に何も言及しておらず、間違いではない
- Clang++はwarningを出す動きのままだろうから、読者から見て現実に近い方が例としては良いだろう

と判断してそのまま載せました、が、あまり良くなかったですね。

修正方針ですが、備考欄に書くアイデアを使わせて頂きます。出力例は空にして、備考に移動させ現在のClang++の動作を説明し、オプションの話も書こうと思います。

**Comment by katsuster** [comment]
プログラマのミスで「意図せず」未知の属性を指定した場合、警告を出さないと気づかないので、Clang++やGCCの警告を出力するデフォルト設定は合理的だと思われるのですが、、、

現時点では私の推測に過ぎないので、リファレンスサイトには書かない方が良いですよね。

警告する動作にした根拠も探してみます。見つかるかなあ。

**Comment by faithandbrave** [comment]
念のため、私の想定はより明確には「処理系とグローバルの名前空間の属性で不明なものは警告を出力し、それ以外の名前空間の属性については警告を出力しない」というものでした。
以下のブログも、その見解に合致しているように思います：

- [C++17 Features - Bartek's coding blog](http://www.bfilipek.com/2017/01/cpp17features.html#ignore-unknown-attributes)

Clangのこの仕様への対応は、C++17対応がはじまる前に行われたように思います。そのために、名前空間を考慮した対応は行われていないのではないかと推測します。

リファレンスサイトで実際に書くために必要なのは、想定ではなく事実になりますので、備考欄には「不明な属性を無視するという仕様が、実際にはどのような動作になるか」を書くことになるかと思います。

**Comment by katsuster** [comment]
ありがとうございます。
事実として、コンパイル結果とオプションの話だけ書きました。

（以下、雑談です）

「処理系とグローバルの名前空間の属性で不明なものは警告を出力し、それ以外の名前空間の属性については警告を出力しない」
この仕様を持ってしても`[[gnuu::fallthrough]]`のように名前空間をミスしたとき見逃してしまいますね。
コンパイラとしては、プログラマの意図なら無視して、ミスなら警告するのが理想ですが、コードから前者か後者か判別するのは難しそうです。少なくとも私は方法が思いつきません…。

**Comment by katsuster** [comment]
refs 書くの忘れた orz

**Comment by yumetodo** [comment]
```cpp
[[gnu::deprecated]] void g() {}
  //C++標準に規定されていないが、コンパイラにとって既知の属性
```

ここなんですが、例の部分までではclangでコンパイルすることを記述していません。

したがって、例の中のコメントに説明を書くのではなく、備考欄にClangの場合は``[[gnu::deprecated]] ``は既知です、と記述するべきではないでしょうか?

このままだとすべてのコンパイラが``[[gnu::deprecated]] ``が既知であるかのように見えます。実際には例えばVisual Studio 2015以降では``C5030 属性 'gnu::deprecated' は認識されません``がでるはずです。

**Comment by katsuster** [comment]
ご指摘ありがとうございます。

P0283R2には、

- 標準に規定されている属性
- それ以外
- 各実装は固有の名前空間を選べ

のように挙げられていたので、合わせて例を 3つ用意しましたが、確かに誤解を招きますね。実装固有の属性については、どう書いたら良いものか……。

例からコメントを削ってしまうと何が何だかわからないので、ご提案頂いた内容とは少し異なりますが、コメントにClangとGCCでは既知である、他のコンパイラではそうではないことを追記しました。
