### ISSUE TITLE
[C++17][言語機能] __has_include

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#431]
`__has_include`の言語機能解説を作成してください。

- [インクルードするファイルが存在するかを確認する`__has_include`](http://faithandbrave.hateblo.jp/entry/2016/05/09/175923)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
一通り書いたのでcloseします。
