### ISSUE TITLE
[C++17][言語機能] 非推奨だったbool型に対するインクリメント演算子を削除

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#434]
「非推奨だったbool型に対するインクリメント演算子を削除」の解説を作成してください。

- [C++1z 非推奨だった`bool`型に対するインクリメント演算子を削除](http://faithandbrave.hateblo.jp/entry/2016/11/01/162946)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by yumetodo** [comment]
# 疑問点

- ``operator --``が文面的に復活できるように思うのは気のせいだろうか・・・？
- bool型に対する``operator++``をoverloadできるようになっている気がするのはやはり気のせいだろうか・・・

**Comment by faithandbrave** [comment]
@yumetodo さんに書いていただいた初版について、書き方を整理させていただきました。ご確認ください。
https://github.com/cpprefjp/site/commit/2721fe44de040a0303ab82c1618af4380f4ace58

**Comment by faithandbrave** [comment]
> operator --が文面的に復活できるように思うのは気のせいだろうか・・・？
復活というのは具体的にはどの部分を言っていますか？

> bool型に対するoperator++をoverloadできるようになっている気がするのはやはり気のせいだろうか・・・

インクリメント演算子は非メンバ関数として定義できるようですので、それだけ見るとオーバーロードできそうな気はしますが、`float`に対して剰余演算子をオーバーロードできないのと同じ理由で、できないように思います。
演算子オーバーロードはクラスもしくは列挙型に対して許可されたもので、組み込み型は対象外なのですかね。(コンパイラが定義した拡張の`__int128_t`とかの組み込み型はそこから外れるとして)

**Comment by yumetodo** [comment]
>タイトルが「operator++(bool)の除去」となっていたが、これはoperator++(bool)がill formedな書き方であるため(前置インクリメントはbool::operator++(), 後置インクリメントはbool::operator++(int)なので、どちらにも当てはまらない)、「bool型に対するインクリメント」に修正。「除去は」ほかに合わせて「削除」にした

``operator++(bool)``というのは一応提案文章に合わせたんですが、了解です。

>不明な記述「」を削除。おそらくMarkdownエディタによって自動挿入されるものであると思われる

あ・・・、VSCodeでMarkdown書いているんですが、Markdown Lintを常に有効にしていて、今回は要らない警告だけdisableを書いていたのを忘れてました。そういえばMarkdown Lintとかはとくに書けていないんですね。

>とくに、インデントはcpprefjpサイトでは2スペースである

修正ありがとうございます。

>復活というのは具体的にはどの部分を言っていますか？

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0002r1.html

をみると、bool型を除く、という記述が前置および後置の``operator --``から削除されており(§ 5.2.6 / § 5.3.2)、かといってIncrementとdecrementに共通する記述部分にbool型を除く、という記述が追加されているようには見えません。なので、これはbool型に対する``operator --``を処理系依存動作として実装できてしまうんじゃないかと思ったのです。このdiffに無いだけでどこかにそうさせない文面があるのでしょうか・・・？

**Comment by yumetodo** [comment]
あー、N4659見たら、

```
§ 5 => § 8
§ 5.2.6 => § 8.2.6
§ 5.3.2 => § 8.3.2
§ 13.6 => § 16.6
```

に番号が変わっているな・・・。提案文章の番号を信じたのは間違いでした。なおした方がいいですよね？

**Comment by faithandbrave** [comment]
反応遅くなりました。すでに修正されたようで、ありがとうございます。
節番号は規格のバージョンが変わるとよくズレるので、バージョン変更でズレにくいタグも書いておくと調べやすくなりますね。
タグはPDFの右側に書いてあります。8.2.6は[expr.post.incr]、8.3.2は[expr.pre.incr]になります。

**Comment by k-satoda** [comment]
>> bool型に対するoperator++をoverloadできるようになっている気がするのはやはり気のせいだろうか・・・

...
> 演算子オーバーロードはクラスもしくは列挙型に対して許可されたもので、言語の組み込み型は対象外なのですかね。(コンパイラが定義した拡張の`__int128_t`とかの組み込み型はそこから外れるとして)

n4660 [over.oper] 16.5 p6 （↓）の制約によりオーバーロードできないようになってます。
> An operator function shall either be a non-static member function or be a
> non-member function that has at least one parameter whose type is a class, a
> reference to a class, an enumeration, or a reference to an enumeration. ...

**Comment by yumetodo** [comment]
@faithandbrave それもそうですね。修正しました

@k-satoda なるほど。ありがとうございます。

**Comment by yumetodo** [comment]
@faithandbrave 
- https://github.com/cpprefjp/site/commit/acce9ebfe8098f75b25de23175914e3d89bcc788
- https://cpplover.blogspot.jp/2015/10/c2015-09-pre-kona.html

のようにインクリメント/デクリメントのbool型に対する仕様が十分理解されていないように思うんですが、

- bool型に対する``operator --``はもともとない([ブログの方には](http://faithandbrave.hateblo.jp/entry/2016/11/01/162946)記述あり)
- bool型に対する``operator ++``はtrue/falseをトグルしない(私自身[トグルすると勘違いしていた](http://qiita.com/yumetodo/items/8d8f20a971d0ca2a8b84#comment-41e56e73dd66cf4871fe))

点をもっと強調したほうがいいでしょうか？それとも削除される機能だからそこまで必要ないでしょうか？

**Comment by faithandbrave** [comment]
[CONTRIBUTING.md](https://github.com/cpprefjp/site/blob/master/CONTRIBUTING.md)に、以下のように書いていますので、情報として不足していると感じたら、編集者の裁量の範囲で書き足してください。

> ## 正確なものに不要な情報はない
> 
> 本サイトが提供するコンテンツは、編集者間での合意がとれるものである限りにおいて、「提供しなくてよい情報」というものはないと考えています。情報を書きすぎてはいけないということはありませんので、情報不足と思われる場所を見つけたら、現在の本サイトのスコープに収まる限りは追記していただいてかまいません。
> 
> スコープを超えるコンテンツを提供したい場合には、pull requestかissueを発行して、合意をとってください。

情報量が多くなってきたら段落を分けるとかの工夫をして整理すればなんとでもなりますので、書きすぎは、あまり気にしなくてよいです。

今回の場合は、雛形ページにある以下の段落を使用するのがよいのではないでしょうか。

> ## この機能が必要になった背景・経緯
> 
> (ここには、その言語機能が必要になった背景や経緯を記述します。その言語機能で解決したい問題は何だったのかは、ユーザーがその言語機能を実際に使う上で重要な情報となります。)

今回の場合、雛形の見出しタイトルが適さないような気がするので「この機能を削除するに至った背景・経緯」とかに修正して、「xxの機能はわかりにくく、誤解やバグの元だった」のようなことを調査して書き、元々許可されていた動作を書くとよいと思います。

**Comment by yumetodo** [comment]
@faithandbrave わかりました。文面を考えてみます。

**Comment by faithandbrave** [comment]
標準でdeprecatedになった履歴は見つけられませんでしたが、StackOverflowで納得できそうな回答はありました。

- [bool operator ++ and --](http://stackoverflow.com/questions/3450420/bool-operator-and)
- [Why does the boolean type in C++ support ++ but not --?](https://softwareengineering.stackexchange.com/questions/230928/why-does-the-boolean-type-in-c-support-but-not)

整数型の別名として`bool`を実装していたころの名残でインクリメント演算子があったけど、それは推奨されていたものではない、という感じでしょうか。

**Comment by yumetodo** [comment]
# Therac-25事件

[Therac-25](https://en.wikipedia.org/wiki/Therac-25)の事故の例が出てきて、``operator++``を使う文化に対し、C++にboolを追加する際にオーバーフローに起因するTherac-25の事件再発防止のために常にtrueにする仕様になった、と推測しています。

## ref

- [Therac-25 - Wikipedia](https://en.wikipedia.org/wiki/Therac-25)
- [An Investigation of Therac-25 Accidents - I](http://courses.cs.vt.edu/professionalism/Therac_25/Therac_1.html)
- [Therac-25 - II](http://courses.cs.vt.edu/professionalism/Therac_25/Therac_2.html)
- **[Therac-25 - III](http://courses.cs.vt.edu/professionalism/Therac_25/Therac_3.html)**
- [Therac-25 - IV](http://courses.cs.vt.edu/professionalism/Therac_25/Therac_4.html)
- [Therac-25 - V](http://courses.cs.vt.edu/professionalism/Therac_25/Therac_5.html)
- **[Datent, Magnet, and Ptime subroutines](http://courses.cs.vt.edu/professionalism/Therac_25/Side_bar_4.html)**
- **http://courses.cs.vt.edu/professionalism/Therac_25/Figure.4.GIF**
- [THERAC-25 Computerized Radiation Therapy](http://web.archive.org/web/20071212183729/http://neptune.netcomp.monash.edu.au/cpe9001/assets/readings/www_uguelph_ca_~tgallagh_~tgallagh.html)

# bcc32の実装バグ

[Borland bool++｜freeml byGMO](http://www.freeml.com/cppll/9957/latest)

なんていう実装バグもあったようです。

- https://twitter.com/wraith13/status/236136124366585856
- [bool値をインクリメントする……？ (3ページ目) - Togetterまとめ](https://togetter.com/li/356718?page=3)

**Comment by yumetodo** [comment]
#436 のmergeによって、書きたいことは大体かけたと思うのでcloseします。
