### ISSUE TITLE
[C++17][言語機能] enum class変数の初期値として整数を指定する際の規則を調整

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#439]
「enum class変数の初期値として整数を指定する際の規則を調整」の解説を作成してください。

- [P0138R2 Construction Rules for enum class Values](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0138r2.pdf)
- [言語機能解説の雛形ページ](https://github.com/cpprefjp/site/blob/master/editors_doc/lang_template_page.md)

**Comment by katsuster** [comment]
初版をコミットしたのでクローズします。
