### ISSUE TITLE
proposal: SD-6機能テストマクロの一覧表を作成するべきか

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#443]
内容的には

- [SD-6: SG10 Feature Test Recommendations : Standard C++](https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations)
- [Feature Test Recommendations - cppreference.com](http://en.cppreference.com/w/cpp/experimental/feature_test)

の翻訳になるが、cpprefjpの言語機能解説のページとリンクした一覧表には需要があるのではないか？

そこで

- SD-6機能テストマクロの一覧表作成
- 既存の言語機能解説、ライブラリ解説で機能テストマクロに言及し忘れているものを探す
- 既存の言語機能解説、ライブラリ解説から一覧表ページヘのリンクを貼る

ことを提案する。

問題としては

- そもそも必要か
- 作成する場合どこに作るか(`/lang/sd-6-sg10-feature-test-recommendations/README.md` とか？)
- `__cpp_lib_experimental_`から始まるものはどうするか

**Comment by faithandbrave** [comment]
ぼくはテストマクロはあまり有意義なものではないと思うので積極的に賛成はしませんが、本サイトの方針である「正確な情報に不要なものはない」というものから反対もしません。
「有意義ではない」というのは、コンパイラの自己申告的な情報でしかないからで、実装が完全であることや、バグがないことを保証するものではないからです (ライブラリ単位をサポートするテストマクロが定義されていたとしても、そのうち一部機能が未サポートなこともある)。
Boost.Configとかは、「Boostの実装で使用するのに十分な実装になっていれば、そのコンパイラ向けにマクロを定義する」という方針になっていて、VC++向けに長い間`decltype`とExpression SFINAEが実装されているとは認められなかった経緯もあります。ユーザー立場からの実装評価が必要という事例です。
libstdc++とかlibc++の実装内部で共通のマクロを使って実装できるという感じで、標準ライブラリの実装者にとってはある程度有意義な機能なのでしょうけどね。

作成する場合は、言語バージョンごとにまとめページを作成するのがよいと思います。`/lang/cpp11/feature_test_macros.md`とか。

experimentalな機能は言語バージョンとは別のタイミングで承認され、次期標準のためにコンパイラが実装経験を得るためのものです。なので、アーリーアダプター向けの機能と割り切って、言語バージョンとは独立した位置に「次期標準のための実験機能」のような階層を作り、そこは随時追加・随時削除をする場にしてもよいのかなと思います。Technical Specificationが承認あるいはコンパイラが実装をはじめた段階で追加、標準に正式に採用されコンパイラが実装した段階で削除、のように。

**Comment by e-kwsm** [comment]
> ぼくはテストマクロはあまり有意義なものではないと思うので積極的に賛成はしませんが、本サイトの方針である「正確な情報に不要なものはない」というものから反対もしません。
「有意義ではない」というのは、コンパイラの自己申告的な情報でしかないからで、実装が完全であることや、バグがないことを保証するものではないからです

確かにそうですが，コンパイルが通ったかどうかで正しく実装されているか判断するのも危険かと思います．

機能テストマクロの存在そのものを知らないユーザもいると思うので，何かしらの形で触れることに賛成です．

---

作成する場所は

1. 「更新された定義済みマクロ [`/lang/cpp17/predefined_macros.md`](../tree/master/lang/cpp17/predefined_macros.md) etc」に各値を書く
1. 「言語機能 [`/lang.md`](../tree/master/lang.md)」に『機能が提供されているか確かめるには』などとして外部リンクに誘導
 
はいかがでしょうか？

---

experimental な機能については実装済みかどうかユーザが気を配っていると思うので書かなくても構わないかなと思います．

**Comment by faithandbrave** [comment]
「更新された定義済みマクロ」は言語標準が提供するもので、機能テストマクロはコンパイラに定義することを推奨するものなので、立ち位置が少し違うのですよね。

ですので、言語のバージョンごとに `/lang/cpp11/feature_test_macros.md` というページを用意することを提案していました。バージョンごとに用意するのは、ページが肥大化しないための措置です。

機能テストマクロは、言語・ライブラリ機能の解説ページと対応していた方が使いやすいと思いますので、cppreferenceとかの英語ページに誘導するよりは、cpprefjp内で完結していたほうがよいかと思います。

experimentalな機能については、ページのメンテナンスコストがかかるだけで、恩恵を受けるユーザーは少ないと思うので、書きたいという強い動機がとくになければ書かない方が、ほかに注力できてよいと思います。

**Comment by e-kwsm** [comment]
[C++14](../tree/master/lang/cpp14/predefined_macros.md)/[17](../tree/master/lang/cpp17/predefined_macros.md) では `__cplusplus` しか載っていないのでまとめてしまおうと思ったのですが乱暴でしたか．

> バージョンごとに用意する

賛成です．

**Comment by faithandbrave** [comment]
ここまでで意見は集まりきったと思いますので、ここから一週間くらいで提案者の @yumetodo さんからなにもなければ、本Issueは終了しますよ。

**Comment by yumetodo** [comment]
@faithandbrave では

- `/lang/cppxx/feature_test_macros.md`に作成する
- `__cpp_lib_experimental_`から始まるものは無視

ということで、作成TASK Issueを作ってこのIssueをcloseでいいでしょうか？

**Comment by faithandbrave** [comment]
はい、それで大丈夫です。

**Comment by yumetodo** [comment]
- C++11: #447
- C++14: #448
- C++17: #449
