### ISSUE TITLE
std::basic_ostreamのストリームバッファに対するオーバーロードは書式化か非書式化か？

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#450]
@egtra 

https://cpprefjp.github.io/reference/ostream/basic_ostream/op_ostream.html

このページでは、ストリームバッファに対するオーバーロードだけが非書式化であると記載されています。

```cpp
// ストリームバッファの非書式化出力
basic_ostream<CharT, Traits>& operator<<(basic_streambuf<CharT, Traits>* sb);
```

C++03からC++17まで、規格書上でこの関数は書式化(Formatted)であると記載されています。

```cpp
// 30.7.5.2, formatted output
basic_ostream<charT, traits>& operator<<(const void* p);
basic_ostream<charT, traits>& operator<<(nullptr_t);
basic_ostream<charT, traits>& operator<<(basic_streambuf<char_type, traits>* sb);

// 30.7.5.3, unformatted output
basic_ostream<charT, traits>& put(char_type c);
basic_ostream<charT, traits>& write(const char_type* s, streamsize n);
```

ストリームバッファを非書式化と記載したのは、意図したものでしょうか？単なるミスである場合は修正します。

**Comment by faithandbrave** [comment]
私の方で、C++17対応で`nullptr_t`のオーバーロードを追加しようとしていたのですが、書式化と非書式化どちらに分類すればよいかわからなくなっていました。

`nullptr_t`は実装定義のなんらかの(おそらく固定)文字列を返すだけなので、非書式化と言えると思いますが、規格書では書式化に分類されています。
このページでの分類基準が規格書と異なっているのであれば、そこに合わせたい、という意図です。

**Comment by faithandbrave** [comment]
文字列の`operator<<`は`setw`とか`right`とかの影響を受けるので、`nullptr_t`は書式化ですね。ストリームバッファはわからないですが、`nullptr_t`はとりあえず対応してしまいます。

**Comment by egtra** [comment]
はい、これは意図したとおりです。`[ostream.inserters]`の`basic_ostream<charT,traits>& operator<<(basic_streambuf<charT,traits>* sb);`のところには、`Effects: Behaves as an unformatted output function  (as described in 27.7.3.7, paragraph 1).`と書かれているためです。そのため、非書式化関数としました。

**Comment by faithandbrave** [comment]
ありがとうございます。Formattedのところに書いてあるのはまぎらわしいですね・・・。ぼくの読み落としでした。失礼しました。
