### ISSUE TITLE
「非推奨だった bool 型に対するインクリメント演算子を削除(C++17)」に関する曖昧な記述

### ISSUE THREAD

**Issue by tai2** [cpprefjp/site#452]
https://cpprefjp.github.io/lang/cpp17/remove_deprecated_increment_of_bool.html

こちらのページの

>すると、これが1になるまでif文の中の式は実行されない。

という文について、「if文の中の式」が、`flag++` を指しているのか、`std:cout << ','` を指しているのか判断できませんでした。前者と解釈する場合、その意味をどう解釈すれば良いのかわかりませんでした。
後者と解釈する場合、「1になるまでif文の中の式は実行されない」という記述と矛盾すると思います。

**Comment by faithandbrave** [comment]
私が書いたわけではないですが、`std:cout << ','`の方だと読み取りました。しかしこれが矛盾するというのはよくわかりませんでした。

オーバーフローによって`flag`の値が負数になるから、1以上になるまで加算しないと、その間カンマが出力されない、ということを意図しているのだと思います。
そのようにより具体的に記述すればよいかとは思いますが、「矛盾」というのがどの点を指しているのかを伺ってから修正しようと思います。

**Comment by faithandbrave** [comment]
あぁ、すいません。負数でも0でなければカンマは出力されるから、1以外でもカンマ出力は行われる、というご指摘でしょうか。

**Comment by tai2** [comment]
>負数でも0でなければカンマは出力されるから、1以外でもカンマ出力は行われる

はい、そうです。
(自分の理解が甘くて、文章の意図を理解できていない可能性があるので、まずはissueを立てさせてもらいました。)

**Comment by faithandbrave** [comment]
@tai2 確認ありがとうございます。私の方で修正しておきました。
5分後くらいには、サイトの方に反映されると思います。

修正内容に問題があればreopenしてください。

**Comment by yumetodo** [comment]
@tai2 あああ、完全に間違っていますね・・・
@faithandbrave 修正ありがとうございます。

**Comment by yumetodo** [comment]
ref:
- #434
