### ISSUE TITLE
cpprefjpサイトでの次期C++バージョンの取り扱い方針

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#454]
C++17では、Final Committee Draft (FCD) が公開されるまで2017年中のリリースが不確かとみてcpprefjpサイトで取り扱いをしていませんでした。
しかし、C++17からは3年周期での言語アップデートで、仕様が固まったものから順次リリースという形式になったため、リリース次期が不確かで言語バージョンが確定しない、という事態は起こらなくなりました。

ですので、C++20からは、cpprefjpサイトでは随時対応を許可していきたいと考えています。
これについて、ご意見あればお願いします。

この方針で決定した場合は、READMEと編集者向けドキュメントの更新をもって、本Issueを閉じようと思います。

**Comment by faithandbrave** [comment]
C++20の記事が上がってきているので、とりあえずWikiページを用意しておきました。

https://github.com/cpprefjp/site/wiki/cpp20

Editor's Reportがまだ上がってきていないので、具体的な対応リストはまだ書いていません。

**Comment by yumetodo** [comment]
今のところはConceptが入ったんでしたっけ。

3年周期での言語アップデートということなので、マージされ次第解説を書き始める方向でいいと思います。

**Comment by faithandbrave** [comment]
随時対応の方針で行く場合は、Working Draftに機能がマージされる (Editor's Reportにpaper番号もしくはissue番号が載る) ことを持って、その機能の解説を許可する、ということになりそうですね。Issueがready状態になった、というのでもOK。
提案段階で書いてはいけないので、そのルールは明記することになります。

**Comment by faithandbrave** [comment]
とくに反対意見がなさそうでしたので、作業方法を明記し、サイトのトップページと本リポジトリのREADMEを「最新C++バージョンに対応」と記載しておきました。
