### ISSUE TITLE
Pull Requestをマージできる人を明確にする

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#455]
いまのところ、Pull Requestが来たときには私か @usagi さんがマージしていますが、GitHubの権限としては編集チームのメンバーならだれでもマージできます。
Pull Requestを送ってくれた方を編集チームに招待するには管理者権限が必要となりますが、マージする人と、編集チームへ招待する人は分かれていてよいと思います。

このリポジトリで作業されている方には、Pull Requestが妥当なものか判断できる方が大勢いますので、Pull Requestのレビューとマージも可能な方にはどんどんお願いしたいと考えています。

この方針にご意見あればお願いします。
問題なければ、CONTRIBUTING.mdに「Working Teamのメンバ (このリポジトリへのPush権限をお持ちの方) は、Pull Requestのマージができる」ということと、「Pull Requestのマージを確認したあとに、管理者がWorking Teamに招待する」ということの2点を記載しようと思います。

だれがPush権限を持っているかは、以下のどちらかのページを参照すればわかるので、長時間マージされないままになっているPull Requestがあれば、個人的にレビューをお願いしてもよいでしょう。(議論自体はできるだけここで行ってほしいですが)

- https://github.com/orgs/cpprefjp/people
- https://github.com/cpprefjp/site/graphs/contributors

***
コミュニティの代謝のために、アクティブに活動している方には今後、管理者権限もお配りしようかとも考えていますが、そのためには管理者用の議論場所を用意する必要もありそうなので (以前はあったけど、いまはここでしか議論していない)、それは今後の課題ですね。

**Comment by yumetodo** [comment]
以前
https://github.com/cpprefjp/site/issues/424#issuecomment-296379913
でprotect branchの設定を有効にされたと思いますが、同じ設定画面でGithun Organizationのrepoは誰がPull Requestをマージできるかbranchごとに設定できます。

![image](https://user-images.githubusercontent.com/10869046/28413244-d5fa3310-6d81-11e7-94cb-ceb06be129e5.png)

Push権限とPull Requestのマージ権限をわける必要もありそうならこういう手段もあります。ただしこの場合、Owner権限を持たない場合はPull Requestを投げてセルフマージするような話になりますが。

**Comment by faithandbrave** [comment]
私としては管理者の負担を減らすために、ほかのひともマージしていいですよ、という意図でした。
Pull Requestのマージ権限を分けたいという動機がある方がいましたら、ご意見お願いします。

**Comment by faithandbrave** [comment]
遅くなりましたが、CONTRIBUTING.mdを更新し、push権限を持っている方はPull Requestをマージできることを明記しました。
記述に問題があればreopenお願いします。軽微な修正や言い回しを直す程度であれば、直接修正していただいてかまいません。
