### ISSUE TITLE
random_device: mingw gcc向けのworkaroundを具体的に書く

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#458]
#451 の議論の結果`random_device`が擬似乱数生成器で定義される可能性があることに触れたが、その最も有名な<sup>[要出典]</sup>実装であるmingw gcc向けのwork aroundを紹介してもいいのではないか。

イメージとしてはこんな感じのを載せる。`rand_s`は`Windows.h`の前に`_CRT_RAND_S`のdefineが必要でworkaroundには不適。`CryptGenRandom`を用いる。

```cpp
#include <random>
#if defined(__MINGW32__) && defined(__GNUC__) && !defined(__clang__)
#include <system_error>
#include <limits>
#include <string>
#include <Windows.h>
#include <wincrypt.h>
namespace workaround_mingw_gcc {
class random_device {
private:
  class crypt_context {
  private:
    HCRYPTPROV prov_;
  public:
    crypt_context(DWORD prov_type, LPCTSTR container = nullptr, LPCTSTR provider = nullptr, DWORD flags = 0)
    {
      using std::system_category;
      using std::system_error;
      const auto er = ::CryptAcquireContext(&this->prov_, container, provider, prov_type, flags);
      if(!er) {
        throw system_error(
          std::error_code(::GetLastError(), system_category()),
          "CryptAcquireContext:(" + std::to_string(er) + ')'
        );
      }
    }
    crypt_context(const crypt_context&) = delete;
    void operator=(const crypt_context&) = delete;
    ~crypt_context() noexcept
    {
      ::CryptReleaseContext(this->prov_, 0);
    }
    //HCRYPTPROV& get() noexcept { return this->prov_; }
    const HCRYPTPROV& get() const noexcept { return this->prov_; }
  };
  crypt_context prov_;
public:
  using result_type = unsigned int;
  explicit random_device(const std::string& /*token*/ = "workaround_mingw_gcc ")
  : prov_(PROV_RSA_FULL)
  {}
  random_device(const random_device&) = delete;
  void operator=(const random_device&) = delete;
  //~random_device() = default;
  double entropy() const noexcept { return 0.0; }
  result_type operator()()
  {
    using std::system_category;
    using std::system_error;
    result_type re;
    const auto er = ::CryptGenRandom(this->prov_.get(), sizeof(re), reinterpret_cast<BYTE*>(&re));
    if(!er) {
      throw system_error(
        std::error_code(::GetLastError(), system_category()),
        "CryptGenRandom:(" + std::to_string(er) + ')'
      );
    }
    return re;
  }
  static constexpr result_type min() { return std::numeric_limits<result_type>::min(); }
  static constexpr result_type max() { return std::numeric_limits<result_type>::max(); }
};
}
namespace cpprefjp {
  using workaround_mingw_gcc::random_device;
}
#else //defined(__MINGW32__) && defined(__GNUC__) && !defined(__clang__)
namespace cpprefjp {
  using std::random_device;
}
#endif //defined(__MINGW32__) && defined(__GNUC__) && !defined(__clang__)
```

ref

- [Example C Program: Duplicating a Session Key (Windows)](https://msdn.microsoft.com/en-us/library/aa382048.aspx)
- [CryptAcquireContext function (Windows)](https://msdn.microsoft.com/en-us/library/aa379886.aspx)
- [CryptReleaseContext function (Windows)](https://msdn.microsoft.com/en-us/library/aa380268.aspx)
- [CryptGenRandom function (Windows)](https://msdn.microsoft.com/en-us/library/aa379942.aspx)
- [Cryptographic Provider Types (Windows)](https://msdn.microsoft.com/en-us/library/aa380244.aspx)
- [MSC30-C. 疑似乱数の生成に rand() 関数を使用しない](https://www.jpcert.or.jp/sc-rules/c-msc30-c.html)

**Comment by faithandbrave** [comment]
workaroundを紹介するのは問題ないと思います。
書く場所は、処理系の備考欄あたりでしょうか。

**Comment by yumetodo** [comment]
そうですね。

では上記のコードを使って問題ないか、意見が欲しいです。

コンパイルテストに使ったコード:
https://gist.github.com/yumetodo/68bd4796e128babb506766c03f116641

**Comment by faithandbrave** [comment]
Windows環境がないため、ドキュメントでの確認ですが、実装としては問題ないと思います。
細かいところでは、コードの書き方に一貫性がない箇所がいくつかありました：

- Windows APIを呼び出す際に、グローバル名前空間を明示的に参照している(`::`を先頭に付けている)ところと、そうでないところがある
- 関数パラメータの末尾にスペースがあるところと、ないところがある

それと、`crypt_context`の`HCRYPTPROV& get() noexcept { return this->prov_; }`は、このサンプル上は必要なさそうに思えました。

**Comment by faithandbrave** [comment]
`crypt_context`が入れ子クラスになっているため、`random_device`内でユースケースが閉じているのですよね。「あった方が後々便利かも」という設計は、実際の開発では大いに理解できるのですが、サンプルコードとしては必要最小限の方が、理解を助けてくれると思います。

**Comment by yumetodo** [comment]
ところで規格書みるとどうも

```cpp
~random_device() = default;
```

は書け、ということらしいのですが、必要なんですかね・・・？

**Comment by faithandbrave** [comment]
インタフェースの明示としてあるだけなので、実装を示す分にはあってもなくても、どちらでもよいです。

**Comment by yumetodo** [comment]
@faithandbrave 書いてみました。
コード中の`CryptGenRandom`とかにもリンクを貼りたかったのですが、やり方がわからなかったのでやってません。

**Comment by faithandbrave** [comment]
ありがとうございます。
コードブロック中の識別子にリンクを貼るのは、cpprefjp/boostjpのMarkdown拡張記法を用意してあります。
https://cpprefjp.github.io/editors_doc/specialized.html

コードブロックのすぐ下に、箇条書き記法で`* CryptGenRandom[link http://hogehoge.com]`みたいにすれば、リンクを貼れます。

**Comment by yumetodo** [comment]
絶対リンク貼れるのは見落としていました・・・。

**Comment by yumetodo** [comment]
@faithandbrave 作業終了しました。確認してcloseお願いします

**Comment by faithandbrave** [comment]
確認しました。ありがとうございます。
