### ISSUE TITLE
cpprefjpのアイコンを作る

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site#461]
昨日からMemberになりました。よろしくお願いします。

今のcpprefjpにはアイコンが無いので少し寂しいです。（ですよね？）
というわけで、たたき台を作りました。

## ラフスケッチ

参考までに、最初のラフスケッチがこれです：
![icon-sketch-1](https://user-images.githubusercontent.com/1901813/29213401-201276c0-7ede-11e7-82a4-40a16a1ad605.png)

## サンプル

このラフを基にIllustratorで作ったサンプルがこれです：
![cpprefjp-icon-sample-jp 0 5x](https://user-images.githubusercontent.com/1901813/29213415-30a1c27a-7ede-11e7-9c5a-a198e7f35a08.png)
![cpprefjp-icon-sample-hiragana 0 5x](https://user-images.githubusercontent.com/1901813/29213418-32e860ca-7ede-11e7-9dc0-c23295d9adec.png)
![cpprefjp-icon-sample-shuriken-fly 0 5x](https://user-images.githubusercontent.com/1901813/29213437-3791783c-7ede-11e7-97e7-08542025ed58.png)
![cpprefjp-icon-sample-shuriken-single 0 5x](https://user-images.githubusercontent.com/1901813/29213440-3904f7ac-7ede-11e7-8921-e69cc45a84c7.png)

## アイコンの思想

アイコンの思想としては以下のようなことを想定しました。

### 1. ターゲットがC++ということが分かる

大体分かると思います。  
4個目に関しては文字は「C」ですがシルエット自体が十字なので。

### 2. 日本語の情報を扱っていることが分かる

１個目と２個目は文字で日本を表現しているので分かると思います。

３個目と４個目では方向性を変えて、モチーフで表現しています。  
「C」「＋」という2つの文字を絶対に入れるという縛りのもとで、「日本」を表現しようと思ってかなり悩んだんですが、自分の想像力では手裏剣しか思いつきませんでした。  
手裏剣は言わずもがな日本っぽいですし、十字なのでプラス記号も表現できると言えそうです。

### 3. 16x16pxで判別できる

実際に16x16pxで表示してみると以下のような感じになります。

![cpprefjp-icon-preview-chrome-tabs](https://user-images.githubusercontent.com/1901813/29213874-18f40460-7ee0-11e7-8d90-7dad58f629c0.png)

### 4. 二値化した時にシルエットだけで判別できる

大丈夫だと思います。

![cpprefjp-icon-preview-grayscale-white-bg](https://user-images.githubusercontent.com/1901813/29214464-6ec32b12-7ee2-11e7-9c6c-fc9f743b30aa.png)
![cpprefjp-icon-preview-grayscale-black-bg](https://user-images.githubusercontent.com/1901813/29214466-6fe52180-7ee2-11e7-9a64-c5659a1b601b.png)

---

以下の点についてどう思うかコメントしていただければ幸いです。

- cpprefjpにアイコンが必要と思うか
- このサンプルのデザインについて
- その他アイデアなどあれば

cc: @cpprefjp/coreteam @cpprefjp/workingteam 

議論の方向性についてはとりあえずコアチームに任せます（とりあえずアサインしておきます）。

**Comment by faithandbrave** [comment]
ありがとうございます。デザインにまではなかなか手が回らないため、とても助かります。
アイコンは、あった方がよいと思います。いただいたサンプルもどれもよいと思うので、なかなか私が「これ！」と決めるのはむずかしいですね。
ほかにどなたか推しがあれば、とくになければ @saki7 さんの好みで決めてよいかと思います。

**Comment by rinatz** [comment]
個人的には4つ目のCと手裏剣を2つ目のアイコンの配置の仕方で配置したら
格好良くなりそうな気がしました・・・！

**Comment by usagi** [comment]
初見の素直な感想です。

1. 著名な言語となったC#と紛らわしさを感じました。
2. 日本語である事がわかりやすいですが++だけではC++を連想できないので++をC++にした方が良いと感じました。
3. アーティスティックにデザインされすぎてしまっていてC++への連想性が薄らいでいるように感じました。
4. (3)案よりは何を表しているか読み取りやすいのですが、Cと読めてもC++とは読めませんでした。

4案からの選択であれば(2)案にC++である事が伝わりやすい改修を施した意匠設計がよいと思います。

**Comment by saki7** [comment]
@faithandbrave @rinatz @usagi ご意見ありがとうございます。指摘の内容はそれぞれ把握しました。

それぞれの意見について僕が思う所を書いても良いのですが、  
結局対象のデザインが何であろうが、個別のデザインの具体的な内容について議論を深めることにあまり意味が無いような気がしてきました。

懸念していたことではあるのですが、やはり、この進め方だと問題があると思います。デザインにゴールは無いからです。かといって、「異論があるなら代案を提出しろ」と言うのは違うと思います。

一方で、コミュニティドリブンのプロジェクトである以上、僕はある程度民主的なプロセスは踏む必要があると思っています。以下のいずれかが良いのではないでしょうか。

1. 一般公募期間と一般投票期間をそれぞれ設定して、純粋な得票数により決める
2. 一般公募期間を設定して、コアメンバによる多数決で決める

公募はこのIssue、投票はReaction機能が使えそうです。

とりあえず、進め方をはっきりさせたいので、進め方に関してコアチームの人の意見が欲しいです。

**Comment by faithandbrave** [comment]
議論に参加するメンバーはそれほど多くないので、投票性はそれほど機能しないと思います。A案1票とB案2票といった差で結論が出ても、それが多くの得票数を集めたことによって決定したとは言いにくいです。
ですので、ここは「意見を集めた上で、独裁的に決める」くらいでよいのではないかと思います。

「これに決まるのだけは絶対イヤだ」のような意見に対してはその理由を詰める必要はあるでしょうが、そうでない限りは、どれに決まっても一定の理解は得られるのではないかと思います。
最終決定権は、今回は @saki7 さんが持ってよいと思います。どの改修案を受け入れるかも含めて、デザイナーさんのモチベーション次第な部分が大きいと考えたためです。
技術的な部分に関しても、たとえば16x16pxでアイコンを判別できるためには、実際の改修にも制約があって実現できないこともあるでしょう。そういったことに関して、デザインの知見が大きい方に決定権を渡しておいた方が改修案の採用・不採用に関して間違いが起きにくいと思います。

本サイトにおいて、デザインに頼る要素はそれほど多くないと思っていますので、デザインチームはまだ設けなくてもよいかなと思います。

**Comment by yumetodo** [comment]
意見を言う前に一つ情報提供。

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">ところで某++の会とcomp-prog-jpが両方アイコンCで見分けにくい</p>&mdash; Az (<a href="https://twitter.com/azaika_">@azaika_</a>) <a href="https://twitter.com/azaika_/status/810514759690817537">2016年12月18日</a></blockquote>

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">昔はてなリング用に作ったC++のアイコンがありまして良かったらどうぞ。 <a href="https://t.co/pEmo1nzIfZ">pic.twitter.com/pEmo1nzIfZ</a></p>&mdash; hotpepsi (<a href="https://twitter.com/hotpepsi">@hotpepsi</a>) <a href="https://twitter.com/hotpepsi/status/810518620967149568">2016年12月18日</a></blockquote>

Slackの「C++の会」のアイコンが見づらいという話に対して

![C++](https://pbs.twimg.com/media/Cz-KW6qVIAAuYX1.png)

のアイコンが提示されていたようで、(結局議論は放置・・・)個人的にはこれが気に入っているので、hotpepsi氏に声をかけるという選択肢はありでしょうか・・・？

**Comment by yumetodo** [comment]
ただ自分でhotpepsi氏のアイコン気に入っているとか言っておいてなんですが、いずれも辞書感がないというか・・・。cpprefjpはただのC++情報サイトじゃないわけで。

**Comment by faithandbrave** [comment]
私としては、デザインコンペのような、複数人で持ち寄って戦わせるようなことはしたくないのですよね。とくに今回の場合、 @saki7 さんは自薦、hotpepsiさんは他薦となっています。私は、 @saki7 さんが能動的に貢献してくれようとしている点をもって、採用としたいです。

cpprefjp以外にもアイコンを必要としているところはあります。たとえばboostjpやWandboxなど。貴重な人的リソースは、集中させて戦わせるよりも、適時空いているところに入ってもらったほうがよいのではないでしょうか。

**Comment by yumetodo** [comment]
@faithandbrave わかりました。しかし、いずれも辞書感を欠くなという印象です。4つの中では1つ目かなと思いますが。

**Comment by saki7** [comment]
おっけーです。アキラさんの意見を踏まえて、今回のアイコンに関しては僕が決定することにします。
とりあえず、この4案のどれかで考えています。

## 4案について、 8/20 (日) 21:00 まで意見を募集します。

内容は何でも構いません。頂いたコメントは最大限尊重することを約束します。

---

@yumetodo さんのコメントが良い所を突いていたので、そこだけ少し書きたいと思います。

辞書感をアイコンで表現するには、一般的には書籍をモチーフにします。 :books: :book: :blue_book:  
書籍のモチーフには、技術的な問題と思想的な問題があると考えました。

16x16pxという狭い枠を書籍の外枠で更に狭めて、その中に「C++」と「日本感」を入れるのは難しいです。

人は、書籍のようなアイコンをひと目見ると、おそらく想像するのは辞典です。辞典にはものごとの定義を正確に記述するという通念があるので、cpprefjpのアイコンが辞典風のアイコンだと、書かれている内容の正確性や執筆ポリシーに関して誤解を与える可能性があります（CONTRIBUTINGに準じる）。

僕は、実際に問題が起こるかどうかというより、アイコンの持つ無意識的な訴求力が気になりました。そこで、僕の上記「アイコンの思想」には「辞書感を入れる」という点を入れていません。

**Comment by yumetodo** [comment]
Wikipediaはただの百科辞書ではなく、**だれでも参加できる**百科辞書=知の集積を目指しています。

![Wikipedia logo](https://ja.wikipedia.org/static/images/project-logos/jawiki.png)

このようなロゴにそれが現れていると考えます(がどこで議論されたのか検索可能性が低く遡及できていない)

一方より小さいことが求められるアイコンは

![Wikipedia icon](https://ja.wikipedia.org/static/favicon/wikipedia.ico)

シンプルなものが用いられています。

---

ウィキペディアンの端くれとしては確かに

>Wikipediaは、「百科事典」と言いつつも、アイコンに書籍のモチーフを使っていません。

は説得力がありますね・・・。しかし、一方で小さいことが要求されるアイコンとイメージが重視されるロゴが同じである必要もないわけで、その議論をどこでするかはともかく、ロゴについでも議論があっていいかなと思います。

**Comment by saki7** [comment]
はい。ロゴについての議論は何でも歓迎なのですが、僕の上のコメントは僕の４案に辞書感が無い理由を書いただけですので、その点についてはご理解頂ければなと思います。

**Comment by yumetodo** [comment]
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">1だけギリギリOK（JPのやつ）<br><br>２は意味不明、せめて「シ＋＋」<br>３はDirectX<br>4 はただのCに見える</p>&mdash; 芳乃さくら (@MaverickTse) <a href="https://twitter.com/MaverickTse/status/896523907573862400">2017年8月13日</a></blockquote>

**Comment by saki7** [comment]
期限になりました。

頂いた意見を総合的に考えた結果、サンプル3つ目の手裏剣アイコンにしたいと思います。コメント頂きありがとうございました ✨ 

改めて色々な条件の下でこのアイコンを表示してみましたが、特に問題はなさそうなので微調整せずにこのまま行こうかと思います。あとは、実際に使うだけなのですが、解決すべき問題がいくつかあります。

### 1. アイコン画像自体のライセンス

cpprefjp と同じ CC-BY ではなく、べつの改変できないライセンスの方が良いように思います (CC-BY-NC-ND とか)。  

（本来は前もって決めておくべきだったと反省してますが、今回に限ってはこのIssueで決まったライセンスに沿った形にすることを僕が保証します）

### 2. アイコン画像データ

基本的には 512x512px の png ファイルを、透過／白背景でそれぞれ1枚、公開しておけば良いと思います。

cpprefjp/image のルートに `/cpprefjp/icon/` というディレクトリを掘ってPRする形で良いでしょうか？

### 3. 実際のデプロイ作業

1. GitHub Organizationその他で使われるプロフィール用アイコンの設定
2. GitHub Pages の favicon の設定

1はpngファイルをそのまま使えば良いと思いますが、プロフィール画像が異常にクロッピングされるサイトもあるので、そういうのがもしあれば、対策は個別でやる方がいいと思います（具体的にはTwitterのアイコンとかGoogle +のアイコンとか）。

2に関しては少し実務上のコストがかかりますが、作業としては、

i) https://realfavicongenerator.net/ を使って、各種モバイルデバイスに対応したアセットファイルを自動生成する 

手作業で各種faviconを生成するのは闇なので、そこそこ認知度のあるこのサービスを使うことを推奨します。（ソースには512pxの透過pngを使用）

ii) GitHub Pages のリポジトリルートに出来上がった各種アセットファイルを配置する （ディレクトリ構造を保たないとダメ）

これはWebの方の鯖缶の方に任せたいと思います。  
僕の方で実際に試してみましたが、特に問題はなさそうです。背景色が必要な場所では `#f5f8fc` あたりを使えばよさそうです。

**Comment by yumetodo** [comment]
>べつの改変できないライセンスの方が良いように思います

と思う根拠を教えていただければと思います。

>CC-BY-NC-ND とか

NCは不要では(商用利用を禁止するだけの適当な理由を見いだせない)

---

NDよりSAを推しておきたい(NDは不自由がすぎるとおもうので)。

**Comment by saki7** [comment]
団体／企業／コミュニティのイメージとなるロゴを、「自由に改変＋再配布・営利利用できるライセンス」で配布している実例を僕は知りません。

CC-BYだと、たとえば誰かが勝手にcpprefjpのロゴを使ったTシャツを作って有料で配ったりした場合に、制限できないと思います。そういう利用可能性を含めて許可するという趣旨であれば、僕はCC-BYにすることに異存はありません。

現実的には、技術的な文脈でcpprefjpのアイコンを使う際は著作権法上の引用の要件をほぼ満たすと思うので、仮にNCにしたとしても、例えば自分の技術系電子書籍でアイコンを使ったとしても問題は起きないと思います。

ライセンスについて僕が考えたことはこんな感じです。

**Comment by yumetodo** [comment]
>CC-BYだと、たとえば誰かが勝手にcpprefjpのロゴを使ったTシャツを作って有料で配ったりした場合に、制限できないと思います。

いっそだれか作ってコミケにでも出してくれないだろうか、絶対買う。
・・・という個人的な欲求はさておき、まあ理解はできるので、個人的には意見保留にします。

**Comment by saki7** [comment]
わかりました。僕としては、 @faithandbrave さんが反対でなければ、CC-BY-NC-NDでいきたいです。

**Comment by faithandbrave** [comment]
ライセンスはそれで行きましょう。ロゴとかアイコンのデザインについては、好きにいじられると印象操作に使われたりもしますしね。
ライセンスの例外扱いは、cpprefjp/imageリポジトリのREADMEに書いておけばよいでしょう。

アイコン画像は、 @saki7 さんはcpprefjp/imageリポジトリへの書き込み権限を持っているので、直接コミットしていただいて大丈夫です。
デプロイ作業は、私の方でやっておきます。そこまでおわったら、このIssueをクローズします。

**Comment by saki7** [comment]
@faithandbrave コミットしました！　デプロイ頼みます！

**Comment by yumetodo** [comment]
@saki7 License書いたものも上げてください！

**Comment by faithandbrave** [comment]
デプロイできました。ひとまず、以下のページには適用されています。
https://cpprefjp.github.io/reference/regex/basic_regex/op_deduction_guide.html

残りは、日時のMarkdown-HTML全変換で適用されます。アイコンを更新する場合は、cpprefjp/site_generatorリポジトリまでお願いします。
私の以下のコミットを参考にしていただければ。
https://github.com/cpprefjp/site_generator/commit/e5be9d53b26d0e21848455dd017f605350d96117

**Comment by faithandbrave** [comment]
ライセンスは、site_generatorの方にも書くついでに、imageリポジトリの方も私の方でやっておきます。

**Comment by faithandbrave** [comment]
ナビゲーションバーにも、アイコンを表示してみました。
https://cpprefjp.github.io/lang/cpp17/type_deduction_for_class_templates.html

32x32のfaviconをそのまま使っていますが、問題あれば教えてください。
https://github.com/cpprefjp/site_generator/commit/b7a0eaf7f95c3c5a4467369b638a9cc4bde1ccb5

問題なさそうなら、日時の変換が確認された時点でこのIssueを閉じます。

**Comment by yumetodo** [comment]
@faithandbrave `site/index.md`にも記載が必要と考えますがどうでしょう？

**Comment by saki7** [comment]
@faithandbrave 確認しました。

ライセンス記載ありがとうございます。生成手順のドキュメント化助かりました。  
ライセンスは僕も `site/index.md` にも記載した方がよいと思います。 (@yumetodo)

---

確認してみたのですが、realfavicongenerator だと、アンチエイリアスがちょっと残念な感じですね。svgのアウトライン化もヤバめです。

なので、自動生成されたマニフェストファイルはそのままで、画像だけ僕が手動で差し替えたいと思います。これは見た目上の些細な修正なので、今後の変更では基本的に realfavicongenerator を使うだけで良いと思います（デザイナが必要と感じたら差し替え）。

**Comment by yumetodo** [comment]
@saki7 @faithandbrave `site/index.md`に追記しました。

**Comment by saki7** [comment]
@yumetodo たすかりました！

**Comment by saki7** [comment]
@faithandbrave 

### オリジナルのアイコン類の色がおかしかったのでコントラストを下げる修正を入れました (image に v1.1として反映済)

お手数ですが、GitHub Organizationのプロフィール画像等をv1.1に差し替えて頂けますか？

### アンチエイリアスがおかしかったので修正PRしました cpprefjp/site_generator#17 

詳しい内容は差分を見てみてください。

### アセットの配置の修正

generatorの方で、`browserconfig.xml` `manifest.json` が `/static/favicons/` 以下に置かれていますが、これらのマニフェストはモバイルデバイスが機械的に見に行くので、 `/` （完全なルート）に置く必要があります。中身の修正はやっておいたので、場所だけルートに移動してください（generatorの仕様がよく分からなかったので……）。

**Comment by faithandbrave** [comment]
GitHub Organizationの画像を差し替えました。(反映には時間がかかります。)

site_generatorでは、staticディレクトリを自動的にそのまま`cpprefjp.github.io`リポジトリにコピーするので、site_generatorのそのあたりの挙動を直し、リポジトリ直下に移動するディレクトリを用意することにします。やっておきます。

**Comment by saki7** [comment]
> GitHub Organizationの画像を差し替えました。(反映には時間がかかります。)

Thanks!

> site_generatorでは、staticディレクトリを自動的にそのままcpprefjp.github.ioリポジトリにコピーするので、site_generatorのそのあたりの挙動を直し、リポジトリ直下に移動するディレクトリを用意することにします。やっておきます。

お願いします。

`favicon.png` という（どこからも参照されていない）ファイルを1個追加したのですが、これはHTMLが読み込まれる前にブラウザがプリフェッチするのを想定してるので、このファイルもルートに移動してもらえると助かります。

---

ちょっと戻りますが。

> ナビゲーションバーにも、アイコンを表示してみました。
> https://cpprefjp.github.io/lang/cpp17/type_deduction_for_class_templates.html
> (by @faithandbrave)

めっちゃいい感じですね。ありがとうございます。

このような用途には、なるべく大きい解像度のpngを使うのがよさそうです。そのため、site_generatorの PR 17 で  `/cpprefjp/static/static/original-icons/` を追加しました。

上記ディレクトリの中身は、実質 `cpprefjp/image` の内容と同じですが、 `cpprefjp` のコンテンツ内でアイコンを参照するために予約する意図があります。ナビゲーションバー以外にも、例えば「画像処理」のようなコンテンツのexampleで画像を使いたい時に、このアイコン画像が使えれば便利だと思います。

```css
.navbar-brand:before {
    content: "";
    float: left;
    display: inline-block;
    overflow: hidden;
    padding-top: 32px;
    background: url(/static/original-icons/cpprefjp-icon-v1.1-transparent.png);
}
```

UI周りで `img` を直置きするのはあまりよくないので、こういう感じのCSSにすればいい感じになると思います。  
（追加で `"cpprefjp - C++日本語リファレンス"` をfloatする必要有）

**Comment by yumetodo** [comment]
>このような用途には、なるべく大きい解像度のpngを使うのがよさそうです。

pngよりはsvg貼りたいという思い。

**Comment by saki7** [comment]
@yumetodo 
svgは描画結果がレンダラー依存なので、あまり信用してないんですよね。  
レンダリング結果がすごく大きかったりすごく小さかったりする場合に崩れやすく、ズーム機能に弱かったりします。

なので、ユーザとしては、svgファイルは「SVG」という形式が必要な場面で使われることを期待します。

**Comment by faithandbrave** [comment]
ルートディレクトリに置くファイルですが、とくに何も気にしなくても、site_generatorの`cpprefjp/static`ディレクトリの直下にファイルを置けば、ルートディレクトリに置かれるようです。(robots.txtがあるところ)

とりあえず、指定された3ファイルは移動しておきました。
https://github.com/cpprefjp/site_generator/commit/6230f0e13f1c2c687072acee647d9a3e238bf155

**Comment by faithandbrave** [comment]
んー。CSSがよくわかっておらず、ナビゲーションバーのアイコンが下にずれてしまうのですよねぇ…。ちょっとこれは @saki7 さんにお願いしたいです。

**Comment by saki7** [comment]
とりあえず、残るタスクはナビゲーションバーのアイコンの調整だけなので、別のIssueに移動します。

これにてこのIssueを閉じたいと思います。関係各位のご協力に感謝します。
