### ISSUE TITLE
検索機能の強化

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site#463]
（このIssueの内容は古いものです。v1に含むものは cpprefjp/crsearch#2 へ移動しました）

---

こういうのがあったら便利じゃないでしょうか。

![image](https://user-images.githubusercontent.com/1901813/29582321-3a256914-87b7-11e7-884c-8d464bb4ecee.png)

## 機能（案）

- [ ] インクリメンタルサーチ
- [ ] AND検索
- [ ] キーボードショートカット（`/` キーでフォーカス）

## 検索対象（案）

- [ ] 標準ライブラリ（識別子名）
- [ ] 標準ライブラリ（マクロ）
- [ ] 標準ライブラリ（ヘッダ名）
- [ ] 標準規格のセクション名（バージョン毎）
  - [ ] C++03
  - [ ] C++11
  - [ ] C++14
  - [ ] C++17
  - [ ] 最新ドラフト
- [ ] cpprefjp内「言語機能」コンテンツのタイトル
- [ ] cpprefjp内「article」コンテンツのタイトル
- [ ] Googleカスタム検索へのフォールバック

## 実装方法

- JavaScript
  - ES2017 で書いて Webpack + Babel でトランスコンパイル
  - jQueryに依存
- CSS
- cpprefjpのインデクサー
- 標準規格のインデクサー
- インデックスデータ (自動生成) (json)
  - site_generator でインデクサーを叩く
  - cpprefjpのGitHubリポジトリでホストする形

APIサーバとかは立てない形で、クライアントサイドのブラウザ内のJavaScriptで完結させるつもりです。

## 実装見積もり

- JavaScript/CSS部分
  - 3週間くらい
- cpprefjpのインデクサー
  - 1週間くらい？
  - `site_generator` か `markdown_to_html` が md を喋れると思うので、簡単なJSONファイルを追加で吐いてもらう
- 標準規格のインデクサー
  - C++でゼロから作って2週間くらい（とりあえず後回し）

---

こういうの欲しくないですか？

**Comment by usagi** [comment]
個人的にはさほど強い要求はありませんが、ウェブサイトのモダンな機能として、また確認すべきキーワードの曖昧な初心者用の機能として有用なので提案の機能追加それ自体は対応可能な方がリソースを使って頂けるのであれば実装して構わないと思います。

心配いらないとは思いますが念のために懸念される注意すべきと思われる点も挙げておきます。以下の懸念に運用として事実上影響しないようであれば作ってみて、PRでレビューを受け、マージしたら良いと思います。

1. この機能の追加実装のために cpprefjp の記事編集コストが上昇しないこと。（インデクサーのためのキーワードを事実上必ず手書きしなければならない、とか）
2. C++で作るアプリケーションのホスト、実行環境、保守のコストが cpprefjp の運用に負担とならないこと。（既存環境以外に保守コストの大きなホストを要求する、とか、C++で作られる意味が薄く相対的に高い保守コストが cpprefjp に要求されることになる、とか、C++で作るが Emscripten による JS 化を前提としており依存ライブラリーが複雑化したりビルドが不安定となる可能性が高い、とか）

なお、キーバインディング `/` については私個人としてはデフォルトONでも構いません。しかし、 cpprefjp はウェブサイトの特性上、多様なユーザーの利用が想定されますから、デフォルトOFFとし、有効にしたいユーザーだけがONにしてCOOKIE保存して使える形態で実装される事が好ましいと推量します。

Vimがどう、Vimiumがどう、Emacsでは云々、そういう玄人ユーザーは選択肢さえあればON/OFFを自分でカスタマイズすれば良い事ですが、 cpprefjp を利用するユーザーのうち電算機の扱い自体にも拙さの残るユーザーにとっては、玄人ユーザーにとってのキーバインディングの便利さも「謎の挙動」で慌てる原因となるだけの事が多いものです。

提案を見た現時点での私からの意見は以上です。

**Comment by saki7** [comment]
@usagi コメントありがとうございます。

JavaScriptの本体は僕が書きます。バックエンドの方（インデクサー）はやってくれる人が居ればお願いしたい所ですが、誰も居なければ僕が `site_generator` のソースコードを読んで自分で実装します。

やりたい人がやればいいと思うので、誰かに作業を強制するつもりはないです。

> 1. この機能の追加実装のために cpprefjp の記事編集コストが上昇しないこと

閲覧や編集に際して追加のコストは一切かからないようにします。今までの編集方法で編集していれば、自動でインデックスされるような形にします。

> 2. C++で作るアプリケーションのホスト、実行環境、保守のコストが cpprefjp の運用に負担とならないこと

この提案でC++で作る可能性があるツールは「標準規格のインデクサー」だと思います。  
これはpdfからセクションヘッダを取ってJSONを吐けばいいだけなので、PythonとかRubyの方が楽だとは思います。ちなみに僕はRubyは書けますがPythonは書けません。JavaScriptでpdfのパーサを書くつもりも無いです。

いまのsite_generatorがPythonで動いている以上、Rubyもコマンド1発で入ると思うので、僕以外の誰かが助けてくれない場合は僕がRubyで書きます。

**Comment by usagi** [comment]
rubyといってもrailsが絡むようなものにはならないはずなので、他にベターな提案、本件へのリソース提供を頂ける方が現れない場合は実行環境（おそらく @melpon さんと確認・調整必要）で対応可能か確認の上で ruby で書いてしまって構わないと思います。C++で書く場合も保守性やライブラリーの性能など合理性が高いのならC++でも構わないとは思います。

-----
私信: この頃 cpprefjp へ意匠設計やユーザビリティー面でたくさんの貢献を頂きありがとうございます。これからもよろしくおねがいいたします。

**Comment by faithandbrave** [comment]
一旦 @melpon に意見をもらいましょう。

**Comment by melpon** [comment]
実装言語については、言語が増えるとビルド手順が増えて手間なので、できれば今使ってる Python で統一したいです。

cpprefjpインデクサーの生成については、結構簡単に作れそうなので、「こういう形式で」って伝えてくれれば自分が site_generator の方に作っておきます。

標準規格のインデクサーの生成については、Python 製の PDF ライブラリはあるっぽいので、それを使って何とかする感じですかね。

あと、最悪トランスパイル済みのデータだけ配置すればいいとはいえ、Webpack+Babel でトランスパイル可能な環境も作った方が良さそうなので、そこも何か考える必要ありますね。
最近ビルド環境やライブラリが大分古くなっててヤバいのと併せて、何とかしておきます（多分 Docker 任せ）。

**Comment by saki7** [comment]
@melpon 

分かりましたー！一緒に頑張りましょう。  
標準規格のインデクサーはとりあえず後回しで。後で考えましょう。

Webpack+Babel は、 `npm` （とV8のビルドに必要なライブラリ類） さえ入ってれば最低限の自動ビルド環境はできると思います。Webpackはv2が欲しいです。

cpprefjp/crsearch というリポジトリを新しく作って僕にwrite渡してもらえますか？  
インデックスのjsonの仕様はWikiにまとめたいと思います。

**Comment by melpon** [comment]
> cpprefjp/crsearch というリポジトリを新しく作って僕にwrite渡してもらえますか？

作りました。
コアチームと @saki7 さんだけ write できる状態のはずです。

> Webpack+Babel は、 npm （とV8のビルドに必要なライブラリ類） さえ入ってれば最低限の自動ビルド環境はできると思います。Webpackはv2が欲しいです。

了解です。
適当に Webpack+Babel でビルド可能な状態でリポジトリに置いといて下さい。
それをこっちでビルドできるように環境を整えます。

**Comment by saki7** [comment]
ひとまずたたき台を書いたので、 cpprefjp/crsearch#1 を立てました。

あとは [WIP] 的なPRを作ってからここのIssueの内容を少しずつ移動していきます。

**Comment by saki7** [comment]
「作る」という合意は取れましたし、めるぽんさんが一緒に作ってくれることになったので、このIssueの目的は果たされたと思います。closeします。

今後の v1 の進捗は、 cpprefjp/crsearch#2 を参照してください。
