### ISSUE TITLE
[proposal]自動リンク切れ検出をCIで

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#466]
現状、
https://github.com/cpprefjp/markdown_to_html
によって、cpprefjp内のリンク切れは自動検出できている。しかし外部サイトについては

https://github.com/cpprefjp/markdown_to_html/blob/8a191aa91feac62b97e568876cedde3976bdccc1/html_attribute.py#L205-L213

より、チェックを行っていない。

しかしリンク切れはよくある話で現に
https://github.com/cpprefjp/site/search?utf8=%E2%9C%93&q=%E3%83%AA%E3%83%B3%E3%82%AF%E5%88%87%E3%82%8C&type=Commits
60件ほどのcommitがリンク切れ修正に費やされている。どう考えても自動検出するべきである。

ここで、リンク切れ検出を`markdown_to_html`でやってしまうとcommiterからはそれを確認できない。そこでリンク切れ検出に特化したscriptを書き、CIサービス上で走らせることを提案する。

具体的にはCommonMark形式およびcpprefjp独自拡張のリンク形式を正規表現で抜き出し、RFC3986に準拠しているかと、実際にGETリクエストを投げてstatus codeが200になるかを調べる処理を全部の`.md`ファイルに対し実行する。

---

ところで

https://github.com/cpprefjp/site/blob/master/editors_doc/specialized.md#リンクの存在チェック

には

> プログラムの修飾でlinkを使用した際に

とあるんですが、

https://github.com/cpprefjp/markdown_to_html/blob/8a191aa91feac62b97e568876cedde3976bdccc1/html_attribute.py#L197

見る感じ、CommonMark形式のリンクでもhtml直書きでもチェックしてますよね・・・？

**Comment by faithandbrave** [comment]
いまは他作業が詰まっているため、しばらく保留します。

**Comment by melpon** [comment]
> ここで、リンク切れ検出をmarkdown_to_htmlでやってしまうとcommiterからはそれを確認できない。そこでリンク切れ検出に特化したscriptを書き、CIサービス上で走らせることを提案する。

自分的には、markdown_to_htmlを実行するのをCIサービス上でやって、そこでリンク切れ等があったらissueにエラーを投げてくれるのが、サーバを維持する必要も無くなって一番楽ができますね。

> 見る感じ、CommonMark形式のリンクでもhtml直書きでもチェックしてますよね・・・？

その通りなので、修正して貰えると。

**Comment by yumetodo** [comment]
@melpon 修正しました。

> markdown_to_htmlを実行するのをCIサービス上でやって

というより site_generatorをCIで動かすんですよね、markdown_to_htmlはそれのsubmoduleなので。

Github Issueにエラー投げますか・・・

**Comment by melpon** [comment]
修正ありがとうございます！

> というより site_generatorをCIで動かすんですよね、markdown_to_htmlはそれのsubmoduleなので。

です。

> Github Issueにエラー投げますか・・・

まあそこは後でも良いですね。最初の方は気になった人が CI サービスのページを見に行けばいいだけなので。
まずはエラーをみんなで共有できる状態になってることが重要だと思います。

**Comment by melpon** [comment]
というかよく考えたら、

> cpprefjp内のリンク切れは自動検出できている。

とあるんですが、今は、毎日の変換でリンク切れのメールが自分に飛んできてる状態です。
こんな感じ。

<img width="687" alt="2017-08-26 18 03 48" src="https://user-images.githubusercontent.com/816539/29740067-1135d28a-8a89-11e7-836e-3720643aa5a7.png">


なので、外部リンクに対するリンク切れをやる前に、今検出してるリンク切れをみんなが見れるようにして直せるようにするプロセスが必要ですね。

**Comment by yumetodo** [comment]
するとGithub Issueへの通知はおいておいてとりあえずCI上からデプロイするようにするべきですかね。

**Comment by melpon** [comment]
ですね。まずそれが出来ると、サーバ管理の問題と、内部リンク切れの問題が解決できそうです。

あとはそこに外部リンク切れをチェックする機能を入れて、GitHub Issueへの通知機能を入れれば完了ですかね。

GitHub への通知に関しては CI で [Commit Status API](https://developer.github.com/v3/repos/statuses/) を使って各コミットにステータスを設定するのでもいいかなと思ったんですけど、外部リンクはコミットとは無関係に消えていくので、どうするか悩ましいところ…。

**Comment by yumetodo** [comment]
というよりそもそもの問題で、今一日一回強制rebuildしてますが、CIに持っていくとそれってできないような・・・。

あれか、`cpprefjp/site`を`cpprefjp/site_generator`のsubmoduleにして、`cpprefjp/site`に紐付けるCIはそのsubmoduleのupdate、`cpprefjp/site_generator`に紐付けるCIでほんちゃんdeployすればいいのか。

**Comment by yumetodo** [comment]
いや、逆か。cpprefjp/site_generatorをcpprefjp/siteのsubmoduleにするべきだな

**Comment by saki7** [comment]
CIの改善が必要不可欠な提案に関しては、CIそのものをオープンにしないと解決できないので、現時点では wontfix とした上で close します。ただし、提案としては有効かつ非常に有意義なので、 invalid のラベルはつけません。

担当者が決まった場合はassignの上でreopenするか、別のIssueとして立て直してください。

**Comment by saki7** [comment]
補足ですが、現時点でCIや変換サーバは全て @melpon が管理しているため、CI周りを大規模に変更する場合は、

1. cpprefjp 全体の合意形成
2. 移行先のCIサービスを熟知している担当者
3. @melpon との緊密な連携

上記の点が少なくとも必要です。

ただ、CI周りの管理が大変なのは事実なので、やる気がある方がいれば是非やっていただきたいと考えています。その場合は、明確な計画が無くてもお気軽にIssueを立てて相談してください。
