### ISSUE TITLE
「RANLUX の乱数列が重複しない」という記述について

### ISSUE THREAD

**Issue by e-kwsm** [cpprefjp/site#468]
[`subtract_with_carry_engine`](../blob/1d0cf2b562fcefe3e379be8ad7d782f066688d26/reference/random/subtract_with_carry_engine.md#%e6%a6%82%e8%a6%81) の
>RANLUX法は、重複のない独立した乱数列を生成することで知られている。

ですが，これは [`ranlux24`](../blob/1d0cf2b562fcefe3e379be8ad7d782f066688d26/reference/random/ranlux24.md#%e6%a6%82%e8%a6%81) にある
>異なるシードのジェネレータ間では、乱数列が重複しない

ということでしょうか．

また，これに関するリファレンスはありますか．

**Comment by faithandbrave** [comment]
意図としてはその通りです。
RANLUXの説明を、どれを見て書いたか忘れてしまったので (どこにも書いてなかった)、調べます。

**Comment by saki7** [comment]
まず、これはRANLUX法に固有のことではないと考えまして、その上で規格を読んでみました。

[rand.eng.sub] には、乱数列の重複とか独立性に関する記述はなさそうです。  
上位の 29.6.3 [rand.eng] にも特にそういう記述は見当たりません。

29.6.3.1 に記述のある requirements を見てみると、以下のような注釈があります。

> [rand.req.eng] Table 104
> E(q) (269)
> 269) This constructor (as well as the subsequent corresponding seed() function) may be particularly useful to applications requiring a large number of independent random sequences.

要するに、別の生成器のインスタンスを受け取るコンストラクタ E(q) を使えば、独立した乱数列を必要とするアプリケーションに有用だよ、ということだと思います。  
なので、このIssueが参照している箇所の記述は、 rand.eng における一般的なヒントを指しているのだと思いますが、執筆時の意図はこのような感じでしょうか？ @faithandbrave 

いずれにせよ、この記述はRANLUX法に固有のことではないと思うので、このページからは削除して、かわりにengine系をまとめる記事に書いておけば良いのではないかと思います。

**Comment by saki7** [comment]
もしこれが僕の勘違いで、RANLUX法に特有の保証などがあるのでしたらおしえてください。

**Comment by faithandbrave** [comment]
いや、違います。
乱数には周期があるため、RANLUX以外の擬似乱数生成器はシードを与えることで乱数列の開始位置をずらすことができます。RANLUXはシードを変えることで開始位置をずらすのではなく乱数列自体が異なります。
これは規格の保証とかの話ではなく、アルゴリズムの特徴の話です。

**Comment by saki7** [comment]
なるほど。となると、 discard_block_engine ([rand.adapt.disc]) の機能として実現している感じでしょうか。

**Comment by faithandbrave** [comment]
なにを読んだのか全く思い出せないのですが、とりあえず以下のスライドに書いてました：

- [Random Numbers - a quick and dirty guide](http://www-pha.physik.hu-berlin.de/seminar/kostrzewa_rng.pdf)

> notion of average distance at sufficient luxury level ensures that different seed values produce truly independent sequences

CERNの以下のページもリンクしておいたほうがよさそうですね。(代わりに昔のページが消えてる気がする)

- [Ranlux - Random number generator](http://luscher.web.cern.ch/luscher/ranlux/)

**Comment by faithandbrave** [comment]
異なるシード (different seed) を与えることで、独立した乱数列 (independent sequence) が生成されることが数学的に照明されている、というのをどこかで見たのですが、ちょっと思い出せないです。
なかなかまとまった時間がとれないので、どなたか調べるのを手伝っていただけると助かります。

これは、私が書いた内容が正しいかの検証のためと、cpprefjpのranluxの解説ページに、参照として記事や論文を貼ることで、ほかの人が情報を追えるようにするためです。

**Comment by e-kwsm** [comment]
[F. James, RANLUX: A Fortran implementation of the high-quality pseudorandom number generator of Lüscher. *Comp. Phys. Commun.* **79**, 111–114 (1994)](https://doi.org/10.1016/0010-4655(94)90233-X) によると

> In order to simplify the choice of luxury, five standard levels are defined:
>* level 0 (*p* = 24): equivalent to the original RCARRY of Marsaglia and Zaman, very long period, but fails many tests.
>* level 1 (*p* = 48): considerable improvement in quality over level 0, now passes the gap test, but still fails spectral test.
> * level 2 (*p* = 97): passes all known tests, but theoretically still defective.
> * level 3 (*p* = 223): DEFAULT VALUE. Any theoretically possible correlations have a very small chance of being observed.
> * level 4 (*p* = 389): highest possible luxury, all 24 bits of mantissa are chaotic.
>
> Both the initialization and the setting of the luxury level are performed with:
> `CALL RLUXGO (LUX INT Ki K2)`
> which initializes the generator from one positive integer INT (略) The 32-bit integer INT is used internally to initialize a multiplicative congruential generator which in turn initializes all the 24 seeds inside RANLUX. This means that two values of INT which differ by only one bit will cause totally different initialization of RANLUX, and each of the 2<sup>31</sup> different values of INT gives rise to an independent sequence which will generate on average about 10<sup>160</sup> numbers before overlapping any sequence produced by any other value of INT.

10<sup>160</sup> 個以上の数を生成すると重複が生じるとあります．

ただ，以下が分かりません:
* どの level なのか
  level 1 はスペクトル検定等には落ちるが異なるシードの乱数列は独立ということ？
* Fortran 実装との差異
  [`ranlux24_base`](https://github.com/cpprefjp/site/blob/master/reference/random/ranlux24_base.md) が使う整数は少なくとも 32 ビットだが，[`ranlux48_base`](https://github.com/cpprefjp/site/blob/master/reference/random/ranlux48_base.md) は少なくとも 64 ビット

また，[Random Numbers - a quick and dirty guide](http://www-pha.physik.hu-berlin.de/seminar/kostrzewa_rng.pdf) の <q>at sufficient luxury level</q> が具体的にどのレヴェルを指しているのか，何ビットの整数を想定しているか不明です．

**Comment by faithandbrave** [comment]
メモ程度ですが。

- [The RANLUX pseudorandom number generator implemented in OpenCL](https://community.amd.com/thread/139236)
- [RANLUXCL / ranluxcl.clのドキュメンテーションコメント](https://bitbucket.org/ivarun/ranluxcl/src/d1655c031f922c16206bfd3d9ce8ff91eab0d3d0/ranluxcl.cl?at=default&fileviewer=file-view-default)

**Comment by faithandbrave** [comment]
> RANLUX is based on chaos theory, and what we are actually doing when selecting a luxury value is setting how many values to skip over (causing decorrelation).

> RANLUXはカオス理論にもとづいており、贅沢さレベルの選択で実際に行うことは、より多くの値をスキップすることである (それによって非相関を引き起こす)。

**Comment by faithandbrave** [comment]
- [V115 Uniform Random Numbers of Guaranteed Quality](http://cmd.inp.nsk.su/old/cmd2/manuals/cernlib/shortwrups/node244.html)

CERNのページはこちらに移動していました。
このページの贅沢さレベルの表を見ると、レベル3では非常に小さな確率で相関が発生し、レベル4では完全に非相関になる、というふうに読めます。

**Comment by faithandbrave** [comment]
> level 3 (p = 223): DEFAULT VALUE. Any theoretically possible correlations have a very small chance of being observed.
> level 4 (p = 389): highest possible luxury, all 24 bits of mantissa are chaotic.

10<sup>160</sup> 個以上の数を生成すると重複が生じる、というのは、文章を読む限りでは、レベル3について言っているように思います。
レベル3の場合に非常に小さな確率で相関が発生し、レベル4では発生しない、ということではないでしょうか。
レベル3をデフォルトと言っていることで、後の説明がそれを基本としているように読めます。

**Comment by e-kwsm** [comment]
> [F. James, RANLUX: A Fortran implementation of the high-quality pseudorandom number generator of Lüscher. *Comp. Phys. Commun.* **79**, 111–114 (1994)](https://doi.org/10.1016/0010-4655(94)90233-X) によると

リダイレクトがうまくいかないので
* [ScienceDirect](http://www.sciencedirect.com/science/article/pii/001046559490233X)
* [arXiv:hep-lat/9309020 <q>A Portable High-Quality Random Number Generator for Lattice Field Theory Simulations</q>](https://arxiv.org/abs/hep-lat/9309020)

---

>10<sup>160</sup> 個以上の数を生成すると重複が生じる、というのは、文章を読む限りでは、レベル3について言っているように思います。
レベル3の場合に非常に小さな確率で相関が発生し、レベル4では発生しない、ということではないでしょうか。
レベル3をデフォルトと言っていることで、後の説明がそれを基本としているように読めます。

レベル 3 は実装上のデフォルトというだけです．

> The 32-bit integer INT is used internally to initialize a multiplicative congruential generator which in turn initializes all the 24 seeds inside RANLUX. This means that two values of INT which differ by only one bit will cause totally different initialization of RANLUX

異なるシードによって異なる状態で初期化されるというのはレベルに依りませんし，「レベル 3 においては」のような文句がないためそのように断定することはできないと思います (導出が丁寧であればフォローできるのですが)．

---

RANLUX の 欠陥を指摘している論文もあり，[M. Matsumoto, et al., Common Defects in Initialization of Pseudorandom Number Generators, *ACM Trans. Model. Comput. Simul.* **17**, Article No. 15 (2007)](https://doi.org/10.1145/1276927.1276928) によると

> In the standard implementation by James [1994], *r* is 199 by default, and the largest value that the user can choose is 365. These values are claimed to assure no correlation, using a discussion based on chaos theory [Luscher 1994]. However, Figure 3 shows obvious correlations even after skipping 199 words. This implies that Luscher [1994] misused chaos theory: He neglected the nearly affine property of the transition function of SWB (註: subtract-with-borrow). Actually, it turns out that for every fixed *n* < 48, the *n*th output of the default `ranlux` (註: [GSL](http://www.gnu.org/software/gsl/) version 1.6) is a nearly affine function of *s* with defect ratio < 1/2. Thus, similar phenomena are observed for such *n* whenever *s* changes linearly. This dependence fades away for *n* ≥ 48, so ranlux has a transient nearly affine dependence.

実際に以下のコード

```cpp
#include <iostream>
#include <random>

using namespace std;

//! print n-th output of PRNG for seeds s = 1, 2,..., 100
template<typename PRNG> void matsumoto2007(unsigned n)
{
    for (unsigned s = 0; s <= 100; s++)
    {
        PRNG r{s};
        r.discard(n - 1);
        cout << s << '\t' << r() << '\n';
    }
}

int main()
{
    matsumoto2007<ranlux24>(41);
    return 0;
}
```

で検証すると，[`ranlux_24`](https://github.com/cpprefjp/site/blob/master/reference/random/ranlux24.md) が 41 番目に生成する乱数には相関 (nearly affine dependence: *x_n* = *a_n* *s* + *c_n* + (small error) mod *M*) があります:

![ranlux24](https://user-images.githubusercontent.com/11627708/30057844-75ebfa64-9273-11e7-8d02-c0fd22174145.png)

レベル 4 ([`ranlux48`](https://github.com/cpprefjp/site/blob/master/reference/random/ranlux48.md)) でも [`ranlux48_base`](https://github.com/cpprefjp/site/blob/master/reference/random/ranlux48_base.md) の乱数を捨てる前 (*n* ≤ 11) はこの相関があります．

**Comment by faithandbrave** [comment]
なるほど、調査ありがとうございます。
cpprefjpとしては、RANLUX推しをしたいわけでもないので、より正確な特徴の説明と、ほかの擬似乱数生成器とのトレードオフ、可能であれば問題点とその対策が示せればよいですね。

- 相関がないのではなく、相関が低いこと
- トレードオフは現状の速度と、品質(特徴)の説明でよいと思う
- N番目からM個の乱数を捨てることで相関をより低くできる、というワークアラウンド

この3つくらいが示せればよいでしょうか。
