### ISSUE TITLE
reference/concepts という構造は適切か

### ISSUE THREAD

**Issue by e-kwsm** [cpprefjp/site#469]
#467

* C++17 時点で concepts は規格に入っていません
* 規格では `Callable` などは <q>requirement</q> であり，[解説ページ](https://github.com/cpprefjp/site/blob/54ad673e06e2202af4ca644546864d5b57a49abf/reference/concepts/Callable.md#%E6%A6%82%E8%A6%81)でも「要件」とされています．
  `concepts` 下ではなく `requirement` 下に置く方が適切です．
* 現在 [`/reference`](https://github.com/cpprefjp/site/tree/535b4a14982ebdd74173477078853a0dc62e3c0a/reference) 下にあるのは concepts を除いてヘッダです．この構造は混乱を招きます．
https://cpprefjp.github.io の左ペインでもヘッダと非ヘッダは区別されていません:
![サイト左ペイン](https://user-images.githubusercontent.com/11627708/29896179-e2d78442-8e16-11e7-9851-77059a255116.png)
なので，以下を提案します:
     1. `concepts` 以外を新設した `/header` に移す (`concepts` を `requirement` にリネームする)
     2. `concepts` を `/lang`  (`/lang/requirement`) に移す
     3. `concepts/*` を新設した `/requirement` に移す

  もしこの構造を維持するのであれば，サイトの左ペインで `<stdexcept>` のように表示する必要があると考えます．
* タイトルで `std::Callable` とすべきではないと思います．

**Comment by faithandbrave** [comment]
現在の構造は、将来との互換性のためにそうしています。

たとえば現在あるコンセプトのリファレンスを`/lang/requirement`に移動したとして (要件はライブラリのためにあるので言語の下に置く構造は間違いですが)、将来ライブラリ機能としてのコンセプトが入った時に、説明のためにあった便宜上の機能としてあった`/lang/requirement`を`/reference/concepts`に移動したとします。
そのときに発生するのは、外部サイトからのリンク切れです。私は、ゴミが残るという点において、リダイレクトという手法には極力頼りたくありません。
現在の`/reference/concepts`は、N2800 (C++11 CD) 時点での構造を元にしています。コンセプトが言語機能としてどのようなものになるにしても、ライブラリとしてはそのヘッダに入る可能性が高いとみてそうしています。
もちろん可能性問題ですので、`/reference/concepts`には実際にはならず、やむなく移動する必要があるかもしれません。
ですが、ほかの構造にしたときには可能性として必ず発生する問題になります。

ファイル名の変更、ディレクトリの移動などは、やむを得ず発生する以外は、極力減らしたいです。
`/reference/concepts`以下を説明によって混乱の程度を下げるのならばよいと思います。 @e-kwsm さんの言う「読者の混乱」には、「間違った使用によってバグが発生する」というようなものは含みません。ないものは使えませんし、現状`/reference/concepts`の下にあるものも、C++11に入る予定で入らなかったコンセプト機能の構文ではなく自然言語で書いてあるため、それをライブラリ機能として使おうと思っても言語機能を使用した定義がないために使えません。

**Comment by saki7** [comment]
説明のために、例として cppreference を挙げます。  
cppreference では、コンセプト関係のディレクトリ（ページ）は2つあります。

1つ目は、 [/cpp/concept](http://en.cppreference.com/w/cpp/concept) です。  
ここでは、要件としてのコンセプトの説明と、個別のコンセプトのリファレンスが含まれています。

2つ目は、 [/cpp/language/constraints](http://en.cppreference.com/w/cpp/language/constraints) です。  
ここでは、コンセプトを将来の言語仕様の一部として解説しています。

Callable などの個別の説明は `/w/cpp/concept/*` 以下に入っています。

cppreference では、ヘッダ類のページはそもそも `/w/cpp/header/*` 以下に配置されています。そしてここではヘッダの概要が羅列されているだけで、解説ページとしての中身はほとんどありません。

---

cppreference の例を踏まえて、僕の意見を書きます。

> 現在 /reference 下にあるのは concepts を除いてヘッダです．この構造は混乱を招きます．

いまの cpprefjp の「リファレンス」カテゴリは、単なるヘッダの羅列ではないです。解説ページとしての中身があります。

要するに、 今のcpprefjpの `/reference/何かのヘッダ/何かのクラス` という構造は、 cppreference でいうところの `/w/cpp/何かのヘッダ/何かのクラス` という構造と何ら変わらないと思います。

僕は、この構造で  `/reference/concepts/Callable.html` というようなページが含まれている現状に何も違和感を感じません。

似たディレクトリ構造の cppreference のような巨大なサイトで混乱が招かれていないのに、cpprefjpで問題が起こりますか？

そもそも、 @e-kwsm さんが仰るような「読者の混乱」のようなものが起きたとして、現実にどれだけ大きな問題が起こりますか？　それは、今議論をする必要性や緊急度があるものでしょうか？

ここ最近の cpprefjp のコンセプト周りの議論はあまりに不毛と言わざるをえません。  
僕は、現実に何も問題が起きておらず、コンセプト周りのページに本腰を入れて作ろうとしている担当者も不在の状況で議論する必要性を感じません。これは、 @faithandbrave さんも繰り返し言ってきたことです。

**Comment by faithandbrave** [comment]
> タイトルで std::Callable とすべきではないと思います．

これはミスなので、見つけたら適時直してください。

**Comment by faithandbrave** [comment]
すいません、追加情報ですが、C++の現在の仕様は、C++11 Committee draftのN2800のときに入ったコンセプトを単にrevertするのではなく、それを自然言語に変換するようにして仕様が作られています。
ですので、用語としてコンセプトを使っていないだけで、コンセプトではあります。

**Comment by faithandbrave** [comment]
それと、コンセプト以外を`/reference`から`/header`に移す案ですが、これは外部サイトからのリンクがほぼ全滅してしまうので、もうできないです。
cpprefjpは元々、標準ライブラリのリファレンスとして作ったものに、多方面からの強い要望を受けて言語機能の解説を加えたものです。そのため、それを想定していない作りとして`/reference`階層があります。
`/lib`階層とかにしたいのはやまやまですが、さすがにユーザーを無視した大規模なリンク切れはできないので、これは本サイトの運営者として許可できません。

**Comment by e-kwsm** [comment]
[/reference/container_concepts.md](https://github.com/cpprefjp/site/blob/caf3388dd5d702d7b4a26347a10bd15980a29546/reference/container_concepts.md) と同様に [/reference/concepts.md](https://github.com/cpprefjp/site/blob/d1ebe5c21732582ad50892edcb048053c9ca7488/reference/concepts.md) で「ライブラリとして提供されている機能ではない」と断ることで私が懸念する事態は避けられると思います．

>それと、コンセプト以外を<code>/reference</code>から<code>/header</code>に移す案ですが、これは外部サイトからのリンクがほぼ全滅してしまうので、もうできないです。
cpprefjpは元々、標準ライブラリのリファレンスとして作ったものに、多方面からの強い要望を受けて言語機能の解説を加えたものです。そのため、それを想定していない作りとして<code>/reference</code>階層があります。
<code>/lib</code>階層とかにしたいのはやまやまですが、さすがにユーザーを無視した大規模なリンク切れはできないので、これは本サイトの運営者として許可できません。

分かりました．
