### ISSUE TITLE
サイドバーのツリー表示内の特別なページをまとめてソートしたい

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site#472]
cpprefjpの画面左のツリー表示内で、特別な関数や仕様についてのページをまとめてソートしたいです。今は [おそらく不定の順序](https://github.com/cpprefjp/site_generator/blob/d1478183888c68a3639fcaa2e5c4912f3aaaae16/cpprefjp/templates/content.html#L13) でソートされているので、探すときに少し苦労します。

![image](https://user-images.githubusercontent.com/1901813/32007070-75bbd176-b9e3-11e7-9d62-c78b4ba22048.png)

---

特別なページというのは、メンバ関数・マクロ・フリー関数等に該当しない規格上の仕様を説明しているページです。例えば以下のようなものがあります：

- [array::初期化](https://cpprefjp.github.io/reference/array/op_initializer.html)
- [bitset::コンストラクタ](https://cpprefjp.github.io/reference/bitset/op_constructor.html)
- [array::推論補助](https://cpprefjp.github.io/reference/array/op_deduction_guide.html)
- [atomic/ロックフリープロパティ](https://cpprefjp.github.io/reference/atomic/lock_free_property.html)

※コンストラクタは一応メンバ関数ですが、あえて含めています

ルールとしては、

- 案１：タイトルに半角カッコを付ける (e.g. `推論補助` → `(推論補助)` )
- 案２： cpprefjp/markdown_to_html が [認識する新しいタグ](https://github.com/cpprefjp/site_generator/blob/6c9fe56990c8e1a5e93a480067f52fe5947da625/run.py#L178) を作る (e.g. `* function[meta special]`)

を考えています。

作業内容としては、いったん全ての特別なページを変更して回る作業が必要で、これは僕がやります。漏れがあった場合は気づいた方がその都度直して頂ければと思います。

cc: @cpprefjp/coreteam 

refs: cpprefjp/crsearch#14

**Comment by faithandbrave** [comment]
コンストラクタ、デストラクタ、推論補助とかは、ツリー状の順番は決まっていますね。site_generatorの以下のコードを参照してください。
順序を規定しているもの以外 (初期化) とかは、ページ名で昇順になっているかと思います。
https://github.com/cpprefjp/site_generator/blob/master/settings/cpprefjp.py#L75

ページの見出しとして「vector::コンストラクタ」のように表示されるのが気持ち悪いということであれば、「vector::(コンストラクタ)」に直すのは、やってもらって大丈夫です。

`<ratio>`のSI接頭辞とかもそうですね。
https://cpprefjp.github.io/reference/ratio/si_prefix.html

**Comment by saki7** [comment]
@faithandbrave 

なるほど。 `初期化` についてはこのリストで頭に持って来れば大丈夫だと思うのですが、 `ロックフリープロパティ` のようなページも頭に来て欲しいです。これをsite_generatorでハードコードするのは闇だと思うので、その解決策として案２はどうでしょうか。

見た目については、下のようなものを考えてます（微妙に色がついてるのは適当）。

![image](https://user-images.githubusercontent.com/1901813/32009060-e555e620-b9e8-11e7-93aa-b5eb90031174.png)

**Comment by faithandbrave** [comment]
案2でいいと思います。見た目について、こだわりがとくにないという理由で、それで異論ないです。

**Comment by saki7** [comment]
わかりました。とりあえず実装してPR投げます 🍰
