### ISSUE TITLE
サンプルコードの拡張記法を導入したい

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site#473]
今日から、cpprefjp上でサンプルコードを実行可能になりました。既に試して頂いた方もいるかと思います。 （フロントエンド周りの変更は [cpprefjp/kunai](https://github.com/cpprefjp/kunai) と [cpprefjp/site_generator](https://github.com/cpprefjp/site_generator) の範囲になります）

今のcpprefjpでは、サンプルコードはMarkdownのコードブロックでそのまま書かれています。

``````markdown
```cpp
int a = 42;
```
``````

これは書きやすい一方、cpprefjpには“サンプルコード”以外のコードスニペットも多く含まれています。

今は、「このコードがサンプルコードかどうか」を判断するために、バックエンド (cpprefjp/site_generator) や フロントエンド (cpprefjp/kunai) ではすごく泥臭い方法で頑張って解析しています。

フロントエンドでは大体のページに対応できていますが、 article/ 以下の記事など どうしても判断できないコードスニペットもあって対応に苦慮しています。

そこで、「サンプルコード」を書く場合にコードブロックの先頭を以下のように書く記法を cpprefjp/site 全体に導入することを提案します。

``````markdown
```cpp example
int a = 42;
std::string s = "ほげほげ";
```
``````

11/10（金）まで意見を募集します。問題がなければ、編集者向けドキュメントなどを整備する形になります。

---

経緯： https://github.com/cpprefjp/site_generator/issues/30#issuecomment-341319188

refs: cpprefjp/site_generator#30
cc: @cpprefjp/coreteam @cpprefjp/workingteam

**Comment by saki7** [comment]
これは CommonMark に準拠した記法になるので、 `cpp example` を認識できないパーサは `cpp` にフォールバックできます。つまり、書き忘れても今までと同じ表示になるので大丈夫です。

**Comment by take-cheeze** [comment]
おお！すばらしいですね！
サンプルコードをパッと実行できるのいいですねー。
ちょっとどこに書けばいいのかアレですが、compileボタンがあるのなら、エディタを開かずにcompileボタンを押すとエディタを開いて実行していただけると出力確認しつつできていいかなーと思いました。

**Comment by faithandbrave** [comment]
`cpp example`を書く場所ですが、基本的には「インクルードとmain関数を含む完全なコードのコードブロック」に対して付けます。
例外は、翻訳単位のようなものの説明のために、コードが分割されているようなケースです。

pthreadライブラリのような環境依存のライブラリを使用しているコードであっても、`cpp example`にしてもらって大丈夫です。

**Comment by saki7** [comment]
@take-cheeze 記事に書いてある出力結果は一応エディタの下に残してあるのですが、この結果と出力を比較するときに見づらいということでしょうか？　詳しく教えて頂けますとありがたいです

**Comment by take-cheeze** [comment]
@saki7 とりあえず実行ボタンが既にあるなら押してみたいって心理なだけです。

**Comment by saki7** [comment]
@take-cheeze 今だと フロントエンドが on/off 切り替え（一番左のボタン） で on になっていないと Compile 押せないようになっているので、そのあたりが分かりづらいのかもしれません

**Comment by yumetodo** [comment]
@saki7 確かに`Try Code`を押さないと`Compile`が押せないですね・・・。そもそも`Try Code`を押すまで`Compile`を`Display: none;`にできないですかね？

**Comment by saki7** [comment]
このIssueでフロントエンドについて議論するのはよくないので、フロントエンドについて踏み込んだ内容があれば [cpprefjp/kunai](https://github.com/cpprefjp/kunai) に お願いします。

**Comment by saki7** [comment]
Note: 意見募集は今日までです

**Comment by saki7** [comment]
:art: :joy: :joy: :eagle: :factory: :factory:
