### ISSUE TITLE
[FYI] saki7さんに管理者権限をお渡ししました

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#474]
アナウンスです。
saki7 さんに、cpprefjpとboostjpの管理者権限をお渡ししました。
彼には最近、Webのフロントエンド周りでいろいろと作業をお願いし、精力的に活動されています、サーバー・フロントエンド関係の一通りのツールリポジトリへの書き込み権限や、新規リポジトリを作る権限があったほうが動きやすいだろう、という判断により管理者権限をお渡しすることになりました。

新しいことをする際にIssueで合意を得る必要があるのは、Working Teamの方々と変わりません。
みなさん、今後ともよろしくお願いします。

このIssueは数日したら閉じます。

**Comment by saki7** [comment]
よろしくお願いします :space_invader: :sparkles: :joy: :ok_man: :art: :art: :art:
