### ISSUE TITLE
サイドバーのバグ潰しへの協力のお願い

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site#476]
文責： @cpprefjp/design 
cc: @cpprefjp/workingteam

今日からサイドバーを新しくしました。編集者の皆さんは、バグや怪しい挙動を見つけた際に [cpprefjp/kunai](https://github.com/cpprefjp/kunai) まで報告をお願いします。

Issueを立てる際には、 Projects の指定を、このIssueと同じ「[Sidebar v2](https://github.com/orgs/cpprefjp/projects/1)」に指定してください。既知の問題などはプロジェクトページで管理しているので、報告する際の参考にしてください。

問題が起きた時のために、画面左上 `Legacy sidebar [x]`  のチェックを入れると以前の表示に戻るようにしてあります。大きな問題が解消したら、以前のサイドバーへのフォールバックを取り除きます。その時点で完了とします。

## Sidebar v1

- 単純なツリー構造なので、上下方向に無限に長くなることが避けられない
- 全て静的なHTMLとして生成して埋め込んでいたため、cpprefjp内の全てのページが500KBほどあった
- 上記の理由によりHTMLをminifyせざるをえず、site_generatorの再変換が4時間以上かかっていた

## Sidebar v2

- ツリー構造をやめた
- crsearch.json のデータをそのまま利用
- HTMLに埋め込まないため、ページが500KB→30KB

---

@cpprefjp/design: Sidebar v2に上がったIssueのトリアージをお願いします。

**Comment by saki7** [comment]
見た目けっこうひどかったので cpprefjp/kunai@df0caf9e37666de79d7207a00da92e2ae463768d  で軽く直しました、ついでにスマホも直したのでPCとスマホどちらでも綺麗に見れると思います

![screenshot_20171107-091859](https://user-images.githubusercontent.com/1901813/32470769-3628adf4-c39d-11e7-80e8-e99d57dc56ec.png)

**Comment by faithandbrave** [comment]
バグレポではない報告です。
iPhone 7のiOS 10のSafariブラウザ環境で、サイドバーのみが表示されメインコンテンツが表示されない問題がありました。iOS 11に上げたら直りました。

それと、バグ報告先はcpprefjp/kunai、と書かれていますが、プロジェクトはなぜかcpprefjp/site側にあるようです。報告先がちょっと曖昧になっている気がします。 @usagi さんがこちらのリポジトリに報告したのもそのせいかな、と。

**Comment by saki7** [comment]
@faithandbrave iOS 10以前のWebkitの問題だと思います。flex周りでwebkitのベンダープレフィックスをつける変更で包括的に直ると思うので、対応します。

GitHubのProjectは、リポジトリ単位と組織単位の2つあって、Sidebar v2は組織単位で作っています。このProjectを作る前に実験してみたのですが、リポジトリ単位で作ってしまうと別のリポジトリのIssueを全く参照できないようなので、こうなっています。

**Comment by faithandbrave** [comment]
あ、Organization GroupごとにProjectsを設定できましたね。忘却の彼方でした。失礼しました。

**Comment by saki7** [comment]
めちゃくちゃ重かった問題を cpprefjp/kunai#35 で完全解決したのでこれで致命的な問題は（IE11の表示崩れ）以外なくなったと思います

IE11の件はちょっと僕の手に負えないので誰か助けてください。僕の家にIE11を常時起動できるWindowsマシンが無いので、検証自体ができません。今まではブラウザスクリーンショットを取ってくれるサービスを使ってたんですが流石にこれだと限界があります。

**Comment by saki7** [comment]
あと、Twitterなどで「cpprefjpの新しいデザインが見づらい」という意見が上がっていることは把握しているのですが、具体的にどこがどういう風に見づらいのか僕は分かっていません（設計したのが僕なので）。

見づらいという意見を言っている方々にFF外から失礼するわけにはいかないので、僕はFF外から失礼はしませんし、ここのMemberの方々もそういうことはやらないようにお願いしたいのですが、その一方でやはり具体的に見づらい所がどこかという点は知りたいです。

cpprefp/kunai#35 の遅延評価のついでに実装したツリー展開機能でだいたいの見づらさは解消したと思うのですが、これでもまだ致命的に見づらいと感じる方がもしここを見ていましたら、なるべく詳しく詳細を教えてください。対応します。

**Comment by faithandbrave** [comment]
直接報告しないぼやきは意見として拾わなくていいと思いますが、サイドバーについて個人的に思うのは以下です：

- 展開したところのスクロールで誤操作が起こりやすい
    - 内部スクロールのしすぎでページ全体がスクロールしてしまうのは、操作としてイライラの感情が起こりやすい。ここは、元々のツリーUIに対するディスアドバンテージかな、と思います。
- リファレンス以外も全て、デフォルトで畳んでほしい
    - とくに編集者向けドキュメントは、HTMLページで読むことを想定しておらず、Markdownの書き方を調べるためのものです。展開してあるのは意図ととしてちょっと困ります。
- Wandboxでコード実行する部分は、コード例の上部にあるバーが大きくて主張しすぎかな、という気はしています。

ほか、アイコン類も含めて、とくに不満はないです。

**Comment by faithandbrave** [comment]
UIについては、慣れたものから慣れないものへの移行、ずっと使っていたものから新しいものへの移行で、ある程度、思い出補正によって前のほうがよかった、という意見はどのサイトでも起こることです。
「使いにくい」という直接の意見があれば具体的に聞いて解決してよいと思いますが、見た目が気に食わない程度であれば思い出補正である場合があるので、慣れれば不満がでなくなる部分は多くあるでしょう。

**Comment by saki7** [comment]
> - 展開したところのスクロールで誤操作が起こりやすい
>   内部スクロールのしすぎでページ全体がスクロールしてしまうのは、操作としてイライラの感情が起こりやすい。ここは、元々のツリーUIに対するディスアドバンテージかな、と思います。

ああ、これは非常に分かります。ただ、これを防ぐためにはブラウザのウィンドウレベルでグローバルなスクロールキャンセル処理を入れるしかなくて、この方法はWebサイトの実装としてあまりお行儀がよくないので悩んでいます。

これのもう1つの解決法はサイドバー全体を常時左側にposition: fixedで固定することですが、これはサイト自体のコンセプトとしてそういう「左側のサイドバーは常に固定！絶対出ているべき！」という風に主張が激しくなるので、この仕様を採用するとしたらこれは合意形成が必要なレベルな気がしています。

> - リファレンス以外も全て、デフォルトで畳んでほしい

これは実装としては結構手間がかかるのですが、僕もそのうち直そうと思っていたので直したらデプロイします

> - Wandboxでコード実行する部分は、コード例の上部にあるバーが大きくて主張しすぎかな、という気はしています。

分かりました。これは調整します

---

> IE11の件は、ぼくもWindows環境が職場にも家にもないので、いまのところはお手伝いできません。報告者の @usagi さんに検証に付き合っていただくか、もしくはほかの協力者が現れない限りは、Issueとして残しておいて対応は保留にするしかないのではないかと思います。

分かりました。

> UIについては、慣れたものから慣れないものへの移行、ずっと使っていたものから新しいものへの移行で、ある程度、思い出補正によって前のほうがよかった、という意見はどのサイトでも起こることです。
> 「使いにくい」という直接の意見があれば具体的に聞いて解決してよいと思いますが、見た目が気に食わない程度であれば思い出補正である場合があるので、慣れれば不満がでなくなる部分は多くあるでしょう。

そういうことであれば良いんですが、そうではなくデザインとして悪いせいで見づらいという結論が出てしまうと僕としては悲しいですね……

**Comment by saki7** [comment]
ところで、ツリービューが見づらい件は色々試して遊んでいたらそこそこ良さそうな物が出来たので試しに本番に投入しました。これはこれで人によっては嫌いな人もいる類のUIだとは思うんですが、前と比べるとこっちの方がいい気がしてます

cpprefjp/kunai#36

![peek 2017-11-10 01-47](https://user-images.githubusercontent.com/1901813/32618317-b575fa70-c5ba-11e7-8be6-363923269941.gif)

**Comment by faithandbrave** [comment]
いろいろ対応ありがとうございます。
一点気になったのは、スクロールバーが出ているときに、折りたたみ・展開機能が使えないことですね。いまのところ対応策はノーアイデアで申し訳ないですが・・・。

**Comment by yumetodo** [comment]
ツリー展開機能に一つ不満があるとすれば、ツリー展開してスクロール中に項目名が表示し続けてくれるのはいいんですが、スクロールして閉じると、ツリー展開せずにスクロールしたのと同じところまでスクロールされてしまうことでしょうか・・・

| 閉じる前 | 閉じた後 |
|-----------|----------|
| ![image](https://user-images.githubusercontent.com/10869046/32637529-a512ef9c-c5fd-11e7-98f5-5d25fadb43d1.png) | ![image](https://user-images.githubusercontent.com/10869046/32637532-a728dd46-c5fd-11e7-86b7-7715cb464211.png) |

**Comment by saki7** [comment]
@faithandbrave:

> 一点気になったのは、スクロールバーが出ているときに、折りたたみ・展開機能が使えないことですね。いまのところ対応策はノーアイデアで申し訳ないですが・・・。

これを解決するためにはやはりこれをやるしかないですね

>> これのもう1つの解決法はサイドバー全体を常時左側にposition: fixedで固定することですが、これはサイト自体のコンセプトとしてそういう「左側のサイドバーは常に固定！絶対出ているべき！」という風に主張が激しくなるので、この仕様を採用するとしたらこれは合意形成が必要なレベルな気がしています。 (@saki7)

---

@yumetodo:

> ツリー展開機能に一つ不満があるとすれば、ツリー展開してスクロール中に項目名が表示し続けてくれるのはいいんですが、スクロールして閉じると、ツリー展開せずにスクロールしたのと同じところまでスクロールされてしまうことでしょうか・・・

直します。ただ、expected behaviorを定義するのが難しいです。気持ち良いスクロールを実現できるためのコーナーケースの条件分岐を定義するのが結構難しい

**Comment by faithandbrave** [comment]
サイドバーを左固定にしていないのは、以下のIssueによるものなので、 @melpon と相談して決めていただければ。
https://github.com/cpprefjp/site/issues/242

**Comment by saki7** [comment]
@faithandbrave なるほど。こういう理由でしたか。元々左固定だったとのことで、その時点で不満が出ていなくて、幅が可変になった時にレイアウトの問題があったということですね。

それなら、これはCSSのメディアクエリとFlexboxのflex-directionの切り替え1発でしっかり調整できるので、いっそのことサイトのコンセプトレベルでサイドバーを左固定にしようと思います。

**Comment by saki7** [comment]
まだサイドバーは固定にしてないですが、レスポンシブ周りをかっちり作り直しました

これがうまくはまればIE11もついでに直るんじゃないかと思ってますが……どうなんですかね？

![peek 2017-11-10 19-10](https://user-images.githubusercontent.com/1901813/32653349-f74f5cb2-c64a-11e7-8ea1-17673cecdf72.gif)

**Comment by saki7** [comment]
一応このIssueのマイルストーンでは明後日で完全移行ということにしていますが、IE11の件以外で何か致命的な問題があったら教えてください。なければ明後日の時点でレガシーサイドバーは完全に見れなくなります！！

**Comment by k-satoda** [comment]
新しいのを少し触ってみて「・・・あれ？」と気になって Legacy sidebar と
比べて見たところで、前のほうが良かったっぽいところを
cpprefjp/kunai#43, cpprefjp/kunai#44 に書いときした。

・・・でも Project の設定は見当たらなかったです。・・・と書いてる間に
@saki7 さんに設定してもらえたようで、ありがとうございます。
（なんか権限が要るのかな？）

**Comment by saki7** [comment]
@k-satoda 提案ありがとうございます。

Projectのページ https://github.com/orgs/cpprefjp/projects/1 を閲覧すること自体はできますか？ GitHubのヘルプによると、MemberであればProjectのRead/Writeが自動でつくと書いてあるのですが、何か設定をミスってるかもしれないです。

**Comment by k-satoda** [comment]
@saki7 はい Project のページは見えてます。
site 側の既存 Issue を開くと "Project" の右側に歯車があってそこから変更できそうなんですが、
kunai のほうには歯車が見えないです。

"project maintainer" の権限が要る模様（？）。
https://help.github.com/articles/creating-an-issue/
> If. you're a project maintainer, you can assign the issue to someone, add it to a project board, associate it with a milestone, or apply a label.

kunai のほうは開発に関われるほどの知識は無いので、 "maintainer" というような権限は無い状態で妥当なようにも思います。

**Comment by saki7** [comment]
@k-satoda ああ、なるほど。orgの設定ではなくてリポジトリ単位の方でしたか。kunai と crsearch は今まで @cpprefjp/design しか Write を持っていなかったんですが、  @cpprefjp/workingteam にも Writeを付けておきます。

……付けてから気づいたのですが、自動Watchが走ったみたいです。バンバン通知が来ると思うので、フロントエンドを触らない方はWatchからは外してみてください。

**Comment by k-satoda** [comment]
@saki7 kunai 側の既存 Issue でも新規 Issue のページでも Projects が設定できる（歯車つきで出る）ようになってました。

Watch の件も了解しました。様子みててきとうに対応します。

**Comment by AinoMegumi** [comment]
Microsoft Edge で致命的な問題があります
![image](https://user-images.githubusercontent.com/11565880/32660568-c95ed3ac-c666-11e7-84cd-5f7fe6a2fff1.png)

**Comment by saki7** [comment]
@AinoMegumi これってEdgeのバージョンいくつですか？

自分用メモ： Promiseの内部ということはclass Treeviewの中のDOM生成周りで、そこで「.index」と「.set」が同時に死ぬとしたらたぶんES2015のWeakMapそのものが存在しないとかいう問題な気がするけど、 Edgeの15か16ならbabelのtransformが効いているはずなので存在しているはず

**Comment by saki7** [comment]
cpprefjp/kunai@8a94139e36bb0de9efc1a918e43315fdea2506cc これで少し自動変換の引っかかりやすさを上げたので、ページをリロードしたら直ってるかもしれません（希望的観測）

**Comment by AinoMegumi** [comment]
@saki7 バージョンは40.15063.674.0です

**Comment by saki7** [comment]
@AinoMegumi ChakraCoreのリポジトリちょっと覗いてみましたけど関連ありそうなものは無いですね。あとWeakMap関連はEdgeではとっくに実装されてたらしいのでこれも関係無さそうです。たぶん純粋にkunaiの問題な気がしますが、これ以上は検証環境（開発用のWindowsマシン）が無いのでわかりません。

**Comment by yumetodo** [comment]
Microsoft Edge 41.16299.15.0でも再現

```json
description: "Unable to get property 'set' of undefined or null reference"
message: "Unable to get property 'set' of undefined or null reference"
number: -2146823281
stack: "TypeError: Unable to get property 'set' of undefined or null reference at value (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:327310) at Anonymous function (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:328959) at r (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:299621) at Anonymous function (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:300666) at e[t] (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:299794) at r (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:72222) at Anonymous function (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:72373) at _ (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:309009) at Anonymous function (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:72167) at e (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:328831)"
```
```json
description: "Unable to get property 'index' of undefined or null reference"
message: "Unable to get property 'index' of undefined or null reference"
number: -2146823281
stack: "TypeError: Unable to get property 'index' of undefined or null reference at Anonymous function (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:109482) at Array.prototype.sort (native code) at value (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:109233) at Anonymous function (https://cpprefjp.github.io/static/kunai/js/kunai.js?cachebust=1510194905180:1:7707) at r (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:299621) at Anonymous function (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:300666) at e[t] (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:299794) at r (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:72222) at Anonymous function (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:72373) at _ (https://cpprefjp.github.io/static/kunai/js/kunai-vendor.js?cachebust=1510194905180:24:309009)"
```

**Comment by yumetodo** [comment]
ややや、毎回発現するわけではなく、大体2回に一回の割合で再現する・・・
確率再現ってことはタイミング系？非同期周りに起因？

**Comment by saki7** [comment]
@yumetodo 確率再現ですか？だとしたらasync/awaitの書き方ミスったヒューマンエラーか、もしくはWebpackの動的なベンダーコードのローダー（Webpackは外部ライブラリをスクリプトファイルごと遅延読み込みできる）のタイミングのどっちかですかね

**Comment by yumetodo** [comment]
あと別件で

>SEC7115: :visited と :link スタイルは、色のみを変更できます。一部のスタイルは :visited に適用されませんでした。

が出てます

**Comment by saki7** [comment]
@yumetodo 

kunai-vendor かつ 名前が index/set かつ Array.prototype.sort の中の無名関数の中 っていう条件が満たされるコードは、僕の記憶の中ではここしかないです https://github.com/cpprefjp/crsearch/blob/cbd0eb1d43901518e9322649cc7c7c988e42c230/js/crsearch/database.js#L243-L245

あとは少し条件が緩くなりますけどここですかね https://github.com/cpprefjp/kunai/blob/8a94139e36bb0de9efc1a918e43315fdea2506cc/js/kunai/ui/treeview.js#L174-L176

まあ想像で書いてもしょうがないんですが……

**Comment by yumetodo** [comment]
これminifyされてないものに差し替えて実験するにはどうしたら良いですかね？

**Comment by saki7** [comment]
1. エラーが高確率で出る本番サイトをブラウザで開く
2. ブラウザの「ソースを表示」機能でhtmlを生で保存する（「名前を付けて保存」は使ってはいけない）
3. htmlファイルの中身の kunai 関連のスクリプトを読み込んでいる要素を手動で削除する
4. 書き換えたあとのhtmlをそのまんまkunai/html/kunai-testing.hbsに上書き保存する
5. npm run dev
6. http://localhost:8080/

でいけます

**Comment by saki7** [comment]
note: 発生箇所がkunaiならkunaiの中でデバッグが完結できますが、もしcrsearchの中だった場合。上の手順そのままでもkunai/crsearch両者の原文デバッグは出来ますがcrsearchはnpmの依存先になっているためリアルタイムで変更しながらデバッグができません。kunai経由でcrsearchの中身を弄りたい場合は、

```bash
npm uninstall --save crsearch
npm install --save crsearchへのローカルの相対パス
```

をすればnpmの依存先がローカルのフォルダを向くので後は js/ 以下の元コードを書き換えた瞬間にWebpackが自動検知してリビルドされるのでデバッグできます

**Comment by melpon** [comment]
ローカル用ビルドなら minify しないので、 https://github.com/cpprefjp/site_generator/blob/master/README.md を見ながらローカルで構築するのも手かも。
が、Docker for Windows だと Bash on Ubuntu on Windows を使ってもマウント周りで危ない気がする…。

**Comment by saki7** [comment]
ああ、それでもいいですね。その方があらゆるページでテストできるのでデバッグ手法としては信頼度が高いです。ただ、site_generatorの環境をローカルで動かす一連の流れを身につけるのは僕は３日くらいかかりました……（普通に手順が難しいので仕方がない）

**Comment by saki7** [comment]
SEC7115の件は直しました

**Comment by yumetodo** [comment]
>https://github.com/cpprefjp/site/issues/476#issuecomment-343535223

ええっとこれはkunaiをビルドしておいてkunaiのhtmlを差し替えるということですかね？

![image](https://user-images.githubusercontent.com/10869046/32671559-39fc9cec-c68b-11e7-9734-96e13168d612.png)

とりあえず見方がわからない・・・

**Comment by saki7** [comment]
あーエラー出力で余計なことをしないでデフォルトの出力をするオプションをいずれ追加しておきます

あ、いや、ビルドする必要は無いです。hbsを差し替えれば npm run dev がリアルタイムのデバッグビルドで見に行くテンプレートがそのまま差し替わるので。

で、この画面が見れているなら成功なんですが、ここから先はIEとの戦いです。まずこのエラーはES6用のPolyfillのjsから出ているので、これの中身を見る必要は無いです。

promise rejection っていうのは要するにasync function の中で例外を投げたらそれがそのままpromise rejectionという扱いになります。要するにasync/awaitの文脈でcatch (e) してないという表示です（C++でいうところの非同期レベルのstd::terminate）

脱線しましたが、このエラーのスタックトレースを見てください。ソースファイル名の表示を押すとか、三角形を押すとか、IEのデバッガーのソースコードの一覧からkunai関係のjsを開くとかで、例外のスタックトレースを１つ１つ上に辿って行くと、kunaiのsourcemap経由でローカルのkunaiのjsファイルの該当行がデバッガ上で見れます。そこがエラーの発生箇所です

**Comment by saki7** [comment]
というか、本番環境のhtmlが必要になるのはhtml周りのバグだけなので、そもそも必要なかったかも知れません。普通に何もしない状態のnpm run devをIEで見た時にこのエラーが確率的に見れるならそれでいいです。あとはスタックトレースを１つ１つ辿るだけです。kunaiかcrsearchの該当行が分かれば最悪僕がエスパーして直せるところまでいけます

**Comment by yumetodo** [comment]
IEじゃなくてEdgeですね。Edgeで追うのはだるいのでとりあえず`http://127.0.0.1:8080/js/browser.js?3b68057c3554b8ae107e`とやらを手元のテキストエディタにコピペして現在追っています。

>Unhandled promise rejection TypeError: Unable to get property 'index' of undefined or null reference

は
https://github.com/cpprefjp/crsearch/blob/cbd0eb1d43901518e9322649cc7c7c988e42c230/js/crsearch/database.js#L243-L245
から飛んでますね

**Comment by yumetodo** [comment]
>Unhandled promise rejection TypeError: Unable to get property 'set' of undefined or null reference

は
https://github.com/cpprefjp/crsearch/blob/fec29874588110d9ad6cf87374c2b4f8ef452698/js/crsearch/crsearch.js#L277
から飛んでます

**Comment by saki7** [comment]
ああこの２個目はURLオブジェクトをnewできないといかいうアレじゃないでしょうか

１個目はL244の前に

```javascript
console.log(a); console.log(b);
```

入れてください

**Comment by yumetodo** [comment]
`console.log`を差し込むとどういうわけか再現率が1/10程度に下がる・・・

![image](https://user-images.githubusercontent.com/10869046/32673177-6ff290bc-c691-11e7-84d0-e13ee6e518f6.png)

**Comment by saki7** [comment]
L234の前に

```javascript
console.log(ns)
console.log(ns.namespace)
console.log(kc)
console.log(kc.categories().has(ns.namespace[0]))
```

**Comment by yumetodo** [comment]
>ああこの２個目はURLオブジェクトをnewできないといかいうアレじゃないでしょうか

https://github.com/cpprefjp/site/issues/477#issuecomment-343038614
これ？
Edgeだと`new`はできるんだけど(build 10240以降)`searchParams`がないんですね
https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Awhatwg-url

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/32673711-86bb543a-c693-11e7-8385-f6893e940613.png)
![image](https://user-images.githubusercontent.com/10869046/32673750-970e391a-c693-11e7-9293-c2103ef4b0c2.png)

**Comment by saki7** [comment]
僕がここで何をやっているのか説明するので分かる範囲で色々試してみてください

crsearchはまずgetTree() の前に cpprefjp/kunai_config のjson/md からcpprefjpのグローバル設定を取ります　それを格納してるクラスのオブジェクトが `kc` 

ここでの実際の処理は「crsearch.json内の全てのトップレベル記事カテゴリをcpprefjp/kunai_configの定義通りにソートする」処理です。で、
 `kc.categories()` っていうのは article.md の中で定義してある「cpprefjpのサイト全体のカテゴリ一覧」の名前をキーとして値にソート順序の数値が入った連想配列です。キーは 「リファレンス」だったら `'reference'` 「言語機能」だったら `'lang'` ですがこれは `ns.namespace[0]` と必ず一致するはずです。なので `kc.categories().get(ns.namespace[0])` していますが、これが `null` になっていると いわゆる致命的なエラーが出ます

**Comment by yumetodo** [comment]
もう夜が明けそうなので明日追ってみます

**Comment by saki7** [comment]
@yumetodo 色々考えてたら原因浮かびました

現行のJavaScriptではネイティブなクラスをMapのキーに出来ないのでところどころでHarmonyのWeakMapを使っているのですが、WeakMapは弱参照なので全ての参照が途切れたタイミングでGCされる可能性があります

Chromeだと今まで一度もエラーが起きていないので、Edgeが多分GCのタイミングがシビアなんでしょう。たぶん合ってると思います。解決策としては連想配列を全て諦めて文字列をキーにしてデータ構造を作り直すくらいですかね。

**Comment by yumetodo** [comment]
https://github.com/cpprefjp/kunai/blob/f11786ad8c9a434272a907efaf032d774326d784/js/kunai/ui/sidebar.js#L10-L13
の時点で`console.log("sidebar.js:13==>", this.kc);`した結果
![image](https://user-images.githubusercontent.com/10869046/32685736-92afa1dc-c6da-11e7-800b-f070f240e245.png)
こうなるのは説明が付きますかね・・・？

**Comment by saki7** [comment]
@yumetodo ん、合ってますね。数も正しいと思います

**Comment by saki7** [comment]
おはようございます、1つ新機能を実装して3つバグを生成しました

とりあえずありがたいことに @yumetodo さんがEdge周りをデバッグしてくれているので便宜上担当者として設定しておきます

**Comment by saki7** [comment]
便宜上という表現は失礼でした、僕の意図としては担当者に設定しますが基本ボランティアなので義務感を感じたら気軽にアサインは外していいということなので……

**Comment by yumetodo** [comment]
https://github.com/cpprefjp/crsearch/blob/fec29874588110d9ad6cf87374c2b4f8ef452698/js/crsearch/kunai-config.js#L138
に

```js
console.log("kunai-config.js:138==>", e)
```

を追記してlogを取った結果

| 表示されない時 | 表示される時 |
|------------------|---------------|
| ![image](https://user-images.githubusercontent.com/10869046/32686499-1d550a4e-c6e9-11e7-8027-f91d5b102675.png) | ![image](https://user-images.githubusercontent.com/10869046/32686500-26b04d92-c6e9-11e7-915f-bf952540c397.png) |

これは

```js
const e = Config.parseMD(data['article.md'], new ArticleProcessor)
```

が死んでる・・・？

**Comment by yumetodo** [comment]
https://github.com/cpprefjp/crsearch/blob/fec29874588110d9ad6cf87374c2b4f8ef452698/js/crsearch/kunai-config.js#L129-L131

`lexer.lex(md_raw).map(e => new Map(Object.entries(e)))`はなんかどっさり色々返してきているので問題は`proc.process`の中だと思うんですが、何をどうしたらいいやら・・・

**Comment by saki7** [comment]
@yumetodo new ArticleProcessorを渡してる部分でこれを変数に保存してなくてそのまま一時オブジェクトとして渡してるのが怪しいので、変数として取っておいて中身をconsole.logするとか（JSにはprivateとかいう概念は無いのでメンバ変数は外からアクセスできる）

**Comment by yumetodo** [comment]
@saki7 

https://github.com/yumetodo/kunai/commit/1ddd372932ce41d9ec6a47bd47ab15cb8d8a8cab
の環境で検証したところ

![image](https://user-images.githubusercontent.com/10869046/32687645-86d32242-c704-11e7-808a-0a461a6b7fb6.png)

>unhandled heading 'TOPLEVEL_CATEGORY'
>unhandled heading 'GLOBAL_QUALIFY_LIST'

が飛んでます

**Comment by yumetodo** [comment]
>https://github.com/cpprefjp/site/issues/476#issuecomment-343546376
>Unhandled promise rejection TypeError: Unable to get property 'set' of undefined or null reference

の件は https://github.com/cpprefjp/crsearch/commit/933a30636885356c6f57e435f6523d2ecd1bd61e で解決しました

**Comment by saki7** [comment]
当初のマイルストーンの設定通り、修正項目は今日の時点でリリースに向けてクローズします。

**Comment by saki7** [comment]
対応は終了
