### ISSUE TITLE
_MSC_VERと_MSC_FULL_VERの対応表を追加する

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#485]
#483 を見ていてそういえば`_MSC_VER`と`_MSC_FULL_VER`の対応表がcpprefjpにほしいなと思いました。

現在私がQiitaで個人的にまとめた
_MSC_VERと_MSC_FULL_VERをまとめる - Qiita
https://qiita.com/yumetodo/items/8c112fca0a8e6b47072d
をほぼそのまま持ってくるイメージです。

https://cpprefjp.github.io/implementation.html#visual_cpp
の「バージョンの表記」を拡張するか別ページに切り分けるかしたいです。

#483 で上がっている言語機能ごとに`_MSC_FULL_VER`をまとめるのはメンテナンスコストが高いとしても、この程度の表なら私でもメンテンスに参加できると思います。

**Comment by faithandbrave** [comment]
ありがとうございます。
メンテナンスしていただけるのであれば、現在あるVisual C++の表を拡張する形でお願いできればと思います。
その際、「馬鹿」のような罵倒表現はこちらに記載しないようお願いします。批判ならば (攻撃的にならなければ) よいですが、罵倒は敵を作ることになるのでいけません。

また、CTPやRCをこちらにも記載するかどうかはお任せしますが、その対応が必須ではないことは、明記していただければと思います。これは、ほかの方が編集する場合があるからです。

**Comment by yumetodo** [comment]
>その際、「馬鹿」のような罵倒表現はこちらに記載しないようお願いします

それが「ほぼ」と書いた理由です・・・

>また、CTPやRCをこちらにも記載するかどうかはお任せしますが、その対応が必須ではないことは、明記していただければと思います。これは、ほかの方が編集する場合があるからです。

Qiitaに書いているのもそのへんは穴がたくさんあるので、とりあえずそのまま持ってきますが、RC, CTPの類は積極的には編集しないこととします

**Comment by yumetodo** [comment]
`[^1]`とかで脚注は貼れないんですね・・・。
