### ISSUE TITLE
[規格] 基本用語、慣用語、略語

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site#489]
C++標準規格における基本用語と、C++の慣用語の解説を書いてください。

略語表もまとめてください。 https://github.com/cpprefjp/site/wiki/略語表

## プログラムに関するもの

- 適格 (well-formed)
- 不適格 (ill-formed)

## 振る舞い・評価順序に関するもの

- 実装依存/処理系定義 (implementation-defined behavior)
- 未規定/不定 (unspecified behavior)
- 未定義 (undefined behavior, __UB__)  
  （鼻から悪魔）

## アルゴリズムに関するもの

- 安定 (stable)  
  （挿入、ソート）

## 規格に関するもの

- 未規定 (unspecified)  
  （型など）
- 欠陥 (defect)  
  参考: http://faithandbrave.hateblo.jp/entry/2017/08/10/120545

## 慣用語、英語、ラテン語

- 合法
- 違法
- NB
- e.g.
- i.e.

書く場所は、 article/ 階層以下に新しい記事を作れば良さそうです。作ったら、GLOBAL_QUALIFY_LISTも更新して自動リンクにしてください。

これらの用語は、今のcpprefjpでもそこそこ使用実績があり、日常的に触れるものです。英語の用語は、日本語解説サイトとして最低限必要だと感じる基本的なものを独断で入れました (@saki7)

解説の雰囲気として、中学一年生の教科書程度の平易さが望ましいと思います。

出典として記載するのはなるべく現行の標準規格に留め、出典を付加する場合でも記事本文で理解が完結するようにしてください。

**Comment by faithandbrave** [comment]
GLOBAL_QUALIFY_LISTはコードブロックに対してのみ適用されるので、文章には適用されないですよ。

**Comment by saki7** [comment]
@faithandbrave たとえば `unspecified` などはコードブロックでよく出て来ますが、今は斜体になるだけなので、用語を知らないと少し引っかかりがあると思います。自動リンクで用語解説に飛べると良いかなと。

**Comment by faithandbrave** [comment]
不適格 (ill-formed) は規格用語でユーザーにはなじみがなさそうなので、できるだけ「コンパイルエラー」と書くようにしてます。

未規定、未定義動作、処理系定義は用語としてあってもよいと思います。

`<algorithm>`のページに「狭義の弱順序」の解説があります。
https://cpprefjp.github.io/reference/algorithm.html#strict-weak-ordering
こういった、特定領域の用語 (ヘッダもしくはクラスレベルで解説できる用語) はこのままにして、C++の全体で使うような用語集を作ればよいでしょうか。

略語表は、私と @egtra さんの間で伝えるために、iostream関係のわかりにくい略語を、リファレンスを書く前の段階で調査するためにありました。なので、リファレンスに略語元を記載したら削除する予定でした。

**Comment by saki7** [comment]
背景の説明ありがとうございます。非常に助かります。

> 不適格 (ill-formed) は規格用語でユーザーにはなじみがなさそうなので、できるだけ「コンパイルエラー」と書くようにしてます。

> <algorithm>のページに「狭義の弱順序」の解説があります。
> https://cpprefjp.github.io/reference/algorithm.html#strict-weak-ordering
> こういった、特定領域の用語 (ヘッダもしくはクラスレベルで解説できる用語) はこのままにして、C++の全体で使うような用語集を作ればよいでしょうか。

はい。イメージとして、「特定領域・特定の関数・特定のクラスなどに関係なくサイト全体で出てくる用語のうち、C++の標準規格と関係が深いもの」をまとめた単一解説記事を想像しています。

「不適格」は、GitHubの検索だと数件しか出ないのですが、Googleで全文検索すると40件くらい出て来ます。「未規定」に至っては120件以上出てきます。用語の使い方に関しては柔軟に対応すれば良いと思いますが、広範に渡るので、まとめページがあると心強いです。

**Comment by saki7** [comment]
> 略語表は、私と @egtra さんの間で伝えるために、iostream関係のわかりにくい略語を、リファレンスを書く前の段階で調査するためにありました。なので、リファレンスに略語元を記載したら削除する予定でした。

略語は、数が少なくても1か所に目録としてまとめることで価値が出るので、これも含めれば良いと思います。

訳語表は、ここに既にあるのですが、これも「スタイル」から分離して本Issueのページにまとめた方が良いと思います。 https://cpprefjp.github.io/working_style.html

**Comment by faithandbrave** [comment]
略語はサルベージするのに時間がかかると思いますが、追々でよければ・・・。
`<cmath>`とiostream関係がほとんどだとは思いますが、ほかは思い出せず…。
https://cpprefjp.github.io/reference/cmath/abs.html

**Comment by saki7** [comment]
@faithandbrave 最初から全てを解説しなくても良いので、初版はここのコメントで既に上がっているものだけで良いと思います。

新規に書き下ろす重要性がある用語は、僕が最初に挙げたものでほぼ網羅できていると思います。それ以外の用語については、移動できるなら移動だけします。

解説の本文を増補する必要がある場合は、気づいた人が１つずつ加筆します。

**Comment by yumetodo** [comment]
ところで @akinomyoga 氏による
C++er は“合法”だとか“違法”だとか言いたくて仕方がないけれど、結局どういう意味? それより適合・適格・○○動作・○○規則・診断不要いろいろの関係が謎 - Qiita
https://qiita.com/akinomyoga/items/592e5a3b8438a0c8556b
という記事があって大体これでいいんじゃないかという気がしてしまうんですがどうでしょう・・・？

![img](https://camo.qiitausercontent.com/b7d0214b38b101b79d9eee668e0d8915b99de12c/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f36333433392f32633033616230332d313732352d363432372d323539362d3064323564366137643835302e706e67)

**Comment by saki7** [comment]
cpprefjp ではコンテンツのライセンスを統一する必要があるため、画像を追加する際は cpprefjp/image というリポジトリに追加することになっています。画像の作者の方がcpprefjpのMemberの場合は個別に承認を頂けば良いと思いますが、そうでない場合は、新しく作った方が良いと思います。

画像ではなく本文についても同様です。外部サイトの作者の方に許諾を得て転載している例は今までも何回かはあります。

内容に関しては、僕はリンク先の記事は標準規格を非常に意識した書き方になっていると感じますが、本Issueで最初に書いた僕のイメージはもう少し柔らかいものです。なので、この記事よりはもう少し平易に書き下した方が良いと思います。

**Comment by saki7** [comment]
平易さに関して、僕は「中学一年生の教科書程度の平易さが望ましい」と書いていますが、これはCONTRIBUTINGに準じるので、”自分たちなりの言葉”で書かれているならそれで良いと思います。

**Comment by faithandbrave** [comment]
どこまで詳細に書くかは、ひとつの論点になりますね。用語ごとに1ページ使えるのであればどこまでも詳細に書ける、というものは多くありそうです。
WikipediaとかでもたとえばADLというのでひとつの記事になっています (@egtra さんが書いたらしい)。

解説にサンプルコードや図を付加したい、という意見があるなら、用語ごとに1ページということも考えられるのではないかと思います。
本サイトの方針は、「正確なものに不要なことはない」ということをCONTRIBUTING.mdに書いていますが、どこまでも詳細に書くことは問題なく、平易な説明が必要なら概要文章をそのような形にするといった工夫をすればよいですね。

**Comment by saki7** [comment]
Issueの投稿者として、管理者として、デザイナとしてどのような雰囲気が望ましいかという方針は一応示しましたが、最終的にはアキラさんが仰っているように初版の担当者の方の裁量で工夫して頂ければ充実すると思います。

**Comment by faithandbrave** [comment]
用語ごとに1ページ用意する場合は、用語ページの雛形が必要になります。
これまでの慣習では、たたき台となる記事をひとつ作り、それをレビューして必要な項目 (各見出し) を決めていくことになっていました。

**Comment by faithandbrave** [comment]
今後の拡張性を考えたときに、用語集として多くのページができそうなのであれば、article階層以下ではなく、まず本リポジトリのトップ階層に用語集用のページを作って、その下に階層を作れるようにするのがよいのではないかと思います。

**Comment by saki7** [comment]
たとえば `SFINAE` のように頻出かつ奥が深い用語であれば、用語ごとに1ページ作っても良いと思います。今までは article/ がそういう役割をしていたので特に雛形は無かったはずですが、用語解説としての雛形を作るのは良いことだと思います。

今まで用語集が無かったので、ディレクトリを掘るほどではないかなと思います。ひとまず1記事、Issue本文のようなまとめページが新規にできることが重要なので、初版を作って頂ける方はあまり難しいことを考えずPull requestとして出していただければみんなでサポートできると思います。

**Comment by saki7** [comment]
最初に書いた「慣用語、英語、ラテン語」に関してですが、これはIssueの提案者として僕が思いついたものを入れているので、ここに含まれる単語について意見がある方は書いてください。僕のチョイスとしては、C++の公式のdraftで頻出するものを適当に選んでいます。

**Comment by usagi** [comment]
用語集の独立化、現在の所感としては現状に対して近い将来に有用と思い、賛成します。

とは言え、いざ独立させてみたら1桁の用語解説しか無かった（そんなはずはないけれど）となると作業リソースも勿体無いので、初稿として執筆したい用語をリストアップして用語集の編集準備が整い次第すみやかに解説者がリソースを当てられるように issue と雛形を用意する事とセットで推進したら良いと思います。適当な辞書サイトを参考に、見出し、ページとしての意匠設計は @saki7 さんに期待させて下さい。必要となった際にはよろしくお願いします。

**Comment by usagi** [comment]
related: https://github.com/cpprefjp/site/pull/490#issuecomment-349609818

**Comment by akinomyoga** [comment]
cpprefjp の Member(?) ではないのですが失礼致します。@yumetodo さんに @ で mention されて通知が来ておりましたので議論を拝見しました。

> cpprefjp ではコンテンツのライセンスを統一する必要があるため、画像を追加する際は cpprefjp/image というリポジトリに追加することになっています。画像の作者の方がcpprefjpのMemberの場合は個別に承認を頂けば良いと思いますが、そうでない場合は、新しく作った方が良いと思います。

@yumetodo さんが貼った画像は私が作ったものですが、もし使うのであれば仰って頂ければ問題ありません。また、画像の内容で微妙なところがありましたら修正も承りますし、或いは、そちらで改変していただいても構いません。

> 内容に関しては、僕はリンク先の記事は標準規格を非常に意識した書き方になっていると感じますが、本Issueで最初に書いた僕のイメージはもう少し柔らかいものです。なので、この記事よりはもう少し平易に書き下した方が良いと思います。

そうですね…。私の書いた記事は、厳密な解釈に拘って規格の文面を読んで解釈やその曖昧な点についてあれこれ言うようなものなので、例え平易に書き下したとしてもリファレンスには向かないように思います。リファレンスに載せるのだとすれば、統一された見解・間違いようのない解釈について淡々と述べるものが望ましいはずです。

用語毎に1ページという案は難しいのではないかと思います。例えば、不適格と適格を別ページに分けたり、処理系定義の動作・未規定の動作・未定義の動作を別ページに分けるというのは、却って理解を妨げるように思います。用語毎に1ページあることの利点はページを見つけやすいということかと思いますが、代わりに用語目録のページを作成してそこから各用語の解説に跳べるようにするなどのことも可能であるように思います。とにかく、初めから画一的なルールを設定するのではなく、目的に応じて柔軟に対応していけば良いように思います。やはりこの点に関しても @saki7 さんに賛成で、取り敢えず記事を作るのが良いかと思います。

私見ですが 適格/不適格 および 処理系定義/未規定/未定義の動作に関しては、規格の用語一覧にある定義が既に簡潔で十分なのでそのまま翻訳すれば (必要があれば、適当に実例など添えれば) 十分なように思います。

**Comment by saki7** [comment]
@akinomyoga 貴重なご意見をありがとうございます。画像に関して、もしcpprefjpで使うことになった場合、改めて連絡させていただきます（ありがとうございます）。

ちなみに、cpprefjpのMemberは、いまのところcpprefjpを編集したことのある方にお願いして参加してもらっているもので、cpprefjpの編集自体はGitHubのOrganizationのMemberでなくても誰でも出来るものなので、何かありましたらよろしくお願いします。

**Comment by akinomyoga** [comment]
@saki7 ありがとうございます。

> ちなみに、cpprefjpのMemberは、いまのところcpprefjpを編集したことのある方にお願いして参加してもらっているもので、

そのような仕組みになっているのですね。承知しました。

**Comment by akinomyoga** [comment]
> 編集方法については、 トップページをご参照ください。 https://cpprefjp.github.io/

トップページに

> 1. cpprefjp の Issues にアクセスし、
> 2. あなたが手伝えそうな、まだ誰にもアサインされていないタスクを見つけ、
> 3. その Issue のコメントに「このタスクやります」と書く

とあります。こちらの Issues には GitHub 上誰もアサインされていないようですが、私が書いてみても良いでしょうか

**Comment by saki7** [comment]
@akinomyoga ぜひお願いします。今は担当者はいませんので、お願いしたいと思います

**Comment by akinomyoga** [comment]
ありがとうございます。では、このタスクやります

相談するべきことなど既に色々ある気がしますが、書き始めるとまたさらに色々出て来そうなので、一旦書いてみてからまとめて相談させて頂くことにします。
