### ISSUE TITLE
`operator+ (単項)` 等のリンクが一見切れているように見える

### ISSUE THREAD

**Issue by forno** [cpprefjp/site#495]
kunai に投げるべきなのか判断がつかなかったのですが、ひとまずこちらへIssue出しします。

今のところ `complex` と `valarray` にしか無いのですが、
メンバ関数の `operator+ (単項)` と `operator- (単項)` の表示が一見リンク切れに見えてしまいます。
具体的には(単項)部分にのみリンク色がついて、operatorが黒文字のままになっています。
このままでは見づらいので、全てリンク色になるような修正が欲しいと思います。

参考画像は以下の通り。

https://cpprefjp.github.io/reference/complex.html

![like_unlink](https://user-images.githubusercontent.com/11057257/33880921-86631bc0-df76-11e7-8aaf-e05220efdb60.png)

比較用にリンクになっていない表示の例も載せておきます。

![normal_unlink](https://user-images.githubusercontent.com/11057257/33880930-8fafc02a-df76-11e7-80e9-c1475b3f8685.png)

ちなみに `valarray` には `operator~ (単項)` もありますが、
こちらは単項演算子のみで二項演算子が存在しないので`operator~`にすればよいかと思います。

**Comment by saki7** [comment]
直します！ @cpprefjp/design

**Comment by saki7** [comment]
https://github.com/cpprefjp/kunai/blob/4ea3bbe5779d51ba4f452894d511ce2df9e64385/css/kunai/site/article.css#L60

ここを消せば直る（この黒色は本文色にリセットする意図で入れてた気がするんだけど、どこに影響あったのか憶えていない）

**Comment by saki7** [comment]
本番に反映されたっぽいです。regressionが置きてなければ大丈夫だと思います

@forno 報告ありがとうございました :sparkles:

**Comment by forno** [comment]
反映を確認しました。
素早い対応ありがとうございます。
