### ISSUE TITLE
aタグのname属性を使っている部分をid属性に置き換える

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#496]
https://github.com/cpprefjp/site/pull/493#issuecomment-351053568
より。

aタグのname属性はHTML5では廃止されたので、id属性に置き換える必要があると考えます。

別の選択肢としてはsite_generator側でどうにかすることですが、素直にmarkdownを書き換えてしまう方がいいと思います。

**Comment by saki7** [comment]
@yumetodo HTML5規格に準拠する方が重要なので、記事の書き換えをお願いします。もしスクリプトを使って大規模に書き換える場合は、branchを切ってself-prしてください（マージはセルフマージして大丈夫ですが、prのbranchは消さないようにお願いします）

**Comment by saki7** [comment]
念のため補足： ちなみに cpprefjp/site_generator#19 というのがありますが、これは今は考えなくて大丈夫です

**Comment by saki7** [comment]
フロントエンドに影響があるidの一覧は以下です。

- `navbar-collapse`
- `main`
- `sidebar`

このidを含むhtml要素を記事の方に追加してしまうと、フロントエンドが壊れるので気をつけてください。ここに挙げたもの以外は大丈夫なはずです。

**Comment by yumetodo** [comment]
なんか怖いなぁ。
将来のことを考えてなんかprefixつけて起きます？`s-xxx`とか

**Comment by saki7** [comment]
@yumetodo 大丈夫ですよ。壊れたらrevertできるので。prefixとかは付けなくて大丈夫です。

**Comment by yumetodo** [comment]
あ、だめだ。こっちで変えてしまうと既に貼ってるリンクが壊れる。
フロントエンドで使ってる方だな、prefixつけるなら。
