### ISSUE TITLE
[C++17][ライブラリ] std::basic_string::data()の非const版について記述

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#497]
https://cpprefjp.github.io/reference/string/basic_string/data.html

>c_str と異なり、本メンバ関数で返る配列は NULL（charT()）で終端されていないので、注意すること。

の記述に代表されるようにC++11時代に内容がなっていない。

C++17で非const版が追加されたのでその編集のついでに修正するべき

**Comment by faithandbrave** [comment]
> なお、C++11 からは本メンバ関数は c_str と完全に同一となっているため、以下は C++03 までの挙動についてのみ記載する。
> C++11 からの挙動については c_str を参照のこと。

と概要に書いているので、書き方の問題ですね。

**Comment by yumetodo** [comment]
>書き方の問題ですね。

あー、なるほど。

**Comment by faithandbrave** [comment]
C++17対応にともなって書き方を整理しないといけないのは、そうだと思います。

**Comment by yumetodo** [comment]
C++17対応するときにやればいい気がしたのでタイトル変えました。
