### ISSUE TITLE
md 先頭行が # で始まるタイトルである必要がある」というルールを明文化

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#498]
知らずに #491 で誰も気が付かずにマージした結果、 https://github.com/cpprefjp/kunai/issues/76 のようにフロントエンドが概ね死んだ。
@melpon 氏によってMarkdownにこのルールを適用して( https://github.com/cpprefjp/site/commit/e84a22bc0b19bb0cfd407942ca3244c684db2175 )解決をみたが、明文化するべきルールではないか？

**Comment by faithandbrave** [comment]
雛形に書いておきます。
