### ISSUE TITLE
注釈(脚注)を貼るときの書き方の統一

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#505]
https://github.com/cpprefjp/site_generator/issues/52
にてQiitaにあるような注釈の記法導入は見送られ、各自`a`タグを駆使して実現することとなったが、見た目の統一はした方がいいのではないか。

- 注釈番号の記法(`^1`か`[^1]`か)
- 注釈に飛んだ後戻れるようにする必要はあるか(注釈を貼った場所にも`id`attributeを貼る必要があるか
- `id`attributeの命名規則
- 数字じゃない注釈はどうするか
- 注釈元は`sup`タグで囲い上付き文字にするべきか

このへん。

すでに注釈が利用された例としては、 #485 がある。これは

- `[^1]`
- 戻れない
- `cite-N`
- 使っていない
- していない

のようになっている。

**Comment by faithandbrave** [comment]
私は注釈についてこだわりは持っていないので、いまあるものと意見が衝突したら、もしくはそれでカバーできない状況がでてきたら議論でいいように思います。

**Comment by yumetodo** [comment]
あ、いや #493 と衝突しています。

#493 では

- `^1`
- 戻れる
- `noteN`に飛んで`noteN-src`に戻る
- 使っていない
- `sup`タグ使用

となっていて、主に @akinomyoga 氏とのすり合わせが必要と思っています。

**Comment by akinomyoga** [comment]
これはどのような形で解決されるのでしょう。ルールを制定して何処かに明記し、それに合わせるということになりますか。

- すみません。実は、さらに [`international-standard.md`](https://github.com/akinomyoga/cpprefjp-site/blob/feature/implementation-compliance/international-standard.md) で表の註として `†` を使ってしまいました (さきの "時間計算量" で出ていた `†` に倣ったものです)
- また、参考文献の引用 `cite` と註釈 `note` は微妙に性格が異なるので、必ずしも統一するべきかどうか分かりません (むしろ引用と註は区別した方が良い気がします)
- 参考文献の引用といえば、各ページの `参照` で挙げられているリンクについても文中から参照する場合には同様にリンクを張る可能性も考えられます (今のところそのような使い方はないようですが)。

表の註釈・脚註・参考文献の引用をそれぞれ統合するかどうかも含めて考えた方が良い気がしました

**Comment by yumetodo** [comment]
こういうときはWikipediaに立ち返ってみるべきかと思って見てきたら

- `[1]`
- 戻れる
- `cite_note-N`に飛んで`cite_ref-N`に戻る
- ないが、named refというのがある。その場合`cite_note-NAME-N`に飛んで`cite_ref-NAME_N-M`に飛ぶ
- `sup`使用

となっていた。

---

>すみません。実は、さらに international-standard.md で表の註として † を使ってしまいました (さきの "時間計算量" で出ていた † の案に倣ったものです)

こうしてみると`†`は使わないほうがいいんじゃないかと思えてきました・・・

---

>また、参考文献の引用 cite と註釈 note は微妙に性格が異なるので、必ずしも統一するべきかどうか分かりません (むしろ引用と註は区別した方が良い気がします)

WIkipediaでは`<ref group="注">`のように書いたものを`{{Reflist|group=注}}`のように列挙できるようで、`[注 2]`みたいに表示されます。内部的な通し番号Nはグループによって区別されません。
ex.) [魔法科高校の劣等生 - Wikipedia](https://ja.wikipedia.org/wiki/魔法科高校の劣等生)

というように分けているので、やはり分けて考えるべきでしょうね・・・。Wikipediaのような拡張文法が無い以上、id的にも分けてあげるべきですね。

**Comment by akinomyoga** [comment]
@yumetodo あ、丁度いろいろ嗅ぎ回って似たようなものを表にまとめていたのでした。

| | 註釈元 | ←(リンク)→ | 註釈 | 註釈元`id` / 註釈`id` |
|:--:|:--:|:--:|:--:|:--:|
| [`implementation.md`](https://github.com/cpprefjp/site/blob/master/implementation.md) 表の註 | <a id="comment5-rf4" href="#comment5-fn4">[^N]</a> | 一方向 | <a id="comment5-fn4">[^N]:</a> | -- / `#cite-N` |
| [`implementation-compliance.md`](https://github.com/akinomyoga/cpprefjp-site/blob/feature/implementation-compliance/implementation-compliance.md)<br/>脚註 (現状) | <sup><a id="comment5-rf6" href="#comment5-fn6">N</a></sup> | 両方向 | <a id="comment5-fn6" href="#comment5-rf5">^N</a> | `#noteN-src` / `#noteN` |
| Qiita脚註 | <sup><a id="comment5-rf1" href="#comment5-fn1">N</a></sup> | 一方向 | <a id="comment5-fn1">N.</a> | -- / `#fnN` |
| C++規格PDF脚註 | <sup><a id="comment5-rf2" href="#comment5-fn2">N</a></sup> | 一方向 | <a id="comment5-fn2">N)</a> | -- / -- |
| [Wikipedia脚注](https://ja.wikipedia.org/wiki/Help:%E8%84%9A%E6%B3%A8) | <sup><a id="comment5-rf3" href="#comment5-fn3">[N]</a></sup> | 両方向 | N. <a id="comment5-fn3" href="#comment5-rf3">^</a> | `#cite_ref-N` / `#cite_note-N` |
| Wikipediaテンプレート<br/>[`{{ref}}`](https://ja.wikipedia.org/wiki/Template:Ref) [`{{note}}`](https://ja.wikipedia.org/wiki/Template:Note) | <sup><a id="comment5-rf6" href="#comment5-fn6">[N]</a></sup> | 両方向 | <sup><a id="comment5-fn6" href="#comment5-rf6">a</a></sup> | `#ref_名前` / `#endnote_名前` |

**Comment by yumetodo** [comment]
そういえば注釈/出典を書く場所もありますね、多いのはページ最下部に書くケースですのでそれに合わせてしまいたい(つまり修正案件)

---

リンクは双方向できたほうがやっぱり良いですよね。いかがでしょう？

---

註釈元なのに`^`があるのはおかしいな、なんでつけたんや、過去の私。

あとは`[]`をつけるかどうかですかね？

---

idについては、註釈元id / 註釈idを`note_ref-N`/`note-N`, 出典元id / 出典元を`cite_ref-N`/`cite-N`を提案します。

**Comment by akinomyoga** [comment]
> そういえば注釈/出典を書く場所もありますね、多いのはページ最下部に書くケースですのでそれに合わせてしまいたい(つまり修正案件)

表注は表の直下が良いです。それ以外はページ末尾で問題ありません。ただ、長めの記事の場合には章の末尾の方が良いという場合もあるかなと感じています (どちらが良いかは脚註をどのように読むかによりそう)。この辺りは (Wikipedia で `{{Reflist}}` で指定できるように) 執筆者に任せて良いのではないかという気がします。

> リンクは双方向できたほうがやっぱり良いですよね。いかがでしょう？

そうですね。あった方が便利だなと感じます (僕だけかもしれないけれど、註釈を見てから本文の何処に対応するのか目で探すのをよくやる)

> あとは[]をつけるかどうかですかね？

個人的には [] は付けたほうが良いかなという気がします。例えば Qiita は付けていないのですが、利用していて文字が小さくて脚註があることを見落としそうになるので。

> idについては、註釈元id / 註釈idをnote_ref-N/note-N, 出典元id / 出典元をcite_ref-N/cite-Nを提案します。

賛成です。参照元の書式は <sup>[注 N]</sup> (註釈) / <sup>[N]</sup> (出典) ですかね。註釈・出典の番号も Wikipedia に倣って N. ^ が無難な気がします。

**Comment by yumetodo** [comment]
`Wikipedia の {{Reflist}}`って記事中に全く同じグループ指定のものを複数置いた場合どうなるんでしたっけ・・・？なんとなく一つしか置けないイメージが有りました。

どこか一箇所にまとめないとナンバリングが面倒そう・・・

**Comment by akinomyoga** [comment]
別に同じグループ名にしなければならないということはないので、複数箇所に分けるのだとしたら例えば `{{Reflist|group="章1"}}`, `{{Reflist|group="章2"}}` などで良いのではないでしょうか。

> どこか一箇所にまとめないとナンバリングが面倒そう・・・

寧ろ手動ナンバリングの場合には、一箇所にまとめると後から注を追加する時に番号を大量にシフトしなければならなくなるので、適当に分けた方が良い気がします… (或いは、注の番号と文中に現れる順番は shuffle されていて OK とするか…)

**Comment by akinomyoga** [comment]
あ、でも…複数に分けた場合には区別するためには [N] ではなくて [N.M] の様な形式にしなければならなくなりますね…。[N] の形式を保持 (続きの番号を使用) するとしたら、一箇所にまとめた方が番号の管理は幾らかマシですね…。

**Comment by akinomyoga** [comment]
> Wikipedia の {{Reflist}}って記事中に全く同じグループ指定のものを複数置いた場合どうなるんでしたっけ・・・？なんとなく一つしか置けないイメージが有りました。

これは、実際に Wikipedia でプレビューで試してみたら

```
文章1: <ref>alpha</ref> <ref>beta</ref> <ref>gamma</ref>

{{Reflist}}

文章2: <ref>delta</ref> <ref>epsilon</ref> <ref>zeta</ref>

{{Reflist}}
```

のようなとき

> 文章1: <sup>[1] [2] [3]</sup>
>
> - <a></a>1. ^ alpha
> - <a></a>2. ^ beta
> - <a></a>3. ^ gamma
> 
> 文章2: <sup>[1] [2] [3]</sup>
> 
> - <a></a>1. ^ delta
> - <a></a>2. ^ epsilon
> - <a></a>3. ^ zeta

のような感じに数字が再利用されるみたいです。

**Comment by yumetodo** [comment]
>一箇所にまとめた方が番号の管理は幾らかマシ

ええ、そうなんですよ。幸いにして双方向リンクにしようという方向で話が進んでいるので離れたところに書いてあっても良いかなと思っています。

>数字が再利用

それidはどうなっていますか？

---

それはそうと例えば将来的にフロントエンド側で参照元にマウスをかざしたらツールチップに参照先を表示させるみたいなことをするために、`class`attributeをつけておきたいです(`class="reference"`)

**Comment by akinomyoga** [comment]
> > 数字が再利用
>
> それidはどうなっていますか？

どうも表示の番号と id の番号は独立のようで、id の番号は group に関係なく `<ref>` に文章中での登場順で番号が付くみたいです (つまり、全て `cite_ref-N` の形式で `<ref>` に一意な番号がついている)。

> class="reference"

そうですね…。でも、将来的に対応するということは確定なのでしょうか。class 属性の付加はツールチップの自動生成に対応してからでも良い気がします。

**Comment by yumetodo** [comment]
>どうも表示の番号と id の番号は独立のようで

やっぱり。拡張構文なしにそういう複雑さを受け入れるのはちょっとやってられない思いがあるので、一箇所にまとめたいです・・・。

>class 属性の付加はツールチップの自動生成に対応してからでも良い気がします。

そう言われればそうですね。

**Comment by akinomyoga** [comment]
> やっぱり。拡張構文なしにそういう複雑さを受け入れるのはちょっとやってられない思いがあるので、一箇所にまとめたいです・・・。

OK

**Comment by yumetodo** [comment]
すると構文的には

```md
ありきたりな世界<sup id="note_ref-1"><a href="#note-1">[注1]</a></sup>と私がよく書くがこの元ネタは、おもに工業系と魔術系のModを導入したバージョン1.7.10のありきたりなMinecraftの実況をやっていきます<sup id="cite_ref-1"><a href="#cite-1">[1]</a></sup>、という動画内音声である。

# 注釈

1. <b><a href="#note_ref-1">^</a></b> <span>yumetodoがHello worldと書くのが嫌で代わりによく用いる</span>

# 出典

1. <b><a href="#cite_ref-1">^</a></b> <cite id="cite-1">[【Minecraft】ありきたりな工業と魔術S2 Part01【ゆっくり実況】 - ニコニコ動画](http://www.nicovideo.jp/watch/sm25261912)</cite>
```

こんなかんじですかね？`span`とか`cite`タグ使えたか怪しいですが。

**Comment by akinomyoga** [comment]
個人的にはやはり `<a>` に `id` 属性と `href` 属性を同時に指定するほうが落ち着きます (もし `<a>` に `id` を設定しないのだとすれば、リンクは HTML タグは使わずに単に `[<sup>[注1]</sup>](#note-1)` / `[**^**](#note_ref-1)` で良いのではと思います。太字も Markdown で記法があるので `**～**` の方が良いかなと)。

```md
ありきたりな世界<sup><a id="note_ref-1" href="#note-1">[注1]</a></sup>と私がよく書くがこの元ネタは、
おもに工業系と魔術系のModを導入したバージョン1.7.10のありきたりなMinecraftの実況をやっていきます<sup><a id="cite_ref-1" href="#cite-1">[1]</a></sup>、という動画内音声である。

## 注釈

1. **<a id="note-1" href="#note_ref-1">^</a>** yumetodoがHello worldと書くのが嫌で代わりによく用いる

## 出典

1. **<a id="cite-1" href="#cite_ref-1">^</a>** <cite>[【Minecraft】ありきたりな工業と魔術S2 Part01【ゆっくり実況】 - ニコニコ動画](http://www.nicovideo.jp/watch/sm25261912)</cite>
```

あと、既存の `## 参照` の節と `## 出典` が意味的に被る気がしますが、それでも別々の節として扱いますか。例えば、両者を統合して以下のように混在させても良いように思うのです (文中から参照されている項目についてのみリンクを張る)。

```md
## 参照

1. <cite>[foo](foo)</cite>
2. <cite>[bar](bar)</cite>
3. **<a id="cite-1" href="#cite_ref-1">^</a>** <cite>[baz](baz)</cite>
4. <cite>[foobar](foobar)</cite>
```

それからページ末尾に註釈を集める場合、`implementation-compliance.md` で複数箇所から註釈を参照したい<sup><a id="comment17-rf1" href="#comment17-fn1">[1]</a></sup>のですが、この場合の書き方を決めたほうが良いでしょうか。Wikipedia に倣うならば、例えば以下の様になりましょうか。

```md
文章<sup><a id="note_ref-1-0" href="#note_ref-1">[注1]</a></sup>文章

文章<sup><a id="note_ref-1-1" href="#note_ref-1">[注1]</a></sup>文章

## 注釈

1. <a id="note-1">^</a> <sup>[**a**](#note_ref-1-0) [**b**](#note_ref-1-1)</sup> hello
```

----

1. **<a id="comment17-fn1" href="#comment17-rf1">^</a>** 和訳に注意の必要な語の導入場所と、JIS C++ にできるだけ従うという説明の 2 箇所から。

**Comment by yumetodo** [comment]
>個人的にはやはり <a> に id 属性と href 属性を同時に指定するほうが落ち着きます 

まあそれで良いかもしれませんね。WIkipediaが`<sup>`にid指定していたのでそれに従ってましたが。

>既存の `## 参照`の節と`## 出典`が意味的に被る気がしますが、それでも別々の節として扱いますか。

そもそも`<cite>`タグ使えましたっけ・・・。

リンクするものとしないもので混ざっているのは見づらいのでHTMLでいう`ol`と`ul`に分けておきたい・・・

厳密にはcpprefjp全ての記事を見て参照と出典を分離するべきなんだろうけど、作業量が発散しているのでやりたくない・・・。

>それからページ末尾に註釈を集める場合、implementation-compliance.md で複数箇所から註釈を参照したい[1]のですが、この場合の書き方を決めたほうが良いでしょうか。Wikipedia に倣うならば、例えば以下の様になりましょうか。

それでいいと思います。

**Comment by faithandbrave** [comment]
`<cite>`タグは使えるようです。許可リストに入ってました。
https://github.com/cpprefjp/markdown_to_html/blob/36f45f95cec597afbe1c4e591a43b811bfcf85c3/html_attribute.py

**Comment by akinomyoga** [comment]
> リンクするものとしないもので混ざっているのは見づらいのでHTMLでいうolとulに分けておきたい・・・

まあ、それはそうですね。。取り敢えず今までの方法で規格用語のページを更新してみます。

あと、表の注釈 († としたもの) も全体の注釈に合流することにするのでしょうか。分けたい気がします。

**Comment by akinomyoga** [comment]
あと、`## 参照` を grep して、色々問題点を見つけてしまったのでそれらについても後で Issue を登録させて頂きます。

**Comment by akinomyoga** [comment]
取り敢えず対応してみました。

- [cpprefjp-site/implementation-compliance.md at 736c49](https://github.com/akinomyoga/cpprefjp-site/blob/736c49ba349c7e07e43b38fde7413fbc47843ca8/implementation-compliance.md)
- [cpprefjp-site/international-standard.md at 736c49](https://github.com/akinomyoga/cpprefjp-site/blob/736c49ba349c7e07e43b38fde7413fbc47843ca8/international-standard.md)

対応してみて気付いたこと:

1. `注釈` をページ中で一箇所にまとめることにしましたが、`参照` も一箇所にまとめた方が良さそうでしょうか。因みに、現状で参照が複数箇所あるページは:
    - http://cpprefjp.github.io/reference/deque/insert.html
    - http://cpprefjp.github.io/reference/map/multimap/insert.html
    - http://cpprefjp.github.io/reference/vector.html
2. `## 関連項目` / `## 参照` / `## 出典` / `## 注釈` の現れる順番に指針があった方が良い気がしました
3. `## 参照` は「参考文献として有用そうなもの」として、`## 出典` は「ちょっとした事柄の根拠を示すためのもの (参考文献として勉強するのに向くとは限らない)」という雰囲気で使い分けができるかなと感じました。
    - implementation-compliance.md の例では、参考文献としても出典としても使うものは両方に重複してしまいましたが、それでも良さそうと感じています。
4. international-standard.md では表の注釈をページ最下部に置きましたが、やはりこれは表の直下にあった方が良いように感じました。ただ、表に含まれる reference にも出典的なものや参考文献的なものもあるでしょうから、場合による気もします。

**Comment by faithandbrave** [comment]
参照が複数箇所あるところは、単に書き間違いですね。直しておきます。
関連項目と参照の順番は、関数・クラスの雛形に書いていなかったですが、言語機能の雛形には書いていました。(関連項目、参照の順)
https://github.com/cpprefjp/site/blob/b748b81efbfa8e40959a968c9a632286ecb90e30/editors_doc/lang_template_page.md
これも、ほかの雛形にも書いておきます。

**Comment by faithandbrave** [comment]
出典、注釈は、 @akinomyoga さんのPull Requestをマージしてから雛形に書こうと思います。いま書いていただいた順番を前例として採用しましょう。

**Comment by akinomyoga** [comment]
@faithandbrave ありがとうございます。実は、今の順番は全く何も考えずに並べただけだったのですが、注釈は先の方が良いなどの好みはあれば対応します。

**Comment by faithandbrave** [comment]
> 4. international-standard.md では表の注釈をページ最下部に置きましたが、やはりこれは表の直下にあった方が良いように感じました。ただ、表に含まれる reference にも出典的なものや参考文献的なものもあるでしょうから、場合による気もします。

ページ最下部を「`## 脚注`」、表の直下などに適時配置するものを注釈という扱いにすれば解決でしょうか。

**Comment by faithandbrave** [comment]
脚注の場合は、見出しにする以外に、`***`で罫線を引いてページ最下部 (フッターの上) に書くやり方もありそうな気がします。わかりにくいでしょうか。

***

(ここに脚注を書く)

**Comment by yumetodo** [comment]
@akinomyoga 
>4. international-standard.md では表の注釈をページ最下部に置きましたが、やはりこれは表の直下にあった方が良いように感じました。ただ、表に含まれる reference にも出典的なものや参考文献的なものもあるでしょうから、場合による気もします。

注釈を見ないと文章理解に差し支えがあるものはそもそも注釈を使うのが妥当ではないので、そういう不適切な用例を避けるためにもあえてページ下部に集約するべきじゃないかと考えます。

@faithandbrave 

>脚注の場合は、見出しにする以外に

Qiitaがまさにそれをやっているんですが、私は見づらいと思っています。紙の文章でやるにはそれが適切だとは思いますが、Webページは紙ではないので。

**Comment by akinomyoga** [comment]
> ページ最下部を「## 脚注」、表の直下などに適時配置するものを注釈という扱いにすれば解決でしょうか。

@faithandbrave 表の下部に添えるものはわざわざ "注釈" という見出しはつけないことを想定していました。その場合は、ページ最下部は `## 脚注` でも `## 注釈` でもどちらでも問題ありません。

----

> 注釈を見ないと文章理解に差し支えがあるものはそもそも注釈を使うのが妥当ではないので、そういう不適切な用例を避けるためにもあえてページ下部に集約するべきじゃないかと考えます。

@yumetodo 注釈を使わないとすれば表の場合にはどのようにすれば良いでしょうか。例えば、

> | 通称 (策定時・標準化前に一時的に用いられた通称) | 名称 |
> |:--:|:--:|
> | C++20 (C++2a) | ISO/IEC 14882:2020 (予定) |

というのはありえないですし、かといって文章にして

> 以下の表において通称の列の括弧内は策定時・標準化前に一時的に用いられた通称である。
> 
> | 通称 | 名称 |
> |:--:|:--:|
> | C++20 (C++2a) | ISO/IEC 14882:2020 (予定) |

というのも分かりにくく思います。更に、複数のセルに同じ補足説明を入れたいときには、マークによる注釈が使えないとより辛いことになります。結局 † か <sup>[1]</sup> などのマークで注釈を埋め込む以外にない気がしています。

> | 通称<a id="comment29-rf1" href="#comment29-fn1">†</a> | 名称 |
> |:--:|:--:|
> | C++20 (C++2a) | ISO/IEC 14882:2020 (予定) |
>
> - <a id="comment29-fn1" href="#comment29-rf1">†</a> 括弧内は策定時・標準化前に一時的に用いられた通称

いかがでしょう。

----

> > 脚注の場合は、見出しにする以外に
>
> Qiitaがまさにそれをやっているんですが、私は見づらいと思っています。紙の文章でやるにはそれが適切だとは思いますが、Webページは紙ではないので。

@faithandbrave @yumetodo 個人的には、機能的にも記述的にも `## 出典` と並列のような感じがするので、`## 出典` と同様に見出しを設けたほうが分かりやすい気がしています (結局は、慣れの問題のようにも思いますが)。

**Comment by yumetodo** [comment]
>かといって文章にして

私はそれで良いかなと思ったんですが、わかりにくいですか・・・。うーん。

>更に、複数のセルに同じ補足説明を入れたいときには、マークによる注釈が使えないとより辛いことになります。

別に表の中で注釈/出典を使うなというわけではなく表を特別扱いしないという話なので、そんなに不自由しないと思うんですが。
ex.) [自衛隊 - Wikipedia](https://ja.wikipedia.org/wiki/%E8%87%AA%E8%A1%9B%E9%9A%8A#cite_ref-18)

**Comment by faithandbrave** [comment]
表に対する注釈は、チャートの図を掲載してその直下に説明を記載することと状況が似ているように思います。表自体の説明、表の列の意味や詳細などは、表のすぐそばにあったほうがいい、というのは私は理解できます。

また、縦に長いページの場合には、ページ中央に注釈を書きたい場合があると思います。ここではcpprefjpについて議論していますが、boostjpの場合ですと、逆引きリファレンスなどで縦に長いページがいくつもあります。そちらにも共通ルールを設けられると便利なので、ページ中央に注釈を置けるとうれしいですね。
https://boostjp.github.io/tips/graph.html

**Comment by yumetodo** [comment]
じゃあ末尾に持っていかないときは所属する節名の略称(適当にそのばででっちあげる)を含めて
`cite-${short_name}-${N}`/`cite_ref-${short_name}-${N}`, `note-${short_name}-${N}`/`note_ref-${short_name}-${N}` 
をidとすることにして、その場合節の末尾に置けることにしませんか？

**Comment by akinomyoga** [comment]
> > 更に、複数のセルに同じ補足説明を入れたいときには、マークによる注釈が使えないとより辛いことになります。 by @akinomyoga
>
> 別に表の中で注釈/出典を使うなというわけではなく表を特別扱いしないという話なので、そんなに不自由しないと思うんですが。 by @yumetodo 
> ex.) 自衛隊 - Wikipedia

@yumetodo 自衛隊のページの例だと、表の中にあるのは表の解釈に必要な説明ではなくて、出典ですよね。表の中に、1. 表の註 (表の解釈に必要な補足説明)、2. 注釈 (その他の補足説明)、3. 出典 (根拠などの提示) など色々な種類の補足説明が考えられて、2. と 3. に関してはページ全体のものでも良いけれども、1. に関しては表の附則として記述したいということなのです (2. も 3. も表の附則に入れるということではありません。念のため)。

> 更に、複数のセルに同じ補足説明を入れたいときには、 by @akinomyoga

と書いたのは、例えば時間計算量の PR で議論のあったような

> | コンテナ | 計算量 |
> |--|--|
> | std::vector | O(1) |
> | foo | (O(n)†) |
> | bar | O(1) |
> | baz | O(1) |
> | hoge | (O(n)†) |
> - † 直接はサポートされないが、`std::distance`, etc を用いて実現可能

というような物のことです。この補足説明をページ下部に集めるのは分かりにくいし、だからと言って文章で以下のようにするのは辛いということです。結局、何らかの記号を導入するのが妥当に思われ、それは表の注釈を導入するのと変わらないということです。

> 以下の表において `foo` と `hoge` の○○操作の計算量と `hoge` の××操作の計算量は、直接はサポートされないが、`std::distance`, hogehoge を用いて実現可能なものである。
>
> | コンテナ | ○○操作の計算量 | ××操作の計算量
> |--|--|--|
> | std::vector | O(1) | O(1) |
> | foo | O(n) | O(1) |
> | bar | O(1) | O(1) |
> | baz | O(1) | O(1) |
> | hoge | O(n) | O(n) |

----

> をidとすることにして、その場合節の末尾に置けることにしませんか？ by @yumetodo 

表の場合は節の末尾というより、表の直下に書きたいのですがだめですか。

**Comment by yumetodo** [comment]
では再度まとめなおして提案します。これでどうでしょうか？

---

# 基本的な注釈・出典記法

- `N`: 1から始まる連番

|      | 参照元の見た目 | 参照先の見た目 | 参照元のid   | 参照先のid |
|------|----------------|----------------|--------------|------------|
| 注釈 | `[注N]`        | `N. ^`         | `note_ref-${N}` | `note-${N}`   |
| 出典 | `[N]`          | `N. ^`         | `cite_ref-${N}` | `cite-${N}`   |

```md
ありきたりな世界<sup><a id="note_ref-1" href="#note-1">[注1]</a></sup>と私がよく書くがこの元ネタは、
おもに工業系と魔術系のModを導入したバージョン1.7.10のありきたりなMinecraftの実況をやっていきます<sup><a id="cite_ref-1" href="#cite-1">[1]</a></sup>、という動画内音声である。

## 注釈

1. **<a id="note-1" href="#note_ref-1">^</a>** yumetodoがHello worldと書くのが嫌で代わりによく用いる

## 出典

1. **<a id="cite-1" href="#cite_ref-1">^</a>** <cite>[【Minecraft】ありきたりな工業と魔術S2 Part01【ゆっくり実況】 - ニコニコ動画](http://www.nicovideo.jp/watch/sm25261912)</cite>
```

# 節ごとの注釈・出典記法

- `N`: 1から始まる連番
- `short_name`: 適当にでっち上げたページ内で衝突しない節の名前

|      | 参照元の見た目 | 参照先の見た目 | 参照元のid   | 参照先のid |
|------|----------------|----------------|--------------|------------|
| 注釈 | `[§注N]`        | `N. ^`         | `note_ref-${short_name}-${N}` | `note-${short_name}-${N}`   |
| 出典 | `[§N]`          | `N. ^`         | `cite_ref-${short_name}-${N}` | `cite-${short_name}-${N}`   |


```md
## <a id="define-graph" href="#define-graph">グラフ型を定義する</a>

(前略)

以下は、無向グラフ<sup><a id="note_ref-define-graph-1-a" href="#note-define-graph-1">[§注1]</a></sup>を定義する例：

(中略)

有向グラフ<sup><a id="note_ref-define-graph-1-b" href="#note-define-graph-1">[§注1]</a></sup>で、辺に重みを付ける例：

(中略)

### 注釈

1. <a id="note-define-graph-1">^</a> <sup>[**a**](#note_ref-define-graph-1-a)</sup> <sup>[**b**](#note_ref-define-graph-1-b)</sup>
```

# 表に対する注釈記法

- `N`: 1から始まる連番

|      | 参照元の見た目 | 参照先の見た目 | 参照元のid   | 参照先のid |
|------|----------------|----------------|--------------|------------|
| 注釈 | `†N`        | `N. ^`         | `note_ref-t-${N}` | `note-t-${N}`   |

```md
| コンテナ | ○○操作の計算量 | ××操作の計算量
|--|--|--|
| std::vector | O(1) | O(1) |
| foo | (O(n)<sup><a id="note_ref-t-1" href="#note-t-1">†1</a></sup>) | O(1) |
| bar | O(1) | O(1) |
| baz | O(1) | O(1) |
| hoge | (O(n)†) | (O(n)†) |

1. **<a id="note-t-1" href="#note_ref-t-1">^</a>** 直接はサポートされないが、`std::distance`, etc を用いて実現可能
```

# その他

同じ参照先に対する参照元が複数あるときは、参照元のid末尾に小文字のアルファベット`a`から連続で文字を割り当て、参照先の見た目は

>N. ^ <sup>[**a**]()</sup> <sup>[**b**]()</sup> 本文

のようにする。

出典の本文は`cite`タグで囲う。

**Comment by akinomyoga** [comment]
@yumetodo ありがとうございます。異論はありません。一点だけ: 一つのページに複数表が含まれる場合も考えられるので、`note-t-N` ではなく `note-tM-N` (`M` は表の番号とする) などの方が良さそうです。

**Comment by akinomyoga** [comment]
表の注の形式を @yumetodo さんの案に倣って変更してみました。

- [cpprefjp-site/international-standard.md at 8ebed4](https://github.com/akinomyoga/cpprefjp-site/blob/8ebed4529b4405a599b752cd1f15d3b2d326b122/international-standard.md)

特に気になったことはありません。いかがでしょう。

**Comment by yumetodo** [comment]
>一点だけ: 一つのページに複数表が含まれる場合も考えられるので

反映しました
