### ISSUE TITLE
一部のページのサンプルコード周辺が cpp example 付加時に破壊されている

### ISSUE THREAD

**Issue by akinomyoga** [cpprefjp/site#507]
最も分かりやすいのは http://cpprefjp.github.io/reference/regex/regex_replace.html です。サンプルコード以降のページ内容が何度も繰り返されています。 1b301da91d187ca4257ffcfed351ec17f836e2bc で入ったミスのように思われます。

以下気づいたページ一覧です (他にもある可能性があります):

- http://cpprefjp.github.io/reference/regex/regex_iterator/op_arrow.html
- http://cpprefjp.github.io/reference/regex/regex_iterator/op_assign.html
- http://cpprefjp.github.io/reference/regex/regex_iterator/op_deref.html
- http://cpprefjp.github.io/reference/regex/regex_iterator/op_increment.html
- http://cpprefjp.github.io/reference/regex/regex_replace.html
- http://cpprefjp.github.io/reference/regex/regex_token_iterator/op_arrow.html
- http://cpprefjp.github.io/reference/regex/regex_token_iterator/op_assign.html
- http://cpprefjp.github.io/reference/regex/regex_token_iterator/op_deref.html
- http://cpprefjp.github.io/reference/regex/regex_token_iterator/op_equal.html
- http://cpprefjp.github.io/reference/regex/regex_token_iterator/op_not_equal.html

**Comment by faithandbrave** [comment]
すいません。該当コミットを全てチェックして修正します。
