### ISSUE TITLE
ファイルシステム pathクラスのoperator/に対するページ名

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#513]
`std::filesystem::path`クラスのために用意されている`operator/`と`operator/=`は、パス連結の意味を持ちます。
除算ではないので`op_divide`ではなく、`path`クラスの対応するメンバ関数`append()`と合わせて`op_append`、`op_append_assign`をページ名にしてはどうかと考えたのですが、どうでしょうか。

名前空間 (ライブラリ) 固有の意味なので`op_fs_append`にしたほうがいいとかあれば、ご意見ください。

このような意味別にページを分けた前例としては、ビットシフト演算子`operator<<`に対して`op_left_shift`と`op_ostream`にしたものがあります (右シフトは`op_right_shift`と`op_istream`)。

**Comment by faithandbrave** [comment]
作業が止まるのもよくないので、仮のページ名として`op_append`、`op_append_assign`で作業して、このIssueで結論がでたらページ名を変更しようと思います。

**Comment by yumetodo** [comment]
`op_divide`としてきたのは実際に除算の機能を持っていたからであると認識しているので、改名は問題ないと思います。

ただ、kunaiというかcrserch側で不具合が出たりしないですか・・・？そこだけ不安で(じっそうちゃんと読んでいないので)

**Comment by faithandbrave** [comment]
調べてみたのですが、site_generatorの検索用JSONを作るところ、crsearch、kunaiのどこでも、演算子に対して特別な処理はしていないように見えます。

**Comment by faithandbrave** [comment]
とくに異論がないようですので、`op_append` / `op_append_assign`でページを作成し、ページ名の編集者向けドキュメントにも記載しておきました。
