### ISSUE TITLE
size_tの説明

### ISSUE THREAD

**Issue by aokomoriuta** [cpprefjp/site#516]
細かいことかもしれません＆何か意図があるのかもしれませんが、疑問に思ったのでお聞きします。

[今の説明](https://github.com/cpprefjp/site/blob/639b558335b12d51571ab451e5f663df9175de0b/reference/cstddef/size_t.md)ですと、

> `size_t`は、`sizeof`演算子によって返される符号なし整数型である。

ですが、規格書をみると

> 21.2.4 [support.types.layout] 
> 3. The type size_t is an implementation-defined unsigned integer type that is large enough to contain the size in bytes of any object.

となっていて、単に「オブジェクトのバイト数を表現できる程度に十分に大きい」としか書かれていないのを見つけました。
（そしてむしろsizeofの返り値定義がsize_tに依存している）

ただ、例えば[`std::size()`](https://cpprefjp.github.io/reference/iterator/size.html)などでは配列の要素数として`std::size_t`が使われているので、必ずしも「オブジェクトのバイト数を表現するもの」とは言えないとも思います。

なので、今の説明だとちょっと不正確ではないでしょうか？
上記2例を結合するなら「`size_t`は、オブジェクトのバイト数やコンテナの要素数を表現するための符号なし整数型である。」とかになるのかなと思いますが、ちょっと独自見解が過ぎる気がしないでもないです。

あんまりまとまってなくてすみません。最終的には私からMR投げたいとは思うのですが、どう修正するべきか（そもそも現行にすべきか）相談させてください。

**Comment by faithandbrave** [comment]
たしかにそうですね。
Google Sitesの頃に書かれたものでコミットメッセージも残っていないのですが (システム上そのようなものがなかった)、仕様と用例を分けて記載すればよいかと思います。

**Comment by yohhoy** [comment]
気になってC++03仕様を確認したら、§18.1 [lib.support.types] で「The contents are the same as the Standard C library header `<stddef.h>`, [...]」とC仕様に丸投げしており、C仕様では「`size_t` which is the unsigned integer type of the result of the `sizeof` operator」となっていました。現行説明は、C++03時代の定義から来ているようですね。

**Comment by aokomoriuta** [comment]
@yohhoy 
なるほど、C++03ではこの定義だったのですね。

@faithandbrave の助言も取り込むと

```
`size_t`は、オブジェクトのバイト数を表現できる程度に十分に大きい符号なし整数型である。
C++03まではC言語と同じく「`sizeof`演算子によって返される符号なし整数型」と規定されていた。

オブジェクトのバイト数（例えば`malloc`の引数）やコンテナの要素数（例えば`std::size()`の返り値）を表現するために用いられる。
```

といったような感じでしょうか？こんな方向性で良ければ、（細かいところはMRでレビューいただくとして）書いてみようと思います。

**Comment by faithandbrave** [comment]
そんな感じでいいと思います！Pull Requestお待ちしております。

**Comment by yumetodo** [comment]
なんか聞き覚えある話だなと思ったら、江添さんが
[本の虫: std::size_tの定義のたらい回し](https://cpplover.blogspot.jp/2010/12/stdsizet.html)
書いているこれか。
