### ISSUE TITLE
ヘッダページ = クラスページになっているページ階層を直す

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#522]
現在、連想コンテナを除くコンテナのヘッダと`<complex>`が、ヘッダページ = クラスページになっています。
これは本来、ヘッダページとクラスページを分けるのが正しいです。これまでは現在の階層でも大きな問題になっていなかったのですが、C++17でpolymorphic memory resourceが入ったことで、たとえば`<vector>`ヘッダには`std::vector`と`std::pmr::vector`の2つの型が紐付くようになり、ヘッダページ = クラスページではいけない状況になりました。

`<complex>`はC++17でもヘッダ内に1クラスしかないのでよいのですが、階層構造の統一化のため、この機会に合わせる必要があります。

これらのクラスについて、外部サイトから大規模なリンク切れが発生してしまうのですが、昔からあった負債なのでどこかで精算しないといけませんでした。

できれば現在のページのコミット履歴を維持したいのですが、Gitよくわからず・・・。調べます。

**Comment by faithandbrave** [comment]
`<bitset>`もそうでした。リスト化すると、以下のようになります。

1. `<array>`
2. `<bitset>`
3. `<complex>`
4. `<deque>`
5. `<forward_list>`
6. `<initializer_list>`
7. `<list>`
8. `<stack>`
9. `<vector>`

**Comment by yumetodo** [comment]
単にファイル移動のみのcommitとヘッダページ新規作成commitを作るのではだめでしょうか？

**Comment by yumetodo** [comment]
site_generator側でリダイレクト設定ファイルを読み取ったらリダイレクトするjsが書かれたhtmlを吐くとかできないですかね・・・？

```json
[
  {
    "type": "directory",
    "base": ".",
    "to": "./array/",
    "exclude": "array.md"
  }
]
```

```json
[
  {
    "type": "file",
    "base": "hoge.md",
    "to": "./hoge/hoge.md"
  },
  {
    "type": "file",
    "base": "foo.md",
    "to": "./foo/foo.md"
  }
]
```

設定ファイルのイメージとしてはこんな感じです

**Comment by faithandbrave** [comment]
急ぎでもないので、私も含めただれかがツール整備対応をできるならやってもいいとは思いますが・・・、 @melpon との相談も必要です。

**Comment by melpon** [comment]
リダイレクトを頑張っても、`/reference/complex.md` が、同一のURLなのに、クラスの説明からヘッダの説明に変わるのは防げないですね。
あとリダイレクト用のコード書いたりメンテナンスするのは辛いし、書いてる md と出力する html が1対1で対応じゃなくなるのも微妙だし、サクッと互換性捨てたいところ。
しかし、`<vector>` 以下は結構参照されてそうで、なかなか難しいところですね。

**Comment by melpon** [comment]
静的ファイル（site_generator の cpprefjp/static 以下にあるやつ）としてリダイレクト用の html を必要な URL の数だけ置くのが一番分かりやすそうな気がしますね。

**Comment by yumetodo** [comment]
>リダイレクトを頑張っても、/reference/complex.md が、同一のURLなのに、クラスの説明からヘッダの説明に変わるのは防げないですね。

それは諦めていいと思います。

>しかし、<vector> 以下は結構参照されてそうで、なかなか難しいところですね。

なのでリダイレクトが必要と思います。

>書いてる md と出力する html が1対1で対応じゃなくなるのも微妙だし

じゃあjsonはやめて、リダイレクト用構文をMarkdownに追加しますか？

先頭行に

```md
[Redirect To](path)
```

とあればリダイレクトするjsが埋め込まれたhtmlを吐くようにmarkdown_to_htmlに手を加えるとか。

**Comment by faithandbrave** [comment]
@melpon のイメージとしては、リダイレクトをメンテナンスするのは大変だから、ツールは用意せずリダイレクト用のHTMLをベタで書いて配置し、ある程度の期間を置いたらサポート期間を終了して消す、という感じで読み取りました。

**Comment by faithandbrave** [comment]
- [How to make github follow directory history after renames? - StackOverflow](https://stackoverflow.com/questions/5646174/how-to-make-github-follow-directory-history-after-renames)

Gitがデフォルトで`--follow`を付けてくれるか、GitHubが`--follow`をサポートしてくれるようになれば、過去のファイル名変更したものも辿れるようになるのかなぁ・・・。

**Comment by yumetodo** [comment]
あー、github上でのことでしたか。
たしかにリネームcommit特定してその一つ前のcommitに行ってまた履歴見てとかだいぶだるいことをしています・・・。follow欲しい。

**Comment by faithandbrave** [comment]
とりあえず、直す手順としては、以下のような感じで：

- cpprefjp/siteとcpprefjp/site_generatorに、作業用のブランチを作る
- ファイル移動のみのコミットを作る
- ヘッダページを作るコミットを作る
- リンクを修正するコミットを作る
- 外部サイトからのリンク切れの影響が大きいものに対して、リダイレクトのhtmlファイルを作る
 (`<vector>`だけ用意すればよさそう)
- cpprefjp/siteのブランチをマージ後に、cpprefjp/site_generatorのブランチをマージする

ファイルシステムのリファレンス作成がおわったら、私の方でとりかかります。それまでにやってくださる方がいたらお願いします。

**Comment by YukiMiyatake** [comment]
かなりご無沙汰ですが、私に手伝えそうなら手伝わせて下さい。
内容把握を開始します

**Comment by faithandbrave** [comment]
@YukiMiyatake ありがとうございます。
ちゃんと書いてなかったリダイレクトファイルについてですが、cpprefjp/site_generatorリポジトリの[`cpprefjp/static`ディレクトリ](https://github.com/cpprefjp/site_generator/tree/master/cpprefjp/static)に置いたファイルが、[GitHub Pagesリポジトリ](https://github.com/cpprefjp/cpprefjp.github.io)にデプロイされるようになっています。
いまはCSSやアイコン類をそこに置いていますが、`cpprefjp/static/reference/vector/push_back.html`とかのリダイレクト用HTMLファイルを作って置けばいいはずです。

**Comment by faithandbrave** [comment]
どのページをリダイレクト対象にするかですが、アクセス解析してみると`vector`のメンバ関数だけリダイレクトすればいいかなと思います。

**Comment by yumetodo** [comment]
リダイレクト用HTMLはどう実装しますか？JavaScriptで飛ばすのかmetaタグで飛ばすのか(SEO的にはJavaScriptで`locale.href`をいじるのがよい)

**Comment by faithandbrave** [comment]
JavaScriptの方がいいらしいですね。雛形は作っておいたほうがよさそうです。こんな感じでどうでしょうか？titleやエンコーディングも入れておいたほうがいいでしょうか？

vector/push_back.html

```html
<script type="text/javascript">
  window.location.href = "http://cpprefjp.github.io/reference/vector/vector/push_back.html"
</script>
```

**Comment by yumetodo** [comment]
昔某所で

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>リダイレクト中...</title>
	<script type="text/javascript">
		var redirect = function(url){
			location.href = url;
		};
		var on_load = function(){
			var current_url = window.location.href;
			var new_url = current_url.replace(/.+\/miraiken\//, "https://miraiken.github.io/web/");
			var link = document.getElementById("link");
			link.href = new_url;//href書き換え
			setTimeout(function(){
				redirect(new_url);
			}, 3000);
		};
	</script>
</head>
<body>
	<p>3秒後にページが切り替わります。自動的に切り替わらない場合には<a id="link" href="https://www.example.com/">コチラ</a>をクリックしてください。</p>
	<script type="text/javascript">on_load();</script>
</body>
</html>
```

とか作ったことがありますね。

**Comment by YukiMiyatake** [comment]
とりあえず　私の認識が間違えてたら訂正してください
まずはリダイレクトが不要な vector以外の作業だけ行おうと思っていますが大丈夫ですか？ vectorも同時にする必要ありますか？

cpprefjp/siteに、作業用のブランチを作る
(vector以外) ファイル移動のみのコミットを作る
(vector以外) ヘッダページを作るコミットを作る
(vector以外) リンクを修正するコミットを作る

**Comment by faithandbrave** [comment]
`vector`以外だけ先に作業していただいて大丈夫です。手順は、記載していただいたもので間違いありません。

**Comment by YukiMiyatake** [comment]
とりあえず　確認もこめて　２，３ライブラリずつでCommit作っていくので、PRしたら確認お願いします

**Comment by YukiMiyatake** [comment]
残り

<complex>
<deque>
<forward_list>
<initializer_list>
<list>
<stack>
<vector>

**Comment by yumetodo** [comment]
？

**Comment by YukiMiyatake** [comment]
なんだ　かぎかっこ付きのコピーがタグになるのか　変な挙動

**Comment by yumetodo** [comment]
- [x] `<array>`
- [x] `<bitset>`
- [ ] `<complex>`
- [ ] `<deque>`
- [ ] `<forward_list>`
- [ ] `<initializer_list>`
- [ ] `<list>`
- [ ] `<stack>`
- [ ] `<vector>`

**Comment by faithandbrave** [comment]
`<filesystem>`のリファレンス作成が完了したので、こちら私もとりかかります。
@YukiMiyatake さんの作業状況がわからないので、ひとまず`<vector>`からやります。

**Comment by faithandbrave** [comment]
`<vector>`がおわったので、残りの`<complex>`を引き取りますねー。

**Comment by faithandbrave** [comment]
全部終わったので、閉じます。
@YukiMiyatake さん、ご協力ありがとうございました！
