### ISSUE TITLE
処理系ページのVisual C++の記載について

### ISSUE THREAD

**Issue by sayurin** [cpprefjp/site#524]
処理系ページのVisual C++の記載が気になります。

まず製品名が微妙に違っています。2003までは単体販売が行われており
Visual Studio .NET 2002 (Visual C++ 7.0) → **Visual C++ .NET Standard**
Visual Studio .NET 2003 (Visual C++ 7.1) RTM → 
**Visual C++ .NET Standard 2003**
等でした。2005以降はWebから無償ダウンロードとなっていて
Visual Studio 2005 (Visual C++ 8.0) RTM → **Visual C++ 2005 Express**
等でした。2012辺りから単体での提供がなくなっているためVisual Studioという表記になるかと思いますが、対称性からVisual C++ 2012のように呼ばれることはあります。

また正式リリース前のバージョンについてどこまで記載する方針でしょうか？ 散発的で直近ではVisual Studio 2017 Update6 Preview1～Preview7が抜けていますが、これらを書き始めるときりがありませんし。Go-Live Licenseと言ってRC版であっても製品利用を認めるバージョンもありますが、それがふまえられたリストでもなさそうです。
個人的には正式リリース以降だけの記載で十分かと思います。

**Comment by yumetodo** [comment]
もともと私のqiitaの記事でまとめていたものを持ってきたので、その記事に参考リンクで貼ってある情報か、情報提供があったものか、自分で調べたものが載っているため散発的になっています。

製品名が違うのもその影響です(査読していないので)。

RCについては正直いらないなと思っています。十分に情報を集められない上に、正式版が出た後になおRCを使うという状況が想像できないので。

**Comment by faithandbrave** [comment]
RCやPreviewは、記載した情報が間違っていてもチェックが困難なので、できればなくしたいところです。
Express/Standard/Professionalとかは製品のグレードの部分かなと思うので、省略してよいように思います。
また、ご指摘のように現在はVisual C++という製品はなく、Visual StudioのC++コンパイラのような表現が妥当だとは思いますが、サイト全体の表記変更にも関わるものなので、私からの提案には至っていませんでした。こちら、implementationページ以外も含めた提案があればお願いしたいです。

**Comment by yumetodo** [comment]
Visual C++はVisual Studioについてくるコンパイラの識別子として機能しているように見えます(出典省略)。従ってそこを変えるのには反対です。

RC/Previewについては1週間して反対が無ければ私が除去します

**Comment by sayurin** [comment]
PR書いてみました。（Issueより初めからPRでもよかったのかしら？）

Visual Studioに完全統合されて久しいですが、それでも以前の名称としてVisual C++は十分に認知されていると思います。またこのリストで製品名欄がVisual C++で統一されていれば、他のページでの呼称は現状維持でうまくつながるのではと。

**Comment by yumetodo** [comment]
ref:
#485
