### ISSUE TITLE
std::byte 操作の効果の式についての欠陥修正 LWG2950 をどう扱うか

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#526]
5c7b381450484cfc377a4f064ff826b7d13793b7 で std::byte の操作について
C++17 の文面どおりの記述が追加されましたが、効果の式にちょっと問題があって
すでに [LWG2950](https://cplusplus.github.io/LWG/issue2950) で C++20 向けの WP に修正が取り込み済みとなっています。

これについて、以下のような対応が考えられるかと思うんですが、どうなりますかね？
- 修正後のものに差し替え。（※ [Defect 扱い](http://faithandbrave.hateblo.jp/entry/2017/08/10/120545)）
- 原版を C++17 の規定として、修正後のものを C++20 の規定として併記。

個人的には前者でいいだろうと思うんですが、[C++20の対応状況](https://github.com/cpprefjp/site/wiki/cpp20)のページに
LWG2950 は挙がってたので、対応について何か想定があったりしたのかな？とも
思った次第です。

いずれにしても LWG2950 への参照は追加することになると思ってます。

**Comment by faithandbrave** [comment]
仕様として未定義動作になってしまうのは欠陥扱いですね。
C++20の対応状況Wikiは、明らかにdefectでC++17に含まれるだろうというものは私の判断でC++17ページに移動していたのですが、漏れているものはまだいくつかあると思います。

**Comment by faithandbrave** [comment]
修正しました。
それと、2017年12月までのCWG/LWG Defectを、C++20対応状況ページからC++17対応状況ページに移動しておきました。
