### ISSUE TITLE
コンパイラの実装状況 : MSVC 2017 Update 7に対応する

### ISSUE THREAD

**Issue by sayurin** [cpprefjp/site#540]
- [Announcing: MSVC Conforms to the C++ Standard](https://blogs.msdn.microsoft.com/vcblog/2018/05/07/announcing-msvc-conforms-to-the-c-standard/)

**Comment by sayurin** [comment]
- 本バージョン 2017 Update 7 にて C++17 にほぼ対応が宣言されました。
- Two-phase name lookupへの対応が宣言されました。cpprefjpではC++11未満の内容なので言及する場がないかもです。
- Expression SFINAEへの対応が宣言されました。cpprefjpでは 0af13ac4db5d0432b648fd939c1e76c0467eb8e0 にて2015 Update 3で対応済みとされてしまっています。
- P0283R2 不明な属性を無視する が `No` となっていますが、2015で対応済みとのことです。
- P0296R1 処理の進行保証 は実装に影響しないので `No` ではなく `-` にすべきではないでしょうか？

**Comment by faithandbrave** [comment]
> - Expression SFINAEへの対応が宣言されました。cpprefjpでは 0af13ac4db5d0432b648fd939c1e76c0467eb8e0 にて2015 Update 3で対応済みとされてしまっています。

2015 Update 3時点でKnown Issueがあったことを確認しました。そちらはpartialにして、今回ので完全対応としましょう。
https://blogs.msdn.microsoft.com/vcblog/2016/06/07/expression-sfinae-improvements-in-vs-2015-update-3/

> - P0283R2 不明な属性を無視する が `No` となっていますが、2015で対応済みとのことです。

これは当時の記憶があやふやなのですが、2015で実際に試したところ、`gnu::deprecated`属性とかでコンパイルエラーになったからそう記載していた気がします (『C++ポケットリファレンス』の執筆時に確認)。
cppreferenceの方では、2017 15.3になってますね。
http://en.cppreference.com/w/cpp/compiler_support

> - P0296R1 処理の進行保証 は実装に影響しないので `No` ではなく `-` にすべきではないでしょうか？

はい。

**Comment by faithandbrave** [comment]
対応状況の表はGitHubでバージョン管理されているようなのですが、そちらではNoのままになっていました。
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/visual-cpp-language-conformance.md

**Comment by faithandbrave** [comment]
15.7で対応されていなければ、Noのままでよいように思います。

15.3のリリースノート (?) ページでもNoになっています。
https://blogs.msdn.microsoft.com/vcblog/2017/08/11/c17-features-and-stl-fixes-in-vs-2017-15-3/
