### ISSUE TITLE
wcout/wcin/wclog/wcerrの記事の執筆について

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#559]
現在wcout/wcin/wclog/wcerrは単独の記事がなく、`.nolink`とされている状態です。

ところでこの記事を執筆する場合、このchar版であるcout/cin/clog/cerrの内容とほぼ同一になることが予想されます。

そこでむしろchar版の記事にこれらについても記載するようにするべきではないかと思うのですがどうでしょうか？

それで良ければそういう方向で編集したいと思います。

**Comment by yumetodo** [comment]
同じページに纏めている例
[std::cout, std::wcout - cppreference.com](https://en.cppreference.com/w/cpp/io/cout)

**Comment by faithandbrave** [comment]
ひとまず、その方法で大丈夫です。
いまでも`set`と`multiset`のメンバ関数は共通のページで運用しています。`<stdexcept>`とかもそうです。
元々ひとつのページで運用していたページが、個別の説明が入ってごちゃごちゃしてきたことで、ページをあとから分割したところも多数あります (`<functional>`の関数オブジェクトとかが、グループ単位で解説されていました)。

ただ、ページタイトルはサイト内検索エンジンの都合もあるので、ひとまず`char`版のものにしておいてください。

**Comment by yumetodo** [comment]
了解しました。
