### ISSUE TITLE
関数の例外安全に関する記載について

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#562]
例外安全について記載する際、「例外」のセクションを作った方がよいでしょうか？
多くのページには「例外」のセクションがあるようなのですが（前に自分も書いてた…）、よくよく見たらテンプレートページには無いのに気が付いたので…

**Comment by faithandbrave** [comment]
そうですね。
「## 例外」は、このサイト (のページ雛形) を作った段階ではコンテナくらいしか例外を投げなかったので、一部でしか使わない項目として雛形に項目を作っていなかったですが、例外を投げる機能も増えてきたので、雛形に入れてもよいかと思います。

それと、「## 例外」はいまのところ、例外を投げるか投げないか、投げる場合はどんな条件でなにを投げるかを記載していますが、例外安全の説明としてそれが今後十分かは調査しきれていません (処理に失敗したあとの状態)。

**Comment by yumetodo** [comment]
そういえば時折例外がどうなのかわからなくて結局規格書を見に行く事案に遭遇している・・・

**Comment by kariya-mitsuru** [comment]
なるほど、少なくとも現時点では例外安全の説明についての記載を意図されているわけではない、ということですね。
まずは現状をざっと眺めてみます。

**Comment by faithandbrave** [comment]
自分で書いてすっかり忘れていたのですが、`optional::swap()`には、例外安全性の項目を作っていました。
ほかはないと思います。
https://cpprefjp.github.io/reference/optional/optional/swap.html

**Comment by faithandbrave** [comment]
`## 例外`の項目ですが、`noexcept`演算子内の条件式と、例外安全性についても記載してよいかと思いました。

前者も「例外を投げない保証」という意味で例外安全性ですが、「`noexcept(false)`の場合、なんらかの例外を送出する可能性がある」という文章を書きたかったら、`noexcept`演算子内の条件式とセットで書かないと文章が分散してわかりにくいのではないかと思いました。

これで問題なければ、ひな形ページに説明を追記します。
