### ISSUE TITLE
可変引数テンプレートのstd::move

### ISSUE THREAD

**Issue by znz** [cpprefjp/site#563]
https://cpprefjp.github.io/lang/cpp11/variadic_templates.html に

```c++
template <class Head, class... Tail>
void print(Head&& head, Tail&&... tail)
{
  std::cout << head << std::endl;

  // パラメータパックtailをさらにheadとtailに分割する
  print(std::move(tail)...);
}
```

とありますが、この `std::move` は `std::forward` でなくても良いのでしょうか?

**Comment by yumetodo** [comment]
だめなはず・・・

**Comment by yumetodo** [comment]
というかこの記事よく見たら
https://cpprefjp.github.io/lang/cpp17/folding_expressions.html
fold式(C++17)へのリンク貼ってない・・・

**Comment by faithandbrave** [comment]
修正しました。
