### ISSUE TITLE
「コンパイラの実装状況」の言語機能のリンク先について

### ISSUE THREAD

**Issue by ToruNiina** [cpprefjp/site#565]
C++11, C++14ではcpprefjpの言語機能ページへ遷移しますが、C++17では現在全てが個別のペーパーへのリンクになっています。また、C++20に関してはどうやら（ちゃんと確認していないですが）cpprefjp内に記事が存在するものはそのページへのリンクに、それ以外はペーパーへのリンクになっているようです。これは推測ですが、言語機能の説明を追加し次第リンクを変更するという流れだったのが人手不足でそのままになっているのではないでしょうか。

他に理由がありましたら閉じていただいて結構です。
単純に人手不足が理由でしたらあとでPull Reqを送ろうと思っていますが、どうでしょう。

**Comment by faithandbrave** [comment]
あ、すいません。
あとでまとめてcpprefjp内の解説ページへのリンクに置き換えようかと思っていましたが、ライブラリの方の作業がいそがしくて言語解説が滞っていました。
言語解説がすぐに進むわけでもないので、置き換えていただいて大丈夫です。
