### ISSUE TITLE
any_castの要件と効果に現れるValueTypeについて

### ISSUE THREAD

**Issue by tshino** [cpprefjp/site#576]
any_castの要件と効果のところが、

> `using U = remove_cv_t<remove_reference_t<ValueType>>;`であるとして、

のようになっていますが、
この`ValueType`という型はページ内のどこにも説明がないため、何か間違えていると思いました。

`any_cast`のテンプレート引数`T`のことを指している気がしますが、
規格の文書がそもそも同様の記述で間違っているようなので、
適切な修正方法がよく分かりませんでした。
問題提起にとどまりますが、ご確認よろしくお願いします。

**Comment by faithandbrave** [comment]
N4762のworking draftでは以下のようになっているので、正しくは`T`ですね。

> Let `U` be the type `remove_cvref_t<T>`

**Comment by tshino** [comment]
確認ありがとうございます。残りも修正しました。
