### ISSUE TITLE
equivalentの訳語 : 等価か同等

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#582]
サイト内で、equivalentの訳語として「等価」と「同等」で表記揺れしています。どちらも多く使われていて、私は「同等」を使用していました。

[スタイルページの訳語表](https://cpprefjp.github.io/working_style.html)にも載っていなかったので、この機会に決めたいです。

決め方のポイントとしては、多くの文献で使われている一般的な訳語にしたいです。昔はxが使われていたけどいまはyが一般的とか、または分野によって使われる訳語が違うから本サイトではこれが適切、とかあるかと思います。

関連Issue :

- [累乗 or 冪乗 #204](https://github.com/cpprefjp/site/issues/204)
- [アライメントとアラインメント #344](https://github.com/cpprefjp/site/issues/344)

**Comment by faithandbrave** [comment]
C++規格書内での用語equivalentの使われ方ですが、以下のようになっています：

- 関数の効果として、関数`f()`は関数`g()`を呼び出すこととequivalentである
    - これは、関数内で使用する操作の要件と、意味論としてequivalentであるといっていて、その制約のなかでさらに最適化の余地があるため、完全に同じとは限らない
- filesystemライブラリの[`equivalent()`関数](https://cpprefjp.github.io/reference/filesystem/equivalent.html)
    - 「2つのエンティティが、ファイルシステムとして同等かを確認する。2つが同じパスの場合は同等、それに加えてシンボリックリンクと元のファイルも同等、同じinodeを参照するハードリンクも同等と判断される。」
- [`error_category::equivalent()`メンバ関数](https://cpprefjp.github.io/reference/system_error/error_category/equivalent.html)
    - エラーカテゴリ (enum) とエラー値 (int) が同値か
- equivalence relation
    - アルゴリズムの文脈で、A = BかつB = CであればA = Cである、というような関係性の意味として使われる。Wikipediaでは[同値関係](https://ja.wikipedia.org/wiki/%E5%90%8C%E5%80%A4%E9%96%A2%E4%BF%82)と訳されるが、本サイトでは等価関係になっている

**Comment by faithandbrave** [comment]
equivalence relationについては、等価関係よりも同値関係の方が使われてそうでした。
Googleの検索で見つかった件数としては、以下のようになっていました：

- 同値関係 "equivalence relation" : 834件
- 等価関係 "equivalence relation" : 420件

**Comment by faithandbrave** [comment]
equivalentの「等価」か「同等」かは、いま調べている限りではどちらも多く使われていて、同文書内でも表記揺れしているドキュメントが多く、判断つかない状況です。

個人の記事や論文は排して、書籍、企業の文献、集合知サイト、言語の (準) 公式ドキュメントをみて考える必要がありそうです。

**Comment by yumetodo** [comment]
C++03のJIS翻訳はどうしているんでしょう(自分は見たことない)

**Comment by faithandbrave** [comment]
C++03のJIS規格の訳語は、書籍とかでも使われないので一般訳語とは呼べず、参考にしないほうがよいと思います。

**Comment by yumetodo** [comment]
ECMAScriptのequality operators(`operator ==`)は等価演算子と翻訳されていた気がします
https://github.com/asciidwango/js-primer/commit/660a703bdf7816cbbf6c880a45caba2925a23575

**Comment by faithandbrave** [comment]
んー。ECMAScriptは、`operator==`が等価演算子 (equivalent相当) で、`operator===`が厳密等価演算子 (equality相当) という名前なんですね。
参考にはなりますが、言葉の使い方がC++と違うので微妙なところです。

**Comment by onihusube** [comment]
少し遠回りになりますが

Wikipediaでは[等価性（相等性）](https://ja.wikipedia.org/wiki/%E7%AD%89%E5%BC%8F)は反射律と代入原理を満たす二項関係とあります（この二つの性質はまとめて等号公理と呼ばれます）。

一方、[同値関係（equivalence relation）](https://ja.wikipedia.org/wiki/%E5%90%8C%E5%80%A4%E9%96%A2%E4%BF%82)は反射律・対象律・推移律を満たす二項関係とあります。
等号公理は同値関係の3つの性質に代入原理を足したものであり、等価関係⊂同値関係となります（すなわち、同値は等価を包含しているより弱い関係であり、等価は同値よりも強い関係です）。

また[記号論理における同値](https://ja.wikipedia.org/wiki/%E5%90%8C%E5%80%A4)では同値=等価と書かれていますが、記号論理における命題の同値関係は等号公理を満たしているため、同値関係＝等価関係となるのでこれは正しいです。

以上の事から、Wikipediaでは等価と同値を区別して書いていると思われます。

一方、上で上げられたC++規格書内でのequivalentの使用例や、その他のC++規格文書や提案文書の文脈でのequivalentは、そのほとんどが同値関係という意味合いで利用されています（例えば狭義の弱順序の文脈におけるequivalence、また[宇宙船演算子の提案](http://wg21.link/p0515r3)では明確に同値(equivalent)と等価(equal)が区別されています）。

これらのことから、equivalentの訳としては等価よりも同値もしくは同等がより相応しいかと思います。

しかし、Wikipedia以外に等価と同値を明確に区別して書かれたものや、equivalentの訳として同値（同等）・等価を区別して当てている日本語の文献は見つからなかったので根拠としてはとても弱いです・・・。

**Comment by tshino** [comment]
C++言語の文脈に限っても、
- filesystem::pathでは equivalent(path,path) と path==path が異なる効果をもつこと。
- 宇宙船演算子の提案ではequivalentとequalが別の意味として登場すること。

という事情があるのですね。
これらのことから、equivalent の訳語を決めるにあたって、
紛らわしい equal や operator== の表現も同時に考慮すべきということかと思いました。
これらが区別されるべき場所で混乱しないような訳語であれば望ましいと思います。

**Comment by faithandbrave** [comment]
equalに関しても決めておいたほうがいいですね。同値、等値、等価など、おそらく対になる訳語としてよくある組み合わせもあるでしょうから。

"equivalence relation"も、equivalentと同じ訳語を当てるべきかどうか決める必要があるかと思います。

**Comment by k-satoda** [comment]
僕は Effective STL 訳書 (ISBN 4894714108) の19項「等価と等値の違いを理解しよう」に沿って
"equal" を「等値」、 "equivalent" を「等価」、と使い分けていました。
https://www.google.com/search?q=%22Effective+STL%22+%E7%AD%89%E4%BE%A1+%E7%AD%89%E5%80%A4
https://showa-yojyo.github.io/notebook/meyers01.html#id23
http://skru-y.hatenablog.com/archive/2014/02/22

すでに挙がっているとおり数学的な用語の定着具合としては "equivalent" は「同値」と
されることが多いようで、僕も "equivalent class" についてだけ「同値類」という用語を
訳としてあててしまっています。
https://github.com/cpprefjp/site/commit/942cf01bcf3d5e5693fc511d7a7b696f1342d7b1#diff-17794bf3d42db70d4445a7d2b84ce74eR135
（「等価」を使った同義語が見当たらなかったため。）
ただ「同値」をライブラリ仕様の "Equivalent to:" の訳語としても使うかと考えると
少し不自然な感じがしてしまいます。

また「同値」あるいは「同等」とする場合は "equal" に対して（違いを示す）いい訳語を
選ぶのが難しそうに思いました。

**Comment by faithandbrave** [comment]
そうですね。ライブラリ機能の効果として、「以下の関数を呼び出すことと同値である」と説明するのは日本語として不自然に思います。
equivalentを「同等」とする場合は、対となるequalを「同値」とすると、「同値」をみて「これはequivalentの意味かequalの意味かあいまいだな」となりそうです。

なので、対の訳語として考える場合は、Effective STLにならってequalを「等値」、equivalentを「等価」とすると本サイトとしては使いやすそうに思います。
ただ、そうした場合は、"equivalence relation"をいまのまま「等価関係」としてよいのか、数学用語としてより使われている「同値関係」にすべきか、という選択肢があると思いますが、この3つの用語の訳語を決める観点でのご意見がほしいです。

**Comment by onihusube** [comment]
アルゴリズムの文脈での"equivalence relation"は狭義の弱順序の満たす反対称律より導かれる関係であり、狭義の弱順序も含めて数学的な定義から来ているので、"equivalence relation"は「同値関係」とした方が良いと思います。

equalを「等値」、equivalentを「等価」は他の文脈との兼ね合いを考えると適切だと思います。

**Comment by yumetodo** [comment]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">簡単に『同じ』は駄目か？</p>&mdash; 紺　露里 (@MaverickTse) <a href="https://twitter.com/MaverickTse/status/1092800345577791494?ref_src=twsrc%5Etfw">February 5, 2019</a></blockquote>

**Comment by faithandbrave** [comment]
@k-satoda さんのequivalence relationの訳語案については、サイト内の一貫性として「等価」にしておいたほうがいいから、ということですよね。
これについて、「数学の文脈では常に同値関係が使われるから、主として等価関係を使ってほしい」とかの強い反対意見がある方はいるでしょうか。

**Comment by onihusube** [comment]
数学の文脈で同値類を等価クラスとは言わないと思いますし、同値関係を等価関係も一般的ではないと思われます。

"equivalence relation"や"equivalence class"が登場するところは数学的な背景を伴っているのは明らかですので、正規表現の文脈よりもより広範な数学的な文脈での一般的用例を優先するべきだと考えます。

ですので、サイト内一貫性は損ねるかもしれませんが"equivalence relation"は同値関係、"equivalence class"は同値類としておいた方が他との整合性を取ることができると思います（等価関係、等価クラスではgoogle検索しても数学の同値関係、同値類にかかわるものが出てこない）。

**Comment by k-satoda** [comment]
@faithandbrave はいそうです。数学系の素養のある読者（おそらく少数派）は違和感を感じる
だろうなぁという懸念よりも、サイト内の一貫性を優先しての妥協案として考えています。

@onihusube 僕が思い当たっている具体的な問題としては "equivalence relation" の概念に
ここで初めて触れた読者が一般的でない用語を覚えてしまって困ったことになる、というような
ことが思い当たるんですが、↓のように併記してやることでほぼ無害化できるかと考えています。
```diff
diff --git a/reference/algorithm.md b/reference/algorithm.md
index 2fd0f2c4a..5aaf8f685 100644
--- a/reference/algorithm.md
+++ b/reference/algorithm.md
@@ -136,9 +136,11 @@ return distance(a, b);
   これらの前提のもと、以下を示すことができる。

   - `equiv` は等価関係 (equivalence relation) である
-  - `comp` は `equiv` によって決まる同値類の間での明確な関係を示す
+  - `comp` は `equiv` によって決まる等価クラス (equivalence class) の間での明確な関係を示す
   - その示される関係は狭義の全順序 (strict total ordering) である

+  数学用語の日本語訳として "equivalence relation" には「同値関係」 "equivalence class" には「同値類」が使われることが多いが、本サイトでは `operator==` による "equal" の関係を「等値」の関係として「等価」とは明確に区別するなどの目的で、比較的マイナーな訳語ではあるが「等価関係」「等価クラス」を使う。
+
```
具体的な問題としてほかに想定されていたこととかあれば教えてください。

なお先のコメントで「等価クラス」でもいいかと思った理由として、数は少ないものの
Google 検索でいくつか用例が見つかるようになっていたことがあります。
「出てこない」という状態ではなかったです。
- ["反射" "対称" "推移" "等価関係" site:ac.jp - Google 検索](https://www.google.com/search?q=%22%E5%8F%8D%E5%B0%84%22+%22%E5%AF%BE%E7%A7%B0%22+%22%E6%8E%A8%E7%A7%BB%22+%22%E7%AD%89%E4%BE%A1%E9%96%A2%E4%BF%82%22+site%3Aac.jp)
- ["反射" "対称" "推移" "等価関係" site:go.jp - Google 検索](https://www.google.com/search?q=%22%E5%8F%8D%E5%B0%84%22+%22%E5%AF%BE%E7%A7%B0%22+%22%E6%8E%A8%E7%A7%BB%22+%22%E7%AD%89%E4%BE%A1%E9%96%A2%E4%BF%82%22+site%3Ago.jp)
- [集合 "等価クラス" site:ac.jp - Google 検索](https://www.google.com/search?q=%E9%9B%86%E5%90%88+%22%E7%AD%89%E4%BE%A1%E3%82%AF%E3%83%A9%E3%82%B9%22+site%3Aac.jp)
- [集合 "等価クラス" site:go.jp - Google 検索](https://www.google.com/search?q=%E9%9B%86%E5%90%88+%22%E7%AD%89%E4%BE%A1%E3%82%AF%E3%83%A9%E3%82%B9%22+site%3Ago.jp)

**Comment by faithandbrave** [comment]
私の考えとしては、C++はとくに標準ライブラリについて多くの分野の機能が入っているという背景があるため、全体としての単語レベルの用語統一は (将来的に) できないと考えています。
ライブラリ機能としては、異なる分野で同名の機能があったら名前空間を分けることで意味を分けます。

そのため今回のケースでは、一般的なequal/equivalentと、数学的なequivalent relationで訳語は分かれていてよいのではないかと思います。

**Comment by onihusube** [comment]
@k-satoda 
"equivalence relation"の概念に初めて触れた読者の誤解や混乱を招くというのもそうですが、数学的な下地を持った人が見た時にも意味を捉える障害になるのではと思います。

ですので、一般的でない訳をメインに据えるよりは最初から一般的な訳を選択したほうが混乱が少ないと考えています。

後申し訳ないのですが、Google検索で出てこないというのは用例的な意味ではなく、知らない単語として検索された時に正しく関連したページが出てくるか、という観点で出てこないと言っていました。自然にごっちゃになってしまっていました、すいません。

**Comment by k-satoda** [comment]
狭義の弱順序の説明では「同値関係」「同値類」を使ったうえで、
他の文脈では「等価」を使う旨の説明を沿える方向で考え直してみました。
```diff
diff --git a/reference/algorithm.md b/reference/algorithm.md
index 2fd0f2c4a..4f1f48982 100644
--- a/reference/algorithm.md
+++ b/reference/algorithm.md
@@ -135,10 +135,12 @@ return distance(a, b);

   これらの前提のもと、以下を示すことができる。

-  - `equiv` は等価関係 (equivalence relation) である
-  - `comp` は `equiv` によって決まる同値類の間での明確な関係を示す
+  - `equiv` は同値関係 (equivalence relation) である
+  - `comp` は `equiv` によって決まる同値類 (equivalence class) の間での明確な関係を示す
   - その示される関係は狭義の全順序 (strict total ordering) である

+  数学用語の日本語訳として "equivalence relation" には「同値関係」 "equivalence class" には「同値類」が定着しており、同じく数学的な文脈では上記 `equiv` を満たす２つの値を「同値」 (equivalent) であると言う。しかし特に数学的でない文脈で「同値」と言った場合は `operator==` による "equal" の関係と誤解される可能性が高いと考えられるため、本サイトでは上記 `equiv` による "equivalent" の関係を「等価」 `operator==` による "equal" の関係を「等値」として区別する。
+
```
少しまどろっこしくなった気はしますがアリかとは思いますんで、こんな感じで
よさそうでしょうか？

元々「等価関係」としてたのは、こういう説明を考えるのが面倒だったこと、
こういう説明が必要になる「同値」という用語がそもそも良くないと考えた（僕自身が
馴染みのない分野の慣習の強さを知らず軽視した）こと、が理由だったと思います。

**Comment by faithandbrave** [comment]
ありがとうございます。これで結論とできそうですね。
`<algorithm>`ページについては @k-satoda さん案で修正し、訳語表にもそのように記載。その他全体的にequivalentを「等価」に修正していきます。

**Comment by faithandbrave** [comment]
一通り修正したつもりです。
修正漏れや修正ミス等ありましたら、このタイミングでなくてもいいので修正していただければと思います。

議論に参加していただいたみなさん、ありがとうございます。引き続きよろしくお願いします。
