### ISSUE TITLE
[C++17][ライブラリ] memory_resourceとpolymorphic_allocator関係

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#588]
- [P0220R1 Adopt Library Fundamentals V1 TS Components for C++17 (R1)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0220r1.html)
- [P0337R0 polymorphic_allocatorの代入演算子をdelete定義](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0337r0.html)

**Comment by onihusube** [comment]
終わりましたのでクローズします！

**Comment by yumetodo** [comment]
すくなくともstd::hashの特殊化について書き忘れています。

@onihusube 
他にもないか確認したほうが良さそう・・・

**Comment by onihusube** [comment]
おおう、全く気づきませんでした・・・

**Comment by onihusube** [comment]
N4659に記載が無いなあと思ったら、N4714から入ってるみたいですね  
これ欠陥扱いになっているんでしょうか・・・ちょっとわからないです

いい機会なので追加しておきます

- [N4714 Editors' Report](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4714.html)
- [2978. Hash support for pmr::string and friends](https://cplusplus.github.io/LWG/issue2978)

**Comment by onihusube** [comment]
追加すべきは`<string>`ヘッダくらいでしょうか
プルリクエストの方で修正されてるみたいですが、この場合はマージされるのを待った方が良いのでしょうか？

**Comment by yumetodo** [comment]
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">cpprefjpwikiのC++20の対応状況、N4714のLibrary Issueへの対応抜けてる・・・？</p>&mdash; キノコになりたい🍄 (@onihusube9) <a href="https://twitter.com/onihusube9/status/1131950467028725760?ref_src=twsrc%5Etfw">2019年5月24日</a></blockquote>
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">C++17の方に書いてますね。</p>&mdash; Akira Takahashi (@cpp_akira) <a href="https://twitter.com/cpp_akira/status/1131954176177532928?ref_src=twsrc%5Etfw">2019年5月24日</a></blockquote>
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">なるほど、これらはC++17扱いなのですね<br>見落としていました・・・</p>&mdash; キノコになりたい🍄 (@onihusube9) <a href="https://twitter.com/onihusube9/status/1131954875481243655?ref_src=twsrc%5Etfw">2019年5月24日</a></blockquote>

これの意味がよくわからないです・・・

**Comment by faithandbrave** [comment]
[N4714のEditor's Report](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4714.html)は、日付を見てもらえばわかりますが、C++17のInternational Standardがでる前に発行されたC++20に対する修正リストなのです。
なので、時期的に新機能ではなく仕様バグの修正はC++17に含めるように扱わないといけないものが多くあります。

**Comment by yumetodo** [comment]
> プルリクエストの方で修正されてるみたいですが、この場合はマージされるのを待った方が良いのでしょうか？

#652 は作業完了したのでmerge待ちです(自分でmergeするのは不安があるので)。
