### ISSUE TITLE
[C++17][ライブラリ] 連想コンテナのsplice

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#591]
- [P0083R3 Splicing Maps and Sets (Revision 5)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0083r3.pdf)
- [P0508R0 Wording for GB 58](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0508r0.html)

**Comment by faithandbrave** [comment]
すいません、`node_handle`型ですが、Webサイトのサイドバーが説明用の型のためのページを想定していなかったようで、ちょっと対応に時間がかかります。
`node_handle`階層以下 (メンバ関数とか) のページを作成する場合は、ひとまず`node_handle`ページと同様のページメタ情報 (言語バージョンのみ付ける) で作業しておいていただければと思います。

サイドバー側が対応したら、私の方でページのメタ情報を直します。

**Comment by alphya** [comment]
了解です。

**Comment by faithandbrave** [comment]
対応に時間がかかりそうなので、とりあえず仮で`<node_handle>`ヘッダを作って応急処置しました。
(ヘッダがないとツリーが作れないエラーになる)

正式な対応としては、`node_handle[meta header]`の代わりに`node_handle[meta category]`のようなものになるかと思います。機能としてはひとまずheaderと同等になる予定です。

**Comment by alphya** [comment]
了解しました！

**Comment by alphya** [comment]
記事ができたので、クローズします。
