### ISSUE TITLE
[C++20][ライブラリ] コンセプトページの雛形を作る

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#595]
C++20から言語機能としてコンセプトが入り、それにともなって、標準ライブラリにも`<concepts>`ヘッダにコンセプトが入ります。
ライブラリとして新たな分類の機能なので、雛形を決める必要があります。

このタスクを担当する方は、C++20の`<concepts>`ヘッダの全ての要素を記述できる雛形の作成をお願いします。手順としては、pull requestとしてある程度複雑なコンセプトのリファレンスを提出してレビューしてもらうか、もしくは同じくpull requestとして雛形の提出をしてレビューしてもらってください。

すでにある雛形は、`/editors_doc`ディレクトリ以下にあります。

**Comment by faithandbrave** [comment]
現在、本サイトの`<concepts>`にあるページは、C++11のライブラリ仕様が、入りそうで入らなかったコンセプト言語機能をベースにして書かれたので、説明のために用意したものになっています。

これからC++20向けにそれを置き換えていくことになりますが、`<concepts>`に含まれない`Callable`や`Invoke`は、どこかべつの場所に置くか、書き方を変えるかすることになります。

(Cpp17CopyConstructibleとかどうしようかなぁ・・・。)

**Comment by onihusube** [comment]
すでに[three_way_comparable(_with)](https://cpprefjp.github.io/reference/compare/three_way_comparable.html)で先走ってしまったのですが、いくつか疑問点がありましたのでこちらに。

1. コンセプトをモデル化する（あるいはコンセプトのモデルとなる）型の条件について
コンパイル時にチェックはされないけれど、そのコンセプトを満たすならば満たしていることが要求される意味論的な要件について、どう記述するか？
2. `three_way_comparable`と`three_way_comparable_with`のような関係の2つのコンセプトのページ
説明専用コンセプトなど含めて記述が似通っている場合が多いようですが、ページ分けした方がいいか？
3. 説明専用コンセプトの記述
`range`のコンセプトなども含めて説明専用のコンセプトが多用されているようなので、それはどのように記述されたほうが良いのか？

私はとりあえず、モデルとなる条件は構文的な条件とは分離して、`_with`なコンセプトは1つのページにまとめ、説明専用コンセプトは要件の所にだけ記述しました。

それぞれ、どうするのが良いでしょう？

**Comment by faithandbrave** [comment]
必ずしも規格書用語を使う必要はないので、「モデル」とだけ書いてなにを意味するのかがわかるようどこかに書いておくか、より説明的な項目名にするかですかね。

ほかにも言えるページ分けの基準ですが、関連するものを比較・俯瞰しながら読めたほうがいいのならまとめる、バージョンを重ねて、個々の機能のバージョンごとの違いが多く読みにくくなってきたら分ける、でよいかと思います。

説明専用のコンセプトは、少なくともページ先頭の宣言には含めないほうがよいように思っています。規格書と同じように、ハイフン区切りで斜体の識別子を説明用のものとするサイト内ルールにしておけばいいような気はします。
クラスにも似たような説明用変数とかがあって、そういうのはメンバ関数の個別ページで「説明用変数としてxxを意味する`xx`があるとして、」のようなことを書いていますが、そのようなお断りを毎回書いてもいいかもしれません。その説明が多くて煩わしいようなら、サイトルールの表記を作って個別ページでは断りなしにする感じでしょうか。
全体を把握できていないので、判断しにくいです。

**Comment by faithandbrave** [comment]
コンセプトライブラリはそれなりに大きくてあちこちに分散してるので、いきなり全てを満たす雛形を作るのはむずかしい気がしてきました。
一旦、いまある`<concepts>`と`<compare>`のコンセプトで雛形を作って、`<iterator>`とか`<ranges>`とかはあとで考えて雛形を改訂するのがいいですかね。

@onihusube さんに書いていただいた部分も一通り見て、いま私が把握できる範囲で雛形を作ってPull Requestを出してみます。

**Comment by onihusube** [comment]
そうですね、最初から完璧を目指すにはあまりにも壁が高そうです

お忙しい中タスク投げつけてしまってすいません・・・

**Comment by faithandbrave** [comment]
onihusubeさんの書き方の方向で、この項目でよい気がします。これでひな形を書いてみます。

- 宣言
- 概要
- 要件
- モデル
- 備考
- 例
- バージョン
- 関連項目
- 参照
