### ISSUE TITLE
[C++20][ライブラリ] 三方比較演算子のページ名を決める

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#596]
- [ページファイル名の付け方](https://cpprefjp.github.io/editors_doc/page_names.html)

候補：

- `op_3way_comp` (規格書上の正式な比較演算子名がThree-way comparison operator (三方比較), `lexicographical_compare_3way`アルゴリズムも入るので使いやすい)
- `op_threeway_comp`
- `op_spaceship` (規格書上でも`[expr.spaceship]`とかの短い表記として使われている)
- `op_consistent_comp` (提案ではconsistent comparisonとなっているが、規格書上では使われていない)

個人的には`op_3way_comp`でよいかと考えています。正式名称であることと、`lexicographical_compare_3way`との対応が理由です。

反論、賛成等あればご意見ください。

**Comment by faithandbrave** [comment]
ページ名が決まったら、サイドバーでのページの表示順に追加します。
https://github.com/cpprefjp/site_generator/blob/a17f589c894f33b76b00e13890e2abef6bfcd551/settings/cpprefjp.py

**Comment by yumetodo** [comment]
`op_3way_comp`が適当と思います。

**Comment by usagi** [comment]
1. `op_3way_comp` 
---
経緯: 素直だし日本語名称として普及するであろう呼び方からも想起されやすい。次点で准正式名称的にも扱われる `op_spaceship` にも票を入れようかと思ったけれど、少なくとも≪ここ≫では俗称に配慮あるいは俗称を優先する理由は無い部分と思い、 vote は `op_3way_comp` のみに絞りました。

**Comment by yumetodo** [comment]
調べるうちに前言撤回して`op_spaceship`を推したくなってきました。宇宙船演算子のほうが三方比較演算子という訳より定着している感があるので(Wikipediaの日本語版記事も[宇宙船演算子](https://ja.wikipedia.org/wiki/%E5%AE%87%E5%AE%99%E8%88%B9%E6%BC%94%E7%AE%97%E5%AD%90)でPHP7に由来か？)、ファイル名も合わせたほうがいいのかなと。

**Comment by usagi** [comment]
ここはユーザビリティーへの配慮を公式性のようなものよりも優先する合理性は無いところかなって思考から私は `op_3way_comp` へ入れましたのでその意見と思考については変化ありませんが、`op_spaceship` に反対する強い理由や気持ちもないので、他の方の意見や議論の流れで合理性が判断できればまあそれでもいっかー、くらいのゆるいお気持ちです。
---
おまけ: https://twitter.com/kariya_mitsuru/status/1100559595481624576 みたいな雑談もありました。"慣れのユーザビリティー"や直感性のユーザビリティーを優先できるならば op_ufo.md はふざけているようであながちそうでもなく優れた提案だったかもしれないですね。（この issue は言語規格や公式の文書等で使う表現を議論する段階ではありませんので、これはあくまでもおまけの雑談）

**Comment by faithandbrave** [comment]
俗称として、正式でない文書で宇宙船演算子という言葉を使うのはよいと思うのですが、たとえば条件演算子 (conditional operator) を三項演算子 (ternary operator) と呼ばれて迷惑してる層はけっこういたりしますし (機能名ではなく分類名で呼んでいる)、機能を表す説明的な名称を使っておいたほうがよいのではないかと思います。

宇宙船演算子は、演算子の形を表すジョーク要素のある俗称ですが、その言葉自体は機能を説明していません。

ただこれは、必ずしも規格書で定める正式名称を使うべき、という主張ではありません。cpprefjpでは、規格書用語であるデータメンバ (data member) の代わりに、広く普及しているメンバ変数 (member variable) を使っています。

**Comment by yumetodo** [comment]
自分も`op_3way_comp`支持を放棄したわけではないんですが、

> その言葉自体は機能を説明していません。

すでにPHP7で使われている宇宙船演算子([Spaceship operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.spaceship-op))という語は普及しているようにみえるし、C++に追加されるそれと誤解を招くような点も見つからないので、そっちのほうが広く普及しちゃわないかなという懸念があるんですよね。今調べてびっくりしたのが「宇宙船演算子」でググるとPHP7の話を押しのけて7番目に
[［C++］素敵な宇宙船演算子（<=>） - 地面を見下ろす少年の足蹴にされる私](https://onihusube.hatenablog.com/entry/2019/01/13/180100)
が出てくるんですね。bingだと同サイトが2番目・・・。

そういえばcppreference.comは、と思って見たら三方比較演算子って言ってますね・・・悩ましい。

だれかもう何人か意見がほしい・・・

**Comment by akinomyoga** [comment]
記事中で "三方比較演算子" という名前を使うか "宇宙船演算子" という名前を使うかという話と、頁のファイル名を `op_3way_comp` にするか `op_spaceship` にするかという話が混ざっているような気がするのですが、これらの議論は独立にしても良いのではという気がします。両者が一致している必要性はあるでしょうか。例えば規格の three-way comparison operator と `[expr.spaceship]` / `[class.spaceship]` の様に違っていても良いのではという気がします。

----

以下個人的な感想なので真面目に考慮に入れて頂かなくても大丈夫ですが…

`op_3way_comp` というのが少し気持ち悪いなと思うのは無理やり縮めた感じがするということです。「省略・短縮は色々なやり方があり思い出しにくいのでしない方が良い」という話などを思うと、`op_spaceship` の方が簡潔ですっきりしていて覚えやすい感は確かにあります。例えば `op_3way_comp` の変形版として以下のようなものも考えても良いのかもしれません。

- `op_compare_3way` (典拠:`std::compare_3way`)
- `op_3way` (典拠: 規格 `[alg.3way]`)
- `op_three_way_comparison` (省略はしない版)

思い出しやすさで言うと `op_3way` または `op_three_way_comparison` でしょうか (variation で混乱しなそう)。長い物も含まれていますが、既に `op_left_shift_assign` などの頁名もあるようですから、短くする事に拘らなくても良いのかもしれないな、と思います。

**Comment by faithandbrave** [comment]
ページ名の議論としては、私はすでに示した`std::lexicographical_compare_3way`との対応として`
op_3way_comp`を推していました。
`lexicographical_compare_3way`の方は関数名としてそのままページ名になるので、そことの一貫性がほしいです。

`std::compare_3way`との対応で`op_compare_3way`でもよいですね。

**Comment by tshino** [comment]
`std::lexicographical_compare_3way`や`std::compare_3way`があるのなら、
`op_compare_3way`が一番ストレートでよいですね。

**Comment by akinomyoga** [comment]
確かに `std::compare_3way` が実質関数版の `operator<=>` である事を思うと `op_compare_3way` が良い気がしてきました。

**Comment by usagi** [comment]
このタスクは `op_compare_3way` にまとまった、と考えて良さそうだね💁

https://github.com/cpprefjp/site_generator の方にルール追加タスクを発行してこっちは完了させますね。
