### ISSUE TITLE
サイドバー及び検索が全滅している

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#597]
![image](https://user-images.githubusercontent.com/10869046/53415724-45209c00-3a15-11e9-9748-47f0c219dfbd.png)

左のサイドバーは回りっぱなし、検索ボックスはうんともすんとも言いません。

エラーそのものはcrsearchやkunaiで起きているように思えますが、正確に特定できていないのでとりあえずここに報告します。

Windows 10 Home x64

- Firefox 65.0.1 
- Google Chrome 72.0.3626.119

**Comment by faithandbrave** [comment]
おそらくこのコミットが原因です。
https://github.com/cpprefjp/site/commit/d52528c5b7e2d94da7d75fd313ebe7a4ee54f906

日時の全変換で直ったりするかなぁ、と期待してます。

**Comment by faithandbrave** [comment]
site_generatorでは、MarkdownをHTMLに変換してはいますが、cpprefjpの雛形に沿った記述になっているかはチェックしていません。
そのため、crsearch/kunaiの段階になってからエラーになっているのだと思います。

**Comment by yumetodo** [comment]
>おそらくこのコミットが原因です

ちなみにどのへんが不味そうなんでしょうか？

**Comment by faithandbrave** [comment]
crsearchのコードは見てないですが、1行目が `# ` はじまりになってなくて、ページタイトルをとれなくてサイドバーの生成でエラーになったとかかなぁ、と。

**Comment by faithandbrave** [comment]
<img width="977" alt="2019-02-26 22 53 52" src="https://user-images.githubusercontent.com/240038/53417699-79965700-3a19-11e9-88ca-fad3fe83fe9d.png">

GitHub Pagesの最新コミット (私のコミット) でDestructibleページのkeyがnullになってるので、まだおかしいかも。

**Comment by faithandbrave** [comment]
<img width="990" alt="2019-02-26 23 06 00" src="https://user-images.githubusercontent.com/240038/53418455-34732480-3a1b-11e9-8a46-e88b09d31b00.png">
<img width="856" alt="2019-02-26 23 06 24" src="https://user-images.githubusercontent.com/240038/53418456-34732480-3a1b-11e9-8dbd-e622ec75f1bb.png">

直りました。
なぜか一つ前のコミットを見てることがあるみたいですが、とりあえず直ったということで。

**Comment by faithandbrave** [comment]
site_generator側のこのへんのスクリプトがエラーがない前提で動いてるので、エラーを出力したら止まってくれるのかどうか・・・。
https://github.com/cpprefjp/site_generator/blob/master/crsearch.json/run.py#L221

**Comment by faithandbrave** [comment]
`<concept>`周りが所属ヘッダがない関係でツリーからはみ出てますね・・・。C++20のライブラリ機能で早めに置き換えないと・・・。

**Comment by onihusube** [comment]
書き換え後の確認が甘かったです、本当に申し訳ない・・・・
