### ISSUE TITLE
[C++17][言語機能] 集成体初期化の拡張

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#598]
- [P0017R1 Extension to aggregate initialization](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0017r1.html)

漏れていました。

**Comment by usagi** [comment]
- https://cpprefjp.github.io/lang/cpp17.html

![image](https://user-images.githubusercontent.com/115972/56066170-f0ad6200-5db1-11e9-96b2-4ce84bf4fc79.png)

- https://cpprefjp.github.io/lang/cpp17/extension_to_aggregate_initialization.html

デプロイサイトでの example 群の期待動作も確認。

と、いうわけで完了。
