### ISSUE TITLE
[C++17][ライブラリ] apply

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#599]
- [N3802 `apply()` call a function with arguments from a tuple](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3802.pdf)
- [N3829 `apply()` call a function with arguments from a tuple (V2)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3829.pdf)
- [N3915 `apply()` call a function with arguments from a tuple (V3)](http://isocpp.org/files/papers/N3915.pdf)
- [P0220R0 Adopt Library Fundamentals TS for C++17](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0220r0.html)
- [P0220R1 Adopt Library Fundamentals V1 TS Components for C++17 (R1)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0220r1.html)

**Comment by alphya** [comment]
完了したのでクローズします。
