### ISSUE TITLE
サイドバー及び検索が機能していない

### ISSUE THREAD

**Issue by alphya** [cpprefjp/site#600]
reference/node_handle/node_handle/swap_free.md を追加した際、サイドバーが機能しなくなりました。
そこで、swap_free.md を削除しましたが、サイドバーは機能しないままとなっています。

**Comment by faithandbrave** [comment]
あれ、すいません。確認不足でした。
おそらく日時の全変換で直ると思います。

サイドバーの修正は苦戦していて、しばらくかかりそうです。すいません…。

**Comment by alphya** [comment]
了解です！
サイドバーが対応するまでは、連想コンテナの追加のメンバ関数を書こうと思います！
