### ISSUE TITLE
ページ変換が止まっている

### ISSUE THREAD

**Issue by onihusube** [cpprefjp/site#601]
昨日から、なされた変更がcpprefjpサイトに反映されなくなっているようです。

**Comment by melpon** [comment]
確かに変換を実行してみると、唐突に何のエラーメッセージも無く、エラーコード1で終了しますね…なんだろ

**Comment by faithandbrave** [comment]
こんなのがでてました。
nbspが含まれているのが原因な気がします。

```
[Parse Error : reference/map/map.md]
  370 <td>C++17</td>
  371 </tr>
  372 <tr>
  373 <td><code>insert_return_type</code></td>
  374 <td>ノードを挿入した結果を記述するために使用されるクラス型。次のテンプレートの特殊化である。<br/> template&lt;class Iterator, class NodeType&gt; <br/>struct insert-return-type <br/>{ <br/>&nbsp;&nbsp;Iterator position; <br/>&nbsp;&nbsp;bool     inserted; <br/>&nbsp;&nbsp;NodeType node; <br/>}; <br/> ただし、<code>insert-return-type</code>の名前は説明用であり、未規定である。</td>
  375 <td>C++17</td>
  376 </tr>
  377 </tbody>
  378 </table>
  379 <h2>非メンバ関数</h2>
```

**Comment by faithandbrave** [comment]
表の中はあまりいろいろできないので、メンバ型用のページを作るか、表の外にコードブロックを書くかするのがいいと思います。とりあえず私の方で直します。

**Comment by faithandbrave** [comment]
@melpon 
サーバーの変換はなぜか途中で止まっていますが、手元で全変換したら最後まで行ったので、とりあえず全変換してもらいたいです。

**Comment by alphya** [comment]
修正ありがとうございます！

**Comment by faithandbrave** [comment]
メンバ型のページですが、雛形だけ作ってあります。unordered系のメンバ型の説明が長かったのでそのうち個別ページを作らないとなーと思って、ひとまず雛形ルールだけ決めてあります。
https://cpprefjp.github.io/editors_doc/type-type_template_page.html

**Comment by faithandbrave** [comment]
@melpon 相変わらずサーバーでの変換がなぜか途中で止まっていますが、ぼくはサーバーに入れないので、一旦調査をめるぽんにお願いしたいです。

**Comment by faithandbrave** [comment]
このコミットで直りましたね。調査ありがとうございます。
https://github.com/cpprefjp/site/commit/bea61ee74602c677ebf2e755028af7da3627f68e

謎の文字ってなんだろう・・・。Vimで制御文字とか表示する設定にしていても表示されない・・・。

**Comment by faithandbrave** [comment]
@onihusube さん、編集環境はどのようなものでしょうか？

**Comment by onihusube** [comment]
@faithandbrave 
主にVSCodeで書いております。

cppreference.comの対応するページから関数名やクラス名をコピペするときに引っ付いてきてる様子なので、今後より注意しますorz

**Comment by kariya-mitsuru** [comment]
入ってたのはソフトハイフンですね。
[Unicode Character 'SOFT HYPHEN' (U+00AD)](https://www.fileformat.info/info/unicode/char/00ad/index.htm)
今回の件と関係あるかどうかわかりませんが、こんなのを見つけました。
[767950 - Soft hyphen is being included in a copy and paste clipboard operation - chromium - Monorail](https://bugs.chromium.org/p/chromium/issues/detail?id=767950)
