### ISSUE TITLE
stringの比較

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#603]
https://github.com/cpprefjp/site/commit/9695dd41b41932e74b901b339ed4cc450e667f0e#commitcomment-32878434

@k-satoda さんから @onihusube さん宛に、コミットに対するコメントとして指摘が上がっていたので、issueとして拾っておきます。

それと、直前のコミットですが、これも「デフォルトの`char_traits`では」を先頭に付けるか「(この動作は`char_traits`でカスタマイズでき、大文字・小文字を区別しない比較もできる)」のような注釈が必要かと思います。
https://github.com/cpprefjp/site/commit/3884cfcca7cb4fee1e5be5a79a414ee8456d8faf

**Comment by onihusube** [comment]
恥ずかしながら`char_traits`の役割を全く知りませんでしたorz
等価比較についてはご指摘の通りに修正しておきます。

**Comment by faithandbrave** [comment]
対応ありがとうございます。
