### ISSUE TITLE
基本クラスと基底クラスという用語がまぜこぜで使われている

### ISSUE THREAD

**Issue by agate-pris** [cpprefjp/site#612]
[is_standard_layout - cpprefjp C++日本語リファレンス](https://cpprefjp.github.io/reference/type_traits/is_standard_layout.html) を見ていて気になったのですが, 「基本クラス」と「基底クラス」という言葉が同じ意味でありながらまぜこぜで使われている場面が見受けられます.

基本的に, どちらかに統一すべきと考えます. 私は base class という言葉の翻訳として「基底クラス」を支持します. 特に問題が無ければ実際の変更作業は私がやりたいと思います. まずは皆さんの意見を伺えますでしょうか?

作業の流れとしてはフォークして pull request を送ればよいだけでしょうか?

**Comment by faithandbrave** [comment]
ありがとうございます。数日意見を待って、反論なければ「基本クラス」に統一する修正をしていただければと思います。
ここで合意が得られれば、Pull Requestでなく直接修正で大丈夫です。

こちらに訳語表があるので、そちらにも修正お願いします。
https://github.com/cpprefjp/site/blob/master/working_style.md

**Comment by agate-pris** [comment]
承知しました。

**Comment by melpon** [comment]
> 反論なければ「基本クラス」に統一する修正をしていただければ

これは「基底クラス」のtypoですかね？

**Comment by yumetodo** [comment]
base classの訳は「基底クラス」が適当じゃないかと思うのですが

**Comment by akinomyoga** [comment]
因みに JIS X 3014:2003 でも「基底クラス」ですね。記事の数は同じくらいのようです。

- <a href="https://www.google.co.jp/search?q=%22%E5%9F%BA%E6%9C%AC%E3%82%AF%E3%83%A9%E3%82%B9%22%20site%3Acpprefjp.github.io">"基本クラス" site:cpprefjp.github.io - Google 検索</a> 29件
- <a href="https://www.google.co.jp/search?q=%22%E5%9F%BA%E5%BA%95%E3%82%AF%E3%83%A9%E3%82%B9%22%20site%3Acpprefjp.github.io">"基底クラス" site:cpprefjp.github.io - Google 検索</a> 28件

**Comment by faithandbrave** [comment]
あ、すいません。ちぐはぐなこと言ってました。
私は統一されていればどちらでもいいので、反論なければ「基底クラス」で。

**Comment by agate-pris** [comment]
基底クラス派が多く根拠もあるので、週末までに何もなければそちらで良さそうですね。 fundamental type との混同が無いようにだけ気を付けます。

**Comment by usagi** [comment]
`基本クラス` / `基底クラス` に関連して `基本型` / `基底型` も一緒にチェック＆必要に応じて統一をこのタスクに加えて頂けると嬉しいかも。（タスク粒度または他の理由から別タスクにするのももちろんアリ。）

![image](https://user-images.githubusercontent.com/115972/56082391-500f7e80-5e53-11e9-927b-452c34a2433d.png)

![image](https://user-images.githubusercontent.com/115972/56082397-5e5d9a80-5e53-11e9-9460-2fb3b781002b.png)

**Comment by agate-pris** [comment]
基底クラスに対する反対意見内容なので進め始めます。

**Comment by agate-pris** [comment]
プッシュ権限を持っていないので結局プルリクエストを送りました。

既に訳語表に _fundamental type_ が入っており、かつその訳語が「基本型」となっている個所が存在しました。よって、混乱を防ぐため、そちらの修正を先に行い単一のプルリクエストとしました。

**Comment by faithandbrave** [comment]
完了しているようなので閉じます。

**Comment by agate-pris** [comment]
何故か完了していないと思いこんでいました。 ありがとうございます。
