### ISSUE TITLE
一部を除いてほとんど内容が同じクラスに関してページを纏めることの可否 

### ISSUE THREAD

**Issue by onihusube** [cpprefjp/site#621]
#588 の作業の中でsynchronized_pool_resourceとunsynchronized_pool_resourceという二つのクラスのリファレンスを書こうしているのですが、この二つのクラスはスレッドセーフであるか否かという点を除いて全く同じ内容になりそうです。  
そして、参照している規格（N4659）においても、この二つはPool resourceとしてまとめて書かれています。

この様な場合にこの二つのクラスのリファレンスを1つのページに纏めることは許されるのでしょうか？  
纏めるとした場合ページ名等は合意を取った方がいいのでしょうか？また、過去にまとめた例があれば教えて頂きたいです。

纏めるとしたら、pool_resource.mdとしてヘッダページを纏めて、pool_resourceというフォルダ配下に各メンバの説明を追加していくことを考えています。

- [Pool resource classes - N4659](https://timsong-cpp.github.io/cppwp/n4659/mem.res#pool)

**Comment by faithandbrave** [comment]
まとめていただくのは問題ないです。
このサイト内でも、いくつかの箇所でページをまとめているところはあります。

https://cpprefjp.github.io/reference/ratio/si_prefix.html
https://cpprefjp.github.io/reference/execution/execution/execution_policy.html

`plus`/`minus`、`equal_to`/`less`などの関数オブジェクトも、元々はページを統合して解説していました。
バージョンが上がるに連れて、どの機能がどのバージョンから、ということの管理がむずかしくなってくると別ページに分けたほうがいい、ということが後々でてくるかもしれませんが、現状でページを統合した方が解説しやすい・見通しがよい・管理しやすいなどがあれば、統合していただいて大丈夫です。

**Comment by faithandbrave** [comment]
https://cpprefjp.github.io/reference/atomic/atomic.html

`atomic`クラスのページは、特定の特殊化にのみあるメンバ関数と共通のメンバ関数で、ページ内で表を分けていたりするので、似た構成にしやすいかもしれません。

**Comment by onihusube** [comment]
atomicのページとても参考になりそうです、ありがとうございます！

pool_resourceとしてまとめて書くことにします。
