### ISSUE TITLE
valarray の関数の戻り値型について（ご意見募集）

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site#626]
`<valarray>` の関数で、戻り値型が `valarray<T>` になっているものは、式テンプレートでの実装を可能とするために規格上 `valarray<T>` 以外の型を返す事が認められています。
参考 [http://eel.is/c++draft/numarray#valarray.syn-3](http://eel.is/c++draft/numarray#valarray.syn-3)

何らかの形でこの内容について触れておいた方が良いと思うのですが、皆さんは以下のいずれの書き方が良いと思いますか？

1. `valarray` のクラスのページにその旨を記載しておく。
2. 各関数のページにその旨を記載しておく。
3. その他

各関数のページに書くと分かりやすいとは思うのですが、ちょっと鬱陶しいかなと思うのと、書くのが面倒だなと思うので、1 かなぁ、と思ってるのですが…

**Comment by kariya-mitsuru** [comment]
あ、すみません、もう一つ。
各関数のページの宣言部分の `valarray<T>` って書いてある所を、どのように記載したらいいかもご意見欲しいです。

1. `valarray<T>` のまま
2. `<cmath>` の *`Promoted`* とかみたいな書き方をする
3. その他

**Comment by faithandbrave** [comment]
Issueが立てられた時点ですでに対処は完了していますので、まずはコミット履歴を参照してください。

**Comment by faithandbrave** [comment]
宣言部分について、仕様のシグニチャが現実に即していないというのはたしかにあるので、unspecifiedや、`<cmath>`のPromotedに近い表記にするのは問題ないと思います。
ただし、比較演算子や論理演算子が`valarray<bool>`を返すことを考慮して、`UnspecifiedValarray<T>`, `UnspecifiedValarray<bool>`のようにテンプレート引数付きの斜体で書くことになると思います。

**Comment by kariya-mitsuru** [comment]
すみません、コミット気が付いてませんでした…
型の書き換え

**Comment by faithandbrave** [comment]
これで終了にしますね。
