### ISSUE TITLE
[C++20][ライブラリ] 不必要なexplicitデフォルトコンストラクタをなくす

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#634]
- [P0935R0 Eradicating unnecessarily explicit default constructors from the standard library](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0935r0.html)

オーバーロードの番号付け直しがたいへん。どこかに前例はあるはず。`vector`かどこか・・・。

-----

作業用に P0935R0 から生成したチェック付きリストを @usagi が加筆 ( issue の top にあったほうが便利よいので edit にて )

1. [ ] Edit 26.6.4.1 [queue.defn], class template queue synopsis, as indicated:
1. [ ] Edit 26.6.4.2 [queue.cons] before p2 as indicated:
1. [ ] Edit 26.6.5 [priority.queue], class template priority_queue synopsis, as indicated:
1. [ ] Edit 26.6.5.1 [priqueue.cons] before p1 as indicated:
1. [ ] Edit 26.6.6.1 [stack.defn], class template stack synopsis, as indicated:
1. [ ] Edit 26.6.6.2 [stack.cons] before p2 as indicated:
1. [ ] Edit 29.6.3.1 [rand.eng.lcong] after p1, class template linear_congruential_engine synopsis, as indicated:
1. [ ] Edit 29.6.3.1 [rand.eng.lcong] before p5 as indicated:
1. [ ] Edit 29.6.3.2 [rand.eng.mers] after p3, class template mersenne_twister_engine synopsis, as indicated:
1. [ ] Edit 29.6.3.2 [rand.eng.mers] before p6 as indicated:
1. [ ] Edit 29.6.3.3 [rand.eng.sub] after p4, class template subtract_with_carry_engine synopsis, as indicated:
1. [ ] Edit 29.6.3.3 [rand.eng.sub] before p7 as indicated:
1. [ ] Edit 29.6.6 [rand.device] after p2, class random_device synopsis, as indicated:
1. [ ] Edit 29.6.6 [rand.device] p3 as indicated:
1. [ ] Edit 29.6.8.2.1 [rand.dist.uni.int] after p1, class template uniform_int_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.2.1 [rand.dist.uni.int] before p2 as indicated:
1. [ ] Edit 29.6.8.2.2 [rand.dist.uni.real] after p1, class template uniform_real_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.2.2 [rand.dist.uni.real] before p2 as indicated:
1. [ ] Edit 29.6.8.3.1 [rand.dist.bern.bernoulli] after p1, class bernoulli_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.3.1 [rand.dist.bern.bernoulli] before p2 as indicated:
1. [ ] Edit 29.6.8.3.2 [rand.dist.bern.bin] after p1, class template binomial_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.3.2 [rand.dist.bern.bin] before p2 as indicated:
1. [ ] Edit 29.6.8.3.3 [rand.dist.bern.geo] after p1, class template geometric_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.3.3 [rand.dist.bern.geo] before p2 as indicated:
1. [ ] Edit 29.6.8.3.4 [rand.dist.bern.negbin] after p1, class template negative_binomial_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.3.4 [rand.dist.bern.negbin] before p2 as indicated:
1. [ ] Edit 29.6.8.4.1 [rand.dist.pois.poisson] after p1, class template poisson_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.1 [rand.dist.pois.poisson] before p2 as indicated:
1. [ ] Edit 29.6.8.4.2 [rand.dist.pois.exp] after p1, class template exponential_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.2 [rand.dist.pois.exp] before p2 as indicated:
1. [ ] Edit 29.6.8.4.3 [rand.dist.pois.gamma] after p1, class template gamma_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.3 [rand.dist.pois.gamma] before p2 as indicated:
1. [ ] Edit 29.6.8.4.4 [rand.dist.pois.weibull] after p1, class template weibull_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.4 [rand.dist.pois.weibull] before p2 as indicated:
1. [ ] Edit 29.6.8.4.5 [rand.dist.pois.extreme] after p1, class template extreme_value_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.5 [rand.dist.pois.extreme] before p2 as indicated:
1. [ ] Edit 29.6.8.5.1 [rand.dist.norm.normal] after p1, class template normal_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.1 [rand.dist.norm.normal] before p2 as indicated:
1. [ ] Edit 29.6.8.5.2 [rand.dist.norm.lognormal] after p1, class template lognormal_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.2 [rand.dist.norm.lognormal] before p2 as indicated:
1. [ ] Edit 29.6.8.5.3 [rand.dist.norm.chisq] after p1, class template chi_squared_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.3 [rand.dist.norm.chisq] before p2 as indicated:
1. [ ] Edit 29.6.8.5.4 [rand.dist.norm.cauchy] after p1, class template cauchy_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.4 [rand.dist.norm.cauchy] before p2 as indicated:
1. [ ] Edit 29.6.8.5.5 [rand.dist.norm.f] after p1, class template fisher_f_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.5 [rand.dist.norm.f] before p2 as indicated:
1. [ ] Edit 29.6.8.5.6 [rand.dist.norm.t] after p1, class template student_t_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.6 [rand.dist.norm.t] before p2 as indicated:
1. [ ] Edit 30.8.2 [stringbuf], class template basic_stringbuf synopsis, as indicated:
1. [ ] Edit 30.8.2.1 [stringbuf.cons] before p1 as indicated:
1. [ ] Edit 30.8.3 [istringstream], class template basic_istringstream synopsis, as indicated:
1. [ ] Edit 30.8.3.1 [istringstream.cons] before p1 as indicated:
1. [ ] Edit 30.8.4 [ostringstream], class template basic_ostringstream synopsis, as indicated:
1. [ ] Edit 30.8.4.1 [ostringstream.cons] before p1 as indicated:
1. [ ] Edit 30.8.5 [stringstream], class template basic_stringstream synopsis, as indicated:
1. [ ] Edit 30.8.5.1 [stringstream.cons] before p1 as indicated:
1. [ ] Edit 31.10 [re.results] after p4, class template match_results synopsis, as indicated:
1. [ ] Edit 31.10.1 [re.results.const] before p1 as indicated:
1. [ ] Edit D.7.1 [depr.strstreambuf], class strstreambuf synopsis, as indicated:
1. [ ] Edit D.7.1.1 [depr.strstreambuf.cons] before p1 as indicated:
1. [ ] Edit D.18.1 [depr.conversions.string] after p1, class template wstring_convert synopsis, as indicated:
1. [ ] Edit D.18.1 [depr.conversions.string] before p16 as indicated:
1. [ ] Edit D.18.2 [depr.conversions.buffer] after p1, class template wbuffer_convert synopsis, as indicated:
1. [ ] Edit D.18.2 [depr.conversions.buffer] before p9 as indicated:

**Comment by faithandbrave** [comment]
前例はvectorでした。
https://cpprefjp.github.io/reference/vector/vector/op_constructor.html

**Comment by usagi** [comment]
次の週末あたりに始めるけど…これはわりと作業量も多くて単純そうなので眠くなりそう。 P0935R0 で番号付けされた単位ごとに少しずつ作業して push しようかな。

**Comment by usagi** [comment]
1. [ ] Edit 26.6.4.1 [queue.defn], class template queue synopsis, as indicated:
1. [ ] Edit 26.6.4.2 [queue.cons] before p2 as indicated:
1. [ ] Edit 26.6.5 [priority.queue], class template priority_queue synopsis, as indicated:
1. [ ] Edit 26.6.5.1 [priqueue.cons] before p1 as indicated:
1. [ ] Edit 26.6.6.1 [stack.defn], class template stack synopsis, as indicated:
1. [ ] Edit 26.6.6.2 [stack.cons] before p2 as indicated:
1. [ ] Edit 29.6.3.1 [rand.eng.lcong] after p1, class template linear_congruential_engine synopsis, as indicated:
1. [ ] Edit 29.6.3.1 [rand.eng.lcong] before p5 as indicated:
1. [ ] Edit 29.6.3.2 [rand.eng.mers] after p3, class template mersenne_twister_engine synopsis, as indicated:
1. [ ] Edit 29.6.3.2 [rand.eng.mers] before p6 as indicated:
1. [ ] Edit 29.6.3.3 [rand.eng.sub] after p4, class template subtract_with_carry_engine synopsis, as indicated:
1. [ ] Edit 29.6.3.3 [rand.eng.sub] before p7 as indicated:
1. [ ] Edit 29.6.6 [rand.device] after p2, class random_device synopsis, as indicated:
1. [ ] Edit 29.6.6 [rand.device] p3 as indicated:
1. [ ] Edit 29.6.8.2.1 [rand.dist.uni.int] after p1, class template uniform_int_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.2.1 [rand.dist.uni.int] before p2 as indicated:
1. [ ] Edit 29.6.8.2.2 [rand.dist.uni.real] after p1, class template uniform_real_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.2.2 [rand.dist.uni.real] before p2 as indicated:
1. [ ] Edit 29.6.8.3.1 [rand.dist.bern.bernoulli] after p1, class bernoulli_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.3.1 [rand.dist.bern.bernoulli] before p2 as indicated:
1. [ ] Edit 29.6.8.3.2 [rand.dist.bern.bin] after p1, class template binomial_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.3.2 [rand.dist.bern.bin] before p2 as indicated:
1. [ ] Edit 29.6.8.3.3 [rand.dist.bern.geo] after p1, class template geometric_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.3.3 [rand.dist.bern.geo] before p2 as indicated:
1. [ ] Edit 29.6.8.3.4 [rand.dist.bern.negbin] after p1, class template negative_binomial_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.3.4 [rand.dist.bern.negbin] before p2 as indicated:
1. [ ] Edit 29.6.8.4.1 [rand.dist.pois.poisson] after p1, class template poisson_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.1 [rand.dist.pois.poisson] before p2 as indicated:
1. [ ] Edit 29.6.8.4.2 [rand.dist.pois.exp] after p1, class template exponential_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.2 [rand.dist.pois.exp] before p2 as indicated:
1. [ ] Edit 29.6.8.4.3 [rand.dist.pois.gamma] after p1, class template gamma_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.3 [rand.dist.pois.gamma] before p2 as indicated:
1. [ ] Edit 29.6.8.4.4 [rand.dist.pois.weibull] after p1, class template weibull_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.4 [rand.dist.pois.weibull] before p2 as indicated:
1. [ ] Edit 29.6.8.4.5 [rand.dist.pois.extreme] after p1, class template extreme_value_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.4.5 [rand.dist.pois.extreme] before p2 as indicated:
1. [ ] Edit 29.6.8.5.1 [rand.dist.norm.normal] after p1, class template normal_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.1 [rand.dist.norm.normal] before p2 as indicated:
1. [ ] Edit 29.6.8.5.2 [rand.dist.norm.lognormal] after p1, class template lognormal_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.2 [rand.dist.norm.lognormal] before p2 as indicated:
1. [ ] Edit 29.6.8.5.3 [rand.dist.norm.chisq] after p1, class template chi_squared_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.3 [rand.dist.norm.chisq] before p2 as indicated:
1. [ ] Edit 29.6.8.5.4 [rand.dist.norm.cauchy] after p1, class template cauchy_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.4 [rand.dist.norm.cauchy] before p2 as indicated:
1. [ ] Edit 29.6.8.5.5 [rand.dist.norm.f] after p1, class template fisher_f_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.5 [rand.dist.norm.f] before p2 as indicated:
1. [ ] Edit 29.6.8.5.6 [rand.dist.norm.t] after p1, class template student_t_distribution synopsis, as indicated:
1. [ ] Edit 29.6.8.5.6 [rand.dist.norm.t] before p2 as indicated:
1. [ ] Edit 30.8.2 [stringbuf], class template basic_stringbuf synopsis, as indicated:
1. [ ] Edit 30.8.2.1 [stringbuf.cons] before p1 as indicated:
1. [ ] Edit 30.8.3 [istringstream], class template basic_istringstream synopsis, as indicated:
1. [ ] Edit 30.8.3.1 [istringstream.cons] before p1 as indicated:
1. [ ] Edit 30.8.4 [ostringstream], class template basic_ostringstream synopsis, as indicated:
1. [ ] Edit 30.8.4.1 [ostringstream.cons] before p1 as indicated:
1. [ ] Edit 30.8.5 [stringstream], class template basic_stringstream synopsis, as indicated:
1. [ ] Edit 30.8.5.1 [stringstream.cons] before p1 as indicated:
1. [ ] Edit 31.10 [re.results] after p4, class template match_results synopsis, as indicated:
1. [ ] Edit 31.10.1 [re.results.const] before p1 as indicated:
1. [ ] Edit D.7.1 [depr.strstreambuf], class strstreambuf synopsis, as indicated:
1. [ ] Edit D.7.1.1 [depr.strstreambuf.cons] before p1 as indicated:
1. [ ] Edit D.18.1 [depr.conversions.string] after p1, class template wstring_convert synopsis, as indicated:
1. [ ] Edit D.18.1 [depr.conversions.string] before p16 as indicated:
1. [ ] Edit D.18.2 [depr.conversions.buffer] after p1, class template wbuffer_convert synopsis, as indicated:
1. [ ] Edit D.18.2 [depr.conversions.buffer] before p9 as indicated:

**Comment by usagi** [comment]
↑に書いても

![image](https://user-images.githubusercontent.com/115972/57162168-65f7da00-6e28-11e9-91b4-81265fb050fa.png)

が出ないみたいだし、 issue の top にチェック付きリストがあった方が便利なのでチェック付きリストを issue の top を edit で追加。

**Comment by faithandbrave** [comment]
こちら、引き取ります。

**Comment by faithandbrave** [comment]
@onihusube さんの方で作業完了してました。
https://github.com/cpprefjp/site/commit/ff7ce0c0ba1752d1379ae3286dd6d6560dacc749
