### ISSUE TITLE
[C++20][ライブラリ] assume_aligned

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#637]
- [P1007R3 `std::assume_aligned`](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1007r3.pdf)

**Comment by usagi** [comment]
今週末かこんどの国民的連休のあたりに書く予定、ということでアサイン。

**Comment by faithandbrave** [comment]
- [ポインタのアライメントを最適化ヒントとしてコンパイラに伝える `assume_aligned()` 関数 (P1007R3) - cppmap](https://cppmap.github.io/standardization/cpp20/#assume_aligned-p1007r3)
