### ISSUE TITLE
[C++20][ライブラリ] uses-allocator構築を実装するためのユーティリティ関数

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#639]
- [P0591R4 Utility functions to implement uses-allocator construction](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0591r4.pdf)

uses-allocatorわかりませぬ。

**Comment by kariya-mitsuru** [comment]
アロケータずきなので（わかるとは言ってない）、valarray 修正終わったらやりたいと思います。

**Comment by kariya-mitsuru** [comment]
終わったのでクローズします。

**Comment by kariya-mitsuru** [comment]
あ、すみません、#588 が終わったらそちらにも修正が必要なので、オープンのままの残しておきます…

**Comment by kariya-mitsuru** [comment]
`polymorphic_allocator::construct` の対応が終わったのでクローズします。
