### ISSUE TITLE
[C++20][ライブラリ] polymorphic_allocatorに、バイト列確保とオブジェクト領域確保の関数を追加

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#642]
- [P0339R6 `polymorphic_allocator<>` as a vocabulary type](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0339r6.pdf)

**Comment by faithandbrave** [comment]
#588 がおわってから

**Comment by onihusube** [comment]
完了しましたのでクローズします
