### ISSUE TITLE
言語機能/C++17の、タプルのコンストラクタの仕様の調整の記述のサンプルコードが謎

### ISSUE THREAD

**Issue by gengar** [cpprefjp/site#651]
https://cpprefjp.github.io/lang/cpp17.html のライブラリ更新の概要のタプルのところのサンプルコードで
```cpp
std::tuple<int, int> pixel_coordinates()
{
  return {10, -15};  // コンパイルエラー
}
```
とありますが、このコードはC++11からコンパイルできるように思います。

**Comment by onihusube** [comment]
この問題が解決されたのはC++17からですが、これは標準ライブラリの欠陥なので過去の標準に遡って適用されています。

解決されたのはC++17における[N4387](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4387)の採択によってですが、[元となったIssue報告](https://cplusplus.github.io/LWG/issue2051)は2011年に上がっているので、C++11まで遡って適用されているようです。  
このため、clangおよびgccは早い段階からこの問題を解決しています。

ちなみに、古いGCCだとこの現象を確認できます。  
https://wandbox.org/permlink/1s8oct6HhQ0mga4D

参考
- [標準C++の欠陥解決は、過去のバージョンに遡って適用される - Faith and Brave - C++で遊ぼう](https://faithandbrave.hateblo.jp/entry/2017/08/10/120545)

**Comment by faithandbrave** [comment]
まだC++17の概要ページにほんとうに概要を記載しただけで、ライブラリ側の正式対応をしていないのですが (オープンなままのタスクIssue #585 )、どこかで一部実装が早い段階からサポートしていて正式仕様があとから追いついた説明を記載しようと思います。

**Comment by gengar** [comment]
事情がよく分かりました。ありがとうございます。個人的な疑問は解決しましたが、これってissueとしてはどうなるんでしょう。assignされた人がcloseするのでしょうか。

**Comment by k-satoda** [comment]
（話をややこしくするようでちょっと心苦しいんですが・・・）
https://wg21.link/P0636R3 "Changes between C++14 and C++17" によれば
N4387 の採択は「欠陥(Defect Report = DR)」ではなく
「既存機能に対する変更(Modifications to existing features)」と分類されてるので、
少なくとも標準化委員会の意図としては遡って適用したつもりは無さそうだったりします。

**Comment by faithandbrave** [comment]
元のタスクは私が担当になっているので、私が対応したらこのIssueも合わせてクローズします。
正式対応する際にあらためてちゃんと調べて書きます。

**Comment by onihusube** [comment]
@k-satoda 
[C++ Standard Library Defect Report List](http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2051)にIssue2051がN4387で解決済みとして載っているのと  
cppreferece.comの[tuple](https://ja.cppreference.com/w/cpp/utility/tuple/tuple)、[pair](https://ja.cppreference.com/w/cpp/utility/pair/pair)のコンストラクタページではN4387が欠陥報告として扱われていることから判断しました。

欠陥報告の扱いについてしっかりと把握できてはいないので間違ってたらすいません・・・

**Comment by k-satoda** [comment]
@onihusube 現状では "Defect Report"(DR) の扱いについて「しっかり把握」というのは
だいぶ難しい状況にあると思ってます。

発行済み規格と DR の扱いについて P0636R3 にまとめられたものが標準化委員会の
立場としては「正しい」と言えるのかもしれませんけど、個々の実装がこの扱いに
従っているとは限りませんし、今後従うかと考えると、不可能だったり費用対効果が
見合わなかったりしそうです。

また、長らく LWG issues 解決の際にそれを DR として扱うかどうかが曖昧に
なっていて、近年になってようやくそのあたりを改めようという動きが少しずつ
進められている状況です。
例: [Retitle "Defect Report List" as "Defect Reports and Accepted Issues" ...](https://github.com/cplusplus/LWG/commit/9c0a27e72906c33298098706a06c11429ac9b56e)
このため DR であるかどうかが判断できないこともありそうです。

cppreference で N4387 を DR 扱いにした変更について、残念ながらその根拠は
ログから読み取れず、見つけられませんでした。
https://en.cppreference.com/mwiki/index.php?title=cpp/utility/pair/pair&diff=102454&oldid=102450
https://en.cppreference.com/mwiki/index.php?title=cpp/utility/tuple/tuple&diff=102451&oldid=101206
メジャーな実装の対応状況を見て書いてるかもしれなくて、ユーザー向けにはそれが
一番有益と言えそうな気もします。

**Comment by faithandbrave** [comment]
`tuple`と`pair`の各コンストラクタページに、処理系が早めに対応している場合があることを記載しました。C++17ページにあるのは概要であって詳細ではないので、そちらはそのままにしておきます。
これで対応完了です。
