### ISSUE TITLE
コード実行機能が動いていない

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#655]
wandboxが落ちているようなのでおそらくそういうことだとは思うのですが、念の為。

**Comment by faithandbrave** [comment]
https://twitter.com/melponn/status/1132889839248875520

> 【お知らせ】Wandbox は現在さくらVPSの障害で動作しません
> https://support.sakura.ad.jp/mainte/mainteentry.php?id=26292

**Comment by faithandbrave** [comment]
普及して動作したので閉じます。
