### ISSUE TITLE
[C++20][ライブラリ] 契約プログラミングサポート<contract>

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#662]
現状、言語機能側だけ対応されているので、備忘用にライブラリ側をタスク化しておきます。

**Comment by tetsurom** [comment]
Contracts自体無くなってしまいましたね……。

**Comment by yumetodo** [comment]
関連commitはbranch分けてrebaseしておき、masterからはrevertしておきますか？

**Comment by faithandbrave** [comment]
C++23に移動して、その後の設計改善に追従するのがよいかと思うのですが、どうでしょ。

**Comment by yumetodo** [comment]
それってC++23のページを作るってことでしょうか？時期尚早な気も・・・

**Comment by faithandbrave** [comment]
3年ごとのリリースなので次がC++23なのは決まっているのと、以前までcpprefjpの方針としてはCommittee Draftがでてからそのバージョンの作業を開始していたのが今は随時対応になっています。
次期バージョンについては確定した情報を提供するものではないので、C++23ページを用意してもよいという認識です。

**Comment by yumetodo** [comment]
そう言えばそうでした。結果的にC++23で契約が再び外れることがあってもその時考えればいいわけですしね。

**Comment by faithandbrave** [comment]
本件と関係なく、 #673 でC++23向けのページを作れるようにしておきました。

**Comment by tetsurom** [comment]
C++20としてはこれ以上できることがなさそうなので、一旦終了します。
