### ISSUE TITLE
[C++20][ライブラリ] 三方比較のライブラリサポート

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#663]
- [P0768R1 Library Support for the Spaceship (Comparison) Operator](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0768r1.pdf)

**Comment by onihusube** [comment]
`strong_equality`と`weak_equality`は削除されると言う話を耳にしたので、ページ作成は保留しておきます。

- [US170 17.11 [cmp] Remove strong_equality and weak_equality](https://github.com/cplusplus/nbballot/issues/168)

**Comment by onihusube** [comment]
終わりましたのでクローズします。
[P1614R2 The Mothership has Landed (Adding <=> to the Library)](http://wg21.link/p1614)の`<compare>`に関わる部分と`lexicographical_compare_three_way`の名前の変更部分は一緒にやっておきました。
