### ISSUE TITLE
bit_cast 実装イメージと未定義動作の話

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/site#664]
@faithandbrave さんの commit 1060be9e835aa4f5fe45bc52109e51fe7335934e の [bit_cast.md](https://github.com/cpprefjp/site/blob/1060be9e835aa4f5fe45bc52109e51fe7335934e/reference/bit/bit_cast.md) を見て気になったことです。
概要より:
> 低レイヤーのプログラムでは、同じビットを維持してほかの型に解釈し直すことが必要とされる。その際、`reinterpret_cast`や共用体を使用すると、Strict Aliasing規則に抵触してしまい未定義動作になってしまう。そのような目的には[`std::aligned_storage`](/reference/type_traits/aligned_storage.md)と`std::memcpy()`を組み合わせて使用することになるが、それを簡単に使用できるようにしたのが本関数である。

備考にある実装イメージより:
> ```cpp
> template<typename To, typename From>
> To bit_cast(const From& from) noexcept { // 実際には、さらに要件チェックが行われる
>   // To型のオブジェクトに直接memcpyするのではなく、アライメント調整した領域にmemcpyして、
>   // その領域をTo型に再解釈キャストする。
>   typename std::aligned_storage<sizeof(To), alignof(To)>::type storage;
>   std::memcpy(&storage, &from, sizeof(To));  // memcpyはconstexprではないため、
>                                              // コンパイラが特殊な実装をする必要がある
>   return reinterpret_cast<To&>(storage);
> }
> ```

僕の知る限りこの `return reinterpret_cast<T&>(storage)` は `return reinterpret_cast<To&>(from)` と同じく
実際のオブジェクトと無関係な型でのアクセスを起こすという理由で未定義動作の範囲内にあり、
違うのは memcpy を挟むことで現代のコンパイラで実際に誤動作に至る可能性をほぼ無くせること、
と認識しています。（この効果を一定条件下で規定しちゃおうというのが https://wg21.link/P0593 の目的、と。）

（↑の認識が正しいとして・・・）
現状の記事のままだと、概要の文面と合わせてこの aligned_storage と memcpy を使ったコードが
未定義動作を回避するものと読み取られそうでヤダなーと思ったんですが、だからといって
既存の手法や実装方法に関する記述をざっくり削除するというのも望ましくないものと思います。
というわけで、いったん issue にしてみることにしました。
認識の正誤や記事の改善方針について意見もらえるとうれしいです。

**Comment by yumetodo** [comment]
https://cpprefjp.github.io/reference/type_traits/aligned_storage.html
には

```cpp
template <class T, std::size_t Capacity>
class StackContainer {
  // 長さ：sizeof(T) * Count、
  // アライメント：alignof(T)
  // でアライメント調整された領域を作る
  typename
    std::aligned_storage<sizeof(T) * Capacity, alignof(T)>::type
  storage;

  std::size_t size_ = 0;

  T* data()
  {
    return static_cast<T*>(static_cast<void*>(&storage));
  }
```

という例が載っているんですが、この`static_cast`二段重ねも問題があるのでしょうか？

**Comment by onihusube** [comment]
static_castの二段重ねは同様のreintepre_castと同じです  
void*への・からのキャストがstrict aliasing ruleに違反するはず

**Comment by yumetodo** [comment]
というか前にどっかでその話聞いたと思ったら
std::aligned_storageを正しく使うためのstrict aliasing rulesとstd::launder - 地面を見下ろす少年の足蹴にされる私
https://onihusube.hatenablog.com/entry/2018/07/22/040059
これだ、placement newの戻り値を掴んで離すなっていう

**Comment by onihusube** [comment]
それ盛大に間違ったこと書いてたので恥ずかしい😅
placement newの戻り値を掴んで離すな、という所は間違ってないはずですけど、それをbit_castに適用しようとするとデフォルトコンストラクトかコピー/ムーブコンストラクトを要求してしまいます・・・

**Comment by yumetodo** [comment]
そういえば @yohhoy さんとやり取りされていたような薄い記憶

**Comment by faithandbrave** [comment]
反応が遅くなってしまってすいません。
`bit_cast`については説明を書き足すとして、`aligned_storage`の例は、以下のように直せば解決でしょうか？

```cpp
#include <iostream>
#include <type_traits>

template <class T, std::size_t Capacity>
class StackContainer {
  // 長さ：sizeof(T) * Count、
  // アライメント：alignof(T)
  // でアライメント調整された領域を作る
  typename
    std::aligned_storage<sizeof(T) * Capacity, alignof(T)>::type
  storage_;

  T* ptr_ = nullptr;
  std::size_t size_ = 0;

public:
  void push(T value)
  {
    // 未初期化領域に要素を作る
    if (size_ <= 0) {
      ptr_ = new (&storage_) T(value);
    }
    else {
      new (reinterpret_cast<T*>(&storage_) + size_) T(value);
    }
    ++size_;
  }

  T& front()
  {
    return *ptr_;
  }

  ~StackContainer()
  {
    for (std::size_t i = 0; i < size_; ++i) {
      (ptr_ + i)->~T();
    }
  }
};

int main()
{
  StackContainer<int, 3> cont;
  cont.push(1);

  std::cout << cont.front() << std::endl;
}
```

**Comment by faithandbrave** [comment]
実装はもともとBoost.Containerの`static_vector`を参考にしていたのですが、あちらが持っている`aligned_storage`にはStrict Aliasing回避用に`data`メンバ変数があってそれを使ってるみたいでした。

**Comment by faithandbrave** [comment]
`bit_cast`の実装イメージに説明付け足しを行いました。

**Comment by k-satoda** [comment]
（ひとまず aligned_storage の件について。何か話が広がりそうであれば
別 issue にしてもらったほうがいいと思います。）

@yumetodo aligned_storage の例にあるキャストは、 bit_cast の例のものと
違ってそこに実際に指定した型のオブジェクトが構築されます。これなら、
オブジェクト構築後に使う分にはほぼ問題無いと思います。

C++14 までは reinterpret_cast だけで有効な気配もあったんですけど、
おそらく現実のコンパイラの最適化と合致しなくなって下記の記述が無くなった
C++17 からは、厳密には std::launder() も加えないと未定義動作の範疇に
なります。
https://timsong-cpp.github.io/cppwp/n4140/basic.compound#3
> ... If an object of type T is located at an address A, a pointer of
> type cv T* whose value is the address A is said to point to that object,
> regardless of how the value was obtained. ...

@faithandbrave 修正案でこの点については改善されるように思います。
`reinterpret_cast<T*>(&storage_) + size_` は `ptr_ + size_` のほうが
簡単でよさそうです。

・・・配列オブジェクトを指さない ptr_ や &storage_ への `... + size_` が
未定義動作になるという問題 <https://wg21.cmeerw.net/cwg/issue2182> が
気になりましたが、回避しようと思うと aligned_storage ではなく
生のバイト配列を使う形にするぐらいしか思いつかないですし、
bit_cast の件と違って未定義動作について誤解を誘うような記述も無いので、
当面はこのままでもいいかと思います。

**Comment by k-satoda** [comment]
@faithandbrave 変更 24ba8177c61d2c49c7d49cba749f4ed07e460e46 見ました。
実装イメージが未定義動作を回避するものではないことを示すようになるのは
改善になると思います。でも、概要の文面にある「std::aligned_storageと
std::memcpy()を組み合わせて使用」もそのままとはいかないように思います。
（typo も見つけてます。 ×"String Aliasing規則" ○"Strict Aliasing規則"）

改めていくらか調べた結果として、以下の点から aligned_storage への言及を
削除してしまったほうがいいんじゃないかと思っています。
- bit_cast の提案 http://wg21.link/P0476 登場以前に aligned_storage と
  memcpy で問題を回避していたという実例が、少なくとも簡単な検索では
  見つけられなかったこと。
- p0476 提案者の LLVM へのコミット https://reviews.llvm.org/rL342739 を
  見るに、提案者もこの reinterpret_cast による aligned_storage からの
  読み取りが未定義動作になることを認識していなかったようであること。
- http://wg21.link/P1413R1 (.pdf) によれば、 aligned_storage は
  そのインターフェースに問題があり、非推奨とされる見込みもあること。

具体的な変更として、概要はこんな感じ:
> 低レイヤーのプログラムでは、同じビットを維持してほかの型に解釈し直したいことがある。その際、`reinterpret_cast`や共用体を使用すると、Strict Aliasing規則に抵触して未定義動作になってしまう。安全な方法としては`std::memcpy()`を使用するなどがあるが、面倒なことなどから前述の危険な方法が多く見られた。そこで、同等の操作を簡単で安全にできるようにしたのが本関数である。

実装イメージはこんな感じ:
> ```cpp
> template<typename To, typename From>
> To bit_cast(const From& from) noexcept { // 実際には、さらに要件チェックが行われる
>   // この実装ではTo型がデフォルト構築可能である必要があるが、C++20のbit_castでは必要無くなる
>   To result;
>   std::memcpy(&result, &from, sizeof(To));  // memcpyはconstexprではないため、
>                                             // コンパイラが特殊な実装をする必要がある
>   return result;
> }
> ```

こんな感じで、周辺の見直しも含めた変更を入れるのがいいかと思ってます。
どうでしょう？

**Comment by yumetodo** [comment]
> aligned_storage は
そのインターフェースに問題があり、非推奨とされる見込みもあること。

なんと・・・。

aligned_storage への言及を削除する方向に同意します。

**Comment by faithandbrave** [comment]
`aligned_storage`と`bit_cast`のページを修正しました。
問題あればreopenするか、直接修正するかお願いします。

それと、本Issueは`bit_cast`に関する問題でしたが、便乗で別件が混じってしまって議論と解決が難しかったです。ひとつの問題に集中できるよう、次からは便乗はせず別Issueとして起こしていただけると助かります。
