### ISSUE TITLE
VS2019 Previewの扱いについて

### ISSUE THREAD

**Issue by onihusube** [cpprefjp/site#672]
VS2019では正式リリースのチャネルと並行してPreview版の配信チャネルが存在しています。  
現在のところ、Previewチャネルではリリースチャネルと比較して1つ先のUpdateの内容が先行して利用できるようです。

- [Visual Studio 2019 RC と Preview 4 - ++C++; // 未確認飛行 C](https://ufcpp.net/blog/2019/2/vs2019rc/)
- [Visual Studio 2019 リリース ノート - Microsoft Docs](https://docs.microsoft.com/ja-jp/visualstudio/releases/2019/release-notes?view=vs-2019#visual-studio-2019-release-notes-history)
- [Visual Studio 2019 Preview リリース ノート - Microsoft Docs](https://docs.microsoft.com/ja-jp/visualstudio/releases/2019/release-notes-preview)

PreviewチャネルではVC++のC++20サポート状況も先行していて、現状では一貫比較機能のほぼフルサポートや`char8_t`とそのライブラリサポート、`std::endian`等の実装がリリースチャネルに先行して行われています。

このプレビュー版をどう扱うかは主に以下のような3つの選択肢があるかと思います

1.  Preview版を次のUpdateとして扱う
    - 現在、Update2(16.2)
2. 正式リリース版を基準とする
    - 現在、Update1(16.1)
3. Preview版とリリース版を区別する

なおcppreference.comでは1の方法を取っているようです。
- [C++ コンパイラのサポート状況 - cppreference.com](https://ja.cppreference.com/w/cpp/compiler_support)

コンパイラの実装状況ページとライブラリ機能の個別のページのごく一部と影響範囲はあまり大きくないですが、一つ決めておいた方が良いかなあと思います。

**Comment by faithandbrave** [comment]
次のUpdate扱いでよいかと思います。

**Comment by onihusube** [comment]
多分異論もないと思うのでそのように書くことにします！
