### ISSUE TITLE
[C++20][ライブラリ] allocator、vector、stringのconstexpr対応

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#688]
- [x] [P0784R7 More `constexpr` containers (言語側も)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0784r7.html)
- [x] [P1004R2 Making `std::vector` constexpr](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1004r2.pdf)
- [x] [P0980R1 Making `std::string` constexpr](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0980r1.pdf)

**Comment by onihusube** [comment]
P0784R7の言語部分は完了しました。

**Comment by faithandbrave** [comment]
Visual Studioでは`constexpr vector`とかが使えるようになっているらしく、Compiler Explorerで試せるようなので、試しながらリファレンスを書いていきます。
https://www.cppstories.com/2021/constexpr-vecstr-cpp20/
