### ISSUE TITLE
C++11 で map / set の erase(q1, q2) は空になる場合を考慮していない？

### ISSUE THREAD

**Issue by iooiau** [cpprefjp/site#692]
(multi)map|set の erase の「参照」節に以下の記述がありますが、

> LWG Issue 2258. a.erase(q1, q2) unable to directly return q2
> 
> C++11では、「a.erase(q1, q2)の結果としてq2が返る」という仕様だったが、要素を削除した結果としてコンテナが空になった場合や、最後尾の要素を削除した場合を、考慮していなかった。C++14では、空の場合にend()イテレータが返ることが明記された。

コンテナが空になる・最後尾の要素が削除されるというのは q2 に end() のイテレータが渡された場合以外にあり得ず、また連想コンテナの erase() によって end() が無効化されることは無いため、C++11 で空になった場合が考慮されていないということは無いのでは。
リンク先を見ても、q2 が const_iterator の場合そのまま返すことはできないと述べているだけで、この注釈にあるようなことは書かれていません。

**Comment by faithandbrave** [comment]
ありがとうございます。修正しました。
