### ISSUE TITLE
priority_queue 「処理順をカスタマイズする (C++11)」例がコンパイルできない

### ISSUE THREAD

**Issue by ShigekiKarita** [cpprefjp/site#695]
ページ https://cpprefjp.github.io/reference/queue/priority_queue.html の最後の例「処理順をカスタマイズする (C++11)」が gcc (9.2.0など) clang (9.0.0など) の -std=c++11 でコンパイルできません。-std=c++2aでは可能です。

https://wandbox.org/permlink/5EfkW40IwhVvNzNK

原因は下記のテンプレート引数のラムダ式の型が C++11 では無引数で構築できないことのようです。

```c++
    std::priority_queue<
      int,
      std::vector<int>,
      decltype(compare) // 比較関数オブジェクトを指定
    > que;
```

> ClosureType() = delete;  (until C++14)
> ClosureType() = default; (since C++20)(only if no captures are specified)
> https://en.cppreference.com/w/cpp/language/lambda

「C++20」の例として紹介するか、コンストラクタ引数にcompareを与えてみてはどうでしょうか？

```c++
    std::priority_queue<
      int,
      std::vector<int>,
      decltype(compare) // 比較関数オブジェクトを指定
    > que(compare);
```

https://wandbox.org/permlink/ex006GkEQpQ7VzHJ

**Comment by faithandbrave** [comment]
ありがとうございます。コンストラクタ引数を渡すよう修正しました。
