### ISSUE TITLE
一貫比較仕様により導出される比較演算子の記述について

### ISSUE THREAD

**Issue by onihusube** [cpprefjp/site#701]
現在 #663 の作業の中で、`<compare>`ヘッダの比較カテゴリ型のところを書いているのですが、これらの型の`!=`演算子は`==`から導出される事を前提として規格書からは記述が省略されています。  
この変更はP1614R2によって行われたものですが、この提案では標準ライブラリの幅広いクラスに対して同様の変更が行われています。

この場合に省略されている各演算子について、cpprefjpにはどう書くべきでしょうか？

選択肢としては以下のものがあるかと思います。

1. 省略する
2. 今まで通りに書く（個別のページで導出されている事を説明）
3. クラスページにだけ導出されている事とともに書いておく

なお、cppreference.comでは規格書に則り省略している模様です。

また、関連する問題としてC++17までは定義されている比較演算子がC++20からは同様に省略されている（記述として削除されている）ので、そちらもどう書けば良いのかというのもあります。
 
この2つのことは結果的に記述として整合が取れたものになると良いのかなと思います。

- 参考
  - [C++20 一貫比較](https://cpprefjp.github.io/lang/cpp20/consistent_comparison.html)
  - [P1614R2 The Mothership has Landed (Adding <=> to the Library)](http://wg21.link/p1614)

**Comment by faithandbrave** [comment]
cpprefjpでは、自動定義される特殊関数として、規格書に載っていないデストラクタとか代入演算子も`= default`としてクラスページに書いてたりはしますね (忘れてて書いていないものもありますが)。
リファレンスとしては、使える機能が列挙されていたほうが便利な気がします。

<https://cpprefjp.github.io/reference/chrono/duration.html>

| 名前                                      | 説明                  | 対応バージョン |
|-------------------------------------------|-----------------------|----------------|
|`(constructor)` | コンストラクタ        | C++11          |
| `~duration() = default;`                  | デストラクタ          | C++11          |
| `operator=(const duration&) = default;`   | 代入演算子            | C++11          |

これを前提とすると、以下のような方針がいい気がします。

- 個別ページがすでにあるものは残す
    - 個別ページでは、C++20から`= default`になったことを記載。備考で`operator==`または`operator<=>`から自動定義されることを記載
- C++20から追加されたクラスの場合は、クラスページの表に`= default`として自動定義される比較演算子を列挙する
    - `operator==`、`operator<=>`の個別ページには、この関数からなにが自動定義されるかを備考で列挙する

**Comment by faithandbrave** [comment]
これの結論がでたら、クラスの雛形ページに方針を記載しようと思います。

**Comment by faithandbrave** [comment]
`operator==`と`operator<=>`も`= default`の場合は、クラスページの表の外に、自動定義される演算子を列挙ですかね (これらの個別ページを作るのがめんどうな場合)。

| 名前 | 説明 | 対応バージョン |
|-----|-----|-----|
| `bool operator==(const X&, const X&) = default;` | 等値比較 | C++20 |
| `bool operator!=(const X&, const X&) = default;` | 非等値比較 | C++20 |
| `bool operator<=>(const X&, const X&) = default;` | 三方比較 | C++20 |
| `bool operator<(const X&, const X&) = default;` | 左辺が右辺より小さいかを判定する | C++20 |
| `bool operator<=(const X&, const X&) = default;` | 左辺が右辺以下を判定する | C++20 |
| `bool operator>(const X&, const X&) = default;` | 左辺が右辺より大きいかを判定する | C++20 |
| `bool operator>=(const X&, const X&) = default;` | 左辺が右辺以上かを判定する | C++20 |

`operator==`により、以下の演算子が自動定義される：

- `operator!=`

`operator<=>`により、以下の演算子が自動定義される：

- `operator<`
- `operator<=`
- `operator>`
- `operator>=`

**Comment by onihusube** [comment]
概ねそれで良いと思いますが、`<=> ==`から導出される演算子は`= default`で定義されているのとは異なり、`< <= > >= !=`演算子を明示的に`= default`する事は少し異なる意味を持ちます。  
大きなものは、アドレスが取れるかどうか、`friend`であるかが`<=> ==` と同じになるかどうか、です。  
P1614R2でも`<=> ==`以外は`= default`で定義されていないはずです。

`<=> ==`以外には`= default`と書いておくのはあまり適切ではなく、「自動定義」よりは「使用可能になる」等の別の表現がより適切かなあと思います。
（重箱の隅なので強い主張ではありませんが・・・）

**Comment by faithandbrave** [comment]
なるほど。それだと、こんな感じですかね。
ちょっと横に長くなりますが、`= default`が書けない代わりに、各行に`(xxにより使用可能)`を記載し、ページの書き残しではないことを明示するということで。

***

| 名前 | 説明 | 対応バージョン |
|-----|-----|-----|
| `bool operator==(const X&, const X&) = default;` | 等値比較 | C++20 |
| `bool operator!=(const X&, const X&);` | 非等値比較 (`==`により使用可能) | C++20 |
| `bool operator<=>(const X&, const X&) = default;` | 三方比較 | C++20 |
| `bool operator<(const X&, const X&);` | 左辺が右辺より小さいかを判定する (`<=>`により使用可能) | C++20 |
| `bool operator<=(const X&, const X&);` | 左辺が右辺以下を判定する (`<=>`により使用可能) | C++20 |
| `bool operator>(const X&, const X&);` | 左辺が右辺より大きいかを判定する (`<=>`により使用可能) | C++20 |
| `bool operator>=(const X&, const X&);` | 左辺が右辺以上かを判定する (`<=>`により使用可能) | C++20 |

**Comment by onihusube** [comment]
もう一つ細かいところが気になってしまったのですが

`= default`なものと、異種型間比較のうち片方の引数順のもので2種類以上の`== <=>`が定義されているとき、   
`= default`なものから導出される演算子は対応する5つ分ですが、異種型間比較の場合は引数順を逆にしたものも導出されるため、定義されている`== <=>`の1種類あたり最大で2×5 + 2×2の演算子が導出されます。

例えば[`strong_ordering`](http://eel.is/c++draft/cmp#strongord)をはじめとする比較カテゴリ型の`==`がそうです（現状は新規追加のクラスではこの他になさそうです）。

`== <=>`は個別ページに書けばいいとして、残りのものはこの場合どうするのが良いでしょう？  
数が増えたら個別ページを作った方が良いか、セル内の改行などによって表にそれぞれ書くか？

**Comment by faithandbrave** [comment]
そういう状況では、個別ページを作ったほうがいいと思いますね。

**Comment by faithandbrave** [comment]
あとは、個別ページでの、導出される関数の宣言の書き方ですかね。
宣言を書かず、説明で使用可能な組み合わせを列挙することも考えられますが、慣れ親しんだ記法で宣言があると使いやすいと思うので、コメントアウトとして宣言を列挙するのはどうでしょう。

```cpp
namespace std {
// operator<=>により、以下のオーバーロードが使用可能になる
// bool operator<(const X&, const X&) noexcept;
}
```

**Comment by onihusube** [comment]
コメントアウトしてしまうとハイライトがかからないので見辛くなってしまうのではと思います  
なので、`== <=>`から導出されるものに関してはこれまで番号を書いていたところに `//(1)により使用可能`のように書くのはどうでしょうか？

あと、`== <=>`から導出される残りの演算子の個別ページの宣言欄もともすれば全部コメントアウトで埋まるのはやはり見栄えが良くないかなあと思いますが、こちらはどうすればいい感じになるかちょっと思いつきません・・・

**Comment by faithandbrave** [comment]
あ、いえ。これは導出された関数用の`operator<`とかの専用ページの書き方の話ですね。

**Comment by faithandbrave** [comment]
コメントアウトが見づらいなら、コメントアウトせずに書いて、備考として「`operator<=>`から導出されたアドレスがとれない」とかの注記を書くとかでしょうか。

**Comment by onihusube** [comment]
あっ、すみません読み違いしてました・・・

備考に書いて置くだけだと通常定義の演算子と混在した時に見分けがつかなくなりそうなので、宣言のところで

```cpp
namespace std {
  bool operator<(const X&, const X&) noexcept;  // (1)
  ...

  // operator<=>により、以下のオーバーロードが使用可能になる
  bool operator<(const X&, const Y&) noexcept;
  bool operator<(const Y&, const X&) noexcept;
  ...
}
```

のように分けておくのはどうでしょう

**Comment by faithandbrave** [comment]
はい。そのうえでこれを

> 備考として「operator<=>から導出されたアドレスがとれない」とかの注記を書くとかでしょうか。

**Comment by onihusube** [comment]
そうですね、良いと思います！

**Comment by faithandbrave** [comment]
念のため、意見待ち期間を設け、なにもなければ月曜くらいに雛形を書いて本タスクを終了としようと思います。

**Comment by k-satoda** [comment]
標準ライブラリ関数については全般的にアドレスを取ることはできない、
あるいは、できても移植性の点で望ましくないと考えられるので、
「アドレスがとれない」の記述は無くして「operator<=>から導出された」だけに
したほうがいいんじゃないかと思います。
https://isocpp.org/std/standing-documents/sd-8-standard-library-compatibility
> Primarily, the standard reserves the right to:
> - Add new names to namespace std
> - Add new member functions to types in namespace std
> - Add new overloads to existing functions
> - Add new default arguments to functions and templates
> - ...

限られた関数について「アドレスがとれない」という記述をした場合、
その記述のない大部分についてはアドレスが取れるとも解釈できてしまいそうで、
良くなさそうです。

@onihusube 「アドレスがとれない」の記述は無くても特に困ることはなさそうに
思いますが、なんかありますかね？

**Comment by yumetodo** [comment]
アドレスの下りは正直このIssue見ててもなんのことかわかってなかったのですが、 @k-satoda さんのコメントでやっと理解しました。

「アドレスがとれない」だけ言われてもよくわからないし、かといって長々説明するのも違うように思うので、「operator<=>から導出された」だけにするに一票です。

**Comment by onihusube** [comment]
ああ、その通りですね・・・・

`<=> ==`演算子から導出されたものは使用可能だけど定義されているわけではない、と言う事がわかるようにと思っていました。  
それは別にアドレスが取れる取れないでなくても良いですし、むしろ誤解の元でしたね・・・

**Comment by faithandbrave** [comment]
クラスの雛形ページに比較演算子の表を記述例として記載し、比較演算子の個別ページの雛形を作成しました。
問題あればreopen / 直接修正 / issue立てをお願いします。
