### ISSUE TITLE
ナビゲーションでは std::timespec_get 関数がヘッダ <timespec_get> に含まれている

### ISSUE THREAD

**Issue by skystar0227** [cpprefjp/site#702]
`std::timespec_get` 関数はヘッダ [`<ctime>`](https://cpprefjp.github.io/reference/ctime.html) に含まれています。

しかし、ナビゲーションのリファレンスおよび[関数ページ](https://cpprefjp.github.io/reference/ctime/timespec_get.html)では、ヘッダ `<timespec_get>` に含まれていることになっているように見えます。

ナビゲーションのリファレンスおよび関数ページでも、`std::timespec_get` 関数はヘッダ `<ctime>` に含まれることを意図していますか？

**Comment by faithandbrave** [comment]
報告ありがとうございます。修正しました。
