### ISSUE TITLE
処理系の「C++11 mode」のような記載を削除したい

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#703]
いま、リファレンスの各ページで動作確認できた処理系バージョンを記載しているところに、「GCC C++11 mode」のように書かれています。
この「C++11 mode」は、言語バージョンの項目と重複しているので削除したいです。

この表記の記載は本サイトの最初期からあり、sscriskさんに作っていただいた雛形に従ったものです。

(オーバーロードごとの言語バージョン、処理系バージョンの記載をどうするか、という問題がほかにあると思いますが、ひとまずここでは重複情報の削除に注力したいです)

**Comment by yumetodo** [comment]
前からよくわからないなと思って言わないでいた部分なので、削除したいという話があるなら酸性です。

**Comment by onihusube** [comment]
いいと思います、ページトップの言語バージョン表示から自明だと思うので要らないと思ってました

**Comment by faithandbrave** [comment]
とくに異論なさそうなので、これは作業しちゃいますね。

**Comment by faithandbrave** [comment]
https://gist.github.com/faithandbrave/b3597f8cf608ad30a5f8535a056a92e9
