### ISSUE TITLE
[C++17][ライブラリ]const std::filesystem::path::value_type*を受け取るoverloadの追加

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#707]
ざっと調べた感じfilesystemのpathを使ってfileを開くために

> [§30.9.1 [fstream.syn]](https://timsong-cpp.github.io/cppwp/n4659/fstream.syn#3)
> 3  In this subclause, member functions taking arguments of `const filesystem​::​path​::​value_­type*` are only be provided on systems where `filesystem​::​path​::​value_­type` ([[fs.class.path]](https://timsong-cpp.github.io/cppwp/n4659/fs.class.path)) is not `char`. [ Note: These functions enable class `path` support for systems with a wide native path character type, such as `wchar_­t`.  — end note ] 

というわけで

https://timsong-cpp.github.io/cppwp/n4659/fstream

```cpp
    explicit basic_fstream(
      const std::filesystem::path::value_type* s,
      ios_base::openmode mode = ios_base::in|ios_base::out);  // wide systems only; see [fstream.syn]
```

を始め結構あちこちこれが追加されているようなので作業する

ref:
- http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2676
- http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2943

ところでLibrary Defect ReportのIssue単体だけ表示するリンクがあったと思うんですが、どなたかご存じないですか？今貼ったURLだと全件読み込むのでとても遅い・・・。

**Comment by faithandbrave** [comment]
Wikiの方に書いてあるのですが、こういうURLです。
https://wg21.cmeerw.net/lwg/issue2676
https://wg21.cmeerw.net/lwg/issue2943

**Comment by yumetodo** [comment]
今週末あたりから作業しはじめると思います。よく見たら2943はまだWPなので無視、というかそもそもbasic_filebuf::open()自体なかった。

**Comment by yumetodo** [comment]
ところで、`basic_ofstream`や`basic_ifstream`のページがないのって何か意図的なものなのか、単に作業者がいなかっただけか、どちらなんでしょうか？

**Comment by faithandbrave** [comment]
iostreamは優先度低めで目標から外していたからですね。
