### ISSUE TITLE
範囲for文の中でイテレータを無効にする操作をしたらまずいことをどこかに書けないか

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#710]
[rforでバグる対処　※for( T aaa : vvv ) - Qiita](https://qiita.com/loppta/items/69a0ed56ff12d2c0261c)
を見ていて思ったのですが、範囲for文で回しているイテレータが無効になるような操作(vectorのresizeで再アロケーションが発生するとか)をしたらまずいという話をどこかに書けないかなと思いました。

この問題は別に範囲for文が直接悪いわけじゃないのですが、範囲for文を使うことでイテレータが直接知覚できなくなることでうっかりそういうことをやる可能性が高まるかもしれないと想像しています。

https://cpprefjp.github.io/lang/cpp11/range_based_for.html

あたりに注意を書こうかと思ったのですが、範囲for文の解説に書くのが妥当か判断できなかったのでIssueを立てました。

**Comment by faithandbrave** [comment]
書いてよいかと思います。
それに加えて、連想コンテナで`it = s.erase(it)`するような操作が範囲for文だとうまく書けない、というのも書いておくといいですかね。

**Comment by yumetodo** [comment]
#708 が終わったらやってみます

連想コンテナのは
eraseの方にも書いたほうが良さそうですね。

memo:
- https://stackoverflow.com/questions/25246937/safe-to-erase-from-map-inside-range-based-for

**Comment by yumetodo** [comment]
vectorとmap系とset系のイテレータ無効になる操作の関数のページにも追記して回ることにします。

**Comment by yumetodo** [comment]
Qiitaの記事書いた人にContributeしてみないかお誘いしています。断られたら私が書きます。

**Comment by yumetodo** [comment]
> vectorとmap系とset系のイテレータ無効になる操作の関数のページにも追記して回ることにします。

思いつく限り全部見てきましたが、イテレータが無効になる話は直接書かれているか、さもなくば効果の項から飛ばされているページに記載があるようなので終了します。

---

と思いましたが、例示したソースコードの`shrink_to_fit`だけリンクがつかないのはなんででしょう・・・？

**Comment by faithandbrave** [comment]
んー。スペースが入ってるからですかね。

**Comment by yumetodo** [comment]
スペースと言いますとどのスペースでしょう・・・？

**Comment by faithandbrave** [comment]
`shrink_to_fit() [link /reference/vector/vector/shrink_to_fit.md]`

`)`と`[`の間ですね。ここにスペースが入るのは想定していなかったですが、実装でたまたま動いてるものもあるみたいですね。ただ、このページでしかスペースは入ってないはずです。

**Comment by faithandbrave** [comment]
連想コンテナのeraseに、イテレート中に要素削除する例を追加しておきました。
あとは`list`と`forward_list`も同様ですかね。`vector`と`deque`はちゃんと調べてないですが、そういうことをしていいのかよくわかってません。

**Comment by onihusube** [comment]
このIssueとは少し外れてしまうのですが、[コンテナライブラリ - cppreference.com](https://ja.cppreference.com/w/cpp/container)のページにあるような表（2つ）がcpprefjpにもどこかにあると良いなあと思ってました・・・

**Comment by faithandbrave** [comment]
article以下に記事として、「コンテナの選択」とか「コンテナの特徴」みたいなタイトルで書くのがいいですかね。

**Comment by faithandbrave** [comment]
cppreferenceにあるようなメンバ関数の表はいらない・・・というか二重管理になるので避けたいですが・・・。

**Comment by faithandbrave** [comment]
articleのルールをちゃんと明文化していないのですが、かんたんにまとめると以下のような感じです：

- 時事的なものではないこと (C++xxのバージョンでyy機能が追加されたからその解説、とかはダメで、xx機能が追加されたバージョン以降でずっと役立つ解説であること)
- 個別のリファレンスページでは解説しにくい俯瞰的なものであること
- なるべくリファレンスページとの二重管理にならないものであること (正引きリファレンスの本サイトに逆引きリファレンスを追加するようなものだと、本サイトのスコープを広げることになり、 個々の修正がしにくくなる)

**Comment by onihusube** [comment]
なるほど、確かに管理面倒そうですね・・・

コンテナに対する操作とイテレータの有効性に絞って少し書いてみることにします（時間がある時に・・・）。

**Comment by faithandbrave** [comment]
残りのシーケンスコンテナのeraseにも、イテレート中に要素を削除する例を追加しておきました。

**Comment by faithandbrave** [comment]
あとは、Boost.Asioの`io_context` (旧`io_service`) のような、空になるまでループし続け、ループ中にさらに要素が追加される、みたいなものに`list::push_back()`が使えるので、そういう例を追加します。
(Boost.Asioの実装では、自前実装の軽量なリンクリストが使われています)

**Comment by faithandbrave** [comment]
`list::push_back()`のページに例を追加しました。
私からはいまのところ、ほかに追加したいものはないです。

**Comment by yumetodo** [comment]
> コンテナに対する操作とイテレータの有効性に絞って少し書いてみることにします（時間がある時に・・・）。

**Comment by yumetodo** [comment]
> loppta [2019-12-18 15:31](https://qiita.com/loppta/items/69a0ed56ff12d2c0261c#comment-9e24f0f55795a06eeacc)
> 初心者に紹介したら、結局、自分が教え直すしかない難易度のドキュメントなんですが、
>例えば
>
>コラム：
>結論を言えば、自身の要素数を範囲forで増やすと正しい値を取れなくなります。よって範囲forは要素数を増やしてはいけません。
>
>というように直感的に分かり、すぐに実装に役立つ文章、とかにはできないのでしょうか？
>それともこういったフォーマットは、このように固く書かなければいけないルールなんでしょうか？
>
>(中略)
>
>C#はマイクロソフトのみがやっているから自由が利くのかもしれないけど、
>C++はいろんなところが介在して、しかも古い人や考え方も混じってて難しいとかあるのですかね。
>
>C#のforeachは、配列（enumerateできるもの）が絶対に変更できない仕様になってしまったのは、
>融通が利かないので、そういった点ではC++の方が楽でいいかと思っています。

> loppta [2019-12-18 15:34](https://qiita.com/loppta/items/69a0ed56ff12d2c0261c#comment-59dd2b5d7747b5b06795)
>この辺のドキュメンテーションの仕様はよくわかっていませんが、作業コストを考えた場合、
>
>結論：
>
>理由：
>
>という流れにはしていけないのでしょうか？
>
>多くの人は理由よりさっさと間違えずに使いたいという気持ちが強そうなので、その辺の温度差が気になるところではあります。

**Comment by yumetodo** [comment]
うーん、なかなか難しい。

**Comment by faithandbrave** [comment]
すべてのユーザーを満足させるドキュメントをひとつのWebサイトで提供することはできないので、本サイトを参考にして書かれた解説記事に期待する部分はあってよいかと思います。必ずしもユーザーの意見を受け入れる必要はないです。
論理展開を工夫する余地はあると思いますが、工夫して使わなければならないケースも存在するので、安易に簡潔な結論を書く必要はないです。

本サイトとして必要なのは、一貫した方針で、できる限り多くの日本語での技術情報を提供することだと思います。一貫さえしていれば、読み慣れることで本サイト内の多くの情報を学びやすくなります。

**Comment by yumetodo** [comment]
やっぱり考え直しても最大公約数はイテレータが無効にならないようにしろ、しか浮かばないですね。
ただ回避策をわかりやすくしてみました。

**Comment by yumetodo** [comment]
自分的にはこれ以上作業するとしたらむしろこの問題が他の言語ではどうなのかの調査ですが、雑な調査をしてQiitaにコメントしたらすぐに[違うよっているコメント](https://qiita.com/loppta/items/69a0ed56ff12d2c0261c#comment-cd4d42f27b508b66ff13)がついたので自分の手には負えなさそうです

というわけでこれ以上は私は作業予定がありません。他の皆様なければcloseしてください。

**Comment by yumetodo** [comment]
@faithandbrave アサインされたのはなにか作業があるのでしょうか・・・？終わったIssueだと思っていたのですが。
それとも[P2012R0](https://wg21.link/p2012r0)が出たからそれに触れるとかそういう話でしょうか？

**Comment by faithandbrave** [comment]
あ、すいません。実際に作業した人を記録のためにアサインしただけでした。

**Comment by yumetodo** [comment]
あ、そうなんですね。

**Comment by yumetodo** [comment]
2da58ef5105c2ba71d84713a5ae5b641187f9e5d で #1111 に追加で言及しました。
