### ISSUE TITLE
[C++20][ライブラリ] PODを非推奨化

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#724]
- [P0767R1 Deprecate POD](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0767r1.html)

提案文書としてはコア言語側ですが、本サイトではライブラリ側だけでよさそうな気がします。
C++20ページのライブラリ変更概要に、`is_pod`の非推奨化も追加してください。

**Comment by yumetodo** [comment]
- [P0488R0 comment US 101 WG21 Working Paper, NB Comments, ISO/IEC CD 14882](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0488r0.pdf#US101)
- [Issue 2323: Expunge POD - WG21 CWG Issues](https://wg21.cmeerw.net/cwg/issue2323)
- [本の虫: PODじゃなくてもいいのでは。](https://cpplover.blogspot.com/2010/05/pod.html)

**Comment by yumetodo** [comment]
[`std::is_trivially_copyable`](https://cpprefjp.github.io/reference/type_traits/is_trivially_copyable.htm)の内容がC++17時点で変更されているのに、追従できていないことに気がつきました。

ref
- [C++初心者に贈る強そうな人からC++のclassに関連する謎な用語を使われたときにみるもの: trivialとか#トリビアルにコピー可能なクラス(trivially copyable class)](https://qiita.com/yumetodo/items/424cc4d15de4edad436a#%E3%83%88%E3%83%AA%E3%83%93%E3%82%A2%E3%83%AB%E3%81%AB%E3%82%B3%E3%83%94%E3%83%BC%E5%8F%AF%E8%83%BD%E3%81%AA%E3%82%AF%E3%83%A9%E3%82%B9trivially-copyable-class)
