### ISSUE TITLE
[C++20][言語機能] 確率が高い分岐と低い分岐を伝える属性 [[likely]], [[unlikely]]

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#729]
- [P0479R5 Proposed wording for likely and unlikely attributes (Revision 5)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0479r5.html)

**Comment by k-satoda** [comment]
タイトルの「当たる」にちょっと違和感があって、別案を考えてみました。
ついでに長さを抑えつつ検索性を向上させて、↓こんな感じが良いかと思いました。
```diff
-当たる確率が高い分岐と、当たる確率が低い分岐をコンパイラに伝える属性を追加
+確率が高い分岐と低い分岐を伝える属性 [[likely]], [[unlikely]] を追加
```

**Comment by faithandbrave** [comment]
それでよいかと思います。

**Comment by yohhoy** [comment]
9f2e86d80edfcec09f196e82e73adc09206970e0 で本文コミットし、後から本チケットの合意内容に合わせて調整しました。
