### ISSUE TITLE
c++17 構造化束縛に誤った例があり，かつ意図が不明

### ISSUE THREAD

**Issue by forno** [cpprefjp/site#734]
https://cpprefjp.github.io/lang/cpp17/structured_bindings.html

# 概要
「配列を分解する」に示される例のうち，以下の例は意図が不明で誤りが含まれる．
しかし，修正の方向性に悩んだため，ここで問題点を共有し解決の方法を探りたい．

以下抜粋

```cpp
  // 参照の例
  {
    int ar[] = {3, 1, 4};
    int (&rar)[3] = ar;
    auto [a, b, c] = rar;

    // ar[1]を値2に書き換える
    b = 2;

    std::cout << a << std::endl;
    std::cout << b << std::endl;
    std::cout << c << std::endl;
  }
```

出力例(抜粋)

```
3
2
4
```

## 誤りについて
何を意図しているかわからないので誤りを複数の方向性から列挙する

- 「`ar[1]`を値`2`に書き換える」とあるが，実際には配列`ar`，および`rar`は変化しない
- `ar`を変化させるデモならば，出力は`ar[i]`であるべき
- 変数`rar`は配列`ra`への参照であるが，これを利用しても構造化束縛の各変数は参照にはならない
- 実際に配列`ar`を変更するには，`auto&`による構造化束縛を行うしかない(それには`rar`は不要)

# 予想される意図と対処の例
## 1. 配列の各要素への参照を構造化束縛し，変更する
この場合は`auto&`を使ったデモに変更することを提案する．
しかし，`auto&`と「配列」には関係性がないため，配列の例にこれを乗せるかは議論の余地がある．

```cpp
  // 参照の例
  {
    int ar[] = {3, 1, 4};
    auto& [a, b, c] = ar;

    // ar[1]を値2に書き換える
    b = 2;

    std::cout << ar[0] << std::endl;
    std::cout << ar[1] << std::endl;
    std::cout << ar[2] << std::endl;
  }
```

出力例

```
3
2
4
```

## 2. 配列の参照を構造化束縛した時の動きを説明する
この場合は，配列の参照への構造化束縛が参照ではなく値のコピーを作ることを示す．
しかし，pairへの参照を構造化束縛しても得られるのは値のコピーであり，配列が特別というわけではないため，配列の例に記載することに議論の余地がある．
更に言うと参照と値で挙動が異なることは稀なので，例示する必要から議論の余地がある．

```cpp
  // 参照の例
  {
    int ar[] = {3, 1, 4};
    int (&rar)[3] = ar;
    auto [a, b, c] = rar; // a, b, cはコピー

    // bの変更はar[1]を変更しない
    b = 2;

    std::cout << b << std::endl;
    std::cout << ar[1] << std::endl;
  }
```

出力例

```
2
1
```

# 所感
恐らく「1. 配列の各要素への参照を構造化束縛し，変更する」を意図しようとした上で，配列の参照を構造化束縛した時の挙動の認識を誤ったまま用いてしまい，さらに出力部分をarではなく各変数にしてしまったために生じたミスと考えられる．
また，意図がなんであったにせよ，配列の例として紹介する内容であったかは疑問である．

この件とは異なるが，`auto&`を用いた構造化束縛の例が存在していないために混乱を生じている面もあるように思う．

自分としてはこの例は完全に削除し，`auto&`を用いた例を別に追加するのが良いように思う．

**Comment by faithandbrave** [comment]
ありがとうございます。完全に忘れたので、思い出します・・・ちょっとお待ちを。

**Comment by faithandbrave** [comment]
配列の参照の例は、`auto&`を使ったものに直し、その上の「組・タプルを分解する例」にも参照の例を追加するのがよさそうに思います。

```cpp
  // 参照の例
  {
    int ar[] = {3, 1, 4};
    auto& [a, b, c] = ar;

    // ar[1]を値2に書き換える
    b = 2;

    std::cout << ar[0] << std::endl;
    std::cout << ar[1] << std::endl;
    std::cout << ar[2] << std::endl;
  }
```

**Comment by forno** [comment]
良いと思います．どちらがプルリクを作りましょうか

**Comment by faithandbrave** [comment]
私が直しておきます。

**Comment by forno** [comment]
よろしくお願いいたします．対応ありがとうございます．

**Comment by faithandbrave** [comment]
修正しました。問題あったら、Issueの再オープン・直接修正・Pull Requestなどをお願いできればと思います。
