### ISSUE TITLE
SOFT HYPHENを削除する？

### ISSUE THREAD

**Issue by hotwatermorning** [cpprefjp/site#735]
バッククオートで囲まれたクラスや関数の名前で、アンダースコアの直後に SOFT HYPHEN (\u+00AD) が含まれている箇所がいくつかあります。

個人的にはこれはあまり必要ではなくて、一括で取り除いてしまってもいいかなと思いますが、どうでしょう？

## 補足

SOFT HYPHEN は、単語を行末で折り返す必要が生じたときに、折り返す行の最後にハイフンを補うことを指示するための記号です。

SOFT HYPHEN があると、エディタによっては原稿中のクラス名や関数名が正しく検索できない問題があります。
（例えば、 vim で reference/memory/make_shared.md b/reference/memory/make_shared.md 中の shared_ptr を検索すると、 SOFT HYPHEN が含まれた shared_ptr の文字列は検索対象になりません）

また、クラスや関数の名前は、（それが非常に長い場合は名前の途中で折り返したいこともあるかもですが、）通常の長さであれば名前全体を次の行に折り返すようにして、名前の途中で折り返さないほうが見やすいと思うので、通常は名前の途中に SOFT HYPHEN を入れる必要はない気がします。

## 参照

https://github.com/cpprefjp/site/issues/601

**Comment by onihusube** [comment]
おそらく意図的に入れているものではなくて、一部のブラウザでコピペするときに_やハイフンの後に勝手に入ってるだけだと思います。  
なので、消してしまっていいかと

**Comment by hotwatermorning** [comment]
ゼロ幅スペース (\u200b) が変なふうに含まれている箇所もあるので、それも合わせて修正します。

**Comment by yumetodo** [comment]
というか経緯みるに今後もうっかりやらかしそうなので、チェックスクリプトを書いていっそCIに掛けるとかしてもいいかもしれません。

**Comment by hotwatermorning** [comment]
@yumetodo おっと。とりあえず手動で消して push しちゃいました。

うっかりやらかすこと考えると、自動でやる仕組み整備しておいたほうが良さそうですね。

**Comment by yumetodo** [comment]
`ag -l "\xAD" | xargs sed s/\xAD//g`で自動化できないかと思ったんですが、なんかうまく行かない

**Comment by hotwatermorning** [comment]
僕のところだと sed に直接文字を指定するのがうまくできなかったので、次のようにして一度変数に対象の文字を入れてから sed で変換しました。

```
TARGET_CHAR=$'\u200b'

# mac 環境なので homebrew で入れた gnu 版 sed である gsed を使っている。
find . -name "*.md" -print0 | xargs -0 gsed -i "s/$TARGET_CHAR//g"
```

**Comment by yumetodo** [comment]
`rg -t md '[\u00ad\u200b]'`のほうが超高速に検査できることがわかった。

置換は手動でやるとして、検査するだけのCIの設定組もうと思います。Github Actions 作る権限あったかな・・・

**Comment by faithandbrave** [comment]
見つけたら or CIに引っかかったら消すという方向で。
