### ISSUE TITLE
boolean-testable 説明専用コンセプトについて

### ISSUE THREAD

**Issue by onihusube** [cpprefjp/site#745]
[P1964R2 Wording for `boolean-testable`](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1964r2.html)の採択によって[`boolean`](https://cpprefjp.github.io/reference/concepts/boolean.html)コンセプトが削除され、代わりに少し弱めのほぼ同意義な[`boolean-testable`](http://eel.is/c++draft/concept.booleantestable)説明専用コンセプトに置換されました。

#711 の作業にあたって、このコンセプトは`boolean`と違って説明専用なので、どこにどう書くかについて少し悩んでいます。  
すでに作成済みの`boolean`ページに書いて[`<concepts>`](https://cpprefjp.github.io/reference/concepts.html)の一覧に載せておくのは誤解をまねく気がしますが、他のコンセプト（[`predicate`](https://cpprefjp.github.io/reference/concepts/predicate.html)や[`equality_comparable`](https://cpprefjp.github.io/reference/concepts/equality_comparable.html)など）からも参照されているのでどこかには書いておきたい・・・

今考えているのは次のどちらかです

- 説明専用であることを明示して、`boolean`ページを置き換えて`<concepts>`の一覧に載せておく
- `predicate`などのページに同居させる

他の方法など、ご意見ありましたら伺いたいです。

**Comment by faithandbrave** [comment]
説明用機能としては`<node_handle>`もありますし、ほかのページから参照されることを考えたら独立したページがあったほうが誘導しやすいとも思うので、以下の方針でよいように思います。

> 説明専用であることを明示して、`boolean`ページを置き換えて`<concepts>`の一覧に載せておく

**Comment by onihusube** [comment]
なるほど、`node_handle`失念してました。

その方向で行くことにします、ありがとうございます！
