### ISSUE TITLE
リンクチェックCIを作る

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#746]
いまはGitHub Actionsのbuildタスクでsite_generatorを動かして、そのコンソールにリンクチェックの結果が出力されますが、site_generatorは出力が膨大なのでリンクチェック結果を見るのが大変になってます。

軽量なリンクチェックのGitHub Actionsを作りたいです。要件は以下：

- サイト内リンクとして.nolinkがついているのに、そのファイルが存在していたらエラーにする
- サイト内リンクが貼られているのに、そのファイルが存在しなかったらエラーにする
- サイト外リンク (http開始) がリンク切れしていたらエラーにする (代替ページは探せそうなら直して、難しそうならissueで相談)
- エラーはひとつのコミットで複数発生することが考えられるので、コンソールにエラー内容をすべて列挙してからエラーにする (エラーを発見しても途中で切らずに、全部調べる)。

**Comment by yumetodo** [comment]
なるほど。

ただ`site_generator`と別に持つとなると、cpprefjp独自記法でのチェックがだるそう。CommonMarkのリンク記法ならすぐに作れると思いますが。

**Comment by faithandbrave** [comment]
Pythonスクリプトとしてはこれでできた気がする。

```python
import glob
import re
import os
import urllib.request
import sys

def check_url(url: str) -> bool:
    try:
        response = urllib.request.urlopen(url)
        response.close()
        return True
    except:
        return False

found_error = False
for p in glob.glob("**/*.md", recursive=True):
    links = []
    dirname = os.path.dirname(p)
    with open(p) as f:
        text = f.read()
        for m in re.finditer(r'\[(.*?)\]\((.*?)\)', text):
            link = m.group(2)
            links.append(link)
        for m in re.finditer(r'[\*-] (.*?)\[link (.*?)\]', text):
            link = m.group(2)
            links.append(link)

    for link in links:
        rel_link = ""
        if link.startswith(".."):
            rel_link = os.path.join(dirname, link)

        if link.startswith("http"):
            if not check_url(link):
                print("{} href {} not found.".format(p, link))
                found_error = True
        elif link.endswith(".nolink"):
            if os.path.exists(rel_link):
                print("nolinked {} href {} found.".format(p, link))
                found_error = True
        else:
            if not os.path.exists(rel_link):
                print("{} href {} not found.".format(p, link))
                found_error = True

if found_error:
    sys.exit(1)
```

**Comment by faithandbrave** [comment]
https://github.com/cpprefjp/markdown_to_html/blob/f528f80c1d43ba261dcb09bb4946b96b757eb4e7/html_attribute.py

**Comment by faithandbrave** [comment]
全然できてなかった。

**Comment by faithandbrave** [comment]
ここで作業中。
https://gist.github.com/faithandbrave/6cc5829db51f7abd57e2bcc226efac22

**Comment by yumetodo** [comment]
外部URLについては、pushごとのCIではリンクリストを生成するにとどめて、それを一日一回存在確認してエラーがあればIssueに通知するようなCIを組むほうがいいと思います。問題はそのリンクリストをどこにおいておくかですが。

リンクリストは例えば

```json
[
  {
    "url": "http://example.com",
    "files": [
      "/rerference/vector/vector/emplace"
    ]
  }
]
```

のような情報を持っていればいいでしょう。

**Comment by faithandbrave** [comment]
なるほど。リストを作るだけなら一瞬なので、一日一回の存在確認のときにいっしょにやってしまっても重くはないです。

URLのリンクチェックは数時間かかりそうなので一日一回の実行がよさそうですが、リダイレクトのはずが404で返ってきてしまったりするのがいまの悩みどころです。

とりあえず、サイト内リンクのチェックと、サイト外リンクのチェックはスクリプトを分けておきます。

**Comment by faithandbrave** [comment]
https://gist.github.com/faithandbrave/6cc5829db51f7abd57e2bcc226efac22

スクリプトはとりあえずできました。
サイト内とサイト外のチェックはスクリプトを分けず、コマンドラインオプションで分けました。

あとはGitHub Actionsに組み込むだけ・・・。自分のリポジトリで実験してからこっちにPull Requestをだします。
