### ISSUE TITLE
範囲forのカスタマイゼーションポイントを見つけるルールを緩和のサンプルコードについて

### ISSUE THREAD

**Issue by kingfisherkawasemi** [cpprefjp/site#757]
初めまして。少し気になるところがあり、issueを立てさせていただきました。
表題の通りです。
[ここ](https://cpprefjp.github.io/lang/cpp20/relaxing_the_range_for_loop_customization_point_finding_rules.html)のコードをWandBoxで実行してみたところ、[C++17でもエラーにはなりませんでした。](https://wandbox.org/permlink/9wJ5c5TyGoqQzYHi)
文意的には[こっちの方](https://wandbox.org/permlink/lUClc8MFncyObdxG)が正しそうなのですが、どうなのでしょうか

**Comment by onihusube** [comment]
少し分かり辛いのですが（私も元の提案文書読んでしばらく考えました・・・）、サンプルコードは合っています。

実際、少し古めの[GCC7.3](https://wandbox.org/permlink/1YAPZnITznZ4fZ2I)や[Clang7.0.0](https://wandbox.org/permlink/guHDJsG7ls4GPflt)などで動かしてみると、`end`メンバがあるのに`begin`が無いというエラーが帰ってきます。

`std::stringstream`は`std::ios_base`から継承した`std::stringstream::end`という **静的メンバ定数** を持っています。`X`は`std::stringstream`を公開継承しているので、`X`もまた`X::end`という静的メンバ定数を持ちます（それはまた、`X`のオブジェクト`x`に対して`x.end`のように使用可能です）。

- [`std::ios_base::seekdir` - cppreference](https://ja.cppreference.com/w/cpp/io/ios_base/seekdir)

C++17までの範囲`for`の仕様では、メンバ関数の`begin()/end()`のどちらかが見つかれば（たとえもう片方が利用可能でなくとも）メンバ関数の`begin()/end()`を使用し、それ以外を考慮しないというものでした。  
しかしそれだと、この例にある`X`のようにたまたま全く意図の違う`end`メンバ（関数ですらない）だけを持っている場合にもメンバ関数としてのそれらのペアを利用しようとするためエラーになってしまいます。

C++20からは、このように片方しか見つからない場合にはメンバ関数の`begin()/end()`の使用を諦め、ADLによって`begin()/end()`を探しに行くようになります。すると、この例の`X`のように別の意図による`end`メンバだけを持っている場合にも、クラス外や`friend`関数として別に`begin()/end()`のペアが適切に用意されていれば範囲`for`で利用可能になります（`begin`メンバだけがある場合も同様です）。

ご提示のコードではメンバとして`begin()`と`end`の両方が見つかっているが、`end`が関数ではない事からエラーを起こしています。この場合のケアは今の所されていません。

**Comment by kingfisherkawasemi** [comment]
なるほど、ありがとうございます。これからは古いバージョンのコンパイラも確認してからissueを立てようと思います。お騒がせしました。
