### ISSUE TITLE
コンセプト : 非関数テンプレートへのrequires節をやめる

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#763]
コンセプトページのvector実装の例で以下のようなことをしていますが、この仕様はなくなったので、直さないといけません。
どう直すか思いつかないので、一旦issueにします。

```
void push_back(const T& x) requires std::copy_constructible<T>
{
  if (size_ >= capacity_)
    throw std::out_of_range("over capacity");

  new (data_ + size_) T(x);
  size_ = size_ + 1;
}

// ムーブ版のpush_back
void push_back(T&& x) requires std::move_constructible<T>
{
  if (size_ >= capacity_)
    throw std::out_of_range("over capacity");

  new (data_ + size_) T(std::move(x));
  size_ = size_ + 1;
}
```

**Comment by yohhoy** [comment]
本件、対応の必要なし＝現状維持で問題ないと思います。

該当2か所はクラステンプレート`MyVector<T>`に属するメンバ関数、つまり templated function declaration とみなされるため requires-clause 指定は依然として許可されます。

https://timsong-cpp.github.io/cppwp/n4861/temp.constr.decl#1
> A template declaration ([temp.pre]) or templated function declaration ([dcl.fct]) can be constrained by the use of a requires-clause. [...]

https://timsong-cpp.github.io/cppwp/n4861/temp#pre-8
> An entity is templated if it is
> - [...]
> - a member of a templated entity,
> - [...]

「非テンプレート関数へのrequires節指定を禁止」した[提案文書P1971R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1971r0.html)でも、例示(Example)がクラステンプレートに属する（非テンプレートな）メンバ関数へと書き換えられています。
```
template<typename T> struct A {
  static void f(int) requires false;
}
```

**Comment by yohhoy** [comment]
@faithandbrave 本issueは wont fix でcloseしてもよさそうですが、いかがでしょう？

**Comment by faithandbrave** [comment]
あ、少し待ってください。まだ確認できてなくて…。

**Comment by faithandbrave** [comment]
確認しました。たしかに、以下のように書いてるので対応なしで大丈夫そうです。

> また、requires節は、クラステンプレートのテンプレートパラメータを、メンバ関数ごとに制約するためにも使用できる。
