### ISSUE TITLE
用語集のようなページの必要性について

### ISSUE THREAD

**Issue by onihusube** [cpprefjp/site#774]
プログラム定義型とかcustomization point object、適格要件などのよく出てくる割には意味が分からない用語についてどこか1箇所に纏まっていると親切かつ便利かなと思います。

サイト内にあって必要なら個別にリンク可能だと良いですが、個別のページが必要かどうかはなんとも言えません。

## 関連

#773 
#489

**Comment by faithandbrave** [comment]
ひとまずarticle以下に記事として書いて、ほかにも用語解説としてほしいものがでてきたら、用語集を用意するのでどうでしょう。
article以下に書くだけであれば、追加の仕組みは必要ありません。

用語集をまじめに作るときは、用語への自動リンクの仕組みを作りたいですね。

**Comment by yumetodo** [comment]
自動リンクというと https://github.com/cpprefjp/site/pull/493#issuecomment-350927851 であったような形態素解析をイメージすればいいのでしょうか？

**Comment by faithandbrave** [comment]
.md中のコードブロック、コード修飾、見出し以外の文章に対するグローバル修飾リストのようなものを用意して.mdレベルで自動置換するのをsite_generatorに入れるくらいかな、というイメージでした。

**Comment by akinomyoga** [comment]
> 自動リンクというと #493 (comment) であったような形態素解析をイメージすればいいのでしょうか？

そちらであった議論に関しては #510 にまとめてあります。すみません、放置されて殆ど死んだような Issue ですが。其処で議論していたのは .md のソースを自動置換する形ではなくて、自動的に生成時に HTML レベルでリンクを埋め込むか、またはクライアント側で動的にリンクを追加するということについて議論していましたね

**Comment by faithandbrave** [comment]
フロントエンドはできるだけ薄くして、なるべくsite_generatorで完結させたいです。
.mdソースを置換するかHTMLレベルでリンクを埋め込むかは、実装の手間や設計としてどちらかが楽かだけな気がしますので、作業者が決めればよいかと思います。

**Comment by faithandbrave** [comment]
@akinomyoga 
onihusubeさんの元々の動機にあった以下の3つの用語をとりあえずすべて登録しようと思ったのですが、見出しになっている「適格要件」と「テンプレートパラメータ制約」は自動リンクされないようです…。

> プログラム定義型とかcustomization point object、適格要件などのよく出てくる割には意味が分からない用語についてどこか1箇所に纏まっていると親切かつ便利かなと思います。

https://cpprefjp.github.io/reference/functional/bind_front.html

こちら、お時間がとれるときにでも見ていただけないでしょうか。以下のコミットの制限を外せばいいようにも思いますが…。

https://github.com/akinomyoga/cpprefjp-markdown_to_html/commit/a9086f44fc1e7587b9918162512195c12fc734a2

**Comment by akinomyoga** [comment]
こんにちは。これは確かに意図的に外したものでした。たしか、「適格要件」と「テンプレートパラメータ制約」についても、実はテスト段階でどうなるか見て、その上で外したような気がします。見出しの中(特に見出し語全体)にまでリンクを貼るというのは美的にも機能的にも変な気がしたからですが、更新していただいた GLOBAL_DEFINED_WORDS のように、リンクではなくて `desc` だけ指定するというのはありですね。外す時には https://github.com/akinomyoga/cpprefjp-markdown_to_html/commit/a9086f44fc1e7587b9918162512195c12fc734a2 の revert ではなくて、正規表現の中から `|h[1-6]` を削除して頂ければ幸いです (`文字列 in 配列` よりもコンパイル済み正規表現の方が効率が良いと思うので)。

**Comment by faithandbrave** [comment]
ありがとうございます。
表示されるようになりました！
https://cpprefjp.github.io/reference/functional/bind_front.html

一旦これでこのタスクは終了にしましょう。
また追加で要望とかがあればissueを立てていただければー。

実装していただいた @akinomyoga さん、ありがとうございましたー。
