### ISSUE TITLE
trivialの訳語がトリビアルと自明で揺れている問題

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#776]
> https://github.com/cpprefjp/site/pull/768#issuecomment-646940587
>
> ところで trivially をトリビアルに訳すのが気になって検索してみたら cpprefjp 内で訳が「自明」と「トリビアル」に割れています (["トリビアル" site:cpprefjp.github.io](https://www.google.co.jp/search?q=%22%E3%83%88%E3%83%AA%E3%83%93%E3%82%A2%E3%83%AB%22+site:cpprefjp.github.io) & ["自明" site:cpprefjp.github.io](https://www.google.co.jp/search?q=%22%E8%87%AA%E6%98%8E%22+site%3Acpprefjp.github.io))。しかも [is_trivial - cpprefjp C++日本語リファレンス](https://cpprefjp.github.io/reference/type_traits/is_trivial.html) は一つのページ内で二つが混在しています:
>
>> 型Tがトリビアル型か調べる。自明型は、…

trivialの訳語がトリビアルと自明で揺れているという指摘があった。

https://cpprefjp.github.io/working_style.html

訳語表では「自明」とすることになっているが、`is_trivially_xxx`系traitsのページを中心にトリビアルという訳語が使われている。

**Comment by faithandbrave** [comment]
C++でのtrivialはコンストラクタとかの暗黙定義のことですが、「自明」というと「説明しなくてもわかる」という意味で広く使われているので混乱しやすい気がします。
訳語は「トリビアル」にしておいて、`is_trivial`のページには「trivial」の意味を書いておくのがよい気がします。

**Comment by yumetodo** [comment]
訳語表の当該部分を書かれたのが @faithandbrave さんだったのでどうしようかと思っていたのですがそういうことでしたら私も同意見です。
https://github.com/cpprefjp/site/commit/bdca70d66eb7768e8d3bb4ffbb4ef4f7f911ee74

@akinomyoga さんはどうでしょう？

**Comment by akinomyoga** [comment]
トリビアルでおっけーです。統一できていれば良いとおもいます
