### ISSUE TITLE
[C++20] 名前付き要件の取り扱い

### ISSUE THREAD

**Issue by tetsurom** [cpprefjp/site#779]
現状では、[conceptsヘッダーのページ](https://cpprefjp.github.io/reference/concepts.html)に

> そのうちどこかに移動するページ

として名前付き要件がまとめられているように、名前付き要件をコンセプトとして扱っています。
しかし、新しく要件のページを作成しようとしたときに少々混乱するのではないかと思います。
(実際、`Formatter`の単独のページを作るか悩んでしまいました)

C++20で本物のコンセプトが導入されるので、名前付き要件の取り扱いを再考する良い機会ではないでしょうか。

* カテゴリーを追加する？
* ヘッダーに属しているのはおかしいので、名前付き要件だけをまとめたページを作成する？
* 属性のように、言語機能として扱う？

**Comment by faithandbrave** [comment]
expositional concept (説明用コンセプト) とかのカテゴリを追加しましょうか？typoしそうなのでpseudo conceptとかでも。

広範囲に使用されるコンセプトなら、headerの代わりにcategoryみたいな区分を用意して内部的な扱いはheaderと同じにする、という感じでしょうか。

**Comment by onihusube** [comment]
名前付き要件はコンセプトほど厳密なものではないので、conceptって入ってると誤解を招くかなあと思います。

同じ理由から、Cpp17~のように広域で使用される名前付き要件はヘッダページのように（`<concepts>`の外で）一纏めにしたいです。

**Comment by tetsurom** [comment]
そのまま `named requirement` だとわかりにくいでしょうか？

同じにしろ、という意図ではありませんが、こういうページはあるといいかもしれません。
https://ja.cppreference.com/w/cpp/named_req

**Comment by faithandbrave** [comment]
では、こんな感じですかね。

- `concept`と同等の識別子カテゴリとして`named requirement`を追加。
- `header`と同等の識別子カテゴリとして`category`を追加。

**Comment by faithandbrave** [comment]
@tetsurom 
named requirementの雛形ページを作ってもらってもいいでしょうか？
規格にある全ての名前付き要件をカバーできなくてもいいですが、たたき台になるものがあると助かります。

**Comment by faithandbrave** [comment]
named requirementはちゃんと動いてるっぽいです。
https://cpprefjp.github.io/editors_doc/named_requirement_template_page.html

**Comment by faithandbrave** [comment]
あとで`<node_handle>`を`[meta category]`にしてみます。

**Comment by yumetodo** [comment]
https://cpprefjp.github.io/editors_doc/specialized.html
への追記が忘れてると思います。これ以外にも最近concept周りで追加したのも(なんでしたっけ)入っていない気がします。

**Comment by faithandbrave** [comment]
category対応が不十分で、サイドバーが一時的に壊れています。修正中です。

**Comment by faithandbrave** [comment]
まだダメっぽい…わからん

**Comment by faithandbrave** [comment]
node_handleを一旦headerに戻しました。ローカルでもうちょっとやってみます。

**Comment by faithandbrave** [comment]
Boostのリリースノートも書かないといけないので、ちょっとすぐには対応できないかもしれません。なるべく早くそちらを片付けます。

**Comment by faithandbrave** [comment]
cpprefjpをローカルで、やっとサイドバーが動かなくなるとこまで動かせたので、バグ調査していきます。
crsearchがnpm moduleになっているのがとても使いにくい。

**Comment by yumetodo** [comment]
npm moduleになっていることが障害になるようなことに遭遇したことがないのですが、どういう状況でしょうか？
単に`node_modules/crsearch`以下のファイルを一度git cloneしたものに置換してそこで`npm run dev`すれば最適化されてない状態で見れると思うのですが

**Comment by faithandbrave** [comment]
https://cpprefjp.github.io/reference/node_handle/node_handle.html
https://cpprefjp.github.io/reference/concepts/Callable.html

@nyaocat さんに見てもらって、categoryとnamed requirementが問題なく動作しました。
あとは編集者向けドキュメントを更新して終了しようと思います。

**Comment by faithandbrave** [comment]
時間がかかってしまってすいませんでしたが、なんとか対応おわりましたのでクローズします。
まだ問題があったら教えてください。
