### ISSUE TITLE
[C++20][言語機能] 丸カッコの値リストからの集成体初期化を許可

### ISSUE THREAD

**Issue by tetsurom** [cpprefjp/site#781]
[P0960R3 Allow initializing aggregates from a parenthesized list of values](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0960r3.html)

**Comment by yumetodo** [comment]
https://github.com/cpprefjp/site/commit/767e4c06d8df593bcaf7c424c7d25a2680c8fcd9#r40712231

> 当初は誰もが波カッコで初期化をするようになるから問題がないと考えられていたが、実際にはそうはならず、丸カッコで初期化するためだけにコンストラクターを書くことが続いていた。

@tetsurom  
意図としては

```cpp
struct A {
  int x,y;
  constexpr A(int x, int y) noexcept : x{x}, y{y} {}
};
```

みたいなコンストラクタを書いてしまっている状況にある、ということだと思うのですがちょっと読み取りにくいです。

**Comment by yumetodo** [comment]
解決されたように思います。 @tetsurom さん対応ありがとうございました

**Comment by faithandbrave** [comment]
@tshino さんからのコメントも記載します。セミコロンも抜けてますね。

> ただし、今まで丸カッコでは書くことのなかった以下のような構文はサポートされない。

```cpp
A a = (1, 2);
int n[] = {1, 2, 3, 4, 5}
A aa[]((1, 2), (3, 4), (5, 6));
```

> @tshino
> tshino 8 days ago Member
> この例の a, n, aa がすべてサポートされないと読み取れるのですが、
> nの例は int n[] = (1, 2, 3, 4, 5); と書けばエラーになるという意味でしょうか？
> であれば波カッコではなく丸カッコで書いてあると理解しやすいと思います。

**Comment by tetsurom** [comment]
これは完全にtypoでした。 e4b2f56a63f637ddb0b3d7b6222e1ebf27a1eaea で修正してあります。

**Comment by yumetodo** [comment]
あ、私が治ってると勘違いしてこっちに転記してませんでした、すみません。
