### ISSUE TITLE
CIの手動トリガー方法について

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#785]
現在は`TRIGGER.md`に適当な文字を書いて代替してるが、どうも公式で手動トリガー方法が追加されたそうです。
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by faithandbrave** [comment]
```
on: 
  workflow_dispatch:
```

をつけて回ればいいんですかね。

**Comment by yumetodo** [comment]
workflow_dispatch以下のオプションって多分いらないので列挙だけしておけばいい気もします。あとは全部のCIに手動トリガーがいるかどうかですかね。

**Comment by faithandbrave** [comment]
変な文字チェッカーはなくてもいい気がしますがあっても困らないので、全部につけていいのではないかと思います。

**Comment by yumetodo** [comment]
ずっと放置していましたが、workflow_dispatch対応しました。図のようにRun workflowというボタンがあると思います。
![image](https://user-images.githubusercontent.com/10869046/98329228-160c5b80-203b-11eb-8803-fd727aaf1cd9.png)

**Comment by faithandbrave** [comment]
ありがとうございます！
