### ISSUE TITLE
[C++20][言語機能]P2002R1: Defaulted comparison specification fixes

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#786]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2002r1.html
某所での  @LoliGothick 氏の指摘によれば
https://cpprefjp.github.io/lang/cpp20/consistent_comparison.html
の内容に変更が必要な可能性がある。

**Comment by yumetodo** [comment]
結局
```cpp
#include <compare>
struct V {
    int x;
    friend auto operator <=>(const V&, const V&);
};
inline auto operator <=>(const V&, const V&) = default;

int main() {}
```

みたいなコードはどうなるのか・

**Comment by yumetodo** [comment]
p2002r1にはあってn4861にはない

> ~~declared~~ defined in the member-specification of `C`

という部分は

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2085r0.html
による変更？？？

**Comment by yumetodo** [comment]
関係ありそうなもの
https://github.com/cplusplus/draft/pull/3767

**Comment by LoliGothick** [comment]
[P2002R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2002r1.html)で§11.11.1に追加されたらしい文面で，
> A definition of a comparison operator as defaulted that appears in a class shall be the first declaration of that function.
というのがあます。

どうやらClangは，この文面の意味を最初の宣言で定義を書かなければならない（=クラス内でしかdefault指定できない）と捉えたように思えます。

https://wandbox.org/permlink/m9pPZivUMDD5IytR

この挙動はcpprefjpのコード例と異なるという指摘を受けまして，このIssueをたてるに至っています。

**Comment by onihusube** [comment]
当初の仕様では、`<=> ==`の`default`定義はクラス内での宣言のみ有効で、クラス外でも`<=> ==`の`default`定義を可能にするのは[P2085R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2085r0.html)で導入されました。clangは[ここ](http://clang.llvm.org/cxx_status.html#cxx20)を見るにまだ未実装です。GCC 10.1ではエラーになりません。

これはP2002R1の内容と衝突しない（マージ可能）な文面であったので（P2085R0を追記したときにそう理解しました）P2002R1でも覆されてはないはずです（私自身はまだP2002R1を未確認なのですが・・・）。

@yumetodo さんの提示されたコードは有効です。

議論の文脈が分からないのですが、おそらくはclangの実装が追い付いていないだけに思えます。

**Comment by yumetodo** [comment]
後のために経緯を要約しておく。

---

まず某所にて、三方比較演算子をクラス外でdefault定義できないという質問が投げかけた。
https://wandbox.org/permlink/Ef7PWd59SEAXJJhs

---

これに対して私が

> a friend of `C` having either two parameters of type `const C&` or two parameters of type `C`.

だから(上述のわたしのコード例のように)friend指定がないとだめでは？という話と、Clangがバグってるのではという話をした。

---

そこに @LoliGothick 氏がP2002に関する編集がなされていないという指摘があり、このIssueを立てるに至りました。

**Comment by onihusube** [comment]
P2002の内容が未追記はその通りですね。すっかり忘れていました・・・

**Comment by yumetodo** [comment]
適当な開いているIssueはなさそうなのでこのIssueで管理ということでいいですかね？

**Comment by LoliGothick** [comment]
流れは
> 後のために経緯を要約しておく。

の通りです、 @yumetodo さんありがとうございます。

僕がissueをたてたほうがいいと思ったのは指摘を受けて編集履歴を見てP2002に関する編集がなされていないなと思ったからです（肝心なところをかき忘れていてすいませんでした）。

**Comment by onihusube** [comment]
追記完了しました！

もしよろしければご確認ください。
