### ISSUE TITLE
チェックに失敗している外部リンクがある

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#802]
https://github.com/cpprefjp/site/issues/710
のときに追加された
https://cpprefjp.github.io/lang/cpp11/range_based_for.html
にある「rforでバグる対処　※for( T aaa : vvv ) - Qiita」という記事へのリンクですが、リンクチェックCIで指摘されていないにもかかわらず、
https://qiita.com/loppta/items/69a0ed56ff12d2c0261c
404になっています。

そもそもこの記事が消えてるのは意図的なものか問い合わせ中ではありますが、報告だけしておきます。
https://twitter.com/yumetodo/status/1300263071412137984?s=20

**Comment by faithandbrave** [comment]
```
url_parts = urllib.parse.urlparse(url)
res = requests.get("://".join([url_parts.scheme, url_parts.netloc]), verify=False, timeout=60.0)
```

このコードで検証されているURLが、`https://qiita.com`になっていて、個別ページが検証されていないっぽい。

**Comment by yumetodo** [comment]
多分引用してるコードはなかったと思われるか、さもなくば状況を再現するのに唯一のコードだと思われるので当該リンクは削除してしまうことにします。問い合わせからだいぶ経ち、ツイート自体はされているようなので無視されていると判断することができると思います。
