### ISSUE TITLE
common_referenceの説明の改善

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#815]
#814 で議論されたように、「ポインタ型やC++17までの標準ライブラリにおける普通のイテレータ型では、そのvalue_typeとreferenceの間には自明な関係性があり」という部分は分かりづらい。

**Comment by faithandbrave** [comment]
冗長にはなりますが、より説明的にするとしたらこんな感じでしょうか。

「ポインタ型やC++17までの標準ライブラリにおける普通のイテレータ型では、その`reference`型は`value_type&`の別名として定義され、`value_type`と`reference`はどちらも`const`左辺値参照を付加することで`const value_type&`に変換することができる」

**Comment by yumetodo** [comment]
そこまで冗長とも思わないし、わかりやすいと思います。

**Comment by faithandbrave** [comment]
@onihusube さんからvoteのリアクションがあったので、それで修正しましょうか。

**Comment by faithandbrave** [comment]
一文が長かったので分割したのと、元の文章の構成をできるだけ保つよう修正しました。
これでひとまずクローズしますが、問題があればreopenや直接修正などをお願いします。
