### ISSUE TITLE
niebloidと呼称されているものについて

### ISSUE THREAD

**Issue by onihusube** [cpprefjp/site#818]
C++20より`std::ranges`名前空間に追加されている関数テンプレートは全て、例えば[この様](http://eel.is/c++draft/range.iter.ops#general-2)に説明されている関数のような何かのようです。

ADLを阻害して同名の`std`名前空間にある古い関数が見つからない様にするのが目的で、おそらく関数オブジェクトで実装されるものと思われます。

これらのもののことをcppreference.comでは*niebloid*と呼んでいるようです。

- [std::ranges::distance - cppreference](https://en.cppreference.com/w/cpp/iterator/ranges/distance)

#712 の作業中に`<iterator>`にある`std::ranges::advance`などのページをすでに追加しましたが、当初は気づいていなかったので普通の関数としてページを作成しました。

- [`std::ranges::advance`](https://cpprefjp.github.io/reference/iterator/ranges_advance.html)
- [`std::ranges::distance`](https://cpprefjp.github.io/reference/iterator/ranges_distance.html)
- [`std::ranges::next`](https://cpprefjp.github.io/reference/iterator/ranges_next.html)
- [`std::ranges::prev`](https://cpprefjp.github.io/reference/iterator/ranges_prev.html)

他にも`<algorithm>`のほぼ全ての関数に対しても同名のものが`std::ranges`名前空間に追加されており、おそらく`<numeric>`ヘッダのものも将来的には同じようになると思われます。

通常の関数と扱いが異なるとはいえ、それによって生じる差異は僅かでしかもそこそこ難解な概念ですが、区別や説明が必要でしょうか？

また、区別されるとしたら*niebloid*と言う呼称がどうなのかと言う問題もあります・・・

**Comment by faithandbrave** [comment]
Range作者のEric Niebler由来の用語っぽいので、直接的に採用はしたくないとこですね。

- [謎の用語niebloid](http://flast.hateblo.jp/entry/2019/03/19/090722)

言語の仕組みに直接ない用語は解説しにくいので標準ライブラリではやめてほしい・・・というのは愚痴ですが、大半のユーザー向けには「関数テンプレート」、より詳しく知りたい人のためにアノテーションとして特殊用語を付加して調べやすくしておく、というのがよいような気はします。

似たような例として`<type_traits>`のメタ関数は直接的に本サイトではメタ関数という用語を使っていませんが、「これらの機能はメタ関数と呼ばれている」とヘッダページに書いてあります。それと近しい方法がとれるのではないかと思います。

**Comment by faithandbrave** [comment]
article以下に「ADLを無効にする関数定義」のような記事を作って備考などで都度そこにリンクを貼るのが、いまの仕組みでできそうなことでしょうか。

**Comment by yohhoy** [comment]
私も faithandbrave さん案に賛同です。
> 大半のユーザー向けには「関数テンプレート」、より詳しく知りたい人のためにアノテーションとして特殊用語を付加して調べやすくしておく

C++標準も [[range.iter.op]/2](http://eel.is/c++draft/range.iter.ops#general-2) にて一旦「関数テンプレート(function templates)」と言い切っていますし。
> The **function templates** defined in [range.iter.ops] are not found by argument-dependent name lookup ([basic.lookup.argdep]). When found by unqualified ([basic.lookup.unqual]) name lookup for the postfix-expression in a function call ([expr.call]), they inhibit argument-dependent name lookup. [...]

**Comment by onihusube** [comment]
基本は関数テンプレートとして扱いつつarticleに説明を書いて誘導する、と言うのが良さそうですね。

ありがとうございます、その方向性で書いてみます。
