### ISSUE TITLE
[C++20] 機能テストマクロをまとめる

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site#825]
C++20の機能が出揃ったので、機能テストマクロとその値をまとめます。

- 言語機能は`15.11 Predefined macro names Table 19: Feature-test macros [tab:cpp.predefined.ft]`
- ライブラリは`17.3.2 Header <version> synopsis [version.syn]`

にまとまっています。

**Comment by yumetodo** [comment]
うーん、なんでビルドが落ちているんでしょう・・・

**Comment by faithandbrave** [comment]
br のタグが許可されてるものと違ってるっぽいですね

**Comment by onihusube** [comment]
お騒がせしました・・・

**Comment by onihusube** [comment]
終わりました！
