### ISSUE TITLE
コンパイラの実装状況ページにProposal numberを載せたい

### ISSUE THREAD

**Issue by h-sao** [cpprefjp/site#852]
言語機能などの一覧に、代表的なProposal numberがあると嬉しいなと思っています
こんなイメージです

![スクリーンショット 2021-03-29 1 15 28](https://user-images.githubusercontent.com/778582/112759613-bedd4680-902e-11eb-81cd-cb2783b62925.png)

ClangやMSVCの実装状況ページでも記載されていますし
（個人的用途かもしれませんが）コンパイラの実装状況一覧からProposal numberを検索したいと、ずいぶん前から思っていたので…
異論なさそうであればわたしの方でPR作ります
文字数が多くなるので嫌など反対意見あればお願いしますmm

**Comment by faithandbrave** [comment]
問題ないかと思います！

**Comment by yumetodo** [comment]
スクレイピングとかを考えるなら`:`区切りではなく表の欄を分けたほうがいいかも？

| 提案文章 | 言語機能 | 説明 |
|------|----------|------|
| P1099R5 | [スコープ付き列挙型のusing宣言](cpp20/using_enum.md) | `using enum EnumType;`もしくは`using EnumType::enumerator`とすることで、列挙値のスコープ指定を省略できるようにする |

**Comment by h-sao** [comment]
これ以上欄が増えると明らかに窮屈になるので、避けた方がいいかなと思ってました
ただ機能的には新たな欄を作るのがベストだとは思います

わたしのブラウザだと今の時点でもこんな風に↓全体的に狭く見えるので

![スクリーンショット 2021-03-31 5 09 39](https://user-images.githubusercontent.com/778582/113051194-ac0a7380-91e0-11eb-8984-ac0a26906fa4.png)

文字数が増えても今のレイアウトに影響なさそうな「言語機能」欄に入れてみました

けど欄そのものを増やします？

**Comment by faithandbrave** [comment]
列を増やすと画面が狭くなってしんどいですね。列幅を制御できるといいのですが、ひとまず言語機能欄に書いてしまってよいと思います。

**Comment by h-sao** [comment]
了解です〜

**Comment by yumetodo** [comment]
JSでtableにclass名を振って(仮に`implementation-status-table`)あげられれば

```js
for(const v of [11, 14, 17, 20, 23]) document.getElementById("cpp" + v).parentElement.nextElementSibling.classList.add("implementation-status-table");
```

CSSで調整が利くとは思うのですが・・・。

```css
.implementation-status-table tr td:nth-of-type(3), td:nth-of-type(4), td:nth-of-type(5), td:nth-of-type(6) {
    width: 5rem;
}
```
![image](https://user-images.githubusercontent.com/10869046/113850422-6c8de980-97d5-11eb-8ad9-652af83f4f5e.png)

**Comment by faithandbrave** [comment]
Markdownのいまのフォーマットで表にclassを付加することはできなくて、やるならsite_generatorで拡張を作ることになりますが、いまは余裕もなくできないので、余裕ができたらそのうち考えましょう。

**Comment by faithandbrave** [comment]
余裕ができたらやることリストでもWikiに作りますかね…。

**Comment by yumetodo** [comment]
site_generatorに手を出さなくてもできると思ったのですが、今やる必要がないのは同意します。

**Comment by h-sao** [comment]
ひとまず亀の歩みですがC++20 の言語機能の他のナンバーは埋めました
https://github.com/cpprefjp/site/commit/6fb0c4bbf9428b41c4bec164f3c08142e373bfae

ただ分からない番号がありまして
「積極的でない`constexpr`関数のインスタンス化」
「条件付きで特殊メンバ関数をトリビアルに定義するように」
の項目のProposal numberがどれに相当するのか分りませんでした
どなたか教えてください～

**Comment by faithandbrave** [comment]
https://github.com/cpprefjp/site/issues/721

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0848r3.html

こちらになります！

**Comment by yohhoy** [comment]
FYI: [Changes between C++17 and C++20 DIS](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2131r0.html) にC++17 to 20差分がまとまっているようです。ご参考に。

**Comment by h-sao** [comment]
C++17のプロポーザル番号について質問です

C++17「参照メンバをもつクラスの置き換え」について
[Changes between C++14 and C++17 DIS](https://isocpp.org/files/papers/p0636r0.html) を見ると、

```
P0137R1 | launder
```
に相当すると思ったのですが、gccとclagのサポートページにはこの番号で実装したという記録がなく、MSVCのサポートページでは15.7で実装済みとなっています

cpprefjpのコンパイラの実装状況ページにはgccでは7、clagは6.0 で実装済みになっているので、わたしが見ているプロポーザル番号が違うのかな？と思いました
どの番号に相当するのか、どなたか教えてください〜mm

**Comment by faithandbrave** [comment]
それで合ってます。

cpprefjpとしてはlaunderのページに、
https://cpprefjp.github.io/reference/new/launder.html

GCCとClangではライブラリの方のサポートページに書いてますね。
https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017
https://libcxx.llvm.org/docs/Cxx1zStatus.html

**Comment by h-sao** [comment]
ライブラリのページでしたか…見落としてました
ありがとうございます、C++17の分は更新しました！
https://github.com/cpprefjp/site/commit/8f730dc01b015bdb22e1355e7b79f842deaa596c
https://github.com/cpprefjp/site/commit/89b3d21e60bc404cbe22d498d38256bdece46e28

スローペースですみません。。。あとはC++11もぼちぼちやりますmm

**Comment by h-sao** [comment]
あと一つだけ判らなかった…
gccとclagのサポートページで、
C++11「一様初期化 (uniform initialization)」がどれに相当するのか、わかりませんでした
これのプロポーザルナンバーについて、どなたか教えてくださいmm

**Comment by faithandbrave** [comment]
initializer listsの提案文書に含まれてますね。braced-init-listの仕様がそれに当たります。
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2672.htm

**Comment by h-sao** [comment]
レスありがとうございます！

提案文書的には、「一様初期化」は「初期化子リスト」と同じということは、`N2672` になるのですが
cpprefjp の実装状況ページで GCCの対応バージョンは

- 初期化子リスト 4.4
- 一様初期化 4.6

になってて、バージョンが異なってるのがちょっと引っかかってます
提案文書は１つにまとまってるけど、機能的には実装が4.4と4.6に分かれたのか、
それとも単純な誤記なのか…？
あとGCC側の4.6のバージョン対応記録で、一様初期化がどれに相当するのかが判らなかったのもあり、もにょってます💦
https://gcc.gnu.org/projects/cxx-status.html#cxx11

まとめると、
- 一様初期化の提案文書は`N2672` にする（Initializer List proposed wordingの中にbraced-init-listの仕様が含まれてる）
- 一様初期化のGCC対応バージョンは4.4 にする（誤記なので修正）
これで良いですかね…？

**Comment by faithandbrave** [comment]
cpprefjpでそのバージョン表記にした経緯は忘れてしまいました…。

GCCのInitializer Listsの対応バージョンは4.4で、そのバージョンでUniform Initializationが問題なく動作することは確認できました。
なので、修正対応としては、 @h-sao さんに提案いただいたもので大丈夫だと思います。

**Comment by h-sao** [comment]
あ、そっか、、
4.4で動作確認すれば話が早かったですね😅
それで更新しておきます！ありがとうございます〜

**Comment by h-sao** [comment]
ひとまず、目的のProposal numberの記載は終えましたので、このissueはクローズします
お付き合い下さったみなさま、ありがとうございました！

**Comment by faithandbrave** [comment]
ありがとうございます！
