### ISSUE TITLE
「エイリアステンプレート経由でのクラステンプレートのテンプレート引数推論」のページのリンク文言修正

### ISSUE THREAD

**Issue by h-sao** [cpprefjp/site#860]
To: @faithandbrave san
お知らせです

些細な更新ですが
「エイリアステンプレート経由でのクラステンプレートのテンプレート引数推論」
のページの、参照リンクにProposal numberが記載されていなかったので、更新しておきました

コミットはこちら
https://github.com/cpprefjp/site/commit/aac4260f03e2e027203db15ef37dc3396a34c647

お知らせですので、確認後このissueはクローズしていただいて問題ないです
よろしくお願いします

**Comment by faithandbrave** [comment]
ありがとうございます。確認しました。
(今週はまるまる休暇中なので、反応が遅くなるかもしれません。)
