### ISSUE TITLE
[C++20] 標準ライブラリの三方比較演算子対応

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site#900]
tupleの比較は宇宙船演算子で定義されるようになった (reported by @akinomyoga https://github.com/cpprefjp/site/pull/899#issuecomment-917767961)

これに対応する

ref:
- #899 

タスク：

- [x] type_info
- [x] coroutine_handle
- [x] error_code
- [x] error_condition
- [x] error_category
- [x] pair
- [x] tuple
- [x] optional
- [x] variant
- [x] monostate
- [x] bitset
- [x] allocator
- [x] unique_ptr
- [x] shared_ptr
- [x] memory_resource
- [x] polymorphic_allocator
- [x] scoped_allocator_adaptor
- [x] function
- [x] type_index
- [x] to_chars_result
- [x] from_chars_result
- [x] char_traits
- [x] basic_string
- [x] basic_string_view
- [x] array
- [x] deque
- [x] forward_list
- [x] list
- [x] vector
- [x] map
- [x] multimap
- [x] set
- [x] multiset
- [x] unordered_map
- [x] unordered_multimap
- [x] unordered_set
- [x] unordered_multiset
- [x] queue
- [x] stack
- [x] reverse_iterator
- [x] move_iterator
- [x] istream_iterator
- [x] istreambuf_iterator
- [x] common_iterator
- [x] counted_iterator
- [x] unreachable_sentinel_t
- [x] iota_view
- [x] filter_view
- [x] transform_view
- [x] take_view
- [x] join_view
- [x] split_view
- [x] complex
- [x] slice
- [x] duration
- [x] time_point
- [x] day
- [x] month
- [x] year
- [x] weekday
- [x] month_day
- [x] month_day_last
- [x] month_weekday
- [x] month_weekday_last
- [x] year_month
- [x] year_month_day
- [x] year_month_day_last
- [x] time_zone
- [x] zoned_time
- [x] leap
- [x] link
- [x] locale
- [x] space_info
- [x] path
- [x] file_status
- [x] directory_entry
- [x] sub_match
- [x] match_results
- [x] regex_iterator
- [x] regex_token_iterator
- [x] thread::id

**Comment by akinomyoga** [comment]
`tuple` の他にもあるかもしれません。以下で一括で修正されてますね…大量の修正です。。

- [P1614R2 - The Mothership has Landed](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1614r2.html)

**Comment by yumetodo** [comment]
あれ、もしかしてcpprefjpでこれの対応してない・・・？(仕事終わったらみてみる

**Comment by akinomyoga** [comment]
検索したら

> [cpp20 · cpprefjp/site Wiki](https://github.com/cpprefjp/site/wiki/cpp20)
>
> paper | タイトル | 対応状況(空 or 完了 or 対応しない or 担当名)
> -- | -- | --
> P1614R2 | The mothership has landed | `<compare>`ヘッダのみ完了

だそうです

**Comment by yumetodo** [comment]
#701 で編集方針話してましたね、後で見る

**Comment by faithandbrave** [comment]
やります

**Comment by yumetodo** [comment]
std::optionalだけメンバーリストのページで三方比較演算子がC++17になっていたので 43d3dbb で修正しました。

**Comment by faithandbrave** [comment]
修正ありがとうございます。ご指摘通りですね。
