### ISSUE TITLE
Range(s)の訳語について

### ISSUE THREAD

**Issue by tetsurom** [cpprefjp/site#901]
`<ranges>`で扱うような意味でのRange(s)の訳はどうするのが良いでしょうか。

- 範囲
- レンジ
- Range (訳さない)

参考:

- [C++20 - cpprefjp](https://cpprefjp.github.io/lang/cpp20.html)  
  「イテレータの組ではなく、コンテナや配列、部分的なコンテナなどを扱う範囲ライブラリ」
  現在の`<ranges>`以下のページではこれを参考に「範囲」としています
- [リファレンス - cpprefjp](https://cpprefjp.github.io/reference.html)  
  「レンジライブラリ」
- [C++20 ranges](https://techbookfest.org/product/5134506308665344)  
  「Rangeライブラリ」

**Comment by yumetodo** [comment]
range-based forを範囲forで通してきている以上、範囲にするのがいいのかなという気がしています

**Comment by faithandbrave** [comment]
これはおそらく、話し言葉で話す際になんと言うかが重要な気がしています。
上記の例で「範囲」と書いたのは私ですが、実際に話をする場では「レンジライブラリ」という言い方をする機会が多いように思うので、私はレンジがいいように思いました。

範囲for文は悩ましいところではありますが、これも日本語の文脈でもrange-based forと話す・書く方が多いので、「レンジfor文」としてしまってもいいかもしれません。

**Comment by yumetodo** [comment]
> これも日本語の文脈でもrange-based forと話す・書く方が多いので、「レンジfor文」としてしまってもいいかもしれません。

自分の中でレンジと言わない根拠はrange-based forの件だけだったので、そっちも治すということであればそれのほうがいいと思います。

**Comment by onihusube** [comment]
昔江添さんがRange vs レンジでアンケートとっていた結果です。

https://twitter.com/EzoeRyou/status/1194155940020273153

個人的にも、カタカナでレンジと書くよりはそのままrange(or Range)と書く方が好みです。

**Comment by yohhoy** [comment]
C++標準Ranges libraryで定義される専門用語(term)であること明確化するため、個人的には「Range (訳さない)」に1票です。次点では「レンジ」でしょうか。

「範囲」は日本語の一般名詞と混同される恐れが高いため、好ましくないと考えています。

**Comment by wx257osn2** [comment]
自分はどう書いてきたっけな…と自分の記事を見返してみましたが，Range表記でしたね．私もrange表記が良いのではないかなと思います

**Comment by tetsurom** [comment]
とりあえずRanges関係はRange表記にしようと思います
