### ISSUE TITLE
サイト全体を .zip としてダウンロードできるリンクの案内

### ISSUE THREAD

**Issue by katahiromz** [cpprefjp/site#917]
Windowsコンパイル済みヘルプ ファイル（chm）は閲覧には非常に便利なファイルだと思います。
なぜchmファイルをリリースしないのですか？
よろしくお願いします。

**Comment by akinomyoga** [comment]
CHM形式は随分前にセキュリティ上の問題から Microsoft が非推奨としたような… ([Wikipedia](https://ja.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help) を見ると18年も昔の話です…)。.zip でまとめてダウンロードしたければ https://github.com/cpprefjp/cpprefjp.github.io/archive/refs/heads/master.zip から。何処かで .zip のダウンロードリンクを案内しても良い気はします。

**Comment by katahiromz** [comment]
https://github.com/cpprefjp/site/releases
ここにリリースページがありますから、こちらで配布できるかと思います。

**Comment by akinomyoga** [comment]
それも一つの手ですね。でも、それよりは https://cpprefjp.github.io/ のサイト本体の方にリンク載せた方が閲覧者的には親切な気もします。https://github.com/cpprefjp/site を見てるのって主に cpprefjp を編集している側の人達ですよね。。後、Release は特定の commit に紐付いているので定期的にリリースをして行く必要があります。それよりは常に最新版をダウンロードできる上記リンクをサイト本体につけた方がメンテナンスしなくて良いので楽かなって思います。

**Comment by katahiromz** [comment]
ありがとうございます。それでは閉じます。

**Comment by akinomyoga** [comment]
案: 例えばこの辺りに新しい項目を追加する等。

![image](https://user-images.githubusercontent.com/8982192/141293477-9e071c2c-1dec-43be-a89d-6b25e743eb8d.png)

**Comment by akinomyoga** [comment]
ところでサイトの左上のメニューアイコン `≡` なのですけれど、こちらの手元 (Google Chrome / Windows) ですとブラウザの幅を広くすると消えてなくなってしまいます。何か僕勘違いしてますか?

**Comment by akinomyoga** [comment]
今 https://github.com/cpprefjp/cpprefjp.github.io/archive/refs/heads/master.zip からダウンロードして試してみたのですけれど、リンクが相対ではなくて絶対 (`/` から始まる) になっている、または https://cpprefjp.github.io ... というURLが直接埋め込まれているという形になっているのでまともに閲覧できませんでした。

なのでやはりダウンロード専用に相対リンクになっている物を生成し直す必要があります。。`<base>` 要素を指定すればそんなに難しくはないのではないかという気がします。その時は @katahiromz さんの仰る様に Release で特別版を提供する必要があります。或いはサイト本体も内部リンクは全部相対リンクに置き換えてしまえば、上記リンクもそのまま使えます。

**Comment by h-sao** [comment]
そういえば、要望一覧みたいなものって書く場所ありましたっけね？
1. サイトをローカル環境のみ（HTML形式）で閲覧したい
1. 上記情報をZIPなどにまとめてダウンロードする機能を、サイト内のリンクに入れたい
という要望だと思うので、まずはどこかに要望内容をまとめておいても良いのかなとは思いました（あるならわたし、追記しますよ）

// 今すぐに、ローカル環境のみでcpprefjpサイトの内容を閲覧したいなら
// HTMLでの閲覧ではなく、Gitデータをマークダウンで見るとかでもいけるような気はします

**Comment by yohhoy** [comment]
他の類似リファレンスではどう対応しているのかと思い、簡単に調べてみました。

cpprefjpや類似リファレンスともにサイトが取り扱う情報の性質上、不特定多数の参加者が公頻繁・小規模に追記改善していくものです。
オフライン環境でも閲覧したいという要望は理解しつつも、個人的にはオフライン閲覧に向いておらず公式提供するほどかな？とは思います。

## cppreference.com
http://en.cppreference.com/
公式／非公式にスナップショット・ダウンロード版を提供しているようです。ただし更新頻度はかなり低いようで、2020年10月時点の非公式スナップショット（2021年11月現在）が最新のようでした。
https://en.cppreference.com/w/Cppreference:Archives

## cplusplus.com
https://www.cplusplus.com
ざっと探してみた範囲では言及見当たりませんでした（Forum回答でサイト全体を`wget`する方策を見かけた程度）

**Comment by yumetodo** [comment]
実用的には月次バッチとかで事足るんじゃないですかね、最新でなくとも

**Comment by akinomyoga** [comment]
> そういえば、要望一覧みたいなものって書く場所ありましたっけね？

(僕が把握していないだけかもしれませんけれど) ない気がします。というより Issues が要望・提案も兼ねているような気がします。特に、現状 @yohhoy さんがつけて下さった様に [enhancement ラベル](https://github.com/cpprefjp/site/labels/enhancement) が実質 "要望・提案の一覧" になっているように思います。

### 内部リンクの問題

ローカルで閲覧できるようにするというのは手許でのテストという観点でも良いのではないかという気がします。現状、ローカルで閲覧できるようにする上での第一の問題点は既に述べましたように、内部のリンクであるように思います (もしかして簡単に解決する方法が既に用意されていましたらすみません)。GitHub Pages で公開していることから静的なコンテンツしか置いていない筈なので、それ以外には大きな問題はないのではないか、と楽観的に考えています。

関連する事なのですが、皆さんは記事を編集する時にどのようにして生成結果の確認を行っていますか。私は昔ローカルで閲覧できるようにするのに挫折して以来、適当に編集して生成結果の事前確認なしで push/merge してしまっています…。それで実際に cpprefjp.github.io に反映された後に問題があれば、また編集し直すという感じです (滅多にその必要性も生じないですが)。

挫折というのは、昔、#510 の様子見で cpprefjp の構造を調べようと思った時に、先ずローカルで site_generator で生成して閲覧できるようにする段階で挫折しました。記憶が定かではないですが、内部のリンクが絶対になっていたりホスト名 cpprefjp.github.io が直接記述されていたりする箇所があったからだった様に思います。 内部リンクが絶対になっているので Web サーバーのトップレベルに置かなければならず新しくWebサーバーを建てる必要があります (localhost:8080 とか)。またホスト名が決め打ちになっている点について、[ホスト名 cpprefjp.github.io を切り替えて生成する設定項目](https://github.com/cpprefjp/site_generator/blob/master/settings/cpprefjp.py#L17)もありましたが、これを変えるだけでは全て置き換わらなかったように思います (記憶が間違っていなければ)。

**Comment by h-sao** [comment]
要望はissueへのラベル付けで事足りますね、失礼しました

わたしも更新時には、最終生成結果を見ずにpushしてます（この文だけ読むと問題ありに聞こえますが…💦）
ただ、手元のマークダウンをプレビューで見てから更新するので
今のところそこまで問題は出てないです

とはいえテスタビリティーが向上するのはおっしゃる通りですので
作業できそうな方がどこかのタイミングでやる、という温度感でもまだ良いのではないかと思います

**Comment by yumetodo** [comment]
自分も同じくsite_generatorを手元で動かそうとして挫折して以降、脳内コンパイルで書いています。

**Comment by yumetodo** [comment]
あー書きますれましたがページ内リンクのチェッカーは毎Push動くのでまあ脳内コンパイルでどうにかなっているという話もあります

**Comment by faithandbrave** [comment]
相対リンクにしてzipでダウンロード可能できるようにするくらいなら、私の方で時間を見つけてやっておきます。

**Comment by faithandbrave** [comment]
@akinomyoga さんが、HTMLをダウンロードできるよう相対リンク化を実装してくださいました。
cpprefjpとboostjpの各トップページに、HTMLのダウンロードリンクを記載してあります。このリンクでは、masterブランチの常に最新のものができます。

@akinomyoga さんの多大な貢献に感謝します。
ありがとうございます！
