### ISSUE TITLE
[C++20][ライブラリ] Rangeライブラリ (<algorithm>)

### ISSUE THREAD

**Issue by tetsurom** [cpprefjp/site#919]
シーケンスを変更しない操作

- [x] `ranges::all_of`
- [x] `ranges::any_of`
- [x] `ranges::none_of`
- [x] `ranges::for_each`
- [x] `ranges::for_each_n`
- [x] `ranges::count`
- [x] `ranges::count_if`
- [x] `ranges::mismatch`
- [x] `ranges::find`
- [x] `ranges::find_if`
- [x] `ranges::find_if_not`
- [x] `ranges::find_end`
- [x] `ranges::find_first_of`
- [x] `ranges::adjacent_find`
- [x] `ranges::search`
- [x] `ranges::search_n`

シーケンスを変更する操作

- [x] `ranges::copy`
- [x] `ranges::copy_if`
- [x] `ranges::copy_n`
- [x] `ranges::copy_backward`
- [x] `ranges::move`
- [x] `ranges::move_backward`
- [x] `ranges::fill`
- [x] `ranges::fill_n`
- [x] `ranges::transform`
- [x] `ranges::generate`
- [x] `ranges::generate_n`
- [x] `ranges::remove`
- [x] `ranges::remove_if`
- [x] `ranges::remove_copy`
- [x] `ranges::remove_copy_if`
- [x] `ranges::replace`
- [x] `ranges::replace_if`
- [x] `ranges::replace_copy`
- [x] `ranges::replace_copy_if`
- [x] `ranges::swap_ranges`
- [x] `ranges::reverse`
- [x] `ranges::reverse_copy`
- [x] `ranges::rotate`
- [x] `ranges::rotate_copy`
- [x] `ranges::shuffle`
- [x] `ranges::sample`
- [x] `ranges::unique`
- [x] `ranges::unique_copy`
- [x] `ranges::is_partitioned`
- [x] `ranges::partition`
- [x] `ranges::partition_copy`
- [x] `ranges::stable_partition`
- [x] `ranges::partition_point`

ソートや、それに関連した操作

- [x] `ranges::is_sorted`
- [x] `ranges::is_sorted_until`
- [x] `ranges::sort`
- [x] `ranges::partial_sort`
- [x] `ranges::partial_sort_copy`
- [x] `ranges::stable_sort`
- [x] `ranges::nth_element`
- [x] `ranges::lower_bound`
- [x] `ranges::upper_bound`
- [x] `ranges::binary_search`
- [x] `ranges::equal_range`
- [x] `ranges::merge`
- [x] `ranges::inplace_merge`
- [x] `ranges::includes`
- [x] `ranges::set_difference`
- [x] `ranges::set_intersection`
- [x] `ranges::set_symmetric_difference`
- [x] `ranges::set_union`
- [x] `ranges::is_heap`
- [x] `ranges::is_heap_until`
- [x] `ranges::make_heap`
- [x] `ranges::push_heap`
- [x] `ranges::pop_heap`
- [x] `ranges::sort_heap`
- [x] `ranges::max`
- [x] `ranges::max_element`
- [x] `ranges::min`
- [x] `ranges::min_element`
- [x] `ranges::minmax`
- [x] `ranges::minmax_element`
- [x] `ranges::clamp`
- [x] `ranges::equal`
- [x] `ranges::lexicographical_compare`
- [x] `ranges::is_permutation`
- [x] `ranges::next_permutation`
- [x] `ranges::prev_permutation`

**Comment by onihusube** [comment]
`<algorithm>`ページ冒頭にいわゆるniebloidについての説明がありますが、一応個別の解説ページがあります。ほぼ同じ事が書いてあるのでどちらかにまとめた方がいいでしょうか？

https://cpprefjp.github.io/article/lib/disable_adl_function.html

**Comment by tetsurom** [comment]
ヘッダーページが長くなると使いづらいと思うので個別ページに任せるようにします。
