### ISSUE TITLE
C++情報源の紹介ページの追加について

### ISSUE THREAD

**Issue by h-sao** [cpprefjp/site#954]
C++に関する情報源の紹介ページがあるといいかなと思っています
具体的にはC++関連の有名なチャットリンクを載せると良いかなと思ってます

例えばこんな感じのリンク↓↓↓

（例）
- CPP Lang (Slack) - https://cppalliance.org/slack/  
**build_system**, **compiler_explorer**, **feature_standard**などチャネルが多数あります

- MSVC STL (Discord) - https://github.com/microsoft/STL/wiki/  
Microsoft VC teamが開設したDiscordチャネルです。次期リリース情報などがリアルタイムに分かります

今は「メーリングリスト」ページがそれに相当すると思いますが
「コミュニティリスト」（？）のような名前に変更し、上記のリンクを載せるなどは
みなさまどう思いますか？

意見お聞かせください～ｍｍ

**Comment by faithandbrave** [comment]
その変更でよいかと思います。

**Comment by h-sao** [comment]
「コミュニティリスト」に変更しました
サイドバーの「メーリングリスト」は、どこで文言を修正するのか一見判らなかったので、そのままにしています

**Comment by faithandbrave** [comment]
直りましたー

**Comment by h-sao** [comment]
@faithandbrave san 
すみません！
ありがとうございました！！
