### ISSUE TITLE
[C++20] thisの暗黙のキャプチャを非推奨化の説明について

### ISSUE THREAD

**Issue by altzweel** [cpprefjp/site#959]
[[=]によるthisの暗黙のキャプチャを非推奨化](https://cpprefjp.github.io/lang/cpp20/deprecate_implicit_capture_of_this_via_defcopy.html
)

> C++20からは、ラムダ式でのデフォルトコピーのキャプチャ指定[=]では、thisポインタがキャプチャされなくなる。

とありますが、非推奨であるだけでキャプチャは一応されるわけではないんでしょうか？

修正の判断に迷ったのでIssueにしました。

**Comment by faithandbrave** [comment]
ご指摘の通りですね。

**Comment by altzweel** [comment]
ありがとうございます。調整しました。
