### ISSUE TITLE
GLOBAL_QUALIFY_LIST.txt への項目追加基準

### ISSUE THREAD

**Issue by tetsurom** [cpprefjp/site#962]
[GLOBAL_QUALIFY_LIST.txt](https://github.com/cpprefjp/site/blob/master/GLOBAL_QUALIFY_LIST.txt)へ項目を追加する基準は何かありますか？

コンセプトが本格的に使われるようになり、大量のリンクを貼る必要が出てきています。そこで、標準のコンセプトを`std::`なしで追加することを考えています。

**Comment by yumetodo** [comment]
> https://github.com/cpprefjp/site/pull/771#issuecomment-646022482
>
>グローバル修飾リストは、C++として使う機会が多いキーワードではなく、本サイトのサンプルコードで頻出するキーワードを登録するところです。
>
>編集者の作業負担を減らすのが主目的ですが、std::byteはいまのところ、aligned_storage、span、memory_resourceくらいからしか参照されていません。aligned_storageはaligned_unionからしか参照されていません。
>
>同じコード修飾を何度も書いて大変だからグローバル修飾リストに登録、とかならいいですが、いまのところ頻出はしていないという認識です。
なにを想定されているのでしょうか。

以前に指針となるものが示されていました。今回の場合は足していい気がしますね・・・？

**Comment by faithandbrave** [comment]
はい、頻出するものは足していただいて大丈夫です。

登録個数の上限はないのですが、いまのところsite_generatorの実装をサボっているせいで、すべてのコードブロックにグローバル修飾リストがまるまるついてしまうので、登録していくほど正規表現によるコード修飾がどんどん遅くなっていってしまいます。
site_generatorの方で「コード内にでてくる修飾のみを適用する」としてしまえば気軽に登録してもらっていいのですが、いまのところは実装の都合で「頻出しているもののみ登録」とさせてもらっています。
