### ISSUE TITLE
C++17 インライン変数についての疑問点

### ISSUE THREAD

**Issue by hi-hori** [cpprefjp/site#972]
https://cpprefjp.github.io/lang/cpp17/inline_variables.html

上記ページにある例ですが、この場合は static inline 指定ではなく static 指定でも
「翻訳単位ごとにアドレスが変わる」の動作になるかと思います。

```cpp
namespace N {
  // static指定(翻訳単位ごとにアドレスが変わる)
  static inline int static_var = 10;
  static inline int static_func(void) {
    return 20;
  }
```

グローバルな変数に対して inline 指定、static inline 指定した場合のそれぞれの動作についての解説もあれば良いかなと思いました。

**Comment by yumetodo** [comment]
そもそも

>https://timsong-cpp.github.io/cppwp/n4861/basic.stc.static#1
>
>All variables which do not have dynamic storage duration, do not have thread storage duration, and are not local have [static storage duration](https://timsong-cpp.github.io/cppwp/n4861/basic.stc.static#def:static_storage_duration)[.](https://timsong-cpp.github.io/cppwp/n4861/basic.stc.static#1.sentence-1)
The storage for these entities lasts for the duration of the program ([[basic.start.static]](https://timsong-cpp.github.io/cppwp/n4861/basic.start.static), [[basic.start.term]](https://timsong-cpp.github.io/cppwp/n4861/basic.start.term))[.](https://timsong-cpp.github.io/cppwp/n4861/basic.stc.static#1.sentence-2)

とあるので、

>この場合は static inline 指定ではなく static 指定でも
「翻訳単位ごとにアドレスが変わる」の動作になるかと思います。

は等価なコードなので一緒になるのはそれはそうなのですよね・・・。

それをどう表現するのかは悩ましいですが。

**Comment by akinomyoga** [comment]
@yumetodo `static inline` や `static` だけでなく `inline` の時も static storage duration では? アドレスを考える時に問題になるのは storage duration というよりもむしろ linkage の気がします (※名前空間スコープの変数に対する `static` は storage duration ではなく linkage を指定するものであることに注意)。今回の `static inline` については、`static` [[basic.link/(3.1)]](https://timsong-cpp.github.io/cppwp/n4861/basic.link#3.1) と `inline` [[basic.link]/(3.2.2)](https://timsong-cpp.github.io/cppwp/n4861/basic.link#3.2.2) という一見して相反する組み合わせにおいてどちらが勝つのかということの気がします。結論は [basic.link]/3 を簡略化すると "`static` ∨ ¬ `inline`" ということなので、`static` が指定されている場合は `inline` があってもなくても同じ linkage になる、と。

----

この頁はインライン変数について記述するもののようなので、このページで static まで含めて包括的に説明するべきなのかというと微妙な気もします。リンケージを説明するページが未だないなら作っても良いのかもしれません。

インライン変数の記事の `static inline` の例は「飽くまで inline と他のキーワードの組み合わせで何が起こるのかの範疇」と思えばあっても良いとは思いますが、一方で現在の書き方だと「翻訳単位ごとに変数を作るには `static inline` にすればいいんだ」と勘違いする人が出てくるというのが @hi-hori さんの懸念に関係することの気がします。そもそも C++ に於いて `static inline` という組み合わせを現実的に使うことはあるのだろうかという謎 (※C言語の `inline` と C++ の `inline` は意味が異なるので、C言語では `static inline` を敢えて使うことに理由があったはず)。

**Comment by akinomyoga** [comment]
関係ないけれど同じ記事で

> `inline`ではない変数宣言のあとに`inline`は宣言できず、文法違反となる。

は文法違反ではなく意味論違反の気がします。。以下文法の抜粋。

```
linkage-specification:
  extern string-literal { declaration-seq opt }
  extern string-literal declaration
declaration:
  block-declaration
  [...]
block-declaration:
  simple-declaration
  [...]
simple-declaration:
  decl-specifier-seq init-declarator-list opt ;
  [...]
decl-specifier-seq:
  decl-specifier attribute-specifier-seq opt
decl-specifier:
  [...]
  inline
```

**Comment by yumetodo** [comment]
staticがinlineに勝つ・・・、まあ確かにそうでした。

**Comment by faithandbrave** [comment]
@akinomyoga さんの方で修正できますか？

**Comment by akinomyoga** [comment]
承りました。後で時間のある時に対応いたします!
