### ISSUE TITLE
[C++23] [ライブラリ] 標準ライブラリモジュールのページ構成

### ISSUE THREAD

**Issue by tetsurom** [cpprefjp/site#994]
標準ライブラリのモジュール `std` と `std.compat` をどのように記事にするか、方針はあるでしょうか。

* [P2465R3 Standard Library Modules std and std.compat](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2465r3.pdf)

ヘッダーページの代わりにモジュールページを作る？
(各モジュールページでは、どのヘッダーファイルの内容を含むのかを紹介する)

- `/reference/std.md`
- `/reference/std.compat.md`

ページ右上に表示される `<header-name>` をモジュール名にする方法が必要？

**Comment by faithandbrave** [comment]
reference階層の代わりにmodule階層を作ってメタ情報としては[meta module]にするのはどうでしょ。

**Comment by tetsurom** [comment]
良いと思います。
試しにその配置で書いてみます。
